function [manifestTable, qualityTable] = audit_case( ...
        definition, specification, domain, generationRuntimeS)
% AUDIT_CASE Build v5 manifest/quality rows from one in-memory mesh domain.

    legacyAuditDefinition = phase32.definition();
    [manifest, ~] = phase32.audit_domain(legacyAuditDefinition, ...
        specification, domain, generationRuntimeS);
    polar = domain.fs.quality_controlled_polar;
    truncation = domain.cfg.outer_truncation.effective;
    manifest.topology_mode = string(definition.topologyMode);
    manifest.requested_near_radial_step_m = polar.requestedNearRadialStepM;
    manifest.realized_near_radial_step_m = polar.realizedNearRadialStepM;
    manifest.requested_outer_radial_step_max_m = ...
        polar.requestedOuterRadialStepMaxM;
    manifest.realized_outer_radial_step_m = polar.realizedOuterRadialStepM;
    manifest.configured_outer_radial_layer_count = ...
        polar.configuredOuterRadialLayerCount;
    manifest.requested_outer_radial_layer_count = ...
        polar.requestedOuterRadialLayerCount;
    manifest.realized_outer_radial_layer_count = ...
        polar.realizedOuterRadialLayerCount;
    manifest.base_theta_count = polar.thetaNodeCount;
    manifest.final_wall_theta_count = truncation.commonOuterThetaNodeCount;
    manifest.top_connector_minimum_angle_deg = ...
        truncation.topSurfaceDerived.oneToTwoConnectorAudit.minimumAngleDeg;
    manifest.top_connector_maximum_aspect_ratio = ...
        truncation.topSurfaceDerived.oneToTwoConnectorAudit.maximumAspectRatio;
    manifest.bottom_connector_minimum_angle_deg = ...
        truncation.bottomSurfaceDerived.oneToTwoConnectorAudit.minimumAngleDeg;
    manifest.bottom_connector_maximum_aspect_ratio = ...
        truncation.bottomSurfaceDerived.oneToTwoConnectorAudit.maximumAspectRatio;
    manifest.design_canonical_sha256 = ...
        string(definition.designCanonicalSHA256);
    manifest.design_git_blob_id = string(definition.designGitBlobID);
    manifest.design_v2_canonical_sha256 = ...
        string(definition.designV2CanonicalSHA256);
    manifest.design_v2_git_blob_id = string(definition.designV2GitBlobID);
    manifest.stale_result_reuse = "NO_MESH_REGENERATED_IN_UNIQUE_DIRECTORY";
    manifestTable = struct2table(manifest);

    components = {domain.body_list{1}, domain.fs, ...
        domain.seabed, domain.farfield};
    names = ["body"; "free_surface"; "bottom"; "farfield"];
    rows = repmat(quality_row(), numel(components), 1);
    for index = 1:numel(components)
        [quality, ~] = phase32a.evaluate_component_quality( ...
            components{index}, names(index), definition);
        row = quality_row();
        fields = fieldnames(quality);
        for fieldIndex = 1:numel(fields)
            row.(fields{fieldIndex}) = quality.(fields{fieldIndex});
        end
        row.mesh_level = specification.level.name;
        row.mesh_level_index = specification.level.index;
        row.omega_rad_s = specification.omegaRadPerS;
        row.topology_mode = string(definition.topologyMode);
        row.requested_near_radial_step_m = polar.requestedNearRadialStepM;
        row.realized_near_radial_step_m = polar.realizedNearRadialStepM;
        row.requested_outer_radial_step_max_m = ...
            polar.requestedOuterRadialStepMaxM;
        row.realized_outer_radial_step_m = polar.realizedOuterRadialStepM;
        row.configured_outer_radial_layer_count = ...
            polar.configuredOuterRadialLayerCount;
        row.realized_outer_radial_layer_count = ...
            polar.realizedOuterRadialLayerCount;
        row.base_theta_count = polar.thetaNodeCount;
        row.final_wall_theta_count = truncation.commonOuterThetaNodeCount;
        row.transition_median_sqrt_area_m = ...
            manifest.transition_median_sqrt_area_m;
        row.manifold_status = manifest.manifold_status;
        row.orientation_status = manifest.normal_orientation_status;
        row.waterline_status = manifest.waterline_continuity_status;
        row.self_intersection_status = manifest.self_intersection_status;
        row.runtime_provenance = "PASS_CURRENT_WORKTREE";
        rows(index) = row;
    end
    qualityTable = struct2table(rows);
end

function row = quality_row()
    row = struct('mesh_level', "", 'mesh_level_index', 0, ...
        'omega_rad_s', NaN, 'topology_mode', "", 'component', "", ...
        'panel_count', 0, 'minimum_panel_area_m2', NaN, ...
        'maximum_panel_area_m2', NaN, 'median_panel_area_m2', NaN, ...
        'mean_sqrt_area_m', NaN, 'median_sqrt_area_m', NaN, ...
        'minimum_edge_length_m', NaN, 'maximum_aspect_ratio', NaN, ...
        'maximum_skewness_deg', NaN, 'minimum_corner_angle_deg', NaN, ...
        'maximum_corner_angle_deg', NaN, 'maximum_warp_deg', NaN, ...
        'poor_panel_count', 0, 'poor_panel_fraction', NaN, ...
        'finite_positive_geometry', false, 'duplicate_panel_count', 0, ...
        'component_gate_pass', false, 'component_gate_status', "NOT_RUN", ...
        'requested_near_radial_step_m', NaN, ...
        'realized_near_radial_step_m', NaN, ...
        'requested_outer_radial_step_max_m', NaN, ...
        'realized_outer_radial_step_m', NaN, ...
        'configured_outer_radial_layer_count', 0, ...
        'realized_outer_radial_layer_count', 0, ...
        'base_theta_count', 0, 'final_wall_theta_count', 0, ...
        'transition_median_sqrt_area_m', NaN, ...
        'manifold_status', "NOT_RUN", 'orientation_status', "NOT_RUN", ...
        'waterline_status', "NOT_RUN", ...
        'self_intersection_status', "NOT_RUN", ...
        'runtime_provenance', "");
end
