function tableOut = evaluate_isolation(definition, omega, manifest, quality)
% EVALUATE_ISOLATION Enforce v5 per-frequency coordinated refinement gates.

    manifest = sortrows(manifest, 'mesh_level_index');
    levelCount = numel(definition.levels);
    countPass = height(manifest) == levelCount && ...
        all(diff(manifest.body_panel_count) > 0) && ...
        all(diff(manifest.free_surface_panel_count) > 0) && ...
        all(diff(manifest.bottom_panel_count) > 0) && ...
        all(diff(manifest.farfield_panel_count) > 0) && ...
        all(diff(manifest.realized_outer_radial_layer_count) > 0) && ...
        all(diff(manifest.base_theta_count) > 0) && ...
        all(diff(manifest.final_wall_theta_count) > 0);
    countPass = countPass && ...
        all(diff(manifest.realized_bottom_core_radial_layer_count) > 0) && ...
        all(diff(manifest.bottom_core_structured_panel_count) > 0);
    hPass = true;
    requestedRealizedPass = true;
    componentNames = unique(quality.component, 'stable');
    for index = 1:numel(componentNames)
        rows = quality.component == componentNames(index);
        componentRows = sortrows(quality(rows, :), 'mesh_level_index');
        hPass = hPass && height(componentRows) == levelCount && ...
            all(diff(componentRows.mean_sqrt_area_m) < 0) && ...
            all(diff(componentRows.median_sqrt_area_m) < 0);
        requestedRealizedPass = requestedRealizedPass && ...
            all(componentRows.realized_near_radial_step_m <= ...
            componentRows.requested_near_radial_step_m .* (1 + 1.0e-10)) && ...
            all(componentRows.realized_outer_radial_step_m <= ...
            componentRows.requested_outer_radial_step_max_m .* (1 + 1.0e-10));
    end
    fsRows = sortrows(quality(quality.component == "free_surface", :), ...
        'mesh_level_index');
    transitionPass = all(diff(fsRows.transition_median_sqrt_area_m) < 0);
    extentPass = max(manifest.actual_top_outer_radius_m) - ...
        min(manifest.actual_top_outer_radius_m) <= ...
        definition.geometryToleranceM && ...
        max(manifest.actual_bottom_outer_radius_m) - ...
        min(manifest.actual_bottom_outer_radius_m) <= ...
        definition.geometryToleranceM;
    qualityPass = height(quality) == 4 * levelCount && ...
        all(quality.component_gate_status == "PASS");
    topologyPass = all(manifest.manifold_status == "PASS") && ...
        all(manifest.normal_orientation_status == "PASS") && ...
        all(manifest.waterline_continuity_status == "PASS") && ...
        all(manifest.self_intersection_status == "PASS");
    hashPass = numel(unique(manifest.combined_geometry_hash)) == levelCount;
    sourcePass = numel(unique(manifest.production_source_hash)) == 1 && ...
        numel(unique(manifest.design_canonical_sha256)) == 1 && ...
        numel(unique(manifest.design_git_blob_id)) == 1 && ...
        numel(unique(manifest.design_v2_canonical_sha256)) == 1 && ...
        numel(unique(manifest.design_v2_git_blob_id)) == 1;
    sourcePass = sourcePass && ...
        numel(unique(manifest.design_v3_canonical_sha256)) == 1 && ...
        numel(unique(manifest.design_v3_git_blob_id)) == 1;
    noReuse = all(manifest.stale_result_reuse == ...
        "NO_MESH_REGENERATED_IN_UNIQUE_DIRECTORY");
    gatePass = countPass && hPass && requestedRealizedPass && ...
        transitionPass && extentPass && qualityPass && topologyPass && ...
        hashPass && sourcePass && noReuse;
    tableOut = table(omega, levelCount, countPass, hPass, ...
        requestedRealizedPass, transitionPass, extentPass, qualityPass, ...
        topologyPass, hashPass, sourcePass, noReuse, pass_fail(gatePass), ...
        'VariableNames', {'omega_rad_s', 'level_count', ...
        'all_requested_integer_counts_strictly_increase', ...
        'all_component_mean_median_h_strictly_decrease', ...
        'realized_steps_meet_requested_maxima', ...
        'transition_median_h_strictly_decreases', ...
        'same_frequency_outer_extent_exact', ...
        'all_component_quality_rows_pass', 'all_topology_contracts_pass', ...
        'combined_hashes_distinct', 'source_and_design_fixed', ...
        'no_stale_result_reuse', 'frequency_geometry_gate'});
end

function text = pass_fail(value)
    if value
        text = "PASS";
    else
        text = "FAIL";
    end
end
