function [summary, details] = evaluate_component_quality( ...
        mesh, componentName, definition)
% EVALUATE_COMPONENT_QUALITY Apply the frozen Phase 3.2 quality thresholds.

    metrics = phase32a.evaluate_panels(mesh.vertices, mesh.normals, ...
        definition.minimumEdgeLengthM);
    panelCount = mesh.n_panels;
    poor = false(panelCount, 1);
    aspectLimit = zeros(panelCount, 1);
    for panelIndex = 1:panelCount
        radiusM = hypot(mesh.centers(panelIndex, 1), ...
            mesh.centers(panelIndex, 2));
        if componentName == "body"
            aspectLimit(panelIndex) = definition.bodyMaximumAspectRatio;
        elseif componentName == "farfield" || ...
                radiusM > definition.meshTransitionRadiusM
            aspectLimit(panelIndex) = definition.outerMaximumAspectRatio;
        else
            aspectLimit(panelIndex) = definition.nearMaximumAspectRatio;
        end
        poor(panelIndex) = ...
            metrics.aspectRatio(panelIndex) > aspectLimit(panelIndex) || ...
            metrics.skewnessDeg(panelIndex) > ...
                definition.maximumSkewnessDeg || ...
            metrics.minimumAngleDeg(panelIndex) < ...
                definition.minimumCornerAngleDeg || ...
            metrics.maximumAngleDeg(panelIndex) > ...
                definition.maximumCornerAngleDeg || ...
            metrics.warpDeg(panelIndex) > definition.maximumWarpDeg || ...
            metrics.minimumEdgeLengthM(panelIndex) <= ...
                definition.minimumEdgeLengthM;
    end
    finitePositive = all(isfinite(mesh.vertices), 'all') && ...
        all(isfinite(mesh.centers), 'all') && ...
        all(isfinite(mesh.normals), 'all') && ...
        all(isfinite(metrics.areaM2)) && all(metrics.areaM2 > 0);
    poorFraction = nnz(poor) / panelCount;
    componentPass = finitePositive && poorFraction <= ...
        definition.maximumPoorPanelFraction;
    summary = struct('component', string(componentName), ...
        'panel_count', panelCount, ...
        'minimum_panel_area_m2', min(metrics.areaM2), ...
        'maximum_panel_area_m2', max(metrics.areaM2), ...
        'median_panel_area_m2', median(metrics.areaM2), ...
        'mean_sqrt_area_m', mean(sqrt(metrics.areaM2)), ...
        'median_sqrt_area_m', median(sqrt(metrics.areaM2)), ...
        'minimum_edge_length_m', min(metrics.minimumEdgeLengthM), ...
        'maximum_aspect_ratio', max(metrics.aspectRatio), ...
        'maximum_skewness_deg', max(metrics.skewnessDeg), ...
        'minimum_corner_angle_deg', min(metrics.minimumAngleDeg), ...
        'maximum_corner_angle_deg', max(metrics.maximumAngleDeg), ...
        'maximum_warp_deg', max(metrics.warpDeg), ...
        'poor_panel_count', nnz(poor), ...
        'poor_panel_fraction', poorFraction, ...
        'finite_positive_geometry', finitePositive, ...
        'duplicate_panel_count', metrics.duplicatePanelCount, ...
        'component_gate_pass', componentPass, ...
        'component_gate_status', pass_fail(componentPass));
    details = table((1:panelCount)', metrics.isTriangle, ...
        mesh.centers(:, 1), mesh.centers(:, 2), mesh.centers(:, 3), ...
        metrics.areaM2, metrics.aspectRatio, metrics.minimumAngleDeg, ...
        metrics.maximumAngleDeg, metrics.skewnessDeg, metrics.warpDeg, ...
        metrics.minimumEdgeLengthM, aspectLimit, ...
        metrics.orientationAlignment, poor, ...
        'VariableNames', {'panel_id', 'is_triangle', 'center_x_m', ...
        'center_y_m', 'center_z_m', 'area_m2', 'aspect_ratio', ...
        'minimum_angle_deg', 'maximum_angle_deg', 'skewness_deg', ...
        'warp_deg', 'minimum_edge_length_m', 'aspect_limit', ...
        'orientation_alignment', 'is_poor'});
end

function text = pass_fail(value)
    if value
        text = "PASS";
    else
        text = "FAIL";
    end
end
