function definition = initialize()
% INITIALIZE Enforce the Phase 3.2A branch and current-worktree provenance.

    packageDirectory = fileparts(mfilename('fullpath'));
    artifactDirectory = fileparts(packageDirectory);
    convergenceDirectory = fileparts(artifactDirectory);
    caseWaveDirectory = fileparts(convergenceDirectory);
    repositoryRoot = fileparts(caseWaveDirectory);
    sourceDirectory = fullfile(repositoryRoot, 'Source Code');

    restoredefaultpath;
    rehash toolboxcache;
    assert(same_path(pwd, repositoryRoot), 'CRESTU:Phase32AMatlabPwd', ...
        'MATLAB pwd must be the authorized Phase 3.2A worktree root.');
    addpath(fullfile(sourceDirectory, '0.Tools Code'), ...
        fullfile(sourceDirectory, '1.Input'), ...
        fullfile(sourceDirectory, '2.Mesh'), ...
        fullfile(sourceDirectory, '3.HessSmith'), ...
        fullfile(sourceDirectory, '4.Potential'), ...
        fullfile(sourceDirectory, '5.Force'), ...
        fullfile(sourceDirectory, '6.MeanDriftLoads'), ...
        caseWaveDirectory, fullfile(caseWaveDirectory, 'Common_Scripts'), ...
        convergenceDirectory, ...
        fullfile(convergenceDirectory, 'Phase3_2_Artifacts'), ...
        artifactDirectory, '-begin');

    [branch, branchStatus] = git_query(repositoryRoot, 'branch --show-current');
    [blockedTag, tagStatus] = git_query(repositoryRoot, ...
        'rev-parse "phase3-2-geometry-blocked-v4^{commit}"');
    blockedCommit = '225389a4f943bb1c4d809226ae6c72d3887dc5c5';
    [~, ancestorStatus] = git_query(repositoryRoot, sprintf( ...
        'merge-base --is-ancestor %s HEAD', blockedCommit));
    assert(branchStatus == 0 && ...
        strcmp(strtrim(branch), 'phase3-2a-polar-topology-remediation') && ...
        tagStatus == 0 && strcmp(strtrim(blockedTag), blockedCommit) && ...
        ancestorStatus == 0, 'CRESTU:Phase32AGitProvenance', ...
        'Phase 3.2A branch or blocked-v4 ancestry provenance failed.');

    requiredFunctions = ["run_frequency_domain_case"; "read_config"; ...
        "build_bmf_domain"; "generate_free_surface_bmf"; ...
        "generate_seabed_mesh"; "apply_rankine_outer_truncation"];
    originalRoot = 'E:\CRESTU-1F_v1.0_20260824\Code\CRESTU';
    for index = 1:numel(requiredFunctions)
        activePath = string(which(requiredFunctions(index)));
        assert(path_is_within(activePath, repositoryRoot) && ...
            ~path_is_within(activePath, originalRoot), ...
            'CRESTU:Phase32ARuntimePath', ...
            'A production function resolved outside the Phase 3.2A worktree.');
    end

    designFile = fullfile(artifactDirectory, ...
        'Phase3_2A_Topology_Design_Decision.md');
    expectedDesignCanonicalSHA256 = ...
        '6f0650154b95df143764999551533fd1e3c78fe980f68db1eecc2cba1e9ab577';
    expectedDesignGitBlobID = ...
        '8afacc9a4c4cb228b9cb45c65aaa9f2a0b1c31dc';
    assert(strcmp(phase32.canonical_lf_hash(designFile), ...
        expectedDesignCanonicalSHA256), ...
        'CRESTU:Phase32ADesignHash', ...
        'The predeclared Phase 3.2A topology design changed.');
    designRelative = strrep(designFile, [repositoryRoot, filesep], '');
    designRelative = strrep(designRelative, '\', '/');
    [designBlob, designBlobStatus] = git_query(repositoryRoot, ...
        sprintf('rev-parse "HEAD:%s"', designRelative));
    assert(designBlobStatus == 0 && ...
        strcmp(strtrim(designBlob), expectedDesignGitBlobID), ...
        'CRESTU:Phase32ADesignBlob', ...
        'The committed Phase 3.2A topology design blob changed.');

    levels = phase32a_levels();

    definition = struct('schemaVersion', 1, ...
        'artifactDirectory', artifactDirectory, ...
        'convergenceDirectory', convergenceDirectory, ...
        'caseWaveDirectory', caseWaveDirectory, ...
        'repositoryRoot', repositoryRoot, ...
        'sourceDirectory', sourceDirectory, ...
        'baselineConfig', fullfile(convergenceDirectory, ...
            'Phase2_2_Artifacts', 'Tests', 'Frustum_Instrumentation', ...
            'Cases', 'Frustum_Top_Only.cfg'), ...
        'formalConfig', fullfile(convergenceDirectory, ...
            'Mesh_Fine', 'Case1_Fine.cfg'), ...
        'designFile', designFile, ...
        'designCanonicalSHA256', expectedDesignCanonicalSHA256, ...
        'designGitBlobID', expectedDesignGitBlobID, ...
        'topologyMode', 'QUALITY_CONTROLLED_V2', ...
        'outerRadiusFactor', 1.5, ...
        'sphereRadiusM', 5.0, ...
        'levels', levels, ...
        'endpointFrequenciesRadPerS', [0.5, 2.0], ...
        'sentinelFrequenciesRadPerS', [0.5, 0.6, 1.0, 1.4, 1.5, 2.0], ...
        'blockedCommit', blockedCommit, ...
        'originalRepository', originalRoot, ...
        'geometryToleranceM', 1.0e-8, ...
        'minimumEdgeLengthM', 1.0e-10, ...
        'bodyMaximumAspectRatio', 4.0, ...
        'nearMaximumAspectRatio', 4.5, ...
        'outerMaximumAspectRatio', 12.0, ...
        'maximumSkewnessDeg', 55.0, ...
        'minimumCornerAngleDeg', 35.0, ...
        'maximumCornerAngleDeg', 145.0, ...
        'maximumWarpDeg', 8.0, ...
        'maximumPoorPanelFraction', 0.05, ...
        'meshTransitionRadiusM', 20.0);
    fprintf('[OK] Phase 3.2A branch/runtime provenance verified.\n');
end

function levels = phase32a_levels()
    template = struct('name', "", 'index', 0, 'eta', NaN, ...
        'bodyDivision', 0, 'fsRadialCounts', [0, 0], ...
        'bottomRadialCounts', [0, 0], 'wallVerticalCount', 0, ...
        'wallThetaCount', 0, 'fsThetaCount', 0, ...
        'bottomThetaCount', 0);
    levels = repmat(template, 3, 1);
    levels(1) = struct('name', "MESH_L1", 'index', 1, ...
        'eta', 0.0707009403590185, 'bodyDivision', 4, ...
        'fsRadialCounts', [4, 2], 'bottomRadialCounts', [4, 2], ...
        'wallVerticalCount', 3, 'wallThetaCount', 64, ...
        'fsThetaCount', 64, 'bottomThetaCount', 64);
    levels(2) = struct('name', "MESH_L2", 'index', 2, ...
        'eta', 0.0550177552570247, 'bodyDivision', 5, ...
        'fsRadialCounts', [5, 3], 'bottomRadialCounts', [5, 3], ...
        'wallVerticalCount', 4, 'wallThetaCount', 80, ...
        'fsThetaCount', 80, 'bottomThetaCount', 80);
    levels(3) = struct('name', "MESH_L3", 'index', 3, ...
        'eta', 0.0412542094946932, 'bodyDivision', 7, ...
        'fsRadialCounts', [6, 4], 'bottomRadialCounts', [6, 4], ...
        'wallVerticalCount', 5, 'wallThetaCount', 112, ...
        'fsThetaCount', 112, 'bottomThetaCount', 112);
end

function [output, status] = git_query(repositoryRoot, arguments)
    [status, output] = system(sprintf('git -C "%s" %s', ...
        repositoryRoot, arguments));
end

function value = same_path(firstPath, secondPath)
    value = strcmpi(normalize_path(firstPath), normalize_path(secondPath));
end

function value = path_is_within(candidatePath, rootPath)
    candidate = normalize_path(candidatePath);
    root = normalize_path(rootPath);
    value = strcmpi(candidate, root) || startsWith(lower(candidate), ...
        [lower(root), filesep]);
end

function value = normalize_path(inputPath)
    value = strrep(char(string(inputPath)), '/', filesep);
    while numel(value) > 3 && endsWith(value, filesep)
        value(end) = [];
    end
end
