function definition = initialize()
% INITIALIZE Enforce the Phase 3.2A branch and current-worktree provenance.

    packageDirectory = fileparts(mfilename('fullpath'));
    artifactDirectory = fileparts(packageDirectory);
    convergenceDirectory = fileparts(artifactDirectory);
    caseWaveDirectory = fileparts(convergenceDirectory);
    repositoryRoot = fileparts(caseWaveDirectory);
    sourceDirectory = fullfile(repositoryRoot, 'Source Code');

    restoredefaultpath;
    rehash toolboxcache;
    assert(same_path(pwd, repositoryRoot), 'CRESTU:Phase32AMatlabPwd', ...
        'MATLAB pwd must be the authorized Phase 3.2A worktree root.');
    addpath(fullfile(sourceDirectory, '0.Tools Code'), ...
        fullfile(sourceDirectory, '1.Input'), ...
        fullfile(sourceDirectory, '2.Mesh'), ...
        fullfile(sourceDirectory, '3.HessSmith'), ...
        fullfile(sourceDirectory, '4.Potential'), ...
        fullfile(sourceDirectory, '5.Force'), ...
        fullfile(sourceDirectory, '6.MeanDriftLoads'), ...
        caseWaveDirectory, fullfile(caseWaveDirectory, 'Common_Scripts'), ...
        convergenceDirectory, ...
        fullfile(convergenceDirectory, 'Phase3_2_Artifacts'), ...
        artifactDirectory, '-begin');

    [branch, branchStatus] = git_query(repositoryRoot, 'branch --show-current');
    [blockedTag, tagStatus] = git_query(repositoryRoot, ...
        'rev-parse "phase3-2-geometry-blocked-v4^{commit}"');
    blockedCommit = '225389a4f943bb1c4d809226ae6c72d3887dc5c5';
    [~, ancestorStatus] = git_query(repositoryRoot, sprintf( ...
        'merge-base --is-ancestor %s HEAD', blockedCommit));
    assert(branchStatus == 0 && ...
        strcmp(strtrim(branch), 'phase3-2a-polar-topology-remediation') && ...
        tagStatus == 0 && strcmp(strtrim(blockedTag), blockedCommit) && ...
        ancestorStatus == 0, 'CRESTU:Phase32AGitProvenance', ...
        'Phase 3.2A branch or blocked-v4 ancestry provenance failed.');

    requiredFunctions = ["run_frequency_domain_case"; "read_config"; ...
        "build_bmf_domain"; "generate_free_surface_bmf"; ...
        "generate_seabed_mesh"; "apply_rankine_outer_truncation"];
    originalRoot = 'E:\CRESTU-1F_v1.0_20260824\Code\CRESTU';
    for index = 1:numel(requiredFunctions)
        activePath = string(which(requiredFunctions(index)));
        assert(path_is_within(activePath, repositoryRoot) && ...
            ~path_is_within(activePath, originalRoot), ...
            'CRESTU:Phase32ARuntimePath', ...
            'A production function resolved outside the Phase 3.2A worktree.');
    end

    definition = struct('schemaVersion', 1, ...
        'artifactDirectory', artifactDirectory, ...
        'convergenceDirectory', convergenceDirectory, ...
        'caseWaveDirectory', caseWaveDirectory, ...
        'repositoryRoot', repositoryRoot, ...
        'sourceDirectory', sourceDirectory, ...
        'blockedCommit', blockedCommit, ...
        'originalRepository', originalRoot, ...
        'geometryToleranceM', 1.0e-8, ...
        'minimumEdgeLengthM', 1.0e-10, ...
        'bodyMaximumAspectRatio', 4.0, ...
        'nearMaximumAspectRatio', 4.5, ...
        'outerMaximumAspectRatio', 12.0, ...
        'maximumSkewnessDeg', 55.0, ...
        'minimumCornerAngleDeg', 35.0, ...
        'maximumCornerAngleDeg', 145.0, ...
        'maximumWarpDeg', 8.0, ...
        'maximumPoorPanelFraction', 0.05, ...
        'meshTransitionRadiusM', 20.0);
    fprintf('[OK] Phase 3.2A branch/runtime provenance verified.\n');
end

function [output, status] = git_query(repositoryRoot, arguments)
    [status, output] = system(sprintf('git -C "%s" %s', ...
        repositoryRoot, arguments));
end

function value = same_path(firstPath, secondPath)
    value = strcmpi(normalize_path(firstPath), normalize_path(secondPath));
end

function value = path_is_within(candidatePath, rootPath)
    candidate = normalize_path(candidatePath);
    root = normalize_path(rootPath);
    value = strcmpi(candidate, root) || startsWith(lower(candidate), ...
        [lower(root), filesep]);
end

function value = normalize_path(inputPath)
    value = strrep(char(string(inputPath)), '/', filesep);
    while numel(value) > 3 && endsWith(value, filesep)
        value(end) = [];
    end
end
