function canonicalDerivative = build_rankine_canonical_boundary_derivative( ...
        boundaryPotential, bodyDerivative, stats, freeSurfaceBC, outerBC)
% BUILD_RANKINE_CANONICAL_BOUNDARY_DERIVATIVE Build q_s on all components.

    panelCount = size(boundaryPotential, 1);
    columnCount = size(boundaryPotential, 2);
    counts = [stats.total_body_panels, stats.fs_panels, ...
        stats.seabed_panels, stats.farfield_panels];
    assert(sum(counts) == panelCount && ...
        isequal(size(bodyDerivative), [counts(1), columnCount]), ...
        'CRESTU:BoundaryDerivativeShape', ...
        'Body derivative or component counts do not match Phi.');
    assert(numel(freeSurfaceBC.nu) == counts(2) && ...
        numel(outerBC.gamma) == counts(4), ...
        'CRESTU:BoundaryDerivativeCoefficientShape', ...
        'FS or outer coefficient vector does not match its component.');
    canonicalDerivative = complex(zeros(panelCount, columnCount));
    bodyRows = 1:counts(1);
    freeSurfaceRows = counts(1) + (1:counts(2));
    outerRows = sum(counts(1:3)) + (1:counts(4));
    canonicalDerivative(bodyRows, :) = bodyDerivative;
    canonicalDerivative(freeSurfaceRows, :) = ...
        -reshape(freeSurfaceBC.nu, [], 1) .* ...
        boundaryPotential(freeSurfaceRows, :);
    canonicalDerivative(outerRows, :) = ...
        reshape(outerBC.gamma, [], 1) .* ...
        boundaryPotential(outerRows, :);
end
