function [cacheKey, cacheSpecification] = build_potential_cache_key( ...
        cfg, meshAudit, omega, modeParity, groupParity, codeVersion)
% BUILD_POTENTIAL_CACHE_KEY Build a complete per-frequency potential-cache key.
%
% Syntax:
%   [cacheKey, cacheSpecification] = build_potential_cache_key(...)
%
% Inputs:
%   cfg          - Frequency-local validated solver configuration [-].
%   meshAudit    - Hashes of body/free-surface/bottom/outer meshes [-].
%   omega        - Wave angular frequency [rad/s].
%   modeParity   - Per-DOF symmetry parity [-].
%   groupParity  - Unique symmetry groups used in assembly [-].
%   codeVersion  - Rankine numerical source-code fingerprint [-].
%
% Outputs:
%   cacheKey           - SHA-256 key covering geometry and solver state.
%   cacheSpecification - Exact manifest serialized to form the key.

    %% 阶段 1: 验证频率与自由度映射

    validateattributes(omega, {'numeric'}, ...
        {'scalar', 'real', 'positive', 'finite'});
    globalDofCount = 6 * cfg.n_bodies;
    assert(size(modeParity, 1) == globalDofCount, ...
        'CRESTU:CacheDofParity', ...
        'Cache manifest DOF count does not match mode parity.');

    %% 阶段 2: 构造完整缓存清单

    problemType = sprintf('radiation=%d;diffraction=%d', ...
        cfg.run.irad, cfg.run.idiff);
    sourceOrientation = get_rankine_source_orientation();
    solverOptions = struct('waterDepth', cfg.water_depth, ...
        'gravity', cfg.grav, 'density', cfg.rho, ...
        'symmetryFlags', [cfg.isx, cfg.isy], ...
        'waterlineTolerance', cfg.z_tol, ...
        'radialNearPanelCount', cfg.fs.nr_near, ...
        'radialSpongePanelCount', cfg.fs.nr_sponge, ...
        'innerRadius', cfg.fs.r_inner, ...
        'outerRadius', cfg.fs.r_outer, ...
        'spongeRatio', cfg.fs.sponge_ratio, ...
        'spongeCoefficient', cfg.fs.mu0, ...
        'farfieldVerticalPanelCount', cfg.fs.nz_farfield, ...
        'timeConvention', 'exp(+i*omega*t)', ...
        'linearSolver', 'dense-LU-partial-pivoting', ...
        'panelKernel', 'constant-quadrilateral-Rankine', ...
        'doubleLayerSourceNormalConvention', ...
        char(sourceOrientation.convention), ...
        'doubleLayerComponentSigns', sourceOrientation.componentSigns, ...
        'doubleLayerOrientationHash', sourceOrientation.signatureHash);
    cacheSpecification = struct('schemaVersion', 1, ...
        'bodyMeshHash', meshAudit.body.hash, ...
        'freeSurfaceMeshHash', meshAudit.freeSurface.hash, ...
        'bottomMeshHash', meshAudit.bottom.hash, ...
        'outerBoundaryMeshHash', meshAudit.outerBoundary.hash, ...
        'mergedGeometryHash', meshAudit.geometry.hash, ...
        'frequency', omega, 'headings', cfg.wave.headings, ...
        'globalDofCount', globalDofCount, ...
        'calculatedLocalDofs', cfg.calc_modes, ...
        'problemType', problemType, ...
        'modeParity', modeParity, 'groupParity', groupParity, ...
        'solverOptions', solverOptions, ...
        'codeVersion', codeVersion.fingerprint);

    %% 阶段 3: 序列化并计算最终键

    cacheKey = sha256_hash(jsonencode(cacheSpecification));
end
