function diagnostics = compute_rankine_physical_bc_diagnostics( ...
        boundaryPotential, canonicalDerivative, geometry, stats, cfg, ...
        parity, problemName, epsilonFactor)
% COMPUTE_RANKINE_PHYSICAL_BC_DIAGNOSTICS Off-surface physical BC audit.
%
% This is intentionally independent of K*Phi-rhs. It reconstructs Phi at
% fluid-side offsets h/2, h, and 2h and applies second-order one-sided and
% Richardson normal differentiation using the solved boundary Phi as f(0).

    if nargin < 9 || isempty(epsilonFactor)
        epsilonFactor = 0.35;
    end
    panelCount = geometry.total_panels;
    assert(size(boundaryPotential, 1) == panelCount && ...
        isequal(size(boundaryPotential), size(canonicalDerivative)), ...
        'CRESTU:PhysicalBCShape', ...
        'Physical BC diagnostic boundary arrays have inconsistent shapes.');
    validateattributes(epsilonFactor, {'numeric'}, ...
        {'scalar', 'real', 'positive', 'finite'});
    orientation = get_rankine_source_orientation( ...
        stats, geometry.normals, geometry.vertices);
    canonicalNormals = geometry.normals .* orientation.columnSigns;
    localPanelSize = sqrt(geometry.areas(:));
    epsilon = epsilonFactor * localPanelSize;
    assert(all(isfinite(epsilon) & epsilon > 0));
    pointsHalf = geometry.centers + canonicalNormals .* (epsilon / 2);
    pointsOne = geometry.centers + canonicalNormals .* epsilon;
    pointsTwo = geometry.centers + canonicalNormals .* (2 * epsilon);
    fprintf('[DIAG] Physical BC %s | panels=%d columns=%d | offsets=h/2,h,2h\n', ...
        char(problemName), panelCount, size(boundaryPotential, 2));
    phiHalf = evaluate_rankine_off_surface(pointsHalf, geometry.normals, ...
        geometry.vertices, stats, boundaryPotential, canonicalDerivative, ...
        cfg, parity);
    fprintf('[DIAG] Physical BC %s | completed offset h/2\n', ...
        char(problemName));
    phiOne = evaluate_rankine_off_surface(pointsOne, geometry.normals, ...
        geometry.vertices, stats, boundaryPotential, canonicalDerivative, ...
        cfg, parity);
    fprintf('[DIAG] Physical BC %s | completed offset h\n', ...
        char(problemName));
    phiTwo = evaluate_rankine_off_surface(pointsTwo, geometry.normals, ...
        geometry.vertices, stats, boundaryPotential, canonicalDerivative, ...
        cfg, parity);
    fprintf('[DIAG] Physical BC %s | completed offset 2h\n', ...
        char(problemName));
    epsilonMatrix = reshape(epsilon, [], 1);
    qAtH = (-3 * boundaryPotential + 4 * phiOne - phiTwo) ./ ...
        (2 * epsilonMatrix);
    qAtHalf = (-3 * boundaryPotential + 4 * phiHalf - phiOne) ./ ...
        epsilonMatrix;
    qRichardson = (4 * qAtHalf - qAtH) / 3;
    residual = qRichardson - canonicalDerivative;
    lengthScale = median(localPanelSize);
    columnScale = max(abs(canonicalDerivative), [], 1);
    columnScale = max(columnScale, ...
        max(abs(boundaryPotential), [], 1) / max(lengthScale, eps));
    columnScale = max(columnScale, eps);
    normalizedResidual = abs(residual) ./ columnScale;
    epsilonSensitivity = abs(qAtHalf - qAtH) ./ columnScale;
    potentialTraceMismatch = abs(phiHalf - boundaryPotential) ./ ...
        max(max(abs(boundaryPotential), [], 1), eps);
    partitions = component_partitions(stats);
    partitionNames = fieldnames(partitions);
    partitionSummary = struct();
    partitionByColumn = struct();
    allValidated = true;
    for partitionIndex = 1:numel(partitionNames)
        name = partitionNames{partitionIndex};
        rows = partitions.(name);
        if isempty(rows)
            partitionSummary.(name) = struct('rowCount', 0, ...
                'sampleCount', 0, 'absoluteResidual', empty_summary(), ...
                'normalizedResidual', empty_summary(), ...
                'epsilonSensitivity', empty_summary(), ...
                'potentialTraceMismatch', empty_summary(), ...
                'status', 'NOT_APPLICABLE_EMPTY_COMPONENT');
            partitionByColumn.(name) = struct([]);
            continue
        end
        absoluteValues = abs(residual(rows, :));
        normalizedValues = normalizedResidual(rows, :);
        sensitivityValues = epsilonSensitivity(rows, :);
        traceValues = potentialTraceMismatch(rows, :);
        finitePass = all(isfinite([absoluteValues(:); ...
            normalizedValues(:); sensitivityValues(:); traceValues(:)]));
        normalizedStats = summary_values(normalizedValues);
        sensitivityStats = summary_values(sensitivityValues);
        statusPass = finitePass && normalizedStats.p95 <= 0.25 && ...
            sensitivityStats.p95 <= 0.25;
        if statusPass
            status = 'VALIDATED_AT_SELECTED_EPSILON';
        else
            status = 'NOT_VALIDATED_NEAR_BOUNDARY_RECONSTRUCTION';
        end
        allValidated = allValidated && statusPass;
        partitionSummary.(name) = struct('rowCount', numel(rows), ...
            'sampleCount', numel(absoluteValues), ...
            'absoluteResidual', summary_values(absoluteValues), ...
            'normalizedResidual', normalizedStats, ...
            'epsilonSensitivity', sensitivityStats, ...
            'potentialTraceMismatch', summary_values(traceValues), ...
            'status', status);
        columnRecords = repmat(struct('columnIndex', 0, ...
            'normalizationScale', NaN, 'normalizedMedian', NaN, ...
            'normalizedP95', NaN, 'normalizedMaximum', NaN, ...
            'epsilonSensitivityP95', NaN), size(boundaryPotential, 2), 1);
        for columnIndex = 1:size(boundaryPotential, 2)
            item = summary_values(normalizedValues(:, columnIndex));
            sensitivityItem = summary_values( ...
                sensitivityValues(:, columnIndex));
            columnRecords(columnIndex) = struct( ...
                'columnIndex', columnIndex, ...
                'normalizationScale', columnScale(columnIndex), ...
                'normalizedMedian', item.median, ...
                'normalizedP95', item.p95, ...
                'normalizedMaximum', item.maximum, ...
                'epsilonSensitivityP95', sensitivityItem.p95);
        end
        partitionByColumn.(name) = columnRecords;
    end
    if allValidated
        overallStatus = 'VALIDATED_AT_SELECTED_EPSILON';
    else
        overallStatus = 'NOT_VALIDATED_ONE_OR_MORE_BOUNDARIES';
    end
    diagnostics = struct('schemaVersion', 1, 'enabled', true, ...
        'problemName', char(problemName), ...
        'diagnosticType', ...
        'off-surface-Green-reconstruction-physical-normal-BC-residual', ...
        'isPhysicalBoundaryConditionResidual', true, ...
        'isAlgebraicResidual', false, ...
        'timeConvention', 'exp(+i*omega*t)', ...
        'canonicalNormalConvention', char(orientation.convention), ...
        'normalDerivativeFormula', ...
        'q_R=(4*q_(h/2)-q_h)/3; second-order one-sided traces', ...
        'epsilonFactorTimesSqrtPanelArea', epsilonFactor, ...
        'epsilonMinMedianMaxM', [min(epsilon), median(epsilon), max(epsilon)], ...
        'normalizationDefinition', ...
        'per-column max(normInf(q_target),normInf(Phi)/median(sqrt(area)))', ...
        'normalizationScaleByColumn', columnScale, ...
        'partition', partitionSummary, ...
        'partitionByColumn', partitionByColumn, ...
        'overallStatus', overallStatus, ...
        'allBoundariesValidated', allValidated, ...
        'limitations', ['Constant panels and near-singular evaluation can ', ...
        'dominate as epsilon decreases; K*Phi-rhs is not used as a ', ...
        'substitute for this physical residual.']);
end

function partitions = component_partitions(stats)
    nb = stats.total_body_panels;
    nf = stats.fs_panels;
    ns = stats.seabed_panels;
    no = stats.farfield_panels;
    partitions = struct('body', 1:nb, ...
        'freeSurface', nb + (1:nf), ...
        'bottom', nb + nf + (1:ns), ...
        'outerBoundary', nb + nf + ns + (1:no));
end

function output = summary_values(values)
    values = sort(reshape(real(values), [], 1));
    output = struct('median', quantile_linear(values, 0.5), ...
        'p95', quantile_linear(values, 0.95), ...
        'maximum', max(values));
end

function output = empty_summary()
    output = struct('median', NaN, 'p95', NaN, 'maximum', NaN);
end

function value = quantile_linear(sortedValues, probability)
    count = numel(sortedValues);
    if count == 1
        value = sortedValues(1);
        return
    end
    position = 1 + (count - 1) * probability;
    lowerIndex = floor(position);
    upperIndex = ceil(position);
    fraction = position - lowerIndex;
    value = (1 - fraction) * sortedValues(lowerIndex) + ...
        fraction * sortedValues(upperIndex);
end
