function diagnostics = compute_rankine_algebraic_diagnostics( ...
        systemMatrix, solution, rightHandSide, stats, problemName)
% COMPUTE_RANKINE_ALGEBRAIC_DIAGNOSTICS Summarize K*phi-rhs by row block.
% These are algebraic solved-system residuals, not off-surface physical-BC
% residuals. The distinction is retained explicitly in saved metadata.

    residual = systemMatrix * solution - rightHandSide;
    assert(isequal(size(residual), size(rightHandSide)), ...
        'CRESTU:AlgebraicDiagnosticShape', ...
        'Residual and right-hand-side dimensions differ.');
    rowSets = partition_rows(stats, size(systemMatrix, 1));
    names = fieldnames(rowSets);
    partition = struct();
    boundaryMax = struct();
    for nameIndex = 1:numel(names)
        name = names{nameIndex};
        rows = rowSets.(name);
        partition.(name) = summarize_residual( ...
            residual(rows, :), rightHandSide(rows, :), numel(rows));
        boundaryMax.(name) = max_or_nan(abs(solution(rows, :)));
    end
    diagnostics = struct( ...
        'enabled', true, ...
        'problemName', char(problemName), ...
        'diagnosticType', ...
        'partitioned-algebraic-residual-Kphi-minus-rhs', ...
        'isPhysicalBoundaryConditionResidual', false, ...
        'physicalBCResidualStatus', 'NOT_COMPUTED_OFF_SURFACE', ...
        'matrixRows', size(systemMatrix, 1), ...
        'matrixColumns', size(systemMatrix, 2), ...
        'rightHandSideColumns', size(rightHandSide, 2), ...
        'absoluteResidualFrobeniusNorm', norm(residual, 'fro'), ...
        'relativeResidualFrobeniusNorm', norm(residual, 'fro') / ...
            max(norm(rightHandSide, 'fro'), eps), ...
        'partition', partition, ...
        'solutionColumnL2Norms', sqrt(sum(abs(solution) .^ 2, 1)), ...
        'solutionL2NormAllEntries', norm(solution(:), 2), ...
        'solutionFrobeniusNorm', norm(solution, 'fro'), ...
        'solutionMaximumMagnitude', max_or_nan(abs(solution)), ...
        'boundaryMaximumPotentialMagnitude', boundaryMax);
end

function rows = partition_rows(stats, matrixSize)
    counts = [stats.total_body_panels, stats.fs_panels, ...
        stats.seabed_panels, stats.farfield_panels];
    assert(sum(counts) == matrixSize, 'CRESTU:AlgebraicDiagnosticCounts', ...
        'Boundary partition counts do not match the matrix size.');
    edges = [0, cumsum(counts)];
    rows = struct('body', edges(1) + 1:edges(2), ...
        'freeSurface', edges(2) + 1:edges(3), ...
        'bottom', edges(3) + 1:edges(4), ...
        'outerBoundary', edges(4) + 1:edges(5));
end

function summary = summarize_residual(residual, rightHandSide, rowCount)
    magnitudes = abs(residual(:));
    if isempty(magnitudes)
        summary = struct('rowCount', rowCount, 'sampleCount', 0, ...
            'absoluteNorm2', NaN, 'absoluteFrobeniusNorm', NaN, ...
            'relativeFrobeniusNorm', NaN, 'medianAbsolute', NaN, ...
            'p95Absolute', NaN, 'maximumAbsolute', NaN);
        return
    end
    sorted = sort(magnitudes);
    p95 = sorted(max(1, ceil(0.95 * numel(sorted))));
    summary = struct('rowCount', rowCount, ...
        'sampleCount', numel(magnitudes), ...
        'absoluteNorm2', norm(magnitudes, 2), ...
        'absoluteFrobeniusNorm', norm(residual, 'fro'), ...
        'relativeFrobeniusNorm', norm(residual, 'fro') / ...
            max(norm(rightHandSide, 'fro'), eps), ...
        'medianAbsolute', median(magnitudes), ...
        'p95Absolute', p95, ...
        'maximumAbsolute', max(magnitudes));
end

function value = max_or_nan(values)
    if isempty(values)
        value = NaN;
    else
        value = max(values(:));
    end
end
