function diagnostics = estimate_rankine_conditioning(systemMatrix)
% ESTIMATE_RANKINE_CONDITIONING Audit raw and equilibrated matrix rcond.
% Scaling is diagnostic only and is never applied to the production solve.

    assert(ismatrix(systemMatrix) && ...
        size(systemMatrix, 1) == size(systemMatrix, 2), ...
        'CRESTU:ConditionMatrixShape', ...
        'Condition diagnostics require a square matrix.');
    rawRcond = rcond(systemMatrix);
    rowMaximum = max(abs(systemMatrix), [], 2);
    rowValid = isfinite(rowMaximum) & rowMaximum > 0;
    rowScale = ones(size(rowMaximum));
    rowScale(rowValid) = 1 ./ rowMaximum(rowValid);
    rowScaled = systemMatrix .* rowScale;
    columnMaximum = max(abs(rowScaled), [], 1);
    columnValid = isfinite(columnMaximum) & columnMaximum > 0;
    columnScale = ones(size(columnMaximum));
    columnScale(columnValid) = 1 ./ columnMaximum(columnValid);
    equilibrated = rowScaled .* columnScale;
    scaledRcond = rcond(equilibrated);
    rawEstimateAvailable = isfinite(rawRcond) && rawRcond > 0;
    scaledEstimateAvailable = isfinite(scaledRcond) && scaledRcond > 0 && ...
        all(rowValid) && all(columnValid);
    diagnostics = struct( ...
        'enabled', true, ...
        'matrixRows', size(systemMatrix, 1), ...
        'matrixColumns', size(systemMatrix, 2), ...
        'estimator', 'MATLAB-rcond dense reciprocal 1-norm estimator', ...
        'rawRcondEstimate', rawRcond, ...
        'scaledRcondEstimate', scaledRcond, ...
        'scaling', ['row max-abs equilibration followed by column max-abs ', ...
        'equilibration; diagnostic only, production solve remains unscaled'], ...
        'rawEstimateAvailable', rawEstimateAvailable, ...
        'scaledEstimateAvailable', scaledEstimateAvailable, ...
        'rawStatus', availability_status(rawEstimateAvailable), ...
        'scaledStatus', availability_status(scaledEstimateAvailable), ...
        'minimumRowScale', min(rowScale), ...
        'maximumRowScale', max(rowScale), ...
        'minimumColumnScale', min(columnScale), ...
        'maximumColumnScale', max(columnScale), ...
        'limitations', ['rcond is a dense reciprocal 1-norm estimate, not ', ...
        'an exact SVD condition number. A scaled/unscaled change is only a ', ...
        'numerical equilibration trend; neither value establishes physical ', ...
        'accuracy or convergence.']);
end

function status = availability_status(available)
    if available
        status = 'ESTIMATE_AVAILABLE';
    else
        status = 'ESTIMATE_UNAVAILABLE_ZERO_NONFINITE_OR_UNSCALABLE';
    end
end
