function freeSurfaceBC = get_rankine_free_surface_robin_bc( ...
        centers, stats, omega, gravity, cfg)
% GET_RANKINE_FREE_SURFACE_ROBIN_BC Resolve every physical FS coefficient.

    validateattributes(omega, {'numeric'}, ...
        {'scalar', 'real', 'positive', 'finite'});
    validateattributes(gravity, {'numeric'}, ...
        {'scalar', 'real', 'positive', 'finite'});
    centers = reshape(centers, [], 3);
    bodyCount = stats.total_body_panels;
    freeSurfaceCount = stats.fs_panels;
    bottomCount = stats.seabed_panels;
    outerCount = stats.farfield_panels;
    assert(size(centers, 1) == bodyCount + freeSurfaceCount + ...
        bottomCount + outerCount, 'CRESTU:FreeSurfaceBCCounts', ...
        'Boundary counts do not match the collocation geometry.');
    [physicalK, ~] = solve_wave_dispersion(omega, gravity, cfg.water_depth);
    nu0 = omega ^ 2 / gravity;
    startRadius = cfg.fs.r_inner;
    width = cfg.fs.r_outer - cfg.fs.r_inner;
    actualMu0 = min(2.5, max(cfg.fs.mu0, 12 / (physicalK * width)));
    if isfield(cfg, 'phase2_2_controls') && ...
            isfield(cfg.phase2_2_controls, 'effective')
        state = cfg.phase2_2_controls.effective;
        startRadius = state.spongeStartRadiusM;
        width = state.spongeWidthM;
        actualMu0 = state.actualMu0;
    end
    assert(isfinite(startRadius) && isfinite(width) && width > 0 && ...
        isfinite(actualMu0) && actualMu0 >= 0, ...
        'CRESTU:FreeSurfaceBCState', ...
        'Resolved free-surface sponge state is invalid.');
    rows = bodyCount + (1:freeSurfaceCount);
    radii = hypot(centers(rows, 1), centers(rows, 2));
    normalizedPosition = max(0, min(1, (radii - startRadius) / width));
    damping = actualMu0 * normalizedPosition .^ 2;
    nu = nu0 * (1 - 1i * damping);
    coefficientHash = numeric_sha256([real(nu); imag(nu)]);
    dampingHash = numeric_sha256(damping);
    radiusHash = numeric_sha256(radii);
    cacheSpecification = struct( ...
        'schemaVersion', 1, ...
        'timeConvention', 'exp(+i*omega*t)', ...
        'canonicalSourceColumn', 'D-nu_j*S', ...
        'nuFormula', 'nu=(omega^2/g)*(1-i*mu(r))', ...
        'profile', 'mu=actualMu0*clamp((r-start)/width,0,1)^2', ...
        'panelCount', freeSurfaceCount, ...
        'nu0PerM', nu0, ...
        'spongeStartRadiusM', startRadius, ...
        'spongeWidthM', width, ...
        'spongeEndRadiusM', startRadius + width, ...
        'actualMu0', actualMu0, ...
        'radiusRangeM', range_or_nan(radii), ...
        'dampingMinMedianMax', min_median_max(damping), ...
        'nuRealRangePerM', range_or_nan(real(nu)), ...
        'nuImagRangePerM', range_or_nan(imag(nu)), ...
        'freeSurfaceRadiusSHA256', radiusHash, ...
        'freeSurfaceDampingSHA256', dampingHash, ...
        'freeSurfaceRobinCoefficientSHA256', coefficientHash);
    freeSurfaceBC = struct('nu', nu, 'damping', damping, ...
        'radii', radii, 'nu0', nu0, 'physicalK', physicalK, ...
        'actualMu0', actualMu0, 'startRadius', startRadius, ...
        'width', width, 'cacheSpecification', cacheSpecification);
end

function values = range_or_nan(input)
    if isempty(input), values = [NaN, NaN]; ...
    else, values = [min(input), max(input)]; end
end

function values = min_median_max(input)
    if isempty(input), values = [NaN, NaN, NaN]; ...
    else, values = [min(input), median(input), max(input)]; end
end

function hashText = numeric_sha256(values)
    values = reshape(double(values), 1, []);
    bytes = [reshape(typecast(uint64(size(values)), 'uint8'), 1, []), ...
        reshape(typecast(values, 'uint8'), 1, [])];
    hashText = sha256_hash(bytes);
end
