function state = get_rankine_boundary_operator_state( ...
        freeSurfaceSpecification, outerSpecification, geometrySHA256)
% GET_RANKINE_BOUNDARY_OPERATOR_STATE Hash geometry and actual BC coefficients.

    assert(isstruct(freeSurfaceSpecification) && ...
        isfield(freeSurfaceSpecification, ...
        'freeSurfaceRobinCoefficientSHA256'), ...
        'CRESTU:BoundaryOperatorFreeSurface', ...
        'Boundary operator state requires the actual FS coefficient hash.');
    assert(isstruct(outerSpecification), ...
        'CRESTU:BoundaryOperatorOuter', ...
        'Boundary operator state requires the outer-BC specification.');
    if isfield(outerSpecification, 'gammaSHA256')
        outerGammaHash = outerSpecification.gammaSHA256;
    else
        outerGammaHash = sha256_hash('CRESTU_EMPTY_OUTER_GAMMA_V1');
    end
    sourceOrientation = get_rankine_source_orientation();
    core = struct( ...
        'schemaVersion', 1, ...
        'geometrySHA256', char(geometrySHA256), ...
        'bodySourceColumn', 'D', ...
        'freeSurfaceSourceColumn', 'D-nu_j*S', ...
        'bottomSourceColumn', 'D', ...
        'outerSourceColumn', 'D+gamma_j*S', ...
        'freeSurfacePanelCount', freeSurfaceSpecification.panelCount, ...
        'freeSurfaceRobinCoefficientSHA256', ...
            freeSurfaceSpecification.freeSurfaceRobinCoefficientSHA256, ...
        'freeSurfaceDampingSHA256', ...
            freeSurfaceSpecification.freeSurfaceDampingSHA256, ...
        'outerGammaSHA256', outerGammaHash, ...
        'doubleLayerOrientationSHA256', sourceOrientation.signatureHash);
    state = core;
    state.boundaryOperatorStateSHA256 = sha256_hash(jsonencode(core));
end
