function codeVersion = get_rankine_code_version()
% GET_RANKINE_CODE_VERSION Fingerprint numerical source files affecting cache validity.
%
% Syntax:
%   codeVersion = get_rankine_code_version()
%
% Outputs:
%   codeVersion - Semantic label, combined code hash, and per-file hashes.

    %% 阶段 1: 定位影响 Rankine 解的源码

    potentialDirectory = fileparts(mfilename('fullpath'));
    sourceDirectory = fileparts(potentialDirectory);
    projectDirectory = fileparts(sourceDirectory);
    relativeFiles = { ...
        fullfile('Source Code', '1.Input', 'read_config.m'), ...
        fullfile('Source Code', '2.Mesh', 'build_bmf_domain.m'), ...
        fullfile('Source Code', '2.Mesh', 'generate_free_surface_bmf.m'), ...
        fullfile('Source Code', '2.Mesh', 'generate_multibody_free_surface_bmf.m'), ...
        fullfile('Source Code', '2.Mesh', 'generate_seabed_mesh.m'), ...
        fullfile('Source Code', '2.Mesh', 'generate_seabed_disk_mesh.m'), ...
        fullfile('Source Code', '2.Mesh', 'generate_reduced_seabed_mesh.m'), ...
        fullfile('Source Code', '2.Mesh', 'generate_farfield_mesh.m'), ...
        fullfile('Source Code', '2.Mesh', 'merge_domain_geometry.m'), ...
        fullfile('Source Code', '2.Mesh', 'tune_sponge_layer.m'), ...
        fullfile('Source Code', '4.Potential', 'assemble_rankine_matrix.m'), ...
        fullfile('Source Code', '4.Potential', 'rankine_panel_integrals.m'), ...
        fullfile('Source Code', '4.Potential', 'solve_complex_system.m'), ...
        fullfile('Source Code', '5.Force', 'compute_hydrodynamic_coeffs.m'), ...
        fullfile('Source Code', '5.Force', 'compute_radiation_damping_energy.m'), ...
        fullfile('Source Code', '5.Force', 'compute_wave_excitation.m'), ...
        fullfile('Source Code', '5.Force', 'solve_rao.m'), ...
        fullfile('Case_Wave', 'run_frequency_domain_case.m')};
    fileHashes = cell(size(relativeFiles));

    %% 阶段 2: 计算逐文件和组合代码哈希

    for fileIndex = 1:numel(relativeFiles)
        absoluteFilename = fullfile(projectDirectory, relativeFiles{fileIndex});
        fileHashes{fileIndex} = sha256_file_hash(absoluteFilename);
    end

    semanticVersion = 'rankine-forensic-cache-v1';
    combinedText = strjoin([{semanticVersion}, relativeFiles, fileHashes], '|');
    codeVersion = struct('semanticVersion', semanticVersion, ...
        'fingerprint', sha256_hash(combinedText), ...
        'relativeFiles', {relativeFiles}, 'fileHashes', {fileHashes});
end
