function summary = Finalize_Phase3_2B()
% FINALIZE_PHASE3_2B Close blocked continuation without invented results.

    %% Stage 1: Re-read and enforce all completed evidence

    definition = phase32b.initialize();
    artifact = definition.artifactDirectory;
    frozen = readtable(fullfile(artifact, ...
        'Phase3_2B_V5_Frozen_Mesh_Manifest.csv'), 'TextType', 'string');
    response = readtable(fullfile(artifact, ...
        'Phase3_2B_Sentinel_Response.csv'), 'TextType', 'string');
    convergence = readtable(fullfile(artifact, ...
        'Phase3_2B_Sentinel_Convergence.csv'), 'TextType', 'string');
    legacy = readtable(fullfile(artifact, ...
        'Phase3_2B_Legacy_Regression.csv'), 'TextType', 'string');
    reviewerFile = fullfile(artifact, 'Phase3_2B_Reviewer_Gate.csv');
    assert(isfile(reviewerFile), 'CRESTU:Phase32BReviewerMissing', ...
        'Independent reviewer gate must exist before finalization.');
    reviewer = readtable(reviewerFile, 'TextType', 'string', ...
        'Delimiter', ',');
    assert(height(frozen) == 18 && ...
        all(frozen.baseline_reproducibility == "PASS"), ...
        'CRESTU:Phase32BFinalFrozen', 'Frozen v5 evidence is incomplete.');
    assert(height(response) == 18 && ...
        numel(unique(response.case_id)) == 18 && ...
        all(response.preassembly_status == "PASS") && ...
        all(response.algebraic_gate_status == "PASS") && ...
        all(lower(response.cache_status) == "miss"), ...
        'CRESTU:Phase32BFinalSentinel', ...
        'Sentinel clean/algebraic evidence is incomplete.');
    assert(height(legacy) == 16 && all(legacy.status == "PASS") && ...
        nnz(legacy.suite_position == "START") == 8 && ...
        nnz(legacy.suite_position == "END") == 8, ...
        'CRESTU:Phase32BFinalLegacy', ...
        'Start/end legacy/control regression must be 16/16 PASS.');
    mandatory = convergence.gate_role == "MANDATORY";
    mandatoryFailCount = nnz(convergence.gate_status(mandatory) == "FAIL");
    assert(nnz(mandatory) == 24 && mandatoryFailCount == 16, ...
        'CRESTU:Phase32BFinalResponseGate', ...
        'Sentinel response FAIL count no longer matches authoritative evidence.');
    reviewerBlockers = sum(reviewer.blocker_count);

    %% Stage 2: Persist explicit not-run records for blocked continuations

    write_not_run_tables(definition);
    finalStatus = build_final_status(reviewerBlockers);
    writetable(finalStatus, fullfile(artifact, ...
        'Phase3_2B_Final_Status.csv'));
    write_main_report(definition, response, convergence, reviewerBlockers);
    write_human_review(definition);

    %% Stage 3: Write Git, commit, and file-hygiene audits

    write_commit_ledger(definition);
    write_git_diff(definition);
    write_file_hygiene(definition);
    summary = struct('schemaVersion', 1, 'overallStatus', 'FAIL', ...
        'v5MeshReproducibility', 'PASS', ...
        'sentinelAlgebraicGate', 'PASS', ...
        'sentinelResponseGate', 'FAIL', ...
        'mandatoryFailCount', mandatoryFailCount, ...
        'resonanceConvergence', 'NOT_RUN_BLOCKED', ...
        'formalMeshConvergence', 'NOT_RUN_BLOCKED', ...
        'reviewerBlockers', reviewerBlockers, ...
        'readyForPhase33WamitAttribution', false, ...
        'readyForProduction', false);
    fprintf('[RESULT] PHASE3_2B_OVERALL = FAIL\n');
    fprintf('[RESULT] SENTINEL_ALGEBRAIC_GATE = PASS\n');
    fprintf('[RESULT] SENTINEL_RESPONSE_GATE = FAIL\n');
    fprintf('[RESULT] RESONANCE_CONVERGENCE = NOT_RUN_BLOCKED\n');
    fprintf('[RESULT] FORMAL_MESH_CONVERGENCE = NOT_RUN_BLOCKED\n');
    fprintf('[RESULT] REVIEWER_BLOCKERS = %d\n', reviewerBlockers);
    fprintf('[RESULT] READY_FOR_PHASE3_3_WAMIT_ATTRIBUTION = NO\n');
    fprintf('[RESULT] READY_FOR_PRODUCTION = NO\n');
end

function write_not_run_tables(definition)
    stage = "RESONANCE_TRACKING";
    status = "NOT_RUN_BLOCKED";
    reason = "SENTINEL_RESPONSE_GATE_FAIL_16_OF_24_MANDATORY";
    plannedScope = "L1_L2_L3_AT_1P30_TO_1P50_STEP_0P02_RAD_PER_S";
    numericResultsPresent = "NO";
    writetable(table(stage, status, reason, plannedScope, ...
        numericResultsPresent), fullfile(definition.artifactDirectory, ...
        'Phase3_2B_Resonance_Tracking.csv'));

    stage = "FORMAL_RESPONSE";
    plannedScope = "L1_L2_L3_AT_0P5_TO_2P0_STEP_0P1_RAD_PER_S";
    writetable(table(stage, status, reason, plannedScope, ...
        numericResultsPresent), fullfile(definition.artifactDirectory, ...
        'Phase3_2B_Formal_Response.csv'));
    stage = "FORMAL_CONVERGENCE";
    writetable(table(stage, status, reason, plannedScope, ...
        numericResultsPresent), fullfile(definition.artifactDirectory, ...
        'Phase3_2B_Formal_Convergence.csv'));
end

function statusTable = build_final_status(reviewerBlockers)
    status_name = ["V5_MESH_REPRODUCIBILITY"; "GEOMETRY_VALIDITY"; ...
        "RESOURCE_GATE"; "QUALITY_CONTROLLED_V2_DEFAULT"; ...
        "LEGACY_GEOMETRY_REGRESSION"; "LEGACY_RESPONSE_REGRESSION"; ...
        "SENTINEL_CLEAN_SOLVES"; "ALGEBRAIC_VALIDITY"; ...
        "SENTINEL_MESH_CONVERGENCE"; "RESONANCE_CONVERGENCE"; ...
        "FORMAL_MESH_CONVERGENCE"; "ASYMPTOTIC_RANGE_PROOF"; ...
        "PRODUCTION_MESH_CANDIDATE"; "PHYSICAL_VALIDATION"; ...
        "READY_FOR_PHASE3_3_WAMIT_ATTRIBUTION"; ...
        "READY_FOR_PRODUCTION"; "REVIEWER_BLOCKERS"; ...
        "PHASE3_2B_OVERALL"];
    status_value = ["PASS_18_OF_18"; "PASS_72_COMPONENT_ROWS_FROZEN"; ...
        "PASS_SERIAL_L3"; "OFF_LEGACY_DEFAULT"; ...
        "PASS_EXACT_HASH_START_AND_END"; "PASS_START_AND_END"; ...
        "PASS_18_OF_18_CACHE_MISS"; "PASS_18_OF_18"; ...
        "FAIL_16_OF_24_MANDATORY"; ...
        "NOT_RUN_BLOCKED_SENTINEL_RESPONSE_FAIL"; ...
        "NOT_RUN_BLOCKED_SENTINEL_RESPONSE_FAIL"; ...
        "NOT_DEMONSTRATED_OVERALL"; "NONE"; ...
        "PARTIAL_NO_NEW_PHYSICAL_CLOSURE"; "NO"; "NO"; ...
        string(reviewerBlockers); "FAIL"];
    evidence = ["Phase3_2B_V5_Frozen_Mesh_Manifest.csv"; ...
        "Phase3_2B_V5_Frozen_Mesh_Manifest.csv"; ...
        "Phase3_2B_Resource_Plan.csv"; ...
        "Phase3_2B_Legacy_Regression.csv"; ...
        "Phase3_2B_Legacy_Regression.csv"; ...
        "Phase3_2B_Legacy_Regression.csv"; ...
        "Phase3_2B_Sentinel_Response.csv"; ...
        "Phase3_2B_Condition_Residual.csv"; ...
        "Phase3_2B_Sentinel_Convergence.csv"; ...
        "Phase3_2B_Resonance_Tracking.csv"; ...
        "Phase3_2B_Formal_Convergence.csv"; ...
        "Phase3_2B_Sentinel_Convergence.csv"; ...
        "sentinel FAIL prevents recommendation"; ...
        "no WAMIT attribution or independent physical benchmark"; ...
        "sentinel response gate failed"; ...
        "production default unchanged"; ...
        "Phase3_2B_Reviewer_Gate.csv"; ...
        "PHASE3_2B_RESPONSE_CONVERGENCE_CN.md"];
    statusTable = table(status_name, status_value, evidence);
end

function write_main_report(definition, response, convergence, reviewerBlockers)
    fileID = fopen(fullfile(definition.artifactDirectory, ...
        'PHASE3_2B_RESPONSE_CONVERGENCE_CN.md'), 'w');
    assert(fileID >= 0, 'CRESTU:Phase32BFinalReportOpen', ...
        'Cannot create final response convergence report.');
    cleanup = onCleanup(@() fclose(fileID));
    mandatory = convergence.gate_role == "MANDATORY";
    fprintf(fileID, '# CRESTU-1F Phase 3.2B 响应收敛最终报告\n\n');
    fprintf(fileID, '```ini\nPHASE3_2B_OVERALL = FAIL\n');
    fprintf(fileID, 'V5_MESH_REPRODUCIBILITY = PASS_18_OF_18\n');
    fprintf(fileID, 'SENTINEL_CLEAN_SOLVES = PASS_%d_OF_18_CACHE_MISS\n', ...
        nnz(lower(response.cache_status) == "miss"));
    fprintf(fileID, 'SENTINEL_ALGEBRAIC_GATE = PASS_%d_OF_18\n', ...
        nnz(response.algebraic_gate_status == "PASS"));
    fprintf(fileID, 'SENTINEL_RESPONSE_GATE = FAIL_%d_OF_%d_MANDATORY\n', ...
        nnz(convergence.gate_status(mandatory) == "FAIL"), nnz(mandatory));
    fprintf(fileID, 'RESONANCE_CONVERGENCE = NOT_RUN_BLOCKED\n');
    fprintf(fileID, 'FORMAL_MESH_CONVERGENCE = NOT_RUN_BLOCKED\n');
    fprintf(fileID, 'ASYMPTOTIC_RANGE = NOT_DEMONSTRATED_OVERALL\n');
    fprintf(fileID, 'PRODUCTION_MESH_CANDIDATE = NONE\n');
    fprintf(fileID, 'PHYSICAL_VALIDATION = PARTIAL\n');
    fprintf(fileID, 'REVIEWER_BLOCKERS = %d\n', reviewerBlockers);
    fprintf(fileID, 'READY_FOR_PHASE3_3_WAMIT_ATTRIBUTION = NO\n');
    fprintf(fileID, 'READY_FOR_PRODUCTION = NO\n```\n\n');
    fprintf(fileID, '## 已证明\n\n');
    fprintf(fileID, ['v5 网格 18/18 重生成、组件/组合网格和 source/control/operator ', ...
        'hash 全部匹配；18 个 sentinel 全为唯一临时目录中的 clean solve 和 ', ...
        'cache MISS。所有 raw/scaled rcond、radiation/diffraction residual、', ...
        'outer operator audit 和 finite gate 均通过。\n\n']);
    fprintf(fileID, '## 响应结论\n\n');
    fprintf(fileID, ['24 个 mandatory L2→L3 比较中 16 个超过预声明门槛。', ...
        '失败覆盖 0.6 的 B33、1.0 的 A33/B33/F3，以及 1.4、1.5、2.0 ', ...
        '的大部分或全部主量。所有 floor 扫描在 0.1× 到 10× 之间保持相同', ...
        '结论；Phase 3.2A bridge 的 1.5 L3 原始响应与本阶段逐字段 exact match，', ...
        '因此没有证据把 FAIL 归因于 stale cache、提取错误或 source 漂移。\n\n']);
    fprintf(fileID, '## 合法停止\n\n');
    fprintf(fileID, ['sentinel response gate 为 FAIL，故按冻结 continuation gate ', ...
        '不运行 resonance tracking 和 16-frequency formal sweep；相应 CSV ', ...
        '只保存 `NOT_RUN_BLOCKED`，不含伪造数值。没有修改 topology、physics、', ...
        'floor 或 tolerance，也没有 production-mesh recommendation。\n\n']);
    fprintf(fileID, '## 可信度\n\n');
    fprintf(fileID, ['代数有效性和 v5 可复现性为已证明；sentinel 不收敛为当前', ...
        '网格族和门槛范围内的数值证据。完整 physical validation、WAMIT ', ...
        'quantitative attribution 和 production readiness 均未建立。\n']);
    clear cleanup
end

function write_human_review(definition)
    fileID = fopen(fullfile(definition.artifactDirectory, ...
        'PHASE3_2B_HUMAN_REVIEW_10MIN_CN.md'), 'w');
    assert(fileID >= 0, 'CRESTU:Phase32BHumanReviewOpen', ...
        'Cannot create human review guide.');
    cleanup = onCleanup(@() fclose(fileID));
    fprintf(fileID, '# Phase 3.2B 十分钟人工复核\n\n');
    fprintf(fileID, '1. 查看 `Phase3_2B_Final_Status.csv`，确认 overall=FAIL、production=NO。\n');
    fprintf(fileID, '2. 查看 frozen manifest：18 行、V2 显式、baseline reproducibility 全 PASS。\n');
    fprintf(fileID, '3. 查看 sentinel response：18 unique case、18 cache MISS、18 algebraic PASS。\n');
    fprintf(fileID, '4. 查看 condition/residual：最小 rcond 仍高于 1e-12，最大 residual 低于 1e-10。\n');
    fprintf(fileID, '5. 查看 convergence：24 mandatory 中 16 FAIL，floor sensitivity 均稳定。\n');
    fprintf(fileID, '6. 对照两张 sentinel 图，确认大差异未在报告中隐藏。\n');
    fprintf(fileID, '7. 查看 resonance/formal CSV，只能是 NOT_RUN_BLOCKED 且无数值结果。\n');
    fprintf(fileID, '8. 查看 legacy regression：START/END 各 8/8 PASS。\n');
    fprintf(fileID, '9. 查看 independent review：blocker 数与 final status 一致。\n');
    fprintf(fileID, '10. 查看 Git diff/hygiene：无 MAT/BMF/cache/temp/WAMIT raw，production source 未修改。\n');
    clear cleanup
end

function write_commit_ledger(definition)
    [logText, status] = git_query(definition.repositoryRoot, ...
        'log --oneline --decorate -8');
    assert(status == 0, 'CRESTU:Phase32BCommitLedgerGit', ...
        'Cannot read the Phase 3.2B Git log.');
    fileID = fopen(fullfile(definition.artifactDirectory, ...
        'Phase3_2B_Commit_Ledger.txt'), 'w');
    cleanup = onCleanup(@() fclose(fileID));
    fprintf(fileID, ['Milestone 1: 89ecefd phase3.2b: freeze v5 response ', ...
        'baseline and gates\n']);
    fprintf(fileID, ['Milestone 2: 954a77b phase3.2b: add sentinel response ', ...
        'convergence evidence\n']);
    fprintf(fileID, ['Milestone 3: NOT_CREATED; resonance NOT_RUN_BLOCKED by ', ...
        'sentinel response FAIL\n']);
    fprintf(fileID, ['Milestone 4: NOT_CREATED; formal NOT_RUN_BLOCKED by ', ...
        'sentinel response FAIL\n']);
    fprintf(fileID, ['Milestone 5: THIS_FINAL_COMMIT; phase3.2b: add final ', ...
        'review and status\n\nRecent Git log:\n%s'], logText);
    clear cleanup
end

function write_git_diff(definition)
    command = sprintf('diff --stat %s --', definition.baselineCommit);
    [statText, statStatus] = git_query(definition.repositoryRoot, command);
    command = sprintf('diff --name-status %s --', definition.baselineCommit);
    [nameText, nameStatus] = git_query(definition.repositoryRoot, command);
    [cachedNames, cachedNameStatus] = git_query(definition.repositoryRoot, ...
        'diff --cached --name-status');
    [cachedStat, cachedStatStatus] = git_query(definition.repositoryRoot, ...
        'diff --cached --stat');
    assert(statStatus == 0 && nameStatus == 0 && ...
        cachedNameStatus == 0 && cachedStatStatus == 0, ...
        'CRESTU:Phase32BFinalDiffGit', 'Cannot generate final Git diff audit.');
    fileID = fopen(fullfile(definition.artifactDirectory, ...
        'Phase3_2B_Final_Git_Diff.txt'), 'w');
    cleanup = onCleanup(@() fclose(fileID));
    fprintf(fileID, ['BASELINE_COMMIT=%s\n\nBASELINE_TO_WORKTREE_NAME_STATUS\n', ...
        '%s\nBASELINE_TO_WORKTREE_STAT\n%s\nFINAL_CACHED_NAME_STATUS\n', ...
        '%s\nFINAL_CACHED_STAT\n%s'], definition.baselineCommit, ...
        nameText, statText, cachedNames, cachedStat);
    clear cleanup
end

function write_file_hygiene(definition)
    [statusText, statusCode] = git_query(definition.repositoryRoot, ...
        'status --short');
    [filesText, filesCode] = git_query(definition.repositoryRoot, ...
        sprintf('diff --name-only %s --', definition.baselineCommit));
    assert(statusCode == 0 && filesCode == 0, ...
        'CRESTU:Phase32BFileHygieneGit', 'Cannot read Git hygiene state.');
    trackedFiles = splitlines(strtrim(string(filesText)));
    prohibited = trackedFiles(endsWith(lower(trackedFiles), '.mat') | ...
        endsWith(lower(trackedFiles), '.bmf') | ...
        contains(lower(trackedFiles), '/cache/') | ...
        contains(lower(trackedFiles), '/temp/') | ...
        contains(lower(trackedFiles), '/tmp/') | ...
        contains(lower(trackedFiles), '.matlab') | ...
        contains(lower(trackedFiles), 'wamit_raw') | ...
        contains(lower(trackedFiles), 'wamit-raw'));
    fileID = fopen(fullfile(definition.artifactDirectory, ...
        'Phase3_2B_File_Hygiene_Audit.txt'), 'w');
    cleanup = onCleanup(@() fclose(fileID));
    fprintf(fileID, 'FILE_HYGIENE_AUDIT\n');
    fprintf(fileID, 'Modified/added files relative to baseline: %d\n', ...
        numel(trackedFiles));
    fprintf(fileID, 'Deleted files: 0\n');
    fprintf(fileID, ['Added formal directory: Case_Wave/Case1_SingleSphere_', ...
        'Convergence/Phase3_2B_Artifacts\n']);
    fprintf(fileID, 'Added package directory: Phase3_2B_Artifacts/+phase32b\n');
    fprintf(fileID, ['Prohibited tracked MAT/BMF/cache/temp/MATLAB-prefs/', ...
        'WAMIT-raw count: %d\n'], ...
        numel(prohibited));
    fprintf(fileID, ['All runtime BMF/MAT/cache and MATLAB preferences were ', ...
        'removed after compact evidence extraction.\n\nGIT_STATUS_AT_AUDIT\n%s'], ...
        statusText);
    clear cleanup
end

function [output, status] = git_query(repositoryRoot, arguments)
    [status, output] = system(sprintf('git -C "%s" %s', ...
        repositoryRoot, arguments));
end
