function summary = Initialize_Phase3_2B_Baseline()
% INITIALIZE_PHASE3_2B_BASELINE Freeze v5 inputs before response solves.

    %% Stage 1: Verify the accepted Phase 3.2A evidence and default mode

    definition = phase32b.initialize();
    manifest = definition.baselineManifest;
    quality = readtable(definition.baselineQualityFile, 'TextType', 'string');
    isolation = readtable(definition.baselineIsolationFile, ...
        'TextType', 'string');
    legacy = readtable(fullfile(definition.phase32aDirectory, ...
        'Phase3_2A_Legacy_Regression.csv'), 'TextType', 'string');
    bridge = readtable(fullfile(definition.phase32aDirectory, ...
        'Phase3_2A_BEM_Bridge_Smoke.csv'), 'TextType', 'string');

    assert(get_polar_topology_mode(struct()) == "LEGACY", ...
        'CRESTU:Phase32BDefaultMode', ...
        'Missing topology mode no longer selects LEGACY.');
    explicit = struct('phase2_2_controls', struct( ...
        'polarTopologyMode', 'QUALITY_CONTROLLED_V2'));
    assert(get_polar_topology_mode(explicit) == "QUALITY_CONTROLLED_V2", ...
        'CRESTU:Phase32BExplicitMode', ...
        'Explicit QUALITY_CONTROLLED_V2 selection failed.');
    assert(height(legacy) == 5 && all(legacy.exact_hash_regression) && ...
        height(bridge) == 2 && all(bridge.solve_status == "PASS"), ...
        'CRESTU:Phase32BBaselineRegression', ...
        'Accepted legacy or bridge baseline is incomplete.');

    codeVersion = get_rankine_code_version();
    frozenSourceHash = unique(manifest.production_source_hash);
    assert(numel(frozenSourceHash) == 1 && ...
        frozenSourceHash == string(codeVersion.fingerprint), ...
        'CRESTU:Phase32BProductionSourceHash', ...
        'Current production source fingerprint differs from frozen v5.');

    %% Stage 2: Freeze the complete manifest without changing v5 semantics

    frozen = bind_preassembly_hashes(definition, manifest);
    frozen.frozen_from = repmat( ...
        "Phase3_2A_V5_Mesh_Manifest.csv", height(frozen), 1);
    frozen.frozen_baseline_commit = repmat( ...
        string(definition.baselineCommit), height(frozen), 1);
    frozen.frozen_topology_mode = repmat( ...
        "QUALITY_CONTROLLED_V2", height(frozen), 1);
    frozen.freeze_status = repmat("PASS", height(frozen), 1);
    frozenFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2B_V5_Frozen_Mesh_Manifest.csv');
    writetable(frozen, frozenFile);

    %% Stage 3: Freeze provenance and source/config/design hashes

    provenance = table('Size', [0, 6], ...
        'VariableTypes', repmat({'string'}, 1, 6), ...
        'VariableNames', {'item', 'value', 'path', 'sha256', ...
            'status', 'notes'});
    [tagObject, tagObjectStatus] = git_query(definition.repositoryRoot, ...
        sprintf('rev-parse refs/tags/%s', definition.baselineTag));
    [tagCommit, tagCommitStatus] = git_query(definition.repositoryRoot, ...
        sprintf('rev-parse "%s^{commit}"', definition.baselineTag));
    assert(tagObjectStatus == 0 && tagCommitStatus == 0 && ...
        strcmp(strtrim(tagCommit), definition.baselineCommit), ...
        'CRESTU:Phase32BBaselineTag', 'Frozen annotated tag verification failed.');
    provenance = add_row(provenance, 'BASELINE_TAG', ...
        definition.baselineTag, '', '', 'PASS', 'annotated tag');
    provenance = add_row(provenance, 'BASELINE_TAG_OBJECT_SHA', ...
        strtrim(tagObject), '', '', 'PASS', 'local tag object');
    provenance = add_row(provenance, 'BASELINE_PEELED_COMMIT_SHA', ...
        strtrim(tagCommit), '', '', 'PASS', 'must equal accepted HEAD');
    provenance = add_file(provenance, 'V5_MESH_MANIFEST', ...
        definition.baselineManifestFile, definition);
    provenance = add_file(provenance, 'V5_MESH_QUALITY', ...
        definition.baselineQualityFile, definition);
    provenance = add_file(provenance, 'V5_CONTROL_ISOLATION', ...
        definition.baselineIsolationFile, definition);
    provenance = add_file(provenance, 'V5_MESH_STATUS', ...
        fullfile(definition.phase32aDirectory, ...
        'Phase3_2A_V5_Mesh_Status.csv'), definition);
    provenance = add_file(provenance, 'TOPOLOGY_DESIGN_V1', ...
        fullfile(definition.phase32aDirectory, ...
        'Phase3_2A_Topology_Design_Decision.md'), definition);
    provenance = add_file(provenance, 'TOPOLOGY_DESIGN_V2', ...
        fullfile(definition.phase32aDirectory, ...
        'Phase3_2A_Topology_Design_Decision_v2.md'), definition);
    provenance = add_file(provenance, 'TOPOLOGY_DESIGN_V3', ...
        fullfile(definition.phase32aDirectory, ...
        'Phase3_2A_Topology_Design_Decision_v3.md'), definition);
    provenance = add_file(provenance, 'BASELINE_CONFIG', ...
        definition.baselineConfig, definition);
    provenance = add_file(provenance, 'FORMAL_REFERENCE_CONFIG', ...
        definition.formalConfig, definition);
    provenance = add_file(provenance, 'PREDECLARED_RESPONSE_GATES', ...
        fullfile(definition.artifactDirectory, ...
        'Phase3_2B_Predeclared_Response_Gates.md'), definition);
    provenance = add_file(provenance, 'WAMIT_DERIVED_PROVENANCE_ONLY', ...
        fullfile(definition.convergenceDirectory, 'Phase3_2_Artifacts', ...
        'Phase3_2_WAMIT_Reference_Provenance.csv'), definition);
    provenance = add_row(provenance, 'PRODUCTION_SOURCE_FINGERPRINT', ...
        codeVersion.fingerprint, '', codeVersion.fingerprint, 'PASS', ...
        'get_rankine_code_version; fixed across 18 frozen rows');
    provenance = add_row(provenance, 'DEFAULT_TOPOLOGY_MODE', 'LEGACY', ...
        '', '', 'PASS', 'negative control via get_polar_topology_mode');
    provenance = add_row(provenance, 'PHASE3_2B_TOPOLOGY_MODE', ...
        'QUALITY_CONTROLLED_V2', '', '', 'PASS', ...
        'must be explicit in every case');
    provenance = add_row(provenance, 'STARTUP_WORKTREE_STATUS', 'CLEAN', ...
        '', '', 'PASS', ...
        'verified before tag creation and Phase 3.2B directory creation');
    provenanceFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2B_Baseline_Provenance.csv');
    writetable(provenance, provenanceFile);

    %% Stage 4: Write the human-readable baseline freeze

    reportFile = fullfile(definition.artifactDirectory, ...
        'PHASE3_2B_BASELINE_FREEZE_CN.md');
    fileID = fopen(reportFile, 'w');
    assert(fileID >= 0, 'CRESTU:Phase32BBaselineReportOpen', ...
        'Cannot create baseline freeze report.');
    cleanup = onCleanup(@() fclose(fileID));
    fprintf(fileID, '# CRESTU-1F Phase 3.2B v5 基线冻结\n\n');
    fprintf(fileID, '```ini\nV5_MESH_REPRODUCIBILITY_BASELINE = PASS\n');
    fprintf(fileID, 'FROZEN_MESH_CASES = %d\n', height(frozen));
    fprintf(fileID, 'FROZEN_COMPONENT_QUALITY = %d/%d PASS\n', ...
        nnz(quality.component_gate_status == "PASS"), height(quality));
    fprintf(fileID, 'FROZEN_FREQUENCY_ISOLATION = %d/%d PASS\n', ...
        nnz(isolation.frequency_geometry_gate == "PASS"), height(isolation));
    fprintf(fileID, 'QUALITY_CONTROLLED_V2_DEFAULT = OFF\n');
    fprintf(fileID, 'LEGACY_Q_ONLY_GEOMETRY = %d/%d EXACT_HASH_PASS\n', ...
        nnz(legacy.exact_hash_regression), height(legacy));
    fprintf(fileID, 'BASELINE_COMMIT = %s\n', definition.baselineCommit);
    fprintf(fileID, 'BASELINE_TAG_OBJECT = %s\n', strtrim(tagObject));
    fprintf(fileID, 'PRODUCTION_SOURCE_SHA256 = %s\n```\n\n', ...
        codeVersion.fingerprint);
    fprintf(fileID, ['本阶段冻结 Phase 3.2A 已接受的 18 行 v5 manifest、72 行组件质量、', ...
        '6 行频率隔离、三份 topology design、realized spacing、outer extent、', ...
        '组件/组合网格哈希和 source/config/control 哈希。没有重新设计 topology，', ...
        '也没有把 V2 改为默认模式。\n\n']);
    fprintf(fileID, '## 冻结网格族\n\n');
    fprintf(fileID, '| Level | eta | body division | FS radial | bottom radial | wall nz | theta | bottom core |\n');
    fprintf(fileID, '|---|---:|---:|---:|---:|---:|---:|---:|\n');
    for levelIndex = 1:numel(definition.levels)
        level = definition.levels(levelIndex);
        fprintf(fileID, '| %s | %.15g | %d | %d+%d | %d+%d | %d | %d | %d |\n', ...
            level.name, level.eta, level.bodyDivision, ...
            level.fsRadialCounts, level.bottomRadialCounts, ...
            level.wallVerticalCount, level.wallThetaCount, ...
            level.bottomCoreRadialLayerCount);
    end
    fprintf(fileID, '\n每个 Phase 3.2B case 都必须在矩阵组装前与冻结行逐字段核验；不一致即停止，变化后的网格不得称为 v5。\n');
    clear cleanup

    summary = struct('schemaVersion', 1, 'frozenCaseCount', height(frozen), ...
        'qualityPassCount', nnz(quality.component_gate_status == "PASS"), ...
        'isolationPassCount', ...
            nnz(isolation.frequency_geometry_gate == "PASS"), ...
        'legacyExactHashPassCount', nnz(legacy.exact_hash_regression), ...
        'productionSourceSHA256', codeVersion.fingerprint, ...
        'overallPass', true);
    fprintf('[RESULT] V5_MESH_REPRODUCIBILITY_BASELINE = PASS\n');
    fprintf('[RESULT] QUALITY_CONTROLLED_V2_DEFAULT = OFF\n');
end

function frozen = bind_preassembly_hashes(definition, manifest)
% BIND_PREASSEMBLY_HASHES Regenerate v5 and freeze operator previews.

    frozen = manifest;
    rowCount = height(frozen);
    frozen.preassembly_operator_hash = strings(rowCount, 1);
    frozen.preassembly_configured_controls_hash = strings(rowCount, 1);
    frozen.preassembly_effective_controls_hash = strings(rowCount, 1);
    frozen.preassembly_source_point_hash = strings(rowCount, 1);
    frozen.preassembly_collocation_point_hash = strings(rowCount, 1);
    frozen.baseline_reproducibility = strings(rowCount, 1);
    for rowIndex = 1:rowCount
        expected = manifest(rowIndex, :);
        level = definition.levels(expected.mesh_level_index);
        omega = expected.omega_rad_s; % [rad/s]
        fprintf('[INFO] Freeze preassembly %d/%d | %.6g rad/s | %s\n', ...
            rowIndex, rowCount, omega, level.name);
        specification = phase32a.create_case(definition, level, omega, ...
            'phase3_2b_baseline_preassembly_freeze');
        cleanup = onCleanup(@() phase32.remove_runtime( ...
            definition, specification.runtimeDirectory));
        domain = build_bmf_domain(specification.configFile);
        [actual, ~] = phase32a.audit_case( ...
            definition, specification, domain, NaN);
        assert_manifest_match(expected, actual);
        [operatorState, controlManifest, meshAudit] = ...
            preview_operator_state(domain, omega);
        frozen.preassembly_operator_hash(rowIndex) = string( ...
            operatorState.boundaryOperatorStateSHA256);
        frozen.preassembly_configured_controls_hash(rowIndex) = string( ...
            controlManifest.configuredSHA256);
        frozen.preassembly_effective_controls_hash(rowIndex) = string( ...
            controlManifest.effectiveSHA256);
        frozen.preassembly_source_point_hash(rowIndex) = string( ...
            meshAudit.sourcePointHash);
        frozen.preassembly_collocation_point_hash(rowIndex) = string( ...
            meshAudit.collocationPointHash);
        frozen.baseline_reproducibility(rowIndex) = "PASS";
        clear cleanup
    end
end

function assert_manifest_match(expected, actual)
    exactTextFields = ["mesh_level"; "topology_mode"; ...
        "body_geometry_hash"; "free_surface_geometry_hash"; ...
        "bottom_geometry_hash"; "farfield_geometry_hash"; ...
        "combined_geometry_hash"; "production_source_hash"; ...
        "physical_state_hash"; "mesh_control_hash"];
    exactNumericFields = ["mesh_level_index"; "omega_rad_s"; ...
        "body_panel_count"; "free_surface_panel_count"; ...
        "bottom_panel_count"; "farfield_panel_count"; ...
        "total_panel_count"; "water_depth_m"];
    toleranceFields = ["actual_top_outer_radius_m"; ...
        "actual_bottom_outer_radius_m"; "target_top_outer_radius_m"; ...
        "target_bottom_outer_radius_m"; ...
        "realized_near_radial_step_m"; ...
        "realized_outer_radial_step_m"];
    for fieldIndex = 1:numel(exactTextFields)
        name = exactTextFields(fieldIndex);
        assert(string(actual.(name)) == string(expected.(name)), ...
            'CRESTU:Phase32BV5TextMismatch', ...
            'Frozen v5 field %s did not reproduce.', name);
    end
    for fieldIndex = 1:numel(exactNumericFields)
        name = exactNumericFields(fieldIndex);
        assert(isequaln(actual.(name), expected.(name)), ...
            'CRESTU:Phase32BV5NumericMismatch', ...
            'Frozen v5 field %s did not reproduce exactly.', name);
    end
    for fieldIndex = 1:numel(toleranceFields)
        name = toleranceFields(fieldIndex);
        scale = max([1.0, abs(actual.(name)), abs(expected.(name))]);
        assert(abs(actual.(name) - expected.(name)) <= 1.0e-12 * scale, ...
            'CRESTU:Phase32BV5ToleranceMismatch', ...
            'Frozen v5 field %s exceeded the comparison tolerance.', name);
    end
end

function [operatorState, controlManifest, meshAudit] = ...
        preview_operator_state(domain, omega)
    meshAudit = audit_domain_meshes(domain);
    cfg = domain.cfg;
    cfg.fs.r_outer = cfg.fs.tuning_report.original_outer_radius;
    [cfg, cfg.fs.tuning_report] = tune_sponge_layer(cfg, omega);
    cfg = apply_phase2_2_mesh_controls(cfg);
    [cfg, ~] = resolve_phase2_2_controls(cfg, omega);
    [cfg, ~] = finalize_phase2_2_manifest(cfg, meshAudit, domain.stats);
    [physicalWaveNumber, ~] = solve_wave_dispersion( ...
        omega, cfg.grav, cfg.water_depth);
    freeSurface = get_rankine_free_surface_robin_bc( ...
        domain.geometry.centers, domain.stats, omega, cfg.grav, cfg);
    nominalMu = cfg.phase2_2_controls.effective.actualMu0;
    outer = get_rankine_outer_absorbing_bc( ...
        domain.geometry.centers, domain.geometry.normals, domain.stats, ...
        omega, cfg.grav, cfg.water_depth, cfg, physicalWaveNumber, nominalMu);
    operatorState = get_rankine_boundary_operator_state( ...
        freeSurface.cacheSpecification, outer.cacheSpecification, ...
        meshAudit.geometry.hash);
    [~, controlManifest] = bind_phase2_2_operator_state(cfg, operatorState);
end

function tableOut = add_file(tableIn, item, filename, definition)
    assert(isfile(filename), 'CRESTU:Phase32BProvenanceFile', ...
        'Required provenance file is missing: %s', filename);
    relativePath = erase(string(filename), ...
        string(definition.repositoryRoot) + filesep);
    tableOut = add_row(tableIn, item, relativePath, relativePath, ...
        sha256_file_hash(filename), 'PASS', 'read-only frozen input');
end

function tableOut = add_row(tableIn, item, value, path, hash, status, notes)
    row = table(string(item), string(value), string(path), string(hash), ...
        string(status), string(notes), 'VariableNames', tableIn.Properties.VariableNames);
    tableOut = [tableIn; row];
end

function [output, status] = git_query(repositoryRoot, arguments)
    [status, output] = system(sprintf('git -C "%s" %s', ...
        repositoryRoot, arguments));
end
