function summary = Run_Phase3_2B_Sentinel()
% RUN_PHASE3_2B_SENTINEL Run exactly 18 isolated v5 sentinel clean solves.

    %% Stage 1: Enforce resource and regression prerequisites

    definition = phase32b.initialize();
    resource = readtable(fullfile(definition.artifactDirectory, ...
        'Phase3_2B_Resource_Plan.csv'), 'TextType', 'string');
    assert(all(resource.resource_gate_status == "PASS_SERIAL_L3") && ...
        all(resource.maximum_concurrent_L3_BEM_solves == 1), ...
        'CRESTU:Phase32BSentinelResourceGate', ...
        'Sentinel requires the measured serial-L3 resource gate.');
    legacy = readtable(fullfile(definition.artifactDirectory, ...
        'Phase3_2B_Legacy_Regression.csv'), 'TextType', 'string');
    startRows = legacy.suite_position == "START";
    assert(nnz(startRows) == 8 && all(legacy.status(startRows) == "PASS"), ...
        'CRESTU:Phase32BSentinelLegacyGate', ...
        'Sentinel requires the 8/8 starting legacy/control regression.');
    outputFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2B_Sentinel_Response.csv');
    assert(~isfile(outputFile), 'CRESTU:Phase32BSentinelExistingOutput', ...
        'Refusing to reuse or overwrite an existing sentinel response file.');

    %% Stage 2: Run endpoints, sensitive region, then stable anchors

    executionOrder = [0.5, 2.0, 0.6, 1.4, 1.0, 1.5]; % [rad/s]
    records = repmat(phase32b.empty_response_record(), 0, 1);
    caseCount = numel(executionOrder) * numel(definition.levels);
    completed = 0;
    for frequencyIndex = 1:numel(executionOrder)
        omega = executionOrder(frequencyIndex); % [rad/s]
        for levelIndex = 1:numel(definition.levels)
            level = definition.levels(levelIndex);
            completed = completed + 1;
            fprintf('[INFO] Sentinel %d/%d | %.6g rad/s | %s\n', ...
                completed, caseCount, omega, level.name);
            record = phase32b.run_v5_case( ...
                definition, level, omega, 'SENTINEL');
            records(end + 1, 1) = record; %#ok<AGROW>
            writetable(struct2table(records), outputFile);
            assert(record.preassembly_status == "PASS" && ...
                record.v5_mesh_reproducibility == "PASS", ...
                'CRESTU:Phase32BSentinelPreassemblyStop', ...
                'A sentinel v5 preassembly gate failed; no further solve is allowed.');
        end
    end

    %% Stage 3: Summarize without weakening failed algebraic cases

    response = struct2table(records);
    allClean = height(response) == 18 && ...
        all(lower(response.cache_status) == "miss") && ...
        all(response.preassembly_status == "PASS");
    algebraicPassCount = nnz(response.algebraic_gate_status == "PASS");
    summary = struct('schemaVersion', 1, 'caseCount', height(response), ...
        'cleanSolveCount', nnz(lower(response.cache_status) == "miss"), ...
        'preassemblyPassCount', ...
            nnz(response.preassembly_status == "PASS"), ...
        'algebraicPassCount', algebraicPassCount, ...
        'allClean', allClean, ...
        'algebraicOverallPass', algebraicPassCount == 18);
    fprintf('[RESULT] SENTINEL_CLEAN_SOLVES = %d/18\n', ...
        summary.cleanSolveCount);
    fprintf('[RESULT] SENTINEL_ALGEBRAIC_PASS = %d/18\n', ...
        algebraicPassCount);
end
