function summary = Run_Phase3_2B_Resource_Pilot()
% RUN_PHASE3_2B_RESOURCE_PILOT Run only the maximum-N L3 resource pilot.

    definition = phase32b.initialize();
    planFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2B_Resource_Plan.csv');
    assert(isfile(planFile), 'CRESTU:Phase32BResourcePlanMissing', ...
        'Prepare the resource plan before the pilot.');
    plan = readtable(planFile, 'TextType', 'string');
    selected = logical(plan.maximum_N_case);
    assert(nnz(selected) == 1, 'CRESTU:Phase32BMaximumNCase', ...
        'The resource plan must identify exactly one maximum-N case.');
    row = plan(selected, :);
    level = definition.levels(row.mesh_level_index);
    record = phase32b.run_v5_case(definition, level, ...
        row.omega_rad_s, 'RESOURCE_PILOT');
    writetable(struct2table(record), fullfile(definition.artifactDirectory, ...
        'Phase3_2B_Resource_Pilot.csv'));
    summary = struct('schemaVersion', 1, ...
        'meshLevel', char(record.mesh_level), ...
        'omegaRadPerS', record.omega_rad_s, ...
        'bemUnknownCount', record.bem_unknown_count, ...
        'solveStatus', char(record.solve_status), ...
        'totalRuntimeS', record.total_runtime_s);
    fprintf('[RESULT] RESOURCE_PILOT_SOLVE_STATUS = %s\n', ...
        record.solve_status);
end
