function [workMatrix, unsymmetrizedDamping, diagnostics] = ...
        compute_rankine_pressure_work( ...
        potential, outwardNormalDerivative, surfaceWeights, omega, density)
% COMPUTE_RANKINE_PRESSURE_WORK Complex pressure-work and damping matrices.
%
% With exp(+i*omega*t), p=-i*rho*omega*Phi and peak complex amplitudes,
%   W_ij = 0.5 * integral[p_i * conj(q_j)] dS,
%   B_ij = 2*W_ij/omega^2.

    assert(isequal(size(potential), size(outwardNormalDerivative)) && ...
        size(potential, 1) == numel(surfaceWeights), ...
        'CRESTU:PressureWorkShape', ...
        'Potential, normal derivative, and quadrature weights do not match.');
    validateattributes(omega, {'numeric'}, ...
        {'scalar', 'real', 'positive', 'finite'});
    validateattributes(density, {'numeric'}, ...
        {'scalar', 'real', 'positive', 'finite'});
    surfaceWeights = reshape(surfaceWeights, [], 1);
    assert(all(isfinite(surfaceWeights) & surfaceWeights > 0));
    pressure = -1i * density * omega * potential;
    workMatrix = 0.5 * (pressure.' * ...
        (conj(outwardNormalDerivative) .* surfaceWeights));
    unsymmetrizedDamping = 2 * workMatrix / omega^2;
    hermitianPart = 0.5 * (unsymmetrizedDamping + ...
        unsymmetrizedDamping');
    diagnostics = struct('schemaVersion', 1, ...
        'timeConvention', 'exp(+i*omega*t)', ...
        'amplitudeConvention', 'peak-complex-amplitude', ...
        'pressureFormula', 'p=-i*rho*omega*Phi', ...
        'meanPowerFormula', 'W=0.5*integral[p_i*conj(q_j)]dS', ...
        'dampingFormula', 'B_unsym=2*W/omega^2', ...
        'hermitianPart', hermitianPart, ...
        'realHermitianDamping', real(hermitianPart), ...
        'hermitianResidual', norm(unsymmetrizedDamping - ...
        unsymmetrizedDamping', 'fro') / ...
        max(norm(unsymmetrizedDamping, 'fro'), eps));
end
