function [dampingFlux, diagnostics] = compute_rankine_radiation_flux( ...
        boundaryPotential, canonicalDerivative, geometry, stats, ...
        omega, cfg, parity, globalModes, options)
% COMPUTE_RANKINE_RADIATION_FLUX Independent control-cylinder energy flux.
% This routine does not call Haskind relations or body-pressure integration.

    if nargin < 8 || isempty(globalModes)
        globalModes = 1:size(boundaryPotential, 2);
    end
    if nargin < 9, options = struct(); end
    options = defaults(options);
    bodyRows = 1:stats.total_body_panels;
    bodyRadius = max(hypot(geometry.centers(bodyRows, 1), ...
        geometry.centers(bodyRows, 2)));
    spongeStart = cfg.phase2_2_controls.effective.spongeStartRadiusM;
    clearance = spongeStart - bodyRadius;
    assert(isfinite(clearance) && clearance > 0, ...
        'CRESTU:FluxCylinderClearance', ...
        'No body-free control-cylinder annulus exists inside sponge start.');
    radii = bodyRadius + options.radiusFractions * clearance;
    [physicalK, ~] = solve_wave_dispersion( ...
        omega, cfg.grav, cfg.water_depth);
    wavelength = 2 * pi / physicalK;
    radiusRecords = cell(numel(radii), 1);
    fprintf('[DIAG] Radiation flux | control radii=%s m | fine=%dx%d\n', ...
        mat2str(radii, 6), options.thetaLevels(end), options.zLevels(end));
    for radiusIndex = 1:numel(radii)
        radius = radii(radiusIndex);
        localGap = min(radius - bodyRadius, spongeStart - radius);
        radialStep = min(options.radialStepWavelengthFraction * wavelength, ...
            options.radialStepGapFraction * localGap);
        radiusRecords{radiusIndex} = evaluate_cylinder(radius, ...
            options.thetaLevels(end), options.zLevels(end), radialStep, ...
            boundaryPotential, canonicalDerivative, geometry, stats, ...
            omega, cfg, parity);
        fprintf('[DIAG] Radiation flux | completed radius %.6g m\n', radius);
    end
    middleIndex = ceil(numel(radii) / 2);
    quadratureRecords = cell(numel(options.thetaLevels), 1);
    for levelIndex = 1:numel(options.thetaLevels)
        if levelIndex == numel(options.thetaLevels)
            quadratureRecords{levelIndex} = radiusRecords{middleIndex};
        else
            radius = radii(middleIndex);
            localGap = min(radius - bodyRadius, spongeStart - radius);
            radialStep = min(options.radialStepWavelengthFraction * wavelength, ...
                options.radialStepGapFraction * localGap);
            quadratureRecords{levelIndex} = evaluate_cylinder(radius, ...
                options.thetaLevels(levelIndex), options.zLevels(levelIndex), ...
                radialStep, boundaryPotential, canonicalDerivative, geometry, ...
                stats, omega, cfg, parity);
            fprintf('[DIAG] Radiation flux | completed quadrature %dx%d\n', ...
                options.thetaLevels(levelIndex), options.zLevels(levelIndex));
        end
    end
    finalRecord = radiusRecords{middleIndex};
    dampingFlux = finalRecord.realHermitianDamping;
    heaveLocalIndex = find(globalModes == 3, 1);
    if isempty(heaveLocalIndex)
        b33ByRadius = NaN(size(radii));
        b33ByQuadrature = NaN(size(options.thetaLevels));
        radiusPlateau = NaN;
        quadratureDelta = NaN;
        radialDerivativeSensitivity = NaN;
        validationStatus = 'NOT_APPLICABLE_NO_HEAVE_COLUMN';
    else
        b33ByRadius = cellfun(@(item) item.realHermitianDamping( ...
            heaveLocalIndex, heaveLocalIndex), radiusRecords);
        b33ByQuadrature = cellfun(@(item) item.realHermitianDamping( ...
            heaveLocalIndex, heaveLocalIndex), quadratureRecords);
        radiusPlateau = (max(b33ByRadius) - min(b33ByRadius)) / ...
            max(max(abs(b33ByRadius)), eps);
        quadratureDelta = abs(b33ByQuadrature(end) - ...
            b33ByQuadrature(end - 1)) / ...
            max([abs(b33ByQuadrature(end)), ...
            abs(b33ByQuadrature(end - 1)), eps]);
        radialDerivativeSensitivity = finalRecord. ...
            dampingSensitivityRelative(heaveLocalIndex, heaveLocalIndex);
        hermitianResidual = max(cellfun(@(item) ...
            item.hermitianResidual, radiusRecords));
        finiteValues = [b33ByRadius(:); b33ByQuadrature(:); ...
            radiusPlateau; quadratureDelta; radialDerivativeSensitivity; ...
            hermitianResidual];
        finitePass = all(isfinite(finiteValues));
        validationPass = finitePass && all(b33ByRadius > 0) && ...
            radiusPlateau <= options.validationTolerance && ...
            quadratureDelta <= options.validationTolerance && ...
            radialDerivativeSensitivity <= options.validationTolerance && ...
            hermitianResidual <= options.hermitianTolerance;
        if validationPass
            validationStatus = 'VALIDATED_CONTROL_CYLINDER_PLATEAU';
        else
            validationStatus = 'NOT_VALIDATED_CONTROL_CYLINDER_OR_QUADRATURE';
        end
    end
    diagnostics = struct('schemaVersion', 1, ...
        'method', 'direct-radiated-wave-pressure-work-control-cylinder', ...
        'independentOfHaskind', true, 'independentOfBodyPressure', true, ...
        'timeConvention', 'exp(+i*omega*t)', ...
        'amplitudeConvention', 'unit-peak-generalized-displacement', ...
        'powerDampingConvention', 'Pmean=0.5*omega^2*xi^H*B*xi', ...
        'bodyMaximumRadiusM', bodyRadius, ...
        'spongeStartRadiusM', spongeStart, ...
        'controlRadiiM', radii, ...
        'controlRadiiOverWavelength', radii / wavelength, ...
        'thetaLevels', options.thetaLevels, 'zLevels', options.zLevels, ...
        'radiusRecords', {radiusRecords}, ...
        'quadratureRecords', {quadratureRecords}, ...
        'selectedRadiusM', radii(middleIndex), ...
        'rawWorkMatrix', finalRecord.rawWorkMatrix, ...
        'unsymmetrizedDamping', finalRecord.unsymmetrizedDamping, ...
        'hermitianResidual', finalRecord.hermitianResidual, ...
        'realHermitianDamping', finalRecord.realHermitianDamping, ...
        'B33ByRadius', b33ByRadius, ...
        'B33ByQuadrature', b33ByQuadrature, ...
        'radiusPlateauRelative', radiusPlateau, ...
        'quadratureDeltaRelative', quadratureDelta, ...
        'radialDerivativeSensitivityRelative', radialDerivativeSensitivity, ...
        'validationTolerance', options.validationTolerance, ...
        'hermitianTolerance', options.hermitianTolerance, ...
        'validationStatus', validationStatus);
end

function record = evaluate_cylinder(radius, nTheta, nZ, radialStep, ...
        boundaryPotential, canonicalDerivative, geometry, stats, ...
        omega, cfg, parity)
    [zNodes, zWeights] = gauss_legendre(nZ, -cfg.water_depth, 0);
    theta = (0:nTheta - 1)' * (2 * pi / nTheta);
    [thetaGrid, zGrid] = ndgrid(theta, zNodes);
    points = @(r) [r * cos(thetaGrid(:)), r * sin(thetaGrid(:)), zGrid(:)];
    phiCenter = evaluate_rankine_off_surface(points(radius), ...
        geometry.normals, geometry.vertices, stats, boundaryPotential, ...
        canonicalDerivative, cfg, parity);
    phiPlus = evaluate_rankine_off_surface(points(radius + radialStep), ...
        geometry.normals, geometry.vertices, stats, boundaryPotential, ...
        canonicalDerivative, cfg, parity);
    phiMinus = evaluate_rankine_off_surface(points(radius - radialStep), ...
        geometry.normals, geometry.vertices, stats, boundaryPotential, ...
        canonicalDerivative, cfg, parity);
    phiPlusHalf = evaluate_rankine_off_surface( ...
        points(radius + radialStep / 2), geometry.normals, geometry.vertices, ...
        stats, boundaryPotential, canonicalDerivative, cfg, parity);
    phiMinusHalf = evaluate_rankine_off_surface( ...
        points(radius - radialStep / 2), geometry.normals, geometry.vertices, ...
        stats, boundaryPotential, canonicalDerivative, cfg, parity);
    qAtH = (phiPlus - phiMinus) / (2 * radialStep);
    qAtHalf = (phiPlusHalf - phiMinusHalf) / radialStep;
    qRichardson = (4 * qAtHalf - qAtH) / 3;
    [~, weightGrid] = ndgrid(theta, zWeights);
    weights = radius * (2 * pi / nTheta) * weightGrid(:);
    [workMatrix, unsymDamping, workDiagnostics] = ...
        compute_rankine_pressure_work(phiCenter, qRichardson, weights, ...
        omega, cfg.rho);
    [~, dampingH] = compute_rankine_pressure_work( ...
        phiCenter, qAtH, weights, omega, cfg.rho);
    [~, dampingHalf] = compute_rankine_pressure_work( ...
        phiCenter, qAtHalf, weights, omega, cfg.rho);
    dampingSensitivity = abs(real(0.5 * (dampingHalf + dampingHalf')) - ...
        real(0.5 * (dampingH + dampingH'))) ./ ...
        max(abs(real(0.5 * (unsymDamping + unsymDamping'))), eps);
    record = struct('radiusM', radius, 'nTheta', nTheta, 'nZ', nZ, ...
        'sampleCount', numel(weights), 'radialStepM', radialStep, ...
        'surfaceAreaFromWeightsM2', sum(weights), ...
        'exactSurfaceAreaM2', 2 * pi * radius * cfg.water_depth, ...
        'rawWorkMatrix', workMatrix, ...
        'unsymmetrizedDamping', unsymDamping, ...
        'realHermitianDamping', workDiagnostics.realHermitianDamping, ...
        'hermitianResidual', workDiagnostics.hermitianResidual, ...
        'dampingSensitivityRelative', dampingSensitivity, ...
        'maximumPotentialMagnitude', max(abs(phiCenter(:))), ...
        'maximumRadialDerivativeMagnitude', max(abs(qRichardson(:))));
end

function options = defaults(options)
    values = struct('radiusFractions', [0.3, 0.6, 0.9], ...
        'thetaLevels', [16, 24, 32], 'zLevels', [8, 10, 12], ...
        'radialStepWavelengthFraction', 0.02, ...
        'radialStepGapFraction', 0.2, 'validationTolerance', 0.05, ...
        'hermitianTolerance', 0.05);
    names = fieldnames(values);
    for nameIndex = 1:numel(names)
        name = names{nameIndex};
        if ~isfield(options, name), options.(name) = values.(name); end
    end
    assert(numel(options.radiusFractions) >= 3 && ...
        numel(options.thetaLevels) >= 3 && ...
        numel(options.thetaLevels) == numel(options.zLevels));
end

function [nodes, weights] = gauss_legendre(order, lowerBound, upperBound)
    indices = (1:order - 1)';
    beta = indices ./ sqrt(4 * indices.^2 - 1);
    jacobi = diag(beta, 1) + diag(beta, -1);
    [vectors, values] = eig(jacobi);
    nodes = diag(values);
    [nodes, orderIndex] = sort(nodes);
    vectors = vectors(:, orderIndex);
    weights = 2 * (vectors(1, :)'.^2);
    nodes = (upperBound + lowerBound) / 2 + ...
        (upperBound - lowerBound) / 2 * nodes;
    weights = (upperBound - lowerBound) / 2 * weights;
end
