function [dampingCandidate, diagnostics] = ...
        compute_haskind_damping_candidate( ...
        phiRadiation, nj, centers, normals, areas, omega, cfg, ...
        modeParity, nTheta)
% COMPUTE_HASKIND_DAMPING_CANDIDATE Unvalidated Haskind outer-product path.
% This function is scientifically separate from control-surface B_flux.

    if nargin < 9 || isempty(nTheta)
        nTheta = 72;
    end
    headings = (0:nTheta - 1) * (360 / nTheta);
    dtheta = 2 * pi / nTheta;
    force = compute_haskind_excitation(phiRadiation, nj, centers, normals, ...
        areas, omega, cfg, headings, modeParity);
    [waveNumber, ~] = solve_wave_dispersion( ...
        omega, cfg.grav, cfg.water_depth);
    if cfg.water_depth > 0
        kh = waveNumber * cfg.water_depth;
        depthFactor = tanh(kh) + kh / (cosh(kh)^2);
    else
        depthFactor = 1;
    end
    prefactor = omega * waveNumber / ...
        (4 * pi * cfg.rho * cfg.grav^2 * depthFactor);
    dampingCandidate = real(prefactor * (force * force') * dtheta);
    dampingCandidate = 0.5 * (dampingCandidate + dampingCandidate.');
    eigenvalues = eig(dampingCandidate);
    tolerance = 1e-10 * max(1, max(abs(eigenvalues)));
    if min(eigenvalues) < -tolerance
        warning('CRESTU:HaskindCandidatePSD', ...
            'Haskind candidate has minimum eigenvalue %g.', ...
            min(eigenvalues));
    end
    diagnostics = struct( ...
        'method', 'Haskind outer-product candidate', ...
        'scientificFunctionName', ...
        'compute_haskind_damping_candidate', ...
        'validationStatus', 'NOT_VALIDATED', ...
        'isEnergyFlux', false, 'isHaskindCandidate', true, ...
        'headings', headings, 'haskind_excitation', force, ...
        'depth_factor', depthFactor, 'wavenumber', waveNumber, ...
        'min_eigenvalue', min(eigenvalues), ...
        'limitations', ['Haskind applicability, amplitude normalization, ', ...
        'and prefactor are not independently validated; this value is not ', ...
        'B_flux and cannot overwrite pressure damping.']);
end
