function result = Run_Phase2_3_ABC_Operator_Audit()
%RUN_PHASE2_3_ABC_OPERATOR_AUDIT Audit the P_FULL outer-ABC normal lineage.
%
% This pre-assembly gate rebuilds the current production geometry in memory,
% selects only the FARFIELD source rows consumed by the P_FULL ABC, and
% separates exact theta, finite-radius asymptotic, and implementation errors.
% It does not change mesh topology or the production ABC model.

    %% Stage 1: Resolve the frozen case, output directory, and production path

    artifactDirectory = fileparts(mfilename('fullpath'));
    convergenceDirectory = fileparts(artifactDirectory);
    caseWaveDirectory = fileparts(convergenceDirectory);
    repositoryRoot = fileparts(caseWaveDirectory);
    phase22TestDirectory = fullfile(convergenceDirectory, ...
        'Phase2_2_Artifacts', 'Tests');
    configFile = fullfile(phase22TestDirectory, 'Frustum_Instrumentation', ...
        'Cases', 'Frustum_Top_Only.cfg');
    legacyBenchmarkBMF = fullfile(phase22TestDirectory, ...
        'Frustum_Instrumentation', 'Cases', ...
        'Frustum_Fine_Top_Only_farfield.bmf');
    finalEqualCountBMF = fullfile(phase22TestDirectory, ...
        'Frustum_Instrumentation', 'Cases', ...
        'Frustum_Fine_Top_Only_Final_farfield.bmf');

    add_production_paths(repositoryRoot);
    functionResolutionFile = audit_runtime_function_resolution( ...
        repositoryRoot, artifactDirectory);
    assert(isfile(configFile), 'CRESTU:Phase23Config', ...
        'Focused Phase 2.3 configuration is missing: %s', configFile);
    assert(isfile(legacyBenchmarkBMF), 'CRESTU:Phase23LegacyBenchmarkMesh', ...
        'Legacy Hankel benchmark BMF is missing: %s', legacyBenchmarkBMF);
    assert(isfile(finalEqualCountBMF), 'CRESTU:Phase23FinalMesh', ...
        'Phase 2.2 final equal-count BMF is missing: %s', finalEqualCountBMF);

    omega = 1.5;                 % Wave angular frequency [rad/s]
    gravity = 9.80665;           % Gravitational acceleration [m/s^2]
    radiusFactors = [1, 1.25, 1.5, 2];
    normalTolerance = 1e-10;
    implementationTolerance = 5e-13;

    fprintf('[INFO] Phase 2.3 ABC pre-assembly audit | omega=%.6g rad/s\n', ...
        omega);

    %% Stage 2: Rebuild the current production mesh entirely in memory

    cfg = read_config(configFile);
    assert(numel(cfg.freq.omegas) == 1 && ...
        abs(cfg.freq.omegas(1) - omega) <= 64 * eps(max(omega, 1)), ...
        'CRESTU:Phase23Frequency', ...
        'The focused configuration must contain only omega=1.5 rad/s.');
    [cfg, cfg.fs.tuning_report] = tune_sponge_layer(cfg, omega);
    cfg = apply_phase2_2_mesh_controls(cfg);
    [cfg, ~] = resolve_phase2_2_controls(cfg, omega);
    [domain, effective] = build_in_memory_domain(cfg);

    bodyCount = domain.stats.total_body_panels;
    freeSurfaceCount = domain.stats.fs_panels;
    bottomCount = domain.stats.seabed_panels;
    farfieldCount = domain.stats.farfield_panels;
    farfieldRows = bodyCount + freeSurfaceCount + bottomCount + ...
        (1:farfieldCount);
    expectedFarfieldRows = (domain.geometry.total_panels - farfieldCount + 1): ...
        domain.geometry.total_panels;
    assert(isequal(farfieldRows, expectedFarfieldRows), ...
        'CRESTU:Phase23FarfieldRowLineage', ...
        'FARFIELD rows are not the tail rows consumed by the production ABC.');
    assert(all(domain.geometry.panel_type(farfieldRows) == 5), ...
        'CRESTU:Phase23FarfieldType', ...
        'A production FARFIELD source row is not boundary type 5.');
    assert(isequal(find(domain.geometry.panel_type == 5).', farfieldRows), ...
        'CRESTU:Phase23FarfieldMask', ...
        'Boundary type 5 selects rows outside the production FARFIELD wall.');

    centers = domain.geometry.centers(farfieldRows, :);
    productionNormals = domain.geometry.normals(farfieldRows, :);
    wallVertices = reshape(domain.geometry.vertices(farfieldRows, :, :), ...
        farfieldCount, 4, 3);
    wallAreas = domain.geometry.areas(farfieldRows);
    radius = hypot(centers(:, 1), centers(:, 2));
    theta = atan2(centers(:, 2), centers(:, 1));
    radialUnit = [cos(theta), sin(theta), zeros(farfieldCount, 1)];
    tangentialUnit = [-sin(theta), cos(theta), zeros(farfieldCount, 1)];

    geometricNormals = diagonal_cross_normals(wallVertices);
    benchmarkNormals = benchmark_first_triple_normals(wallVertices);
    slope = (effective.effectiveTopRadiusM - ...
        effective.effectiveBottomRadiusM) / domain.cfg.water_depth;
    analyticNormals = [-radialUnit(:, 1), -radialUnit(:, 2), ...
        repmat(slope, farfieldCount, 1)];
    analyticNormals = analyticNormals ./ sqrt(1 + slope ^ 2);

    productionNtheta = sum(productionNormals .* tangentialUnit, 2);
    geometricNtheta = sum(geometricNormals .* tangentialUnit, 2);
    analyticNtheta = sum(analyticNormals .* tangentialUnit, 2);
    benchmarkNtheta = sum(benchmarkNormals .* tangentialUnit, 2);
    productionNr = sum(productionNormals .* radialUnit, 2);

    allVertexRows = reshape(domain.geometry.vertices, [], 3);
    nodeTolerance = 256 * eps(max([1; abs(allVertexRows(:))]));
    quantizedVertices = round(allVertexRows / nodeTolerance);
    [~, ~, allNodeIds] = unique(quantizedVertices, 'rows');
    allPanelNodeIds = reshape(allNodeIds, domain.geometry.total_panels, 4);
    wallNodeIds = allPanelNodeIds(farfieldRows, :);
    seamConnectivityPass = structured_wall_connectivity_pass(wallNodeIds, ...
        effective.commonOuterThetaNodeCount, ...
        effective.wallDerived.verticalLayerCount);

    topProductionRows = top_rows_by_magnitude(productionNtheta, 20);
    productionTopTable = normal_lineage_table(topProductionRows, farfieldRows, ...
        wallNodeIds, centers, radius, theta, productionNormals, ...
        geometricNormals, analyticNormals, benchmarkNormals, ...
        productionNtheta, geometricNtheta, analyticNtheta, benchmarkNtheta);
    productionTopFile = fullfile(artifactDirectory, ...
        'Phase2_3_Normal_Lineage_Top20.csv');
    writetable(productionTopTable, productionTopFile);

    %% Stage 3: Reproduce the stale 0.016359 benchmark source exactly

    legacy = read_legacy_benchmark_bmf(legacyBenchmarkBMF);
    legacyFreeSurfaceBMF = strrep(legacyBenchmarkBMF, ...
        '_farfield.bmf', '_fs.bmf');
    legacyBottomBMF = strrep(legacyBenchmarkBMF, ...
        '_farfield.bmf', '_seabed.bmf');
    assert(isfile(legacyFreeSurfaceBMF) && isfile(legacyBottomBMF), ...
        'CRESTU:Phase23LegacyComponentMesh', ...
        'Legacy benchmark FS/bottom component meshes are missing.');
    legacyFreeSurfaceMesh = read_bmf(legacyFreeSurfaceBMF);
    legacyBottomMesh = read_bmf(legacyBottomBMF);
    legacyFreeSurfaceCount = legacyFreeSurfaceMesh.n_panels;
    legacyBottomCount = legacyBottomMesh.n_panels;
    legacyGlobalOffset = bodyCount + legacyFreeSurfaceCount + ...
        legacyBottomCount;
    legacyRadius = hypot(legacy.centers(:, 1), legacy.centers(:, 2));
    legacyTheta = atan2(legacy.centers(:, 2), legacy.centers(:, 1));
    legacyTangentialUnit = [-sin(legacyTheta), cos(legacyTheta), ...
        zeros(legacy.panelCount, 1)];
    legacyNtheta = sum(legacy.normals .* legacyTangentialUnit, 2);
    [legacyMaximumAbsNtheta, legacyMaximumPanel] = max(abs(legacyNtheta));
    legacyNodeTolerance = 256 * eps(max([1; abs(legacy.vertices(:))]));
    legacyQuantized = round(reshape(legacy.vertices, [], 3) / ...
        legacyNodeTolerance);
    [~, ~, legacyNodeIdsFlat] = unique(legacyQuantized, 'rows');
    legacyNodeIds = reshape(legacyNodeIdsFlat, legacy.panelCount, 4);
    topLegacyRows = top_rows_by_magnitude(legacyNtheta, 20);
    legacyTopTable = legacy_lineage_table(topLegacyRows, legacyGlobalOffset, ...
        legacyNodeIds, legacy, legacyRadius, legacyTheta, legacyNtheta);
    legacyTopFile = fullfile(artifactDirectory, ...
        'Phase2_3_Legacy_Hankel_0p016359_Top20.csv');
    writetable(legacyTopTable, legacyTopFile);

    finalBMFMesh = read_bmf(finalEqualCountBMF);
    finalBMFNtheta = cylindrical_ntheta(finalBMFMesh.centers, ...
        finalBMFMesh.normals);
    productionFingerprint = mesh_fingerprint(domain.farfield);
    legacyParsedMesh = read_bmf(legacyBenchmarkBMF);
    legacyFingerprint = mesh_fingerprint(legacyParsedMesh);
    finalFingerprint = mesh_fingerprint(finalBMFMesh);

    maximumMergedVsComponentNormalDifference = max(abs( ...
        productionNormals - reshape(domain.farfield.normals, ...
        farfieldCount, 3)), [], 'all');
    minimumProductionCrossAlignment = min(sum( ...
        productionNormals .* geometricNormals, 2));
    minimumProductionBenchmarkAlignment = min(sum( ...
        productionNormals .* benchmarkNormals, 2));
    maximumProductionAbsNtheta = max(abs(productionNtheta));
    maximumGeometricAbsNtheta = max(abs(geometricNtheta));
    maximumAnalyticAbsNtheta = max(abs(analyticNtheta));
    maximumBenchmarkAbsNtheta = max(abs(benchmarkNtheta));

    lineageNames = ["production_in_memory_assembly_input"; ...
        "phase2_2_final_equal_count_bmf_delivery"; ...
        "legacy_hankel_frozen_unequal_wall"];
    sourceRoles = ["ACTIVE_ASSEMBLY_INPUT"; "DELIVERY_SNAPSHOT_NOT_RELOADED"; ...
        "STALE_BENCHMARK_FIXTURE"];
    sourcePaths = ["in-memory build from Frustum_Top_Only.cfg"; ...
        string(finalEqualCountBMF); string(legacyBenchmarkBMF)];
    topology = [string(effective.wallDerived.topology); ...
        string(finalBMFMesh.header); string(legacy.header)];
    panelCounts = [farfieldCount; finalBMFMesh.n_panels; legacy.panelCount];
    maximumAbsNtheta = [maximumProductionAbsNtheta; ...
        max(abs(finalBMFNtheta)); legacyMaximumAbsNtheta];
    activeAssemblyInput = [true; false; false];
    geometryHashes = [string(productionFingerprint.hash); ...
        string(finalFingerprint.hash); string(legacyFingerprint.hash)];
    lineageSummary = table(lineageNames, sourceRoles, sourcePaths, topology, ...
        panelCounts, maximumAbsNtheta, activeAssemblyInput, geometryHashes, ...
        'VariableNames', {'dataset', 'source_role', 'source_path', ...
        'topology_or_header', 'panel_count', 'max_abs_ntheta', ...
        'active_assembly_input', 'mesh_fingerprint_sha256'});
    lineageSummaryFile = fullfile(artifactDirectory, ...
        'Phase2_3_Normal_Lineage_Summary.csv');
    writetable(lineageSummary, lineageSummaryFile);

    normalLineagePass = maximumProductionAbsNtheta < normalTolerance && ...
        maximumGeometricAbsNtheta < normalTolerance && ...
        maximumAnalyticAbsNtheta < normalTolerance && ...
        maximumBenchmarkAbsNtheta < normalTolerance && ...
        maximumMergedVsComponentNormalDifference == 0 && ...
        minimumProductionCrossAlignment >= 1 - 1e-12 && ...
        minimumProductionBenchmarkAlignment >= 1 - 1e-12 && ...
        seamConnectivityPass && all(productionNr < 0) && ...
        all(domain.geometry.panel_type(farfieldRows) == 5) && ...
        legacyMaximumAbsNtheta > normalTolerance && ...
        legacy.panelCount ~= farfieldCount;

    %% Stage 4: Decompose m=0 and m=1 Hankel operator errors

    [physicalK, ~] = solve_wave_dispersion(omega, gravity, ...
        domain.cfg.water_depth);
    nominalMu = domain.cfg.phase2_2_controls.effective.actualMu0;
    outerBC = get_rankine_outer_absorbing_bc(domain.geometry.centers, ...
        domain.geometry.normals, domain.stats, omega, gravity, ...
        domain.cfg.water_depth, domain.cfg, physicalK, nominalMu);
    assert(numel(outerBC.gamma) == farfieldCount, ...
        'CRESTU:Phase23OuterBCCount', ...
        'Production outer-ABC gamma count does not equal FARFIELD panel count.');
    maximumHelperProjectionDifference = max(abs( ...
        outerBC.tangentialNormal - productionNtheta));
    assert(maximumHelperProjectionDifference <= 64 * eps, ...
        'CRESTU:Phase23OuterBCNormalLineage', ...
        'Production outer-ABC did not consume the audited merged normals.');

    decompositionRows = cell(0, 1);
    scalingRows = cell(0, 1);
    implementationMaximumRelative = 0;
    implementationWeightedL2 = 0;
    scalingClassified = true;
    fittedOrders = NaN(2, 1);
    wallFittedOrders = NaN(2, 1);
    baseModeResults = cell(2, 1);
    for mode = 0:1
        asymptoticWeightedL2 = NaN(numel(radiusFactors), 1);
        cylinderWeightedL2 = NaN(numel(radiusFactors), 1);
        for factorIndex = 1:numel(radiusFactors)
            radiusFactor = radiusFactors(factorIndex);
            scaledGeometryCenters = domain.geometry.centers;
            scaledGeometryCenters(farfieldRows, 1:2) = ...
                radiusFactor * scaledGeometryCenters(farfieldRows, 1:2);
            scaledOuterBC = get_rankine_outer_absorbing_bc( ...
                scaledGeometryCenters, domain.geometry.normals, domain.stats, ...
                omega, gravity, domain.cfg.water_depth, domain.cfg, ...
                physicalK, nominalMu);
            scaledCenters = scaledGeometryCenters(farfieldRows, :);
            components = hankel_components(scaledCenters, productionNormals, ...
                mode, scaledOuterBC.kappa, domain.cfg.water_depth, ...
                scaledOuterBC.gamma);
            thetaMetrics = error_metrics(components.fullExact - ...
                components.exactMeridional, components.fullExact, ...
                components.exactMeridional, components.kPhiScale, wallAreas);
            asymptoticMetrics = error_metrics(components.exactMeridional - ...
                components.analyticProduction, components.exactMeridional, ...
                components.analyticProduction, components.kPhiScale, wallAreas);
            implementationMetrics = error_metrics( ...
                components.actualProduction - components.analyticProduction, ...
                components.actualProduction, components.analyticProduction, ...
                components.kPhiScale, wallAreas);
            cylinderMetrics = cylinder_coefficient_metrics(scaledCenters, ...
                mode, scaledOuterBC.kappa, wallAreas);

            asymptoticWeightedL2(factorIndex) = ...
                asymptoticMetrics.weightedL2Relative;
            cylinderWeightedL2(factorIndex) = ...
                cylinderMetrics.weightedL2Relative;
            implementationMaximumRelative = max( ...
                implementationMaximumRelative, implementationMetrics.maxRelative);
            implementationWeightedL2 = max(implementationWeightedL2, ...
                implementationMetrics.weightedL2Relative);

            scalingRows{end + 1, 1} = scaling_row(mode, radiusFactor, ...
                scaledOuterBC.kappa, scaledCenters, thetaMetrics, ...
                asymptoticMetrics, implementationMetrics, ...
                cylinderMetrics); %#ok<AGROW>
            if radiusFactor == 1
                baseModeResults{mode + 1} = struct( ...
                    'components', components, 'thetaMetrics', thetaMetrics, ...
                    'asymptoticMetrics', asymptoticMetrics, ...
                    'implementationMetrics', implementationMetrics);
                decompositionRows{end + 1, 1} = decomposition_row( ...
                    mode, 'E_THETA', thetaMetrics); %#ok<AGROW>
                decompositionRows{end + 1, 1} = decomposition_row( ...
                    mode, 'E_ASYMPTOTIC', asymptoticMetrics); %#ok<AGROW>
                decompositionRows{end + 1, 1} = decomposition_row( ...
                    mode, 'E_IMPLEMENTATION', implementationMetrics); %#ok<AGROW>
            end
        end

        wallFit = polyfit(log(radiusFactors(:)), ...
            log(asymptoticWeightedL2), 1);
        cylinderFit = polyfit(log(radiusFactors(:)), ...
            log(cylinderWeightedL2), 1);
        wallFittedOrders(mode + 1) = -wallFit(1);
        fittedOrders(mode + 1) = -cylinderFit(1);
        monotonePass = all(diff(cylinderWeightedL2) < 0);
        orderPass = fittedOrders(mode + 1) >= 1.5 && ...
            fittedOrders(mode + 1) <= 2.5;
        scalingClassified = scalingClassified && monotonePass && orderPass;
    end

    decompositionTable = vertcat(decompositionRows{:});
    decompositionFile = fullfile(artifactDirectory, ...
        'Phase2_3_Hankel_Error_Decomposition.csv');
    writetable(decompositionTable, decompositionFile);
    scalingTable = vertcat(scalingRows{:});
    scalingFile = fullfile(artifactDirectory, ...
        'Phase2_3_Hankel_Radius_Scaling.csv');
    writetable(scalingTable, scalingFile);

    %% Stage 4b: Reproduce and classify the legacy physical-k 0.17843% value

    legacyScalingRows = cell(0, 1);
    legacyFittedOrders = NaN(2, 1);
    legacyScalingClassified = true;
    for mode = 0:1
        legacyWeightedL2 = NaN(numel(radiusFactors), 1);
        for factorIndex = 1:numel(radiusFactors)
            radiusFactor = radiusFactors(factorIndex);
            scaledLegacyCenters = legacy.centers;
            scaledLegacyCenters(:, 1:2) = radiusFactor * ...
                scaledLegacyCenters(:, 1:2);
            physicalGamma = analytic_production_gamma( ...
                scaledLegacyCenters, legacy.normals, physicalK, ...
                domain.cfg.water_depth);
            legacyComponents = hankel_components(scaledLegacyCenters, ...
                legacy.normals, mode, physicalK, domain.cfg.water_depth, ...
                physicalGamma);
            legacyAsymptoticMetrics = error_metrics( ...
                legacyComponents.exactMeridional - ...
                legacyComponents.analyticProduction, ...
                legacyComponents.exactMeridional, ...
                legacyComponents.analyticProduction, ...
                legacyComponents.kPhiScale, legacyParsedMesh.areas);
            legacyCylinderMetrics = cylinder_coefficient_metrics( ...
                scaledLegacyCenters, mode, physicalK, ...
                legacyParsedMesh.areas);
            legacyWeightedL2(factorIndex) = ...
                legacyAsymptoticMetrics.weightedL2Relative;
            legacyScalingRows{end + 1, 1} = legacy_scaling_row(mode, ...
                radiusFactor, physicalK, scaledLegacyCenters, ...
                legacyAsymptoticMetrics, legacyCylinderMetrics); %#ok<AGROW>
        end
        legacyFit = polyfit(log(radiusFactors(:)), log(legacyWeightedL2), 1);
        legacyFittedOrders(mode + 1) = -legacyFit(1);
        legacyScalingClassified = legacyScalingClassified && ...
            all(diff(legacyWeightedL2) < 0) && ...
            legacyFittedOrders(mode + 1) >= 1.5 && ...
            legacyFittedOrders(mode + 1) <= 2.5;
    end
    legacyScalingTable = vertcat(legacyScalingRows{:});
    legacyScalingFile = fullfile(artifactDirectory, ...
        'Phase2_3_Legacy_0p17843_Radius_Scaling.csv');
    writetable(legacyScalingTable, legacyScalingFile);
    scalingClassified = scalingClassified && legacyScalingClassified;

    implementationPass = implementationMaximumRelative <= ...
        implementationTolerance && implementationWeightedL2 <= ...
        implementationTolerance;

    %% Stage 5: Emit the machine-readable Phase 2.3 pre-assembly gate

    if normalLineagePass
        abcNormalLineage = 'PASS';
        abcWallNthetaStatus = 'RESOLVED';
    else
        abcNormalLineage = 'FAIL';
        abcWallNthetaStatus = 'UNRESOLVED';
    end
    if implementationPass
        abcImplementationError = 'PASS';
    else
        abcImplementationError = 'FAIL';
    end
    if scalingClassified
        hankelAsymptoticErrorClassified = 'YES';
    else
        hankelAsymptoticErrorClassified = 'NO';
    end

    statusName = ["ABC_NORMAL_LINEAGE"; "ABC_WALL_NTHETA_STATUS"; ...
        "ABC_IMPLEMENTATION_ERROR"; "HANKEL_ASYMPTOTIC_ERROR_CLASSIFIED"; ...
        "P_FULL_ASSEMBLY"; "OMEGA_1P5_FOCUSED_CASE"; ...
        "FORMAL_FREQUENCY_SWEEP"];
    statusValue = [string(abcNormalLineage); string(abcWallNthetaStatus); ...
        string(abcImplementationError); ...
        string(hankelAsymptoticErrorClassified); "NOT_RUN"; "NOT_RUN"; ...
        "NOT_RUN"];
    statusTable = table(statusName, statusValue, ...
        'VariableNames', {'status_name', 'status_value'});
    statusFile = fullfile(artifactDirectory, 'Phase2_3_Audit_Status.csv');
    writetable(statusTable, statusFile);

    result = struct( ...
        'schemaVersion', 1, ...
        'testName', 'Phase 2.3 P_FULL ABC normal/operator closure', ...
        'artifactDirectory', artifactDirectory, ...
        'configFile', configFile, ...
        'legacyBenchmarkBMF', legacyBenchmarkBMF, ...
        'finalEqualCountBMF', finalEqualCountBMF, ...
        'omegaRadPerS', omega, 'physicalKPerM', physicalK, ...
        'productionKappaPerM', outerBC.kappa, ...
        'farfieldGlobalRows', farfieldRows, ...
        'farfieldPanelCount', farfieldCount, ...
        'productionTopology', effective.wallDerived.topology, ...
        'productionMaximumAbsNtheta', maximumProductionAbsNtheta, ...
        'geometricMaximumAbsNtheta', maximumGeometricAbsNtheta, ...
        'analyticMaximumAbsNtheta', maximumAnalyticAbsNtheta, ...
        'benchmarkAlgorithmOnProductionMaximumAbsNtheta', ...
            maximumBenchmarkAbsNtheta, ...
        'finalBMFMaximumAbsNtheta', max(abs(finalBMFNtheta)), ...
        'legacyBenchmarkMaximumAbsNtheta', legacyMaximumAbsNtheta, ...
        'legacyBenchmarkMaximumPanel', legacyMaximumPanel, ...
        'legacyBenchmarkHeader', legacy.header, ...
        'maximumMergedVsComponentNormalDifference', ...
            maximumMergedVsComponentNormalDifference, ...
        'maximumHelperProjectionDifference', ...
            maximumHelperProjectionDifference, ...
        'minimumProductionCrossAlignment', minimumProductionCrossAlignment, ...
        'minimumProductionBenchmarkAlignment', ...
            minimumProductionBenchmarkAlignment, ...
        'structuredSeamConnectivityPass', seamConnectivityPass, ...
        'normalTolerance', normalTolerance, ...
        'implementationTolerance', implementationTolerance, ...
        'implementationMaximumRelative', implementationMaximumRelative, ...
        'implementationWeightedL2Relative', implementationWeightedL2, ...
        'radiusScalingFittedOrders', fittedOrders, ...
        'wallProjectionRadiusScalingFittedOrders', wallFittedOrders, ...
        'legacyPhysicalKRadiusScalingFittedOrders', legacyFittedOrders, ...
        'baseModeResults', {baseModeResults}, ...
        'ABC_NORMAL_LINEAGE', abcNormalLineage, ...
        'ABC_WALL_NTHETA_STATUS', abcWallNthetaStatus, ...
        'ABC_IMPLEMENTATION_ERROR', abcImplementationError, ...
        'HANKEL_ASYMPTOTIC_ERROR_CLASSIFIED', ...
            hankelAsymptoticErrorClassified, ...
        'P_FULL_ASSEMBLY', 'NOT_RUN', ...
        'OMEGA_1P5_FOCUSED_CASE', 'NOT_RUN', ...
        'FORMAL_FREQUENCY_SWEEP', 'NOT_RUN', ...
        'files', struct('productionTop20', productionTopFile, ...
            'legacyTop20', legacyTopFile, 'lineageSummary', ...
            lineageSummaryFile, 'decomposition', decompositionFile, ...
            'scaling', scalingFile, 'status', statusFile, ...
            'legacyPhysicalKScaling', legacyScalingFile, ...
            'functionResolution', functionResolutionFile));
    resultFile = fullfile(artifactDirectory, ...
        'Phase2_3_ABC_Operator_Audit_Result.mat');
    save(resultFile, 'result');
    result.files.mat = resultFile;

    fprintf('[RESULT] ABC_NORMAL_LINEAGE = %s\n', abcNormalLineage);
    fprintf('[RESULT] ABC_WALL_NTHETA_STATUS = %s\n', abcWallNthetaStatus);
    fprintf('[RESULT] PRODUCTION_MAX_ABS_NTHETA = %.17g\n', ...
        maximumProductionAbsNtheta);
    fprintf('[RESULT] LEGACY_HANKEL_MAX_ABS_NTHETA = %.17g | panel=%d\n', ...
        legacyMaximumAbsNtheta, legacyMaximumPanel);
    fprintf('[RESULT] ABC_IMPLEMENTATION_ERROR = %s | max=%.3e | L2=%.3e\n', ...
        abcImplementationError, implementationMaximumRelative, ...
        implementationWeightedL2);
    fprintf('[RESULT] HANKEL_ASYMPTOTIC_ERROR_CLASSIFIED = %s | orders=[%.4f %.4f]\n', ...
        hankelAsymptoticErrorClassified, fittedOrders(1), fittedOrders(2));
    fprintf('[RESULT] P_FULL_ASSEMBLY = NOT_RUN\n');
    fprintf('[RESULT] OMEGA_1P5_FOCUSED_CASE = NOT_RUN\n');
end

function outputFile = audit_runtime_function_resolution(repositoryRoot, ...
        artifactDirectory)
% Prove that no Phase 2.2 shadow implementation is active in this session.
    functionNames = ["apply_rankine_outer_truncation"; ...
        "merge_domain_geometry"; "get_rankine_outer_absorbing_bc"; ...
        "assemble_rankine_matrix"; "get_rankine_source_orientation"];
    relativeExpected = [string(fullfile('Source Code', '2.Mesh', ...
        'apply_rankine_outer_truncation.m')); ...
        string(fullfile('Source Code', '2.Mesh', 'merge_domain_geometry.m')); ...
        string(fullfile('Source Code', '4.Potential', ...
        'get_rankine_outer_absorbing_bc.m')); ...
        string(fullfile('Source Code', '4.Potential', ...
        'assemble_rankine_matrix.m')); ...
        string(fullfile('Source Code', '4.Potential', ...
        'get_rankine_source_orientation.m'))];
    activePath = strings(numel(functionNames), 1);
    expectedPath = strings(numel(functionNames), 1);
    exactMatch = false(numel(functionNames), 1);
    for index = 1:numel(functionNames)
        activePath(index) = string(which(char(functionNames(index))));
        expectedPath(index) = string(fullfile(repositoryRoot, ...
            relativeExpected(index)));
        exactMatch(index) = strcmpi(char(activePath(index)), ...
            char(expectedPath(index)));
    end
    resolution = table(functionNames, activePath, expectedPath, exactMatch, ...
        'VariableNames', {'function_name', 'active_path', 'expected_path', ...
        'exact_production_path_match'});
    outputFile = fullfile(artifactDirectory, ...
        'Phase2_3_Runtime_Function_Resolution.csv');
    writetable(resolution, outputFile);
    assert(all(exactMatch), 'CRESTU:Phase23ShadowPath', ...
        'A shadow implementation is active instead of a production function.');
end

function add_production_paths(repositoryRoot)
    directories = {fullfile(repositoryRoot, 'Source Code', '1.Input'), ...
        fullfile(repositoryRoot, 'Source Code', '2.Mesh'), ...
        fullfile(repositoryRoot, 'Source Code', '4.Potential'), ...
        fullfile(repositoryRoot, 'Source Code', '5.Force'), ...
        fullfile(repositoryRoot, 'Case_Wave')};
    for directoryIndex = 1:numel(directories)
        assert(isfolder(directories{directoryIndex}), ...
            'CRESTU:Phase23ProductionPath', ...
            'Required production directory is missing: %s', ...
            directories{directoryIndex});
        addpath(directories{directoryIndex}, '-begin');
    end
end

function [domain, effective] = build_in_memory_domain(cfg)
%BUILD_IN_MEMORY_DOMAIN Mirror production geometry creation without writes.

    bodyConfiguration = cfg.bodies(1);
    body = transform_body_mesh(read_bmf(bodyConfiguration.mesh_file), ...
        bodyConfiguration);
    body = reduce_mesh_by_symmetry(body, cfg.isx, cfg.isy, cfg.z_tol);
    body.cg = cfg.mass_props(1).cg;
    body.body_id = bodyConfiguration.id;
    bodyWaterline = extract_waterline(body, cfg.z_tol);
    outerWaterline = bodyWaterline;
    if ~isempty(cfg.outer_reference_mesh_file)
        referenceMesh = transform_body_mesh( ...
            read_bmf(cfg.outer_reference_mesh_file), bodyConfiguration);
        referenceMesh = reduce_mesh_by_symmetry(referenceMesh, ...
            cfg.isx, cfg.isy, cfg.z_tol);
        outerWaterline = extract_waterline(referenceMesh, cfg.z_tol);
    end

    freeSurface = generate_free_surface_bmf('', outerWaterline, cfg, false);
    [bottomCfg, bottomReferenceSurface] = get_phase2_2_bottom_mesh_inputs( ...
        cfg, outerWaterline, freeSurface);
    bottom = generate_seabed_mesh(outerWaterline, bottomCfg, ...
        bottomReferenceSurface);
    outerBoundary = generate_farfield_mesh(outerWaterline, cfg, ...
        cfg.fs.nz_farfield);
    [freeSurface, bottom, outerBoundary, effective] = ...
        apply_rankine_outer_truncation(freeSurface, bottom, outerBoundary, ...
        cfg, cfg.fs.tuning_report.wavelengths(1));
    cfg.outer_truncation.effective = effective;

    stats = struct( ...
        'total_body_panels', body.n_panels, ...
        'body_vertices', size(unique(reshape(body.vertices, [], 3), ...
            'rows'), 1), ...
        'waterline_panels', waterline_panel_count(bodyWaterline), ...
        'outer_waterline_panels', waterline_panel_count(outerWaterline), ...
        'fs_panels', freeSurface.n_panels, ...
        'seabed_panels', bottom.n_panels, ...
        'farfield_panels', outerBoundary.n_panels);
    stats.total_dofs = stats.total_body_panels + stats.fs_panels + ...
        stats.seabed_panels + stats.farfield_panels;
    domain = struct('cfg', cfg, 'body_list', {{body}}, ...
        'fs', freeSurface, 'seabed', bottom, 'farfield', outerBoundary, ...
        'waterline', {{bodyWaterline}}, ...
        'body_waterlines', {{bodyWaterline}}, ...
        'outer_waterlines', {{outerWaterline}}, 'stats', stats);
    domain.geometry = merge_domain_geometry(domain);
end

function count = waterline_panel_count(waterline)
    if waterline.is_closed
        count = waterline.n_pts;
    else
        count = max(0, waterline.n_pts - 1);
    end
end

function normals = diagonal_cross_normals(vertices)
    panelCount = size(vertices, 1);
    normals = NaN(panelCount, 3);
    for panelIndex = 1:panelCount
        panel = reshape(vertices(panelIndex, :, :), 4, 3);
        areaVector = cross(panel(3, :) - panel(1, :), ...
            panel(4, :) - panel(2, :));
        magnitude = norm(areaVector);
        assert(isfinite(magnitude) && magnitude > 0, ...
            'CRESTU:Phase23DegeneratePanel', ...
            'Panel %d has a zero diagonal-cross area.', panelIndex);
        normals(panelIndex, :) = areaVector / magnitude;
    end
end

function normals = benchmark_first_triple_normals(vertices)
% Replicate the normal algorithm in the Phase 2.2 Hankel benchmark.
    panelCount = size(vertices, 1);
    normals = NaN(panelCount, 3);
    for panelIndex = 1:panelCount
        panel = reshape(vertices(panelIndex, :, :), 4, 3);
        uniquePanel = unique_panel_vertices(panel);
        found = false;
        for firstIndex = 1:(size(uniquePanel, 1) - 2)
            for secondIndex = (firstIndex + 1):(size(uniquePanel, 1) - 1)
                for thirdIndex = (secondIndex + 1):size(uniquePanel, 1)
                    candidate = cross( ...
                        uniquePanel(secondIndex, :) - uniquePanel(firstIndex, :), ...
                        uniquePanel(thirdIndex, :) - uniquePanel(firstIndex, :));
                    magnitude = norm(candidate);
                    if magnitude > 1e-14
                        normals(panelIndex, :) = candidate / magnitude;
                        found = true;
                        break
                    end
                end
                if found
                    break
                end
            end
            if found
                break
            end
        end
        assert(found, 'CRESTU:Phase23BenchmarkNormal', ...
            'Panel %d has no non-collinear winding triple.', panelIndex);
    end
end

function uniquePanel = unique_panel_vertices(panel)
    uniquePanel = zeros(4, 3);
    uniqueCount = 0;
    for vertexIndex = 1:4
        if uniqueCount == 0 || all(max(abs(uniquePanel(1:uniqueCount, :) - ...
                panel(vertexIndex, :)), [], 2) > 1e-12)
            uniqueCount = uniqueCount + 1;
            uniquePanel(uniqueCount, :) = panel(vertexIndex, :);
        end
    end
    uniquePanel = uniquePanel(1:uniqueCount, :);
end

function pass = structured_wall_connectivity_pass(nodeIds, thetaCount, layerCount)
    pass = size(nodeIds, 1) == thetaCount * layerCount;
    if ~pass
        return
    end
    for layerIndex = 1:layerCount
        rows = (layerIndex - 1) * thetaCount + (1:thetaCount);
        nextRows = rows([2:end, 1]);
        pass = pass && all(nodeIds(rows, 2) == nodeIds(nextRows, 1)) && ...
            all(nodeIds(rows, 3) == nodeIds(nextRows, 4));
        if layerIndex < layerCount
            lowerRows = rows + thetaCount;
            pass = pass && all(nodeIds(rows, 4) == nodeIds(lowerRows, 1)) && ...
                all(nodeIds(rows, 3) == nodeIds(lowerRows, 2));
        end
    end
end

function rows = top_rows_by_magnitude(values, requestedCount)
    [~, order] = sort(abs(values), 'descend');
    rows = order(1:min(requestedCount, numel(order)));
end

function output = normal_lineage_table(rows, globalRows, nodeIds, centers, ...
        radius, theta, productionNormals, geometricNormals, analyticNormals, ...
        benchmarkNormals, productionNtheta, geometricNtheta, analyticNtheta, ...
        benchmarkNtheta)
    count = numel(rows);
    localPanelId = rows(:);
    globalPanelId = globalRows(rows).';
    nodeIdText = strings(count, 1);
    for index = 1:count
        ids = nodeIds(rows(index), :);
        nodeIdText(index) = sprintf('%d|%d|%d|%d', ids);
    end
    boundaryGroup = repmat("FARFIELD", count, 1);
    boundaryType = repmat(5, count, 1);
    output = table(globalPanelId, localPanelId, nodeIdText, boundaryGroup, ...
        boundaryType, centers(rows, 1), centers(rows, 2), centers(rows, 3), ...
        radius(rows), theta(rows), productionNormals(rows, 1), ...
        productionNormals(rows, 2), productionNormals(rows, 3), ...
        productionNtheta(rows), geometricNormals(rows, 1), ...
        geometricNormals(rows, 2), geometricNormals(rows, 3), ...
        geometricNtheta(rows), analyticNormals(rows, 1), ...
        analyticNormals(rows, 2), analyticNormals(rows, 3), ...
        analyticNtheta(rows), benchmarkNormals(rows, 1), ...
        benchmarkNormals(rows, 2), benchmarkNormals(rows, 3), ...
        benchmarkNtheta(rows), ...
        'VariableNames', {'global_panel_id', 'farfield_local_panel_id', ...
        'node_ids', 'boundary_group', 'boundary_type', 'centroid_x_m', ...
        'centroid_y_m', 'centroid_z_m', 'radius_m', 'theta_rad', ...
        'production_nx', 'production_ny', 'production_nz', ...
        'production_ntheta', 'geometric_nx', 'geometric_ny', ...
        'geometric_nz', 'geometric_ntheta', 'analytic_nx', 'analytic_ny', ...
        'analytic_nz', 'analytic_ntheta', 'benchmark_algorithm_nx', ...
        'benchmark_algorithm_ny', 'benchmark_algorithm_nz', ...
        'benchmark_algorithm_ntheta'});
end

function legacy = read_legacy_benchmark_bmf(fileName)
% Reproduce the Phase 2.2 benchmark parser, including unique-vertex centers.
    fileId = fopen(fileName, 'r');
    assert(fileId >= 0, 'CRESTU:Phase23LegacyOpen', ...
        'Cannot open legacy benchmark BMF: %s', fileName);
    cleanup = onCleanup(@() fclose(fileId));
    header = fgetl(fileId);
    line2 = textscan(fgetl(fileId), '%f %d');
    textscan(fgetl(fileId), '%d %d');
    panelCount = sscanf(fgetl(fileId), '%d', 1);
    vertices = zeros(panelCount, 4, 3);
    for panelIndex = 1:panelCount
        for vertexIndex = 1:4
            line = fgetl(fileId);
            while ischar(line) && isempty(strtrim(line))
                line = fgetl(fileId);
            end
            xyz = sscanf(line, '%f', 3);
            assert(numel(xyz) == 3, 'CRESTU:Phase23LegacyVertex', ...
                'Legacy panel %d vertex %d is invalid.', ...
                panelIndex, vertexIndex);
            vertices(panelIndex, vertexIndex, :) = reshape(xyz, 1, 1, 3);
        end
    end
    centers = zeros(panelCount, 3);
    for panelIndex = 1:panelCount
        centers(panelIndex, :) = mean(unique_panel_vertices(reshape( ...
            vertices(panelIndex, :, :), 4, 3)), 1);
    end
    normals = benchmark_first_triple_normals(vertices);
    legacy = struct('file', fileName, 'header', strtrim(header), ...
        'panelType', double(line2{2}), 'panelCount', panelCount, ...
        'vertices', vertices, 'centers', centers, 'normals', normals);
end

function output = legacy_lineage_table(rows, globalOffset, nodeIds, legacy, ...
        radius, theta, ntheta)
    count = numel(rows);
    panelId = rows(:);
    legacyMergedGlobalPanelId = globalOffset + panelId;
    nodeIdText = strings(count, 1);
    uniqueVertexCount = zeros(count, 1);
    for index = 1:count
        ids = nodeIds(rows(index), :);
        nodeIdText(index) = sprintf('%d|%d|%d|%d', ids);
        uniqueVertexCount(index) = size(unique_panel_vertices(reshape( ...
            legacy.vertices(rows(index), :, :), 4, 3)), 1);
    end
    boundaryGroup = repmat("FARFIELD_LEGACY_UNEQUAL_ZIPPER", count, 1);
    boundaryType = repmat(legacy.panelType, count, 1);
    output = table(panelId, legacyMergedGlobalPanelId, nodeIdText, ...
        uniqueVertexCount, boundaryGroup, ...
        boundaryType, legacy.centers(rows, 1), legacy.centers(rows, 2), ...
        legacy.centers(rows, 3), radius(rows), theta(rows), ...
        legacy.normals(rows, 1), legacy.normals(rows, 2), ...
        legacy.normals(rows, 3), ntheta(rows), ...
        'VariableNames', {'legacy_panel_id', ...
        'legacy_merged_global_panel_id', 'node_ids', 'unique_vertex_count', ...
        'boundary_group', 'boundary_type', ...
        'centroid_x_m', 'centroid_y_m', 'centroid_z_m', 'radius_m', ...
        'theta_rad', 'benchmark_nx', 'benchmark_ny', 'benchmark_nz', ...
        'benchmark_ntheta'});
end

function ntheta = cylindrical_ntheta(centers, normals)
    radius = hypot(centers(:, 1), centers(:, 2));
    tangentialUnit = [-centers(:, 2) ./ radius, ...
        centers(:, 1) ./ radius, zeros(size(radius))];
    ntheta = sum(normals .* tangentialUnit, 2);
end

function components = hankel_components(centers, normals, mode, kappa, ...
        waterDepth, actualGamma)
    radius = hypot(centers(:, 1), centers(:, 2));
    theta = atan2(centers(:, 2), centers(:, 1));
    z = centers(:, 3);
    radialUnit = [cos(theta), sin(theta), zeros(size(radius))];
    tangentialUnit = [-sin(theta), cos(theta), zeros(size(radius))];
    radialNormal = sum(normals .* radialUnit, 2);
    tangentialNormal = sum(normals .* tangentialUnit, 2);
    verticalNormal = normals(:, 3);

    argument = kappa .* radius;
    hankel = besselh(mode, 2, argument);
    hankelNext = besselh(mode + 1, 2, argument);
    hankelPrime = (mode ./ argument) .* hankel - hankelNext;
    phase = exp(1i * mode .* theta);
    verticalFactor = cosh(kappa .* (z + waterDepth)) ./ ...
        cosh(kappa * waterDepth);
    phi = hankel .* phase .* verticalFactor;
    radialDerivative = kappa .* hankelPrime .* phase .* verticalFactor;
    thetaDerivative = 1i * mode .* phi;
    verticalDerivative = kappa .* tanh(kappa .* (z + waterDepth)) .* phi;
    fullExact = radialNormal .* radialDerivative + ...
        (tangentialNormal ./ radius) .* thetaDerivative + ...
        verticalNormal .* verticalDerivative;
    exactMeridional = radialNormal .* radialDerivative + ...
        verticalNormal .* verticalDerivative;
    analyticGamma = (-radialNormal) .* ...
        (1i * kappa + 1 ./ (2 .* radius)) + ...
        verticalNormal .* kappa .* tanh(kappa .* (z + waterDepth));
    analyticProduction = analyticGamma .* phi;
    actualProduction = actualGamma .* phi;
    components = struct('Phi', phi, 'radialDerivative', radialDerivative, ...
        'thetaDerivative', thetaDerivative, ...
        'verticalDerivative', verticalDerivative, 'fullExact', fullExact, ...
        'exactMeridional', exactMeridional, ...
        'analyticProduction', analyticProduction, ...
        'actualProduction', actualProduction, ...
        'analyticGamma', analyticGamma, 'actualGamma', actualGamma, ...
        'radialNormal', radialNormal, ...
        'tangentialNormal', tangentialNormal, ...
        'verticalNormal', verticalNormal, ...
        'kPhiScale', abs(kappa .* phi));
end

function gamma = analytic_production_gamma(centers, normals, kappa, waterDepth)
    radius = hypot(centers(:, 1), centers(:, 2));
    radialNormal = (normals(:, 1) .* centers(:, 1) + ...
        normals(:, 2) .* centers(:, 2)) ./ radius;
    verticalNormal = normals(:, 3);
    gamma = (-radialNormal) .* (1i * kappa + 1 ./ (2 .* radius)) + ...
        verticalNormal .* kappa .* tanh(kappa .* ...
        (centers(:, 3) + waterDepth));
end

function metrics = error_metrics(errorValues, firstReference, ...
        secondReference, kPhiScale, areas)
% Use a field-scale floor so local derivative cancellation cannot inflate error.
    absoluteError = abs(errorValues(:));
    pointScale = max([abs(firstReference(:)), abs(secondReference(:)), ...
        kPhiScale(:)], [], 2);
    globalFloor = 1e-12 * max([pointScale(:); 1e-300]);
    denominator = max(pointScale, globalFloor);
    relativeError = absoluteError ./ denominator;
    weights = areas(:);
    assert(all(isfinite(weights) & weights > 0), ...
        'CRESTU:Phase23MetricWeights', ...
        'Hankel benchmark areas must be finite and positive.');
    numeratorL2 = sqrt(sum(weights .* absoluteError .^ 2));
    denominatorL2 = max([sqrt(sum(weights .* abs(firstReference(:)) .^ 2)), ...
        sqrt(sum(weights .* abs(secondReference(:)) .^ 2)), ...
        sqrt(sum(weights .* kPhiScale(:) .^ 2)), ...
        globalFloor * sqrt(sum(weights))]);
    metrics = struct( ...
        'maxAbsolute', max(absoluteError), ...
        'p95Absolute', percentile(absoluteError, 95), ...
        'weightedL2Absolute', sqrt(sum(weights .* absoluteError .^ 2) / ...
            sum(weights)), ...
        'maxRelative', max(relativeError), ...
        'p95Relative', percentile(relativeError, 95), ...
        'weightedL2Relative', numeratorL2 / denominatorL2, ...
        'minimumDenominator', min(denominator), ...
        'globalDenominatorFloor', globalFloor);
end

function metrics = cylinder_coefficient_metrics(centers, mode, kappa, areas)
% Radius-only oracle for the expected O((kappa*r)^-2) truncation scaling.
    radius = hypot(centers(:, 1), centers(:, 2));
    argument = kappa .* radius;
    hankel = besselh(mode, 2, argument);
    hankelNext = besselh(mode + 1, 2, argument);
    hankelPrime = (mode ./ argument) .* hankel - hankelNext;
    exactInwardCoefficient = -kappa .* hankelPrime ./ hankel;
    asymptoticInwardCoefficient = 1i * kappa + 1 ./ (2 .* radius);
    metrics = error_metrics(exactInwardCoefficient - ...
        asymptoticInwardCoefficient, exactInwardCoefficient, ...
        asymptoticInwardCoefficient, ...
        repmat(abs(kappa), size(radius)), areas);
end

function value = percentile(values, percentage)
    values = sort(values(isfinite(values)));
    assert(~isempty(values), 'CRESTU:Phase23Percentile', ...
        'Cannot calculate a percentile from an empty finite vector.');
    if numel(values) == 1
        value = values(1);
        return
    end
    position = 1 + (numel(values) - 1) * percentage / 100;
    lowerIndex = floor(position);
    upperIndex = ceil(position);
    if lowerIndex == upperIndex
        value = values(lowerIndex);
    else
        value = values(lowerIndex) + (position - lowerIndex) * ...
            (values(upperIndex) - values(lowerIndex));
    end
end

function row = decomposition_row(mode, errorClass, metrics)
    row = table(mode, string(errorClass), metrics.maxAbsolute, ...
        metrics.p95Absolute, metrics.weightedL2Absolute, ...
        metrics.maxRelative, metrics.p95Relative, ...
        metrics.weightedL2Relative, metrics.minimumDenominator, ...
        metrics.globalDenominatorFloor, ...
        'VariableNames', {'mode_m', 'error_class', 'max_absolute', ...
        'p95_absolute', 'weighted_l2_absolute', 'max_relative', ...
        'p95_relative', 'weighted_l2_relative', 'minimum_denominator', ...
        'global_denominator_floor'});
end

function row = scaling_row(mode, radiusFactor, kappa, centers, thetaMetrics, ...
        asymptoticMetrics, implementationMetrics, cylinderMetrics)
    radius = hypot(centers(:, 1), centers(:, 2));
    row = table(mode, radiusFactor, min(radius), max(radius), ...
        min(abs(kappa) .* radius), max(abs(kappa) .* radius), ...
        thetaMetrics.maxRelative, thetaMetrics.p95Relative, ...
        thetaMetrics.weightedL2Relative, asymptoticMetrics.maxRelative, ...
        asymptoticMetrics.p95Relative, ...
        asymptoticMetrics.weightedL2Relative, ...
        implementationMetrics.maxRelative, ...
        implementationMetrics.p95Relative, ...
        implementationMetrics.weightedL2Relative, ...
        cylinderMetrics.maxRelative, cylinderMetrics.p95Relative, ...
        cylinderMetrics.weightedL2Relative, ...
        'VariableNames', {'mode_m', 'radius_factor', 'minimum_radius_m', ...
        'maximum_radius_m', 'minimum_abs_kappa_r', 'maximum_abs_kappa_r', ...
        'e_theta_max_relative', 'e_theta_p95_relative', ...
        'e_theta_weighted_l2_relative', 'e_asymptotic_max_relative', ...
        'e_asymptotic_p95_relative', ...
        'e_asymptotic_weighted_l2_relative', ...
        'e_implementation_max_relative', ...
        'e_implementation_p95_relative', ...
        'e_implementation_weighted_l2_relative', ...
        'cylinder_coefficient_asymptotic_max_relative', ...
        'cylinder_coefficient_asymptotic_p95_relative', ...
        'cylinder_coefficient_asymptotic_weighted_l2_relative'});
end

function row = legacy_scaling_row(mode, radiusFactor, physicalK, centers, ...
        asymptoticMetrics, cylinderMetrics)
    radius = hypot(centers(:, 1), centers(:, 2));
    row = table(mode, radiusFactor, physicalK, min(radius), max(radius), ...
        min(physicalK .* radius), max(physicalK .* radius), ...
        asymptoticMetrics.maxRelative, asymptoticMetrics.p95Relative, ...
        asymptoticMetrics.weightedL2Relative, ...
        cylinderMetrics.maxRelative, cylinderMetrics.p95Relative, ...
        cylinderMetrics.weightedL2Relative, ...
        'VariableNames', {'mode_m', 'radius_factor', 'physical_k_per_m', ...
        'minimum_radius_m', 'maximum_radius_m', 'minimum_k_r', ...
        'maximum_k_r', 'legacy_wall_e_asymptotic_max_relative', ...
        'legacy_wall_e_asymptotic_p95_relative', ...
        'legacy_wall_e_asymptotic_weighted_l2_relative', ...
        'cylinder_coefficient_asymptotic_max_relative', ...
        'cylinder_coefficient_asymptotic_p95_relative', ...
        'cylinder_coefficient_asymptotic_weighted_l2_relative'});
end
