function result = Run_Phase2_3_Gated_PFull_Focused()
%RUN_PHASE2_3_GATED_PFULL_FOCUSED Run one gated P_FULL assembly and solve.
%
% The runner requires the completed Phase 2.3 pre-assembly audit and an
% independent zero-blocker reviewer gate.  It runs exactly omega=1.5 rad/s,
% verifies every FARFIELD source column against D+gamma_j*S, and does not
% launch a frequency sweep or WAMIT comparison.

    %% Stage 1: Enforce the pre-assembly and reviewer gates

    artifactDirectory = fileparts(mfilename('fullpath'));
    convergenceDirectory = fileparts(artifactDirectory);
    caseWaveDirectory = fileparts(convergenceDirectory);
    repositoryRoot = fileparts(caseWaveDirectory);
    preflightFile = fullfile(artifactDirectory, ...
        'Phase2_3_ABC_Operator_Audit_Result.mat');
    reviewerFile = fullfile(artifactDirectory, ...
        'Phase2_3_Reviewer_Gate.csv');
    assert(isfile(preflightFile), 'CRESTU:Phase23PreflightMissing', ...
        'Phase 2.3 pre-assembly audit result is missing.');
    assert(isfile(reviewerFile), 'CRESTU:Phase23ReviewerMissing', ...
        'Phase 2.3 independent reviewer gate is missing.');
    loaded = load(preflightFile, 'result');
    preflight = loaded.result;
    reviewer = readtable(reviewerFile, 'TextType', 'string');
    requiredPreflight = strcmp(preflight.ABC_NORMAL_LINEAGE, 'PASS') && ...
        strcmp(preflight.ABC_WALL_NTHETA_STATUS, 'RESOLVED') && ...
        strcmp(preflight.ABC_IMPLEMENTATION_ERROR, 'PASS') && ...
        strcmp(preflight.HANKEL_ASYMPTOTIC_ERROR_CLASSIFIED, 'YES');
    assert(requiredPreflight, 'CRESTU:Phase23PreflightBlocked', ...
        'A required Phase 2.3 pre-assembly status is not closed.');
    assert(all(reviewer.blocker_count == 0) && ...
        all(reviewer.status == "PASS"), 'CRESTU:Phase23ReviewerBlocked', ...
        'Independent reviewer blockers are not zero.');
    reviewerBlockers = sum(reviewer.blocker_count);
    add_production_paths(repositoryRoot);

    %% Stage 2: Rebuild the exact focused production domain in memory

    configFile = preflight.configFile;
    omega = preflight.omegaRadPerS; % Wave angular frequency [rad/s]
    cfg = read_config(configFile);
    [cfg, cfg.fs.tuning_report] = tune_sponge_layer(cfg, omega);
    cfg = apply_phase2_2_mesh_controls(cfg);
    [cfg, ~] = resolve_phase2_2_controls(cfg, omega);
    [domain, effective] = build_in_memory_domain(cfg);
    geometry = domain.geometry;
    panelCount = geometry.total_panels;
    bodyCount = domain.stats.total_body_panels;
    freeSurfaceCount = domain.stats.fs_panels;
    bottomCount = domain.stats.seabed_panels;
    farfieldCount = domain.stats.farfield_panels;
    farfieldRows = bodyCount + freeSurfaceCount + bottomCount + ...
        (1:farfieldCount);
    assert(panelCount == bodyCount + freeSurfaceCount + bottomCount + ...
        farfieldCount && all(geometry.panel_type(farfieldRows) == 5), ...
        'CRESTU:Phase23FocusedCounts', ...
        'Focused production component counts or FARFIELD types are invalid.');
    assert(strcmp(effective.wallDerived.topology, ...
        'legacy-structured-equal-count-quads'), ...
        'CRESTU:Phase23FocusedTopology', ...
        'Focused production wall is not the equal-count structured wall.');

    %% Stage 3: Run the production P_FULL assembly once

    fprintf('[INFO] Phase 2.3 gated production assembly | N=%d | Nff=%d\n', ...
        panelCount, farfieldCount);
    [physicalK, ~] = solve_wave_dispersion(omega, domain.cfg.grav, ...
        domain.cfg.water_depth);
    nominalMu = domain.cfg.phase2_2_controls.effective.actualMu0;
    outerBC = get_rankine_outer_absorbing_bc(geometry.centers, ...
        geometry.normals, domain.stats, omega, domain.cfg.grav, ...
        domain.cfg.water_depth, domain.cfg, physicalK, nominalMu);
    [systemMatrix, bodySingleLayerMatrix, assemblyInfo] = ...
        assemble_rankine_matrix(panelCount, geometry.centers, ...
        geometry.normals, geometry.vertices, domain.stats, omega, ...
        domain.cfg.grav, domain.cfg, [1, 1]);

    %% Stage 4: Reconstruct every FARFIELD source column independently

    assert(domain.cfg.isx == 0 && domain.cfg.isy == 0, ...
        'CRESTU:Phase23FullDomainOracle', ...
        'The all-FARFIELD oracle is restricted to the P_FULL no-image case.');
    sourceOrientation = get_rankine_source_orientation(domain.stats, ...
        geometry.normals, geometry.vertices);
    analyticGamma = analytic_production_gamma( ...
        geometry.centers(farfieldRows, :), ...
        geometry.normals(farfieldRows, :), outerBC.kappa, ...
        domain.cfg.water_depth);
    gammaScale = max([abs(analyticGamma), abs(outerBC.gamma), ...
        repmat(realmin, farfieldCount, 1)], [], 2);
    gammaRelativeError = abs(outerBC.gamma - analyticGamma) ./ gammaScale;

    singleLayerBlock = complex(zeros(panelCount, farfieldCount));
    doubleLayerBlock = complex(zeros(panelCount, farfieldCount));
    inverseFourPi = 1 / (4 * pi);
    oracleTimer = tic;
    for localIndex = 1:farfieldCount
        globalIndex = farfieldRows(localIndex);
        panel = reshape(geometry.vertices(globalIndex, :, :), 4, 3);
        normal = geometry.normals(globalIndex, :);
        for targetIndex = 1:panelCount
            [singleLayerIntegral, doubleLayerIntegral] = ...
                rankine_panel_integrals(panel, ...
                geometry.centers(targetIndex, :), normal);
            singleLayerBlock(targetIndex, localIndex) = ...
                singleLayerIntegral * inverseFourPi;
            doubleLayerValue = -sourceOrientation.columnSigns(globalIndex) * ...
                doubleLayerIntegral * inverseFourPi;
            if targetIndex == globalIndex
                doubleLayerValue = doubleLayerValue + 0.5;
            end
            doubleLayerBlock(targetIndex, localIndex) = doubleLayerValue;
        end
        if mod(localIndex, 34) == 0 || localIndex == farfieldCount
            fprintf('[INFO] FARFIELD oracle %d/%d columns\n', ...
                localIndex, farfieldCount);
        end
    end
    oracleElapsedSeconds = toc(oracleTimer);
    oracleBlock = doubleLayerBlock + singleLayerBlock .* analyticGamma.';
    actualBlock = systemMatrix(:, farfieldRows);
    differenceBlock = actualBlock - oracleBlock;
    columnResidual = zeros(farfieldCount, 1);
    singleLayerNorm = zeros(farfieldCount, 1);
    doubleLayerNorm = zeros(farfieldCount, 1);
    actualColumnNorm = zeros(farfieldCount, 1);
    for localIndex = 1:farfieldCount
        singleLayerNorm(localIndex) = norm(singleLayerBlock(:, localIndex));
        doubleLayerNorm(localIndex) = norm(doubleLayerBlock(:, localIndex));
        actualColumnNorm(localIndex) = norm(actualBlock(:, localIndex));
        stableDenominator = doubleLayerNorm(localIndex) + ...
            abs(analyticGamma(localIndex)) * singleLayerNorm(localIndex);
        columnResidual(localIndex) = norm(differenceBlock(:, localIndex)) / ...
            max(stableDenominator, realmin);
    end
    blockDenominator = norm(doubleLayerBlock, 'fro') + ...
        norm(singleLayerBlock .* analyticGamma.', 'fro');
    blockFrobeniusResidual = norm(differenceBlock, 'fro') / ...
        max(blockDenominator, realmin);
    columnP95Residual = percentile(columnResidual, 95);
    maximumColumnResidual = max(columnResidual);
    matrixOraclePass = maximumColumnResidual <= 1e-12 && ...
        blockFrobeniusResidual <= 1e-13 && ...
        max(gammaRelativeError) <= 1e-12;

    localPanelId = (1:farfieldCount).';
    globalPanelId = farfieldRows.';
    columnTable = table(globalPanelId, localPanelId, real(outerBC.gamma), ...
        imag(outerBC.gamma), real(analyticGamma), imag(analyticGamma), ...
        gammaRelativeError, singleLayerNorm, doubleLayerNorm, ...
        actualColumnNorm, columnResidual, ...
        'VariableNames', {'global_panel_id', 'farfield_local_panel_id', ...
        'production_gamma_real_per_m', 'production_gamma_imag_per_m', ...
        'analytic_gamma_real_per_m', 'analytic_gamma_imag_per_m', ...
        'gamma_relative_error', 'single_layer_column_l2_m', ...
        'double_layer_column_l2', 'actual_column_l2', ...
        'stable_column_relative_residual'});
    columnFile = fullfile(artifactDirectory, ...
        'Phase2_3_PFULL_All_Farfield_Column_Oracle.csv');
    writetable(columnTable, columnFile);

    assemblyPass = all(isfinite(systemMatrix(:))) && ...
        all(isfinite(bodySingleLayerMatrix(:))) && ...
        isequal(size(systemMatrix), [panelCount, panelCount]) && ...
        isequal(size(bodySingleLayerMatrix), [panelCount, bodyCount]) && ...
        max(abs(outerBC.tangentialNormal)) < 1e-10 && matrixOraclePass && ...
        assemblyInfo.outer_source_column_audit.enabled && ...
        assemblyInfo.outer_source_column_audit. ...
            reconstructionRelativeResidual <= 1e-14;
    assert(assemblyPass, 'CRESTU:Phase23AssemblyGate', ...
        'P_FULL production assembly or all-FARFIELD oracle did not pass.');

    %% Stage 5: Solve exactly one omega=1.5 focused diffraction case

    bodyRows = 1:bodyCount;
    bodyCenters = geometry.centers(bodyRows, :);
    bodyNormals = geometry.normals(bodyRows, :);
    [incidentPotential, incidentNormalDerivative] = ...
        decompose_incident_wave_symmetry(bodyCenters, bodyNormals, omega, ...
        domain.cfg.grav, domain.cfg.water_depth, ...
        domain.cfg.wave.headings(1), 1, domain.cfg.isx, domain.cfg.isy, [1, 1]);
    rightHandSide = bodySingleLayerMatrix * incidentNormalDerivative;
    [diffractionSolution, ~] = solve_complex_system(systemMatrix, ...
        rightHandSide, []);
    relativeResidual = norm(systemMatrix * diffractionSolution - ...
        rightHandSide, 'fro') / max(norm(rightHandSide, 'fro'), eps);
    conditioning = estimate_rankine_conditioning(systemMatrix);
    algebraicDiagnostics = compute_rankine_algebraic_diagnostics( ...
        systemMatrix, diffractionSolution, rightHandSide, domain.stats, ...
        'diffraction');
    generalizedNormals = compute_generalized_normals(bodyCenters, ...
        bodyNormals, domain.body_list);
    [excitationForce, pressure] = compute_wave_excitation( ...
        incidentPotential, diffractionSolution(bodyRows, :), ...
        generalizedNormals, geometry.areas(bodyRows), omega, domain.cfg.rho);
    focusedPass = all(isfinite(rightHandSide(:))) && ...
        all(isfinite(diffractionSolution(:))) && ...
        all(isfinite(pressure(:))) && all(isfinite(excitationForce(:))) && ...
        isfinite(relativeResidual) && relativeResidual <= 1e-10 && ...
        conditioning.enabled && conditioning.rawEstimateAvailable && ...
        conditioning.scaledEstimateAvailable && ...
        isfinite(conditioning.rawRcondEstimate) && ...
        isfinite(conditioning.scaledRcondEstimate) && ...
        algebraicDiagnostics.enabled && ...
        isfinite(algebraicDiagnostics.relativeResidualFrobeniusNorm);
    assert(focusedPass, 'CRESTU:Phase23FocusedSolve', ...
        'The omega=1.5 focused P_FULL solve did not pass.');

    %% Stage 6: Persist concise results and update the final Phase 2.3 status

    result = struct('schemaVersion', 1, ...
        'testName', 'Phase 2.3 gated P_FULL omega=1.5 focused case', ...
        'omegaRadPerS', omega, 'panelCount', panelCount, ...
        'farfieldPanelCount', farfieldCount, ...
        'productionMaximumAbsNtheta', ...
            max(abs(outerBC.tangentialNormal)), ...
        'gammaMaximumRelativeError', max(gammaRelativeError), ...
        'maximumFarfieldColumnResidual', maximumColumnResidual, ...
        'p95FarfieldColumnResidual', columnP95Residual, ...
        'farfieldBlockFrobeniusResidual', blockFrobeniusResidual, ...
        'oracleElapsedSeconds', oracleElapsedSeconds, ...
        'productionAssemblyElapsedSeconds', assemblyInfo.elapsed_seconds, ...
        'focusedRelativeResidual', relativeResidual, ...
        'conditioning', conditioning, ...
        'algebraicDiagnostics', algebraicDiagnostics, ...
        'excitationForce', excitationForce, ...
        'REVIEWER_BLOCKERS', reviewerBlockers, ...
        'ABC_IMPLEMENTATION_ERROR', 'PASS', ...
        'P_FULL_ASSEMBLY', 'PASS', ...
        'OMEGA_1P5_FOCUSED_CASE', 'PASS', ...
        'FORMAL_FREQUENCY_SWEEP', 'NOT_RUN', ...
        'READY_FOR_FORMAL_PFULL_FREQUENCY_SWEEP', 'YES', ...
        'columnOracleFile', columnFile);
    resultFile = fullfile(artifactDirectory, ...
        'Phase2_3_PFULL_Focused_Result.mat');
    save(resultFile, 'result');

    summaryMetric = ["panel_count"; "farfield_panel_count"; ...
        "max_abs_ntheta"; "gamma_max_relative_error"; ...
        "max_farfield_column_residual"; "p95_farfield_column_residual"; ...
        "farfield_block_frobenius_residual"; ...
        "focused_linear_relative_residual"; "reviewer_blockers"];
    summaryValue = [panelCount; farfieldCount; ...
        max(abs(outerBC.tangentialNormal)); max(gammaRelativeError); ...
        maximumColumnResidual; columnP95Residual; blockFrobeniusResidual; ...
        relativeResidual; reviewerBlockers];
    summaryTable = table(summaryMetric, summaryValue, ...
        'VariableNames', {'metric', 'value'});
    summaryFile = fullfile(artifactDirectory, ...
        'Phase2_3_PFULL_Focused_Summary.csv');
    writetable(summaryTable, summaryFile);

    statusName = ["ABC_NORMAL_LINEAGE"; "ABC_WALL_NTHETA_STATUS"; ...
        "ABC_IMPLEMENTATION_ERROR"; "HANKEL_ASYMPTOTIC_ERROR_CLASSIFIED"; ...
        "P_FULL_ASSEMBLY"; "OMEGA_1P5_FOCUSED_CASE"; ...
        "FORMAL_FREQUENCY_SWEEP"; ...
        "READY_FOR_FORMAL_PFULL_FREQUENCY_SWEEP"; "REVIEWER_BLOCKERS"];
    statusValue = ["PASS"; "RESOLVED"; "PASS"; "YES"; "PASS"; ...
        "PASS"; "NOT_RUN"; "YES"; string(reviewerBlockers)];
    statusTable = table(statusName, statusValue, ...
        'VariableNames', {'status_name', 'status_value'});
    writetable(statusTable, fullfile(artifactDirectory, ...
        'Phase2_3_Audit_Status.csv'));

    fprintf('[RESULT] P_FULL_ASSEMBLY = PASS\n');
    fprintf('[RESULT] ALL_FARFIELD_COLUMN_MAX = %.3e | P95=%.3e | FROB=%.3e\n', ...
        maximumColumnResidual, columnP95Residual, blockFrobeniusResidual);
    fprintf('[RESULT] OMEGA_1P5_FOCUSED_CASE = PASS | residual=%.3e\n', ...
        relativeResidual);
    fprintf('[RESULT] READY_FOR_FORMAL_PFULL_FREQUENCY_SWEEP = YES\n');
end

function add_production_paths(repositoryRoot)
    directories = {fullfile(repositoryRoot, 'Source Code', '1.Input'), ...
        fullfile(repositoryRoot, 'Source Code', '2.Mesh'), ...
        fullfile(repositoryRoot, 'Source Code', '4.Potential'), ...
        fullfile(repositoryRoot, 'Source Code', '5.Force'), ...
        fullfile(repositoryRoot, 'Case_Wave')};
    for index = 1:numel(directories)
        addpath(directories{index}, '-begin');
    end
end

function [domain, effective] = build_in_memory_domain(cfg)
    bodyConfiguration = cfg.bodies(1);
    body = transform_body_mesh(read_bmf(bodyConfiguration.mesh_file), ...
        bodyConfiguration);
    body = reduce_mesh_by_symmetry(body, cfg.isx, cfg.isy, cfg.z_tol);
    body.cg = cfg.mass_props(1).cg;
    body.body_id = bodyConfiguration.id;
    bodyWaterline = extract_waterline(body, cfg.z_tol);
    outerWaterline = bodyWaterline;
    if ~isempty(cfg.outer_reference_mesh_file)
        referenceMesh = transform_body_mesh( ...
            read_bmf(cfg.outer_reference_mesh_file), bodyConfiguration);
        referenceMesh = reduce_mesh_by_symmetry(referenceMesh, ...
            cfg.isx, cfg.isy, cfg.z_tol);
        outerWaterline = extract_waterline(referenceMesh, cfg.z_tol);
    end
    freeSurface = generate_free_surface_bmf('', outerWaterline, cfg, false);
    [bottomCfg, bottomReferenceSurface] = get_phase2_2_bottom_mesh_inputs( ...
        cfg, outerWaterline, freeSurface);
    bottom = generate_seabed_mesh(outerWaterline, bottomCfg, ...
        bottomReferenceSurface);
    outerBoundary = generate_farfield_mesh(outerWaterline, cfg, ...
        cfg.fs.nz_farfield);
    [freeSurface, bottom, outerBoundary, effective] = ...
        apply_rankine_outer_truncation(freeSurface, bottom, outerBoundary, ...
        cfg, cfg.fs.tuning_report.wavelengths(1));
    cfg.outer_truncation.effective = effective;
    stats = struct('total_body_panels', body.n_panels, ...
        'body_vertices', size(unique(reshape(body.vertices, [], 3), ...
            'rows'), 1), ...
        'waterline_panels', waterline_panel_count(bodyWaterline), ...
        'outer_waterline_panels', waterline_panel_count(outerWaterline), ...
        'fs_panels', freeSurface.n_panels, ...
        'seabed_panels', bottom.n_panels, ...
        'farfield_panels', outerBoundary.n_panels);
    stats.total_dofs = stats.total_body_panels + stats.fs_panels + ...
        stats.seabed_panels + stats.farfield_panels;
    domain = struct('cfg', cfg, 'body_list', {{body}}, ...
        'fs', freeSurface, 'seabed', bottom, 'farfield', outerBoundary, ...
        'waterline', {{bodyWaterline}}, ...
        'body_waterlines', {{bodyWaterline}}, ...
        'outer_waterlines', {{outerWaterline}}, 'stats', stats);
    domain.geometry = merge_domain_geometry(domain);
end

function count = waterline_panel_count(waterline)
    if waterline.is_closed
        count = waterline.n_pts;
    else
        count = max(0, waterline.n_pts - 1);
    end
end

function gamma = analytic_production_gamma(centers, normals, kappa, waterDepth)
    radius = hypot(centers(:, 1), centers(:, 2));
    radialNormal = (normals(:, 1) .* centers(:, 1) + ...
        normals(:, 2) .* centers(:, 2)) ./ radius;
    verticalNormal = normals(:, 3);
    gamma = (-radialNormal) .* (1i * kappa + 1 ./ (2 .* radius)) + ...
        verticalNormal .* kappa .* tanh(kappa .* ...
        (centers(:, 3) + waterDepth));
end

function value = percentile(values, percentage)
    values = sort(values(isfinite(values)));
    assert(~isempty(values), 'CRESTU:Phase23FocusedPercentile', ...
        'Cannot calculate percentile of an empty finite vector.');
    if numel(values) == 1
        value = values(1);
        return
    end
    position = 1 + (numel(values) - 1) * percentage / 100;
    lowerIndex = floor(position);
    upperIndex = ceil(position);
    if lowerIndex == upperIndex
        value = values(lowerIndex);
    else
        value = values(lowerIndex) + (position - lowerIndex) * ...
            (values(upperIndex) - values(lowerIndex));
    end
end
