function summary = Run_Phase3_1B_Frequency_Anomaly_Audit(forceRecompute)
% RUN_PHASE3_1B_FREQUENCY_ANOMALY_AUDIT Isolate 0.6/1.4 response anomalies.
%
% This diagnostic runner never edits WAMIT data and never applies curve
% smoothing.  Remeshed cases use the ordinary production call.  The
% fixed-geometry arm uses the explicit, default-off diagnostic option of
% run_frequency_domain_case and freezes the complete omega=0.60 geometry.

    arguments
        forceRecompute (1, 1) logical = false
    end

    %% Stage 1: Resolve frozen inputs and bind every checkpoint to provenance

    paths = initialize_paths();
    add_production_paths(paths);
    baselineCfg = read_config(paths.phase2_3BaselineConfig);
    formalCfg = read_config(paths.formalFrequencyConfig);
    localFrequencies = [0.54, 0.56, 0.58, 0.59, 0.60, ...
        0.61, 0.62, 0.64, 0.66]; % [rad/s]
    lineageFrequencies = [0.58, 0.59, 0.60, 0.61, 0.62]; % [rad/s]
    fixedFrequencies = [0.56, 0.58, 0.59, 0.60, 0.61, 0.62, 0.64]; % [rad/s]
    raoFrequencies = 1.30:0.02:1.50; % [rad/s]
    fingerprint = audit_fingerprint(paths, localFrequencies, ...
        fixedFrequencies, raoFrequencies, baselineCfg);
    writetable(struct2table(fingerprint), fullfile(paths.artifactDirectory, ...
        'Phase3_1B_Run_Fingerprint.csv'));

    %% Stage 2: Run isolated frequency-local production cases near 0.6

    localCheckpoint = fullfile(paths.artifactDirectory, ...
        'Phase3_1B_Local_Checkpoint.mat');
    [localRecords, localPayloads] = initialize_checkpoint_records( ...
        localFrequencies, localCheckpoint, fingerprint.combinedSHA256, ...
        forceRecompute);
    for frequencyIndex = 1:numel(localFrequencies)
        if localRecords(frequencyIndex).status == "PASS"
            fprintf('[INFO] Reuse fingerprint-matched local checkpoint | omega=%.6g rad/s\n', ...
                localFrequencies(frequencyIndex));
            continue
        end
        omega = localFrequencies(frequencyIndex); % [rad/s]
        fprintf('[INFO] Phase 3.1B remeshed local %d/%d | omega=%.6g rad/s\n', ...
            frequencyIndex, numel(localFrequencies), omega);
        [localRecords(frequencyIndex), localPayloads{frequencyIndex}] = ...
            run_isolated_case(omega, true, baselineCfg, formalCfg, paths);
        checkpointFingerprint = fingerprint.combinedSHA256; %#ok<NASGU>
        save(localCheckpoint, 'localRecords', 'localPayloads', ...
            'localFrequencies', 'checkpointFingerprint', '-v7.3');
    end
    assert(all([localRecords.status] == "PASS"), ...
        'CRESTU:Phase31BLocalSolve', ...
        'One or more 0.6-neighborhood production cases failed.');
    localTable = struct2table(localRecords);
    writetable(localTable, fullfile(paths.artifactDirectory, ...
        'Phase3_1B_Local_Dense_Sweep.csv'));
    write_lineage_artifacts(localTable, localPayloads, lineageFrequencies, ...
        paths.artifactDirectory);
    write_discretization_ledger(localTable, paths.artifactDirectory);

    %% Stage 3: Freeze the complete omega=0.60 production geometry

    fixedCheckpoint = fullfile(paths.artifactDirectory, ...
        'Phase3_1B_Fixed_Geometry_Checkpoint.mat');
    fixedRecords = repmat(empty_record(), numel(fixedFrequencies), 1);
    fixedPayloads = cell(numel(fixedFrequencies), 1);
    fixedLoaded = false;
    if ~forceRecompute && isfile(fixedCheckpoint)
        loaded = load(fixedCheckpoint, 'fixedRecords', 'fixedPayloads', ...
            'fixedFrequencies', 'checkpointFingerprint');
        fixedLoaded = checkpoint_matches(loaded, ...
            fingerprint.combinedSHA256, fixedFrequencies, 'fixedRecords');
        if fixedLoaded
            fixedRecords = loaded.fixedRecords;
            fixedPayloads = loaded.fixedPayloads;
            fprintf('[INFO] Reuse fingerprint-matched fixed-geometry checkpoint.\n');
        end
    end
    if ~fixedLoaded
        [fixedRecords, fixedPayloads] = run_fixed_geometry_case( ...
            fixedFrequencies, 0.60, baselineCfg, formalCfg, paths);
        checkpointFingerprint = fingerprint.combinedSHA256; %#ok<NASGU>
        save(fixedCheckpoint, 'fixedRecords', 'fixedPayloads', ...
            'fixedFrequencies', 'checkpointFingerprint', '-v7.3');
    end
    assert(all([fixedRecords.status] == "PASS"), ...
        'CRESTU:Phase31BFixedSolve', ...
        'One or more fixed-geometry cases failed.');
    fixedTable = struct2table(fixedRecords);
    comparisonTable = build_fixed_geometry_comparison( ...
        localTable, fixedTable, fixedFrequencies);
    writetable(comparisonTable, fullfile(paths.artifactDirectory, ...
        'Phase3_1B_Fixed_Geometry_Comparison.csv'));

    %% Stage 4: Independently audit the dense heave response around 1.4

    raoCheckpoint = fullfile(paths.artifactDirectory, ...
        'Phase3_1B_RAO3_Checkpoint.mat');
    [raoRecords, raoPayloads] = initialize_checkpoint_records( ...
        raoFrequencies, raoCheckpoint, fingerprint.combinedSHA256, ...
        forceRecompute);
    for frequencyIndex = 1:numel(raoFrequencies)
        if raoRecords(frequencyIndex).status == "PASS"
            fprintf('[INFO] Reuse fingerprint-matched RAO checkpoint | omega=%.6g rad/s\n', ...
                raoFrequencies(frequencyIndex));
            continue
        end
        omega = raoFrequencies(frequencyIndex); % [rad/s]
        fprintf('[INFO] Phase 3.1B RAO dense sweep %d/%d | omega=%.6g rad/s\n', ...
            frequencyIndex, numel(raoFrequencies), omega);
        [raoRecords(frequencyIndex), raoPayloads{frequencyIndex}] = ...
            run_isolated_case(omega, false, baselineCfg, formalCfg, paths);
        checkpointFingerprint = fingerprint.combinedSHA256; %#ok<NASGU>
        save(raoCheckpoint, 'raoRecords', 'raoPayloads', ...
            'raoFrequencies', 'checkpointFingerprint', '-v7.3');
    end
    assert(all([raoRecords.status] == "PASS"), ...
        'CRESTU:Phase31BRAOSolve', ...
        'One or more 1.4-neighborhood production cases failed.');
    raoTable = build_rao_denominator_table(struct2table(raoRecords));
    writetable(raoTable, fullfile(paths.artifactDirectory, ...
        'Phase3_1B_RAO3_Denominator_Audit.csv'));

    %% Stage 5: Read-only WAMIT spot checks and machine-readable decisions

    referenceTable = build_reference_comparison(localTable, raoTable, paths);
    writetable(referenceTable, fullfile(paths.artifactDirectory, ...
        'Phase3_1B_Targeted_Reference_Comparison.csv'));
    decisions = classify_results(localTable, comparisonTable, raoTable);
    writetable(struct2table(decisions), fullfile(paths.artifactDirectory, ...
        'Phase3_1B_Provisional_Decisions.csv'));
    sourceAfter = production_source_snapshot(paths);
    writetable(sourceAfter, fullfile(paths.artifactDirectory, ...
        'Phase3_1B_Production_Source_SHA256_After_Diagnostics.csv'));

    summary = struct('schemaVersion', 1, 'fingerprint', fingerprint, ...
        'localTable', localTable, 'fixedTable', fixedTable, ...
        'comparisonTable', comparisonTable, 'raoTable', raoTable, ...
        'referenceTable', referenceTable, 'decisions', decisions, ...
        'sourceAfterDiagnostics', sourceAfter);
    save(fullfile(paths.artifactDirectory, ...
        'Phase3_1B_Diagnostic_Result.mat'), 'summary', '-v7.3');
    fprintf('[RESULT] OMEGA_0P6_FIRST_ANOMALOUS_LAYER = %s\n', ...
        decisions.omega0p6FirstAnomalousLayer);
    fprintf('[RESULT] FREQUENCY_LOCAL_DISCRETIZATION_CAUSAL = %s\n', ...
        decisions.frequencyLocalDiscretizationCausal);
    fprintf('[RESULT] OMEGA_1P4_RAO3_CLASSIFICATION = %s\n', ...
        decisions.omega1p4Rao3Classification);
end

function paths = initialize_paths()
    artifactDirectory = fileparts(mfilename('fullpath'));
    convergenceDirectory = fileparts(artifactDirectory);
    caseWaveDirectory = fileparts(convergenceDirectory);
    repositoryRoot = fileparts(caseWaveDirectory);
    versionDirectory = fileparts(fileparts(repositoryRoot));
    paths = struct('artifactDirectory', artifactDirectory, ...
        'convergenceDirectory', convergenceDirectory, ...
        'caseWaveDirectory', caseWaveDirectory, ...
        'repositoryRoot', repositoryRoot, ...
        'sourceDirectory', fullfile(repositoryRoot, 'Source Code'), ...
        'formalFrequencyConfig', fullfile(convergenceDirectory, ...
            'Mesh_Fine', 'Case1_Fine.cfg'), ...
        'phase2_3BaselineConfig', fullfile(convergenceDirectory, ...
            'Phase2_2_Artifacts', 'Tests', 'Frustum_Instrumentation', ...
            'Cases', 'Frustum_Top_Only.cfg'), ...
        'wamitIrr3Directory', fullfile(versionDirectory, 'WAMIT', ...
            'FullSphereIRR3'));
    required = {paths.formalFrequencyConfig, paths.phase2_3BaselineConfig, ...
        fullfile(paths.wamitIrr3Directory, 'hemisphere.1'), ...
        fullfile(paths.wamitIrr3Directory, 'hemisphere.2'), ...
        fullfile(paths.wamitIrr3Directory, 'hemisphere.4')};
    assert(all(cellfun(@isfile, required)), ...
        'CRESTU:Phase31BRequiredInput', ...
        'A frozen config or read-only WAMIT reference is missing.');
end

function add_production_paths(paths)
    sourceDirectory = paths.sourceDirectory;
    addpath(fullfile(sourceDirectory, '0.Tools Code'), ...
        fullfile(sourceDirectory, '1.Input'), ...
        fullfile(sourceDirectory, '2.Mesh'), ...
        fullfile(sourceDirectory, '3.HessSmith'), ...
        fullfile(sourceDirectory, '4.Potential'), ...
        fullfile(sourceDirectory, '5.Force'), ...
        fullfile(sourceDirectory, '6.MeanDriftLoads'), ...
        paths.caseWaveDirectory, ...
        fullfile(paths.caseWaveDirectory, 'Common_Scripts'), '-begin');
end

function fingerprint = audit_fingerprint(paths, localFrequencies, ...
        fixedFrequencies, raoFrequencies, baselineCfg)
    codeVersion = get_rankine_code_version();
    runnerFile = [mfilename('fullpath'), '.m'];
    runnerSHA256 = sha256_file_hash(runnerFile);
    baselineConfigSHA256 = sha256_file_hash(paths.phase2_3BaselineConfig);
    formalConfigSHA256 = sha256_file_hash(paths.formalFrequencyConfig);
    geometryControls = struct( ...
        'fsRadialCounts', [baselineCfg.fs.nr_near, baselineCfg.fs.nr_sponge], ...
        'outerVerticalPanelCount', baselineCfg.fs.nz_farfield, ...
        'outerTruncationTopQ', baselineCfg.outer_truncation.topRadiusPerWavelength, ...
        'outerTruncationBottomQ', baselineCfg.outer_truncation.bottomRadiusPerWavelength, ...
        'isx', baselineCfg.isx, 'isy', baselineCfg.isy, ...
        'waterDepthM', baselineCfg.water_depth);
    payload = struct('schemaVersion', 1, ...
        'runnerVersion', 'Phase3.1B-root-cause-audit-v1', ...
        'runnerSHA256', runnerSHA256, ...
        'productionDependencySHA256', codeVersion.fingerprint, ...
        'baselineConfigSHA256', baselineConfigSHA256, ...
        'formalConfigSHA256', formalConfigSHA256, ...
        'geometryControls', geometryControls, ...
        'localFrequenciesRadPerS', localFrequencies, ...
        'fixedFrequenciesRadPerS', fixedFrequencies, ...
        'raoFrequenciesRadPerS', raoFrequencies);
    fingerprint = struct('schemaVersion', 1, ...
        'runnerVersion', "Phase3.1B-root-cause-audit-v1", ...
        'runnerSHA256', string(runnerSHA256), ...
        'productionDependencySHA256', string(codeVersion.fingerprint), ...
        'baselineConfigSHA256', string(baselineConfigSHA256), ...
        'formalConfigSHA256', string(formalConfigSHA256), ...
        'geometryControlSHA256', string(sha256_hash(jsonencode(geometryControls))), ...
        'frequencyListSHA256', string(sha256_hash(jsonencode(struct( ...
            'local', localFrequencies, 'fixed', fixedFrequencies, ...
            'rao', raoFrequencies)))), ...
        'combinedSHA256', string(sha256_hash(jsonencode(payload))));
end

function [records, payloads] = initialize_checkpoint_records(frequencies, ...
        checkpoint, fingerprint, forceRecompute)
    records = repmat(empty_record(), numel(frequencies), 1);
    payloads = cell(numel(frequencies), 1);
    for index = 1:numel(frequencies)
        records(index).omega_rad_s = frequencies(index);
    end
    if forceRecompute || ~isfile(checkpoint)
        return
    end
    loaded = load(checkpoint, 'localRecords', 'localPayloads', ...
        'raoRecords', 'raoPayloads', 'localFrequencies', 'raoFrequencies', ...
        'checkpointFingerprint');
    if isfield(loaded, 'localRecords')
        candidateRecords = loaded.localRecords;
        candidatePayloads = loaded.localPayloads;
    elseif isfield(loaded, 'raoRecords')
        candidateRecords = loaded.raoRecords;
        candidatePayloads = loaded.raoPayloads;
    else
        fprintf('[WARN] CHECKPOINT_REUSE = FORBIDDEN | missing record payload: %s\n', ...
            checkpoint);
        return
    end
    frequencyMatch = numel(candidateRecords) == numel(frequencies) && ...
        max(abs(reshape([candidateRecords.omega_rad_s], 1, []) - ...
        frequencies)) <= 64 * eps(max(frequencies));
    fingerprintMatch = isfield(loaded, 'checkpointFingerprint') && ...
        string(loaded.checkpointFingerprint) == string(fingerprint);
    if frequencyMatch && fingerprintMatch
        records = candidateRecords;
        payloads = candidatePayloads;
    else
        fprintf(['[WARN] CHECKPOINT_REUSE = FORBIDDEN | source/config/', ...
            'frequency fingerprint mismatch: %s\n'], checkpoint);
    end
end

function matched = checkpoint_matches(loaded, fingerprint, frequencies, ...
        recordField)
    matched = isfield(loaded, recordField) && ...
        isfield(loaded, 'checkpointFingerprint') && ...
        string(loaded.checkpointFingerprint) == string(fingerprint);
    if ~matched
        fprintf('[WARN] CHECKPOINT_REUSE = FORBIDDEN | fingerprint mismatch.\n');
        return
    end
    records = loaded.(recordField);
    matched = numel(records) == numel(frequencies) && ...
        max(abs(reshape([records.omega_rad_s], 1, []) - frequencies)) <= ...
        64 * eps(max(frequencies));
    if ~matched
        fprintf('[WARN] CHECKPOINT_REUSE = FORBIDDEN | frequency mismatch.\n');
    end
end

function [record, payload] = run_isolated_case(omega, persistFullPhi, ...
        baselineCfg, formalCfg, paths)
    runtimeDirectory = tempname;
    mkdir(runtimeDirectory);
    cleanup = onCleanup(@() remove_runtime_directory(runtimeDirectory));
    caseName = sprintf('Phase3_1B_w%04d', round(1000 * omega));
    configFile = fullfile(runtimeDirectory, [caseName, '.cfg']);
    write_runtime_config(configFile, caseName, omega, baselineCfg, ...
        formalCfg, persistFullPhi);
    results = run_frequency_domain_case(configFile, ...
        'skipPhysicalDiagnostics', true);
    [record, payload] = extract_frequency_record(results, 1, ...
        persistFullPhi, "REMESHED", paths);
    clear cleanup
end

function [records, payloads] = run_fixed_geometry_case(frequencies, anchor, ...
        baselineCfg, formalCfg, paths)
    runtimeDirectory = tempname;
    mkdir(runtimeDirectory);
    cleanup = onCleanup(@() remove_runtime_directory(runtimeDirectory));
    caseName = 'Phase3_1B_FixedGeometry_w0600';
    configFile = fullfile(runtimeDirectory, [caseName, '.cfg']);
    write_runtime_config(configFile, caseName, anchor, baselineCfg, ...
        formalCfg, true);
    results = run_frequency_domain_case(configFile, ...
        'physicsFrequenciesRadPerS', frequencies, ...
        'fixedGeometryAnchorRadPerS', anchor, ...
        'skipPhysicalDiagnostics', true);
    records = repmat(empty_record(), numel(frequencies), 1);
    payloads = cell(numel(frequencies), 1);
    for index = 1:numel(frequencies)
        [records(index), payloads{index}] = extract_frequency_record( ...
            results, index, true, "FIXED_GEOMETRY", paths);
    end
    geometryHashes = string({records.combined_geometry_hash});
    assert(numel(unique(geometryHashes)) == 1 && ...
        string(results.audit.diagnosticState.fixedGeometrySHA256) == ...
        geometryHashes(1), 'CRESTU:Phase31BFixedGeometryHash', ...
        'Fixed-geometry diagnostic did not retain one exact geometry hash.');
    clear cleanup
end

function [record, payload] = extract_frequency_record(results, index, ...
        persistFullPhi, geometryMode, paths)
    record = empty_record();
    omega = results.omegas(index); % [rad/s]
    loaded = load(results.potential_cache_file, 'pot_cache');
    entry = loaded.pot_cache.entries(index);
    audit = results.audit.frequencyEntries(index);
    diagnostics = results.diagnostics(index);
    conditioning = cellfun(@(item) item.conditioning, ...
        entry.solver_diagnostics, 'UniformOutput', false);
    truncation = entry.assembly_info{1}.outer_truncation;
    outer = entry.assembly_info{1}.outer_absorbing_boundary;
    phiBody = entry.phi_rad_body(:, 3); % Heave radiation [m^2/s]
    bodyMesh = load_transformed_body_mesh(results.config);
    areas = reshape(bodyMesh.areas, [], 1); % [m^2]
    assert(numel(areas) == numel(phiBody), ...
        'CRESTU:Phase31BBodyShape', ...
        'Body areas and heave radiation potential have different lengths.');
    nj3 = results.generalized_normals(:, 3);
    panelGeneralizedForce = 1i * omega * results.config.rho .* ...
        phiBody .* nj3 .* areas; % [N] for unit heave displacement
    forceFromPanels = sum(panelGeneralizedForce);
    forceFromProduction = diagnostics.radiation_force(3, 3);
    forceMismatch = abs(forceFromPanels - forceFromProduction) / ...
        max([abs(forceFromPanels), abs(forceFromProduction), eps]);
    assert(forceMismatch <= 1.0e-12, 'CRESTU:Phase31BForceLineage', ...
        'Reconstructed raw F33 differs from the production diagnostic.');

    [minimumArea, maximumArea, minimumAspect, maximumAspect] = ...
        active_geometry_quality(results.config);
    maximumPhiIndex = find(abs(phiBody) == max(abs(phiBody)), 1);
    probeIndices = unique([1, round(numel(phiBody) / 2), numel(phiBody)], ...
        'stable');
    if numel(probeIndices) < 3
        probeIndices(end + 1:3) = probeIndices(end);
    end
    record.omega_rad_s = omega;
    record.geometry_mode = geometryMode;
    record.physical_k_per_m = outer.physicalKPerM;
    record.wavelength_m = 2 * pi / outer.physicalKPerM;
    record.kappa_real_per_m = outer.kappaRealPerM;
    record.kappa_imag_per_m = outer.kappaImagPerM;
    record.phi3_norm = norm(phiBody);
    record.phi3_area_weighted_norm = sqrt(sum(abs(phiBody) .^ 2 .* areas));
    record.phi3_max_abs = abs(phiBody(maximumPhiIndex));
    record.phi3_phase_at_max_deg = angle(phiBody(maximumPhiIndex)) * 180 / pi;
    record.phi3_probe1_real = real(phiBody(probeIndices(1)));
    record.phi3_probe1_imag = imag(phiBody(probeIndices(1)));
    record.phi3_probe2_real = real(phiBody(probeIndices(2)));
    record.phi3_probe2_imag = imag(phiBody(probeIndices(2)));
    record.phi3_probe3_real = real(phiBody(probeIndices(3)));
    record.phi3_probe3_imag = imag(phiBody(probeIndices(3)));
    record.F33_rad_real_N = real(forceFromProduction);
    record.F33_rad_imag_N = imag(forceFromProduction);
    record.F33_rad_abs_N = abs(forceFromProduction);
    record.F33_rad_angle_deg = angle(forceFromProduction) * 180 / pi;
    record.F33_panel_reconstruction_relative_error = forceMismatch;
    record.A33_kg = results.added_mass(3, 3, index);
    record.B33_kg_s = results.damping(3, 3, index);
    record.F3_real_N_per_m = real(results.excitation(3, 1, index));
    record.F3_imag_N_per_m = imag(results.excitation(3, 1, index));
    response = results.rao.complex(3, 1, index);
    denominator = results.rao.dynamic_matrix(3, 3, index);
    record.RAO3_real_m_per_m = real(response);
    record.RAO3_imag_m_per_m = imag(response);
    record.RAO3_abs_m_per_m = abs(response);
    record.RAO3_phase_deg = angle(response) * 180 / pi;
    record.D3_real_N_per_m = real(denominator);
    record.D3_imag_N_per_m = imag(denominator);
    record.D3_abs_N_per_m = abs(denominator);
    record.raw_rcond = min(cellfun(@(item) item.rawRcondEstimate, conditioning));
    record.scaled_rcond = min(cellfun(@(item) item.scaledRcondEstimate, conditioning));
    record.relative_residual = max(cellfun(@(item) ...
        item.radiationRelativeResidual, entry.solver_diagnostics));
    record.body_panel_count = audit.bodyPanelCount;
    record.free_surface_panel_count = audit.freeSurfacePanelCount;
    record.bottom_panel_count = audit.bottomPanelCount;
    record.farfield_panel_count = audit.outerBoundaryPanelCount;
    record.total_panel_count = audit.bemUnknownCount;
    record.outer_radius_top_m = truncation.effectiveTopRadiusM;
    record.outer_radius_bottom_m = truncation.effectiveBottomRadiusM;
    record.legacy_theta_count = truncation.legacyThetaNodeCount;
    record.top_theta_ideal_count = truncation.topThetaCountSelection.idealCount;
    record.top_theta_candidate_count = truncation.topThetaCountSelection.candidateCount;
    record.top_theta_count = truncation.topOuterThetaNodeCount;
    record.bottom_theta_ideal_count = truncation.bottomThetaCountSelection.idealCount;
    record.bottom_theta_candidate_count = truncation.bottomThetaCountSelection.candidateCount;
    record.bottom_theta_count = truncation.bottomOuterThetaNodeCount;
    record.common_wall_theta_count = truncation.commonOuterThetaNodeCount;
    record.top_radial_ideal_count = max(0, ...
        (truncation.effectiveTopRadiusM - truncation.legacyRadiusM) / ...
        truncation.topSurfaceDerived.radialTargetM);
    record.top_radial_layer_count = truncation.topSurfaceDerived.radialLayerCount;
    record.bottom_radial_ideal_count = max(0, ...
        (truncation.effectiveBottomRadiusM - truncation.legacyRadiusM) / ...
        truncation.bottomSurfaceDerived.radialTargetM);
    record.bottom_radial_layer_count = ...
        truncation.bottomSurfaceDerived.radialLayerCount;
    record.wall_vertical_ideal_count = ...
        truncation.wallDerived.countSelection.idealCount;
    record.wall_vertical_candidate_count = ...
        truncation.wallDerived.countSelection.candidateCount;
    record.wall_vertical_layer_count = ...
        truncation.wallDerived.verticalLayerCount;
    record.top_theta_spacing_m = ...
        truncation.topThetaCountSelection.chosenSpacingM;
    record.bottom_theta_spacing_m = ...
        truncation.bottomThetaCountSelection.chosenSpacingM;
    record.top_radial_spacing_m = ...
        truncation.topSurfaceDerived.maximumRadialStep;
    record.bottom_radial_spacing_m = ...
        truncation.bottomSurfaceDerived.maximumRadialStep;
    record.wall_slant_spacing_m = ...
        truncation.wallDerived.maximumSlantStep;
    record.minimum_panel_area_m2 = minimumArea;
    record.maximum_panel_area_m2 = maximumArea;
    record.minimum_panel_aspect_ratio = minimumAspect;
    record.maximum_panel_aspect_ratio = maximumAspect;
    record.body_geometry_hash = string(entry.mesh_audit.body.hash);
    record.free_surface_geometry_hash = string(entry.mesh_audit.freeSurface.hash);
    record.bottom_geometry_hash = string(entry.mesh_audit.bottom.hash);
    record.farfield_geometry_hash = string(entry.mesh_audit.outerBoundary.hash);
    record.combined_geometry_hash = string(entry.mesh_audit.geometry.hash);
    record.status = "PASS";

    fullPhi = complex(zeros(0, 1));
    if persistFullPhi
        rawFile = results.config.files.raw_diagnostics;
        assert(isfile(rawFile), 'CRESTU:Phase31BRawPhiMissing', ...
            'PERSIST_FULL_PHI did not create its bound raw diagnostic MAT.');
        raw = load(rawFile, 'rawDiagnosticSolutions');
        radiationRecords = raw.rawDiagnosticSolutions(cellfun(@(item) ...
            strcmp(item.problemName, 'radiation') && ...
            any(item.columnIndices == 3) && ...
            abs(item.omegaRadPerS - omega) <= 64 * eps(max(1, omega)), ...
            raw.rawDiagnosticSolutions));
        assert(numel(radiationRecords) == 1, ...
            'CRESTU:Phase31BRawPhiShape', ...
            'Expected one full heave-radiation solution record.');
        item = radiationRecords{1};
        localColumn = find(item.columnIndices == 3, 1);
        fullPhi = item.solutionPhi(:, localColumn);
        assert(string(item.geometrySHA256) == record.combined_geometry_hash, ...
            'CRESTU:Phase31BRawPhiHash', ...
            'Full potential geometry hash differs from the active solve.');
    end
    payload = struct('omega_rad_s', omega, ...
        'geometry_mode', geometryMode, ...
        'harmonic_convention', "exp(+i*omega*t)", ...
        'prescribed_heave_displacement_amplitude_m', 1.0, ...
        'prescribed_heave_velocity', "i*omega*n3", ...
        'pressure_formula', "p=-i*rho*omega*phi3", ...
        'generalized_force_formula', "F33=i*omega*rho*sum(n3*phi3*dS)", ...
        'A33_formula', "A33=real(F33)/omega^2", ...
        'B33_formula', "B33=-imag(F33)/omega", ...
        'body_phi3', phiBody, 'full_phi3', fullPhi, ...
        'panel_generalized_force', panelGeneralizedForce, ...
        'probe_indices', probeIndices, ...
        'combined_geometry_hash', record.combined_geometry_hash, ...
        'production_dependency_fingerprint', ...
            string(results.audit.codeVersion.fingerprint), ...
        'repository_root', string(paths.repositoryRoot));
end

function bodyMesh = load_transformed_body_mesh(cfg)
    bodyMesh = read_bmf(cfg.bodies(1).mesh_file);
    bodyMesh = transform_body_mesh(bodyMesh, cfg.bodies(1));
    bodyMesh = reduce_mesh_by_symmetry(bodyMesh, cfg.isx, cfg.isy, cfg.z_tol);
end

function [minimumArea, maximumArea, minimumAspect, maximumAspect] = ...
        active_geometry_quality(cfg)
    meshes = {load_transformed_body_mesh(cfg), read_bmf(cfg.files.fs), ...
        read_bmf(cfg.files.seabed), read_bmf(cfg.files.farfield)};
    areas = cellfun(@(mesh) reshape(mesh.areas, [], 1), meshes, ...
        'UniformOutput', false);
    allAreas = vertcat(areas{:});
    aspects = cellfun(@panel_aspect_ratio, meshes, 'UniformOutput', false);
    allAspects = vertcat(aspects{:});
    minimumArea = min(allAreas);
    maximumArea = max(allAreas);
    minimumAspect = min(allAspects);
    maximumAspect = max(allAspects);
end

function ratios = panel_aspect_ratio(mesh)
    vertices = reshape(mesh.vertices, mesh.n_panels, 4, 3);
    ratios = ones(mesh.n_panels, 1);
    for panelIndex = 1:mesh.n_panels
        panel = reshape(vertices(panelIndex, :, :), 4, 3);
        edges = sqrt(sum((panel([2, 3, 4, 1], :) - panel) .^ 2, 2));
        edges = edges(edges > 1.0e-13);
        ratios(panelIndex) = max(edges) / min(edges);
    end
end

function write_lineage_artifacts(localTable, payloads, frequencies, ...
        artifactDirectory)
    rows = ismembertol(localTable.omega_rad_s, frequencies, ...
        64 * eps(max(frequencies)), 'DataScale', 1);
    lineageTable = localTable(rows, {'omega_rad_s', 'phi3_norm', ...
        'phi3_area_weighted_norm', 'phi3_max_abs', ...
        'phi3_phase_at_max_deg', 'phi3_probe1_real', 'phi3_probe1_imag', ...
        'phi3_probe2_real', 'phi3_probe2_imag', 'phi3_probe3_real', ...
        'phi3_probe3_imag', 'F33_rad_real_N', 'F33_rad_imag_N', ...
        'F33_rad_abs_N', 'F33_rad_angle_deg', ...
        'F33_panel_reconstruction_relative_error', 'A33_kg', ...
        'B33_kg_s', 'D3_real_N_per_m', 'D3_imag_N_per_m', ...
        'RAO3_real_m_per_m', 'RAO3_imag_m_per_m'});
    writetable(lineageTable, fullfile(artifactDirectory, ...
        'Phase3_1B_Radiation_Quantity_Lineage.csv'));
    rawForceTable = localTable(:, {'omega_rad_s', 'F33_rad_real_N', ...
        'F33_rad_imag_N', 'F33_rad_abs_N', 'F33_rad_angle_deg', ...
        'F33_panel_reconstruction_relative_error', 'A33_kg', 'B33_kg_s'});
    writetable(rawForceTable, fullfile(artifactDirectory, ...
        'Phase3_1B_Raw_F33_Complex_Force.csv'));
    selectedPayloads = payloads(rows);
    save(fullfile(artifactDirectory, ...
        'Phase3_1B_Radiation_Phi3_Lineage.mat'), 'selectedPayloads', ...
        '-v7.3');
end

function write_discretization_ledger(localTable, artifactDirectory)
    names = {'omega_rad_s', 'physical_k_per_m', 'wavelength_m', ...
        'A33_kg', 'B33_kg_s', 'F33_rad_real_N', 'F33_rad_imag_N', ...
        'raw_rcond', 'scaled_rcond', 'relative_residual', ...
        'body_panel_count', 'free_surface_panel_count', ...
        'bottom_panel_count', 'farfield_panel_count', 'total_panel_count', ...
        'outer_radius_top_m', 'outer_radius_bottom_m', ...
        'legacy_theta_count', 'top_theta_ideal_count', ...
        'top_theta_candidate_count', 'top_theta_count', ...
        'bottom_theta_ideal_count', 'bottom_theta_candidate_count', ...
        'bottom_theta_count', 'common_wall_theta_count', ...
        'top_radial_ideal_count', 'top_radial_layer_count', ...
        'bottom_radial_ideal_count', 'bottom_radial_layer_count', ...
        'wall_vertical_ideal_count', 'wall_vertical_candidate_count', ...
        'wall_vertical_layer_count', 'top_theta_spacing_m', ...
        'bottom_theta_spacing_m', 'top_radial_spacing_m', ...
        'bottom_radial_spacing_m', 'wall_slant_spacing_m', ...
        'minimum_panel_area_m2', 'maximum_panel_area_m2', ...
        'minimum_panel_aspect_ratio', 'maximum_panel_aspect_ratio', ...
        'body_geometry_hash', 'free_surface_geometry_hash', ...
        'bottom_geometry_hash', 'farfield_geometry_hash', ...
        'combined_geometry_hash'};
    writetable(localTable(:, names), fullfile(artifactDirectory, ...
        'Phase3_1B_Frequency_Local_Discretization_Ledger.csv'));
end

function tableOut = build_fixed_geometry_comparison(localTable, ...
        fixedTable, frequencies)
    tableOut = table();
    for index = 1:numel(frequencies)
        remeshedRow = find(abs(localTable.omega_rad_s - frequencies(index)) <= ...
            64 * eps(max(1, frequencies(index))), 1);
        fixedRow = find(abs(fixedTable.omega_rad_s - frequencies(index)) <= ...
            64 * eps(max(1, frequencies(index))), 1);
        assert(~isempty(remeshedRow) && ~isempty(fixedRow), ...
            'CRESTU:Phase31BComparisonGrid', ...
            'Remeshed/fixed comparison frequency is missing.');
        row = table(frequencies(index), ...
            localTable.F33_rad_real_N(remeshedRow), ...
            localTable.F33_rad_imag_N(remeshedRow), ...
            fixedTable.F33_rad_real_N(fixedRow), ...
            fixedTable.F33_rad_imag_N(fixedRow), ...
            localTable.A33_kg(remeshedRow), fixedTable.A33_kg(fixedRow), ...
            localTable.B33_kg_s(remeshedRow), fixedTable.B33_kg_s(fixedRow), ...
            localTable.raw_rcond(remeshedRow), fixedTable.raw_rcond(fixedRow), ...
            localTable.relative_residual(remeshedRow), ...
            fixedTable.relative_residual(fixedRow), ...
            string(localTable.combined_geometry_hash(remeshedRow)), ...
            string(fixedTable.combined_geometry_hash(fixedRow)), ...
            'VariableNames', {'omega_rad_s', 'F33_remeshed_real_N', ...
            'F33_remeshed_imag_N', 'F33_fixed_real_N', ...
            'F33_fixed_imag_N', 'A33_remeshed_kg', 'A33_fixed_kg', ...
            'B33_remeshed_kg_s', 'B33_fixed_kg_s', ...
            'raw_rcond_remeshed', 'raw_rcond_fixed', ...
            'relative_residual_remeshed', 'relative_residual_fixed', ...
            'remeshed_geometry_hash', 'fixed_geometry_hash'});
        tableOut = [tableOut; row]; %#ok<AGROW>
    end
end

function tableOut = build_rao_denominator_table(tableIn)
    response = complex(tableIn.RAO3_real_m_per_m, ...
        tableIn.RAO3_imag_m_per_m);
    excitation = complex(tableIn.F3_real_N_per_m, ...
        tableIn.F3_imag_N_per_m);
    unwrappedPhaseDeg = unwrap(angle(response)) * 180 / pi;
    amplitudeScale = max(abs(response));
    amplitudeFloor = max(1.0e-6 * amplitudeScale, eps);
    normalizedComplexStep = [NaN; abs(diff(response)) ./ max( ...
        [abs(response(1:end - 1)), abs(response(2:end)), ...
        repmat(amplitudeFloor, numel(response) - 1, 1)], [], 2)];
    amplitudeRelativeStep = [NaN; abs(diff(abs(response))) ./ max( ...
        [abs(response(1:end - 1)), abs(response(2:end)), ...
        repmat(amplitudeFloor, numel(response) - 1, 1)], [], 2)];
    phaseProtected = abs(response) < amplitudeFloor | ...
        abs(excitation) < max(1.0e-6 * max(abs(excitation)), eps);
    tableOut = tableIn(:, {'omega_rad_s', 'F3_real_N_per_m', ...
        'F3_imag_N_per_m', 'A33_kg', 'B33_kg_s', ...
        'RAO3_real_m_per_m', 'RAO3_imag_m_per_m', ...
        'RAO3_abs_m_per_m', 'RAO3_phase_deg', 'D3_real_N_per_m', ...
        'D3_imag_N_per_m', 'D3_abs_N_per_m', 'raw_rcond', ...
        'scaled_rcond', 'relative_residual'});
    tableOut.RAO3_unwrapped_phase_deg = unwrappedPhaseDeg;
    tableOut.RAO3_normalized_complex_step = normalizedComplexStep;
    tableOut.RAO3_amplitude_relative_step = amplitudeRelativeStep;
    tableOut.phase_blocking_protected = phaseProtected;
end

function tableOut = build_reference_comparison(localTable, raoTable, paths)
    radiation = read_wamit_first_order(fullfile(paths.wamitIrr3Directory, ...
        'hemisphere.1'), 1025);
    excitation = read_wamit_excitation(fullfile(paths.wamitIrr3Directory, ...
        'hemisphere.2'), 1025, 9.80665, 1, 1);
    response = read_wamit_rao(fullfile(paths.wamitIrr3Directory, ...
        'hemisphere.4'));
    radiationOmega = reshape(radiation.omegas, [], 1);
    excitationOmega = reshape(excitation.omegas, [], 1);
    responseOmega = reshape(response.omegas, [], 1);
    heading0 = find(abs(excitation.headings) < 1.0e-12, 1);
    responseHeading0 = find(abs(response.headings) < 1.0e-12, 1);
    targetRadiation = [0.58; 0.60; 0.62];
    targetRao = [1.36; 1.40; 1.44];
    rows = cell(numel(targetRadiation) + numel(targetRao), 1);
    for index = 1:numel(targetRadiation)
        omega = targetRadiation(index);
        localIndex = find(abs(localTable.omega_rad_s - omega) <= ...
            64 * eps(max(1, omega)), 1);
        wamitA33 = interp1(radiationOmega, ...
            squeeze(radiation.added_mass(3, 3, :)), omega, 'pchip');
        wamitB33 = interp1(radiationOmega, ...
            squeeze(radiation.damping(3, 3, :)), omega, 'pchip');
        rows{index} = table(omega, "RADIATION", ...
            localTable.A33_kg(localIndex), localTable.B33_kg_s(localIndex), ...
            NaN, NaN, wamitA33, wamitB33, NaN, NaN, ...
            reference_method(radiationOmega, omega), ...
            'VariableNames', {'omega_rad_s', 'comparison_type', ...
            'CRESTU_A33_kg', 'CRESTU_B33_kg_s', ...
            'CRESTU_F3_abs_N_per_m', 'CRESTU_RAO3_abs_m_per_m', ...
            'WAMIT_A33_kg', 'WAMIT_B33_kg_s', ...
            'WAMIT_F3_abs_N_per_m', 'WAMIT_RAO3_abs_m_per_m', ...
            'reference_method'});
    end
    for index = 1:numel(targetRao)
        omega = targetRao(index);
        localIndex = find(abs(raoTable.omega_rad_s - omega) <= ...
            64 * eps(max(1, omega)), 1);
        wamitF3 = interp1(excitationOmega, squeeze(abs( ...
            excitation.force(3, heading0, :))), omega, 'pchip');
        wamitRao3 = interp1(responseOmega, squeeze( ...
            response.amplitude(3, responseHeading0, :)), omega, 'pchip');
        rows{numel(targetRadiation) + index} = table(omega, "RAO", ...
            NaN, NaN, hypot(raoTable.F3_real_N_per_m(localIndex), ...
            raoTable.F3_imag_N_per_m(localIndex)), ...
            raoTable.RAO3_abs_m_per_m(localIndex), NaN, NaN, ...
            wamitF3, wamitRao3, reference_method(responseOmega, omega), ...
            'VariableNames', rows{1}.Properties.VariableNames);
    end
    tableOut = vertcat(rows{:});
end

function method = reference_method(referenceOmega, targetOmega)
    if any(abs(referenceOmega - targetOmega) <= 64 * eps(max(1, targetOmega)))
        method = "EXACT_REFERENCE_FREQUENCY";
    else
        method = "PCHIP_DIAGNOSTIC_INTERPOLATION_NO_TUNING";
    end
end

function decisions = classify_results(localTable, comparisonTable, raoTable)
    remeshedPhiDeviation = isolated_deviation(localTable.omega_rad_s, ...
        complex(localTable.phi3_probe2_real, localTable.phi3_probe2_imag), 0.60);
    remeshedForceDeviation = isolated_deviation(localTable.omega_rad_s, ...
        complex(localTable.F33_rad_real_N, localTable.F33_rad_imag_N), 0.60);
    remeshedADeviation = isolated_deviation(localTable.omega_rad_s, ...
        localTable.A33_kg, 0.60);
    remeshedBDeviation = isolated_deviation(localTable.omega_rad_s, ...
        localTable.B33_kg_s, 0.60);
    fixedForce = complex(comparisonTable.F33_fixed_real_N, ...
        comparisonTable.F33_fixed_imag_N);
    fixedForceDeviation = isolated_deviation(comparisonTable.omega_rad_s, ...
        fixedForce, 0.60);
    fixedADeviation = isolated_deviation(comparisonTable.omega_rad_s, ...
        comparisonTable.A33_fixed_kg, 0.60);
    fixedBDeviation = isolated_deviation(comparisonTable.omega_rad_s, ...
        comparisonTable.B33_fixed_kg_s, 0.60);
    remeshAnomaly = max([remeshedForceDeviation, remeshedADeviation, ...
        remeshedBDeviation]) > 0.50;
    fixedAnomaly = max([fixedForceDeviation, fixedADeviation, ...
        fixedBDeviation]) > 0.50;
    meshHashes = string(localTable.combined_geometry_hash);
    meshDiscontinuity = numel(unique(meshHashes)) > 1;
    if remeshedPhiDeviation > 0.50
        firstLayer = "POTENTIAL";
    elseif remeshedForceDeviation > 0.50
        firstLayer = "RAW_FORCE";
    elseif max(remeshedADeviation, remeshedBDeviation) > 0.50
        firstLayer = "AB_EXTRACTION";
    else
        firstLayer = "UNRESOLVED";
    end
    if remeshAnomaly && ~fixedAnomaly
        causal = "YES";
        firstLayer = "DISCRETIZATION";
    elseif ~remeshAnomaly
        causal = "NO";
    else
        causal = "UNRESOLVED";
    end

    [minimumDenominator, minimumIndex] = min(raoTable.D3_abs_N_per_m);
    maximumResponse = max(raoTable.RAO3_abs_m_per_m);
    responseAtMinD = raoTable.RAO3_abs_m_per_m(minimumIndex);
    denseFinite = all(isfinite([raoTable.RAO3_real_m_per_m; ...
        raoTable.RAO3_imag_m_per_m; raoTable.D3_abs_N_per_m]));
    maximumComplexStep = max(raoTable.RAO3_normalized_complex_step, ...
        [], 'omitnan');
    if denseFinite && responseAtMinD >= 0.8 * maximumResponse && ...
            minimumDenominator < median(raoTable.D3_abs_N_per_m) && ...
            maximumComplexStep < 1.0
        raoClassification = "PHYSICAL_RESONANCE";
    elseif denseFinite && any(raoTable.phase_blocking_protected)
        raoClassification = "NEAR_ZERO_PHASE_ARTIFACT";
    elseif ~denseFinite || maximumComplexStep >= 1.0
        raoClassification = "NUMERICAL_DISCONTINUITY";
    else
        raoClassification = "UNRESOLVED";
    end
    decisions = struct( ...
        'omega0p6FirstAnomalousLayer', firstLayer, ...
        'remeshedPhiDeviation', remeshedPhiDeviation, ...
        'remeshedRawForceDeviation', remeshedForceDeviation, ...
        'remeshedA33Deviation', remeshedADeviation, ...
        'remeshedB33Deviation', remeshedBDeviation, ...
        'fixedRawForceDeviation', fixedForceDeviation, ...
        'fixedA33Deviation', fixedADeviation, ...
        'fixedB33Deviation', fixedBDeviation, ...
        'anomalyPresentWithRemesh', yes_no(remeshAnomaly), ...
        'anomalyPresentWithFixedGeometry', yes_no(fixedAnomaly), ...
        'frequencyLocalMeshDiscontinuity', yes_no(meshDiscontinuity), ...
        'frequencyLocalDiscretizationCausal', causal, ...
        'omega1p4Rao3Classification', raoClassification, ...
        'minimumD3AbsNPerM', minimumDenominator, ...
        'omegaAtMinimumD3RadPerS', raoTable.omega_rad_s(minimumIndex), ...
        'maximumDenseRaoNormalizedComplexStep', maximumComplexStep);
end

function deviation = isolated_deviation(omega, values, target)
    targetIndex = find(abs(omega - target) <= 64 * eps(max(1, target)), 1);
    assert(~isempty(targetIndex) && targetIndex > 1 && ...
        targetIndex < numel(omega), 'CRESTU:Phase31BTargetInterior', ...
        'The isolated-deviation target must be an interior frequency.');
    weight = (omega(targetIndex) - omega(targetIndex - 1)) / ...
        (omega(targetIndex + 1) - omega(targetIndex - 1));
    predicted = values(targetIndex - 1) + weight * ...
        (values(targetIndex + 1) - values(targetIndex - 1));
    scale = max(abs(values));
    floorValue = max(1.0e-6 * scale, eps);
    deviation = abs(values(targetIndex) - predicted) / max( ...
        [abs(values(targetIndex)), abs(predicted), floorValue]);
end

function write_runtime_config(filename, caseName, omega, baselineCfg, ...
        formalCfg, persistFullPhi)
    fileId = fopen(filename, 'w');
    assert(fileId >= 0, 'CRESTU:Phase31BConfigOpen', ...
        'Cannot create runtime config: %s', filename);
    cleanup = onCleanup(@() fclose(fileId));
    body = baselineCfg.bodies(1);
    mass = baselineCfg.mass_props(1);
    inertia = mass.inertia;
    inertiaTokens = [inertia(1, 1), inertia(2, 2), inertia(3, 3), ...
        -inertia(1, 2), -inertia(1, 3), -inertia(2, 3)];
    fprintf(fileId, 'PARA1: Project Case Name\n%s\n\n', caseName);
    fprintf(fileId, 'PARA2: IPOTEN IFORCE IRAD IDIFF IDRIFT\n1 1 1 1 0\n\n');
    fprintf(fileId, 'PARA3: FREQUENCY AND HEADING\n1 1 %.17g %.17g\n', ...
        omega, omega);
    fprintf(fileId, '1\n0\n\n');
    fprintf(fileId, 'PARA4: ENVIRONMENT\n%.17g %.17g %.17g\n\n', ...
        baselineCfg.water_depth, baselineCfg.grav, baselineCfg.rho);
    fprintf(fileId, 'PARA5: BODY\n1\n%d %s %.17g %.17g %.17g %.17g\n\n', ...
        body.id, body.mesh_file, body.pos, body.yaw);
    fprintf(fileId, 'PARA6: MASS PROPERTIES\n%.17g %.17g %.17g %.17g\n', ...
        mass.mass, mass.cg);
    fprintf(fileId, '%.17g %.17g %.17g %.17g %.17g %.17g\n\n', ...
        inertiaTokens);
    fprintf(fileId, 'PARA7: MODES\n');
    fprintf(fileId, '%d ', baselineCfg.calc_modes);
    fprintf(fileId, '\n\nPARA8: FULL DOMAIN\n%d %d\n\n', ...
        baselineCfg.isx, baselineCfg.isy);
    fprintf(fileId, ['PARA9: DOMAIN\n%.17g %d %d %.17g %.17g ', ...
        '%.17g %d\n\n'], baselineCfg.z_tol, baselineCfg.fs.nr_near, ...
        baselineCfg.fs.nr_sponge, baselineCfg.fs.r_inner, ...
        baselineCfg.fs.r_outer, baselineCfg.fs.sponge_ratio, ...
        baselineCfg.fs.nz_farfield);
    fprintf(fileId, 'PARA10: SPONGE\n%.17g\n\n', baselineCfg.fs.mu0);
    fprintf(fileId, ['PARA11: FIXED OUTER-DOMAIN WATERLINE\n', ...
        'OUTER_WATERLINE_MESH %s\n\n'], body.mesh_file);
    fprintf(fileId, ['PARA12: PHASE2.2 OUTER TRUNCATION AUDIT\n', ...
        'OUTER_TRUNCATION_Q %.17g %.17g\n\n'], ...
        baselineCfg.outer_truncation.topRadiusPerWavelength, ...
        baselineCfg.outer_truncation.bottomRadiusPerWavelength);
    fprintf(fileId, ['PARA13: PHASE2.2 AUDIT CONTROLS\n', ...
        'RAW_DIAGNOSTICS 1\nPERSIST_FULL_PHI %d\n'], persistFullPhi);
    assert(formalCfg.wave.headings(1) == 0, ...
        'CRESTU:Phase31BHeadingAuthority', ...
        'The formal validation config no longer starts at zero heading.');
    clear cleanup
end

function tableOut = production_source_snapshot(paths)
    version = get_rankine_code_version();
    relativeFile = string(version.relativeFiles(:));
    sha256 = string(version.fileHashes(:));
    tableOut = table(relativeFile, sha256);
end

function record = empty_record()
    record = struct('omega_rad_s', NaN, 'geometry_mode', "", ...
        'physical_k_per_m', NaN, 'wavelength_m', NaN, ...
        'kappa_real_per_m', NaN, 'kappa_imag_per_m', NaN, ...
        'phi3_norm', NaN, 'phi3_area_weighted_norm', NaN, ...
        'phi3_max_abs', NaN, 'phi3_phase_at_max_deg', NaN, ...
        'phi3_probe1_real', NaN, 'phi3_probe1_imag', NaN, ...
        'phi3_probe2_real', NaN, 'phi3_probe2_imag', NaN, ...
        'phi3_probe3_real', NaN, 'phi3_probe3_imag', NaN, ...
        'F33_rad_real_N', NaN, 'F33_rad_imag_N', NaN, ...
        'F33_rad_abs_N', NaN, 'F33_rad_angle_deg', NaN, ...
        'F33_panel_reconstruction_relative_error', NaN, ...
        'A33_kg', NaN, 'B33_kg_s', NaN, ...
        'F3_real_N_per_m', NaN, 'F3_imag_N_per_m', NaN, ...
        'RAO3_real_m_per_m', NaN, 'RAO3_imag_m_per_m', NaN, ...
        'RAO3_abs_m_per_m', NaN, 'RAO3_phase_deg', NaN, ...
        'D3_real_N_per_m', NaN, 'D3_imag_N_per_m', NaN, ...
        'D3_abs_N_per_m', NaN, 'raw_rcond', NaN, ...
        'scaled_rcond', NaN, 'relative_residual', NaN, ...
        'body_panel_count', NaN, 'free_surface_panel_count', NaN, ...
        'bottom_panel_count', NaN, 'farfield_panel_count', NaN, ...
        'total_panel_count', NaN, 'outer_radius_top_m', NaN, ...
        'outer_radius_bottom_m', NaN, 'legacy_theta_count', NaN, ...
        'top_theta_ideal_count', NaN, 'top_theta_candidate_count', NaN, ...
        'top_theta_count', NaN, 'bottom_theta_ideal_count', NaN, ...
        'bottom_theta_candidate_count', NaN, 'bottom_theta_count', NaN, ...
        'common_wall_theta_count', NaN, 'top_radial_ideal_count', NaN, ...
        'top_radial_layer_count', NaN, 'bottom_radial_ideal_count', NaN, ...
        'bottom_radial_layer_count', NaN, 'wall_vertical_ideal_count', NaN, ...
        'wall_vertical_candidate_count', NaN, ...
        'wall_vertical_layer_count', NaN, 'top_theta_spacing_m', NaN, ...
        'bottom_theta_spacing_m', NaN, 'top_radial_spacing_m', NaN, ...
        'bottom_radial_spacing_m', NaN, 'wall_slant_spacing_m', NaN, ...
        'minimum_panel_area_m2', NaN, 'maximum_panel_area_m2', NaN, ...
        'minimum_panel_aspect_ratio', NaN, ...
        'maximum_panel_aspect_ratio', NaN, 'body_geometry_hash', "", ...
        'free_surface_geometry_hash', "", 'bottom_geometry_hash', "", ...
        'farfield_geometry_hash', "", 'combined_geometry_hash', "", ...
        'status', "PENDING");
end

function remove_runtime_directory(folder)
    if isfolder(folder) && startsWith(lower(folder), lower(tempdir))
        try
            rmdir(folder, 's');
        catch exception
            warning('CRESTU:Phase31BRuntimeCleanup', ...
                'Could not remove runtime directory %s: %s', ...
                folder, exception.message);
        end
    end
end

function text = yes_no(value)
    if value
        text = "YES";
    else
        text = "NO";
    end
end
