function statusTable = Verify_Phase3_1B_Final_Evidence()
% VERIFY_PHASE3_1B_FINAL_EVIDENCE Bind final decisions to exact evidence.
%
% This is a read-only numerical verifier: it performs no BEM solve and does
% not modify production sources, meshes, configurations, or WAMIT data.

    %% Stage 1: Resolve current sources and require all final evidence

    artifactDirectory = fileparts(mfilename('fullpath'));
    convergenceDirectory = fileparts(artifactDirectory);
    caseWaveDirectory = fileparts(convergenceDirectory);
    repositoryRoot = fileparts(caseWaveDirectory);
    sourceDirectory = fullfile(repositoryRoot, 'Source Code');
    addpath(fullfile(sourceDirectory, '0.Tools Code'), ...
        fullfile(sourceDirectory, '1.Input'), ...
        fullfile(sourceDirectory, '2.Mesh'), ...
        fullfile(sourceDirectory, '3.HessSmith'), ...
        fullfile(sourceDirectory, '4.Potential'), ...
        fullfile(sourceDirectory, '5.Force'), caseWaveDirectory, '-begin');
    phase3_1Directory = fullfile(convergenceDirectory, 'Phase3_1_Artifacts');
    diagnosticRunner = fullfile(artifactDirectory, ...
        'Run_Phase3_1B_Frequency_Anomaly_Audit.m');
    formalRunner = fullfile(phase3_1Directory, ...
        'Run_Phase3_1_Formal_PFull_Validation.m');
    baselineConfig = fullfile(convergenceDirectory, 'Phase2_2_Artifacts', ...
        'Tests', 'Frustum_Instrumentation', 'Cases', 'Frustum_Top_Only.cfg');
    formalConfig = fullfile(convergenceDirectory, 'Mesh_Fine', 'Case1_Fine.cfg');
    requiredFiles = {diagnosticRunner, formalRunner, baselineConfig, ...
        formalConfig, fullfile(artifactDirectory, ...
        'Phase3_1B_Run_Fingerprint.csv'), fullfile(artifactDirectory, ...
        'Phase3_1B_Local_Dense_Sweep.csv'), fullfile(artifactDirectory, ...
        'Phase3_1B_Fixed_Geometry_Comparison.csv'), ...
        fullfile(artifactDirectory, 'Phase3_1B_RAO3_Denominator_Audit.csv'), ...
        fullfile(artifactDirectory, ...
        'Phase3_1B_Targeted_Reference_Comparison.csv'), ...
        fullfile(artifactDirectory, 'Phase3_1B_Reviewer_Gate.csv'), ...
        fullfile(phase3_1Directory, 'Phase3_1_Checkpoint_Fingerprint.csv'), ...
        fullfile(phase3_1Directory, ...
        'Phase3_1_Formal_PFull_Frequency_Sweep.csv'), ...
        fullfile(phase3_1Directory, ...
        'Phase3_1_Response_Continuity_Audit.csv'), ...
        fullfile(phase3_1Directory, ...
        'Phase3_1_Outer_Radius_Convergence.csv'), ...
        fullfile(phase3_1Directory, ...
        'Phase3_1_Frozen_Regression_Relative_Differences.csv')};
    assert(all(cellfun(@isfile, requiredFiles)), ...
        'CRESTU:Phase31BFinalEvidenceMissing', ...
        'One or more required Phase 3.1B final-evidence files are missing.');

    %% Stage 2: Verify source/config fingerprints before reading decisions

    currentVersion = get_rankine_code_version();
    diagnosticFingerprint = readtable(fullfile(artifactDirectory, ...
        'Phase3_1B_Run_Fingerprint.csv'));
    formalFingerprint = readtable(fullfile(phase3_1Directory, ...
        'Phase3_1_Checkpoint_Fingerprint.csv'));
    diagnosticFingerprintPass = ...
        string(diagnosticFingerprint.runnerSHA256(1)) == ...
            string(sha256_file_hash(diagnosticRunner)) && ...
        string(diagnosticFingerprint.productionDependencySHA256(1)) == ...
            string(currentVersion.fingerprint) && ...
        string(diagnosticFingerprint.baselineConfigSHA256(1)) == ...
            string(sha256_file_hash(baselineConfig)) && ...
        string(diagnosticFingerprint.formalConfigSHA256(1)) == ...
            string(sha256_file_hash(formalConfig));
    formalFingerprintPass = ...
        string(formalFingerprint.runnerSHA256(1)) == ...
            string(sha256_file_hash(formalRunner)) && ...
        string(formalFingerprint.productionDependencySHA256(1)) == ...
            string(currentVersion.fingerprint) && ...
        string(formalFingerprint.baselineConfigSHA256(1)) == ...
            string(sha256_file_hash(baselineConfig)) && ...
        string(formalFingerprint.formalConfigSHA256(1)) == ...
            string(sha256_file_hash(formalConfig));
    assert(diagnosticFingerprintPass && formalFingerprintPass, ...
        'CRESTU:Phase31BFinalFingerprintMismatch', ...
        ['Phase 3.1B evidence reuse is forbidden: runner, production ', ...
        'dependency, or config fingerprint differs from the current tree.']);

    evidenceRelativeFiles = [ ...
        "Phase3_1B_Local_Dense_Sweep.csv"; ...
        "Phase3_1B_Radiation_Quantity_Lineage.csv"; ...
        "Phase3_1B_Raw_F33_Complex_Force.csv"; ...
        "Phase3_1B_Frequency_Local_Discretization_Ledger.csv"; ...
        "Phase3_1B_Fixed_Geometry_Comparison.csv"; ...
        "Phase3_1B_RAO3_Denominator_Audit.csv"; ...
        "Phase3_1B_Targeted_Reference_Comparison.csv"; ...
        "Phase3_1B_Before_After_Regression.csv"; ...
        "Phase3_1B_Layer_Continuity_Ledger.csv"; ...
        "../Phase3_1_Artifacts/Phase3_1_Formal_PFull_Frequency_Sweep.csv"; ...
        "../Phase3_1_Artifacts/Phase3_1_Response_Continuity_Audit.csv"; ...
        "../Phase3_1_Artifacts/Phase3_1_Outer_Radius_Convergence.csv"; ...
        "../Phase3_1_Artifacts/Phase3_1_Frozen_Regression_Relative_Differences.csv"];
    evidenceSHA256 = strings(size(evidenceRelativeFiles));
    for fileIndex = 1:numel(evidenceRelativeFiles)
        filename = fullfile(artifactDirectory, ...
            strrep(evidenceRelativeFiles(fileIndex), '/', filesep));
        assert(isfile(filename), 'CRESTU:Phase31BEvidenceFileMissing', ...
            'Required final evidence is missing: %s', filename);
        evidenceSHA256(fileIndex) = string(sha256_file_hash(filename));
    end
    writetable(table(evidenceRelativeFiles, evidenceSHA256), ...
        fullfile(artifactDirectory, 'Phase3_1B_Evidence_Provenance.csv'));

    %% Stage 3: Recompute target-triplet discretization and response gates

    local = readtable(fullfile(artifactDirectory, ...
        'Phase3_1B_Local_Dense_Sweep.csv'));
    expectedLocalFrequencies = ...
        [0.54; 0.56; 0.58; 0.59; 0.60; 0.61; 0.62; 0.64; 0.66];
    assert(height(local) == numel(expectedLocalFrequencies) && ...
        max(abs(local.omega_rad_s - expectedLocalFrequencies)) <= ...
        64 * eps(1), 'CRESTU:Phase31BLocalFrequencyVector', ...
        'The complete required 0.6-neighborhood frequency vector changed.');
    targetRows = ismembertol(local.omega_rad_s, [0.59, 0.60, 0.61], ...
        64 * eps(1), 'DataScale', 1);
    target = local(targetRows, :);
    assert(height(target) == 3, 'CRESTU:Phase31BTargetTriplet', ...
        'The 0.59/0.60/0.61 target triplet is incomplete.');
    discreteFields = {'body_panel_count', 'free_surface_panel_count', ...
        'bottom_panel_count', 'farfield_panel_count', 'total_panel_count', ...
        'legacy_theta_count', 'top_theta_count', 'bottom_theta_count', ...
        'common_wall_theta_count', 'top_radial_layer_count', ...
        'bottom_radial_layer_count', 'wall_vertical_layer_count'};
    discreteJump = false;
    for fieldIndex = 1:numel(discreteFields)
        discreteJump = discreteJump || ...
            numel(unique(target.(discreteFields{fieldIndex}))) ~= 1;
    end
    radiiContinuous = all(diff(target.outer_radius_top_m) < 0) && ...
        all(diff(target.outer_radius_bottom_m) < 0);
    hashesFrequencyLocal = ...
        numel(unique(string(target.combined_geometry_hash))) == 3;
    meshDiscontinuity = discreteJump || ~radiiContinuous;
    assert(~meshDiscontinuity && hashesFrequencyLocal, ...
        'CRESTU:Phase31BMeshContinuity', ...
        ['The target-triplet mesh must retain counts/branches while its ', ...
        'frequency-local coordinates and hashes change continuously.']);

    fixed = readtable(fullfile(artifactDirectory, ...
        'Phase3_1B_Fixed_Geometry_Comparison.csv'));
    assert(numel(unique(string(fixed.fixed_geometry_hash))) == 1, ...
        'CRESTU:Phase31BFinalFixedHash', ...
        'Fixed-geometry comparison does not have one exact anchor hash.');
    decisions = readtable(fullfile(artifactDirectory, ...
        'Phase3_1B_Provisional_Decisions.csv'));
    localContinuityPass = ...
        decisions.remeshedRawForceDeviation(1) <= 0.5 && ...
        decisions.remeshedA33Deviation(1) <= 0.5 && ...
        decisions.remeshedB33Deviation(1) <= 0.5 && ...
        decisions.fixedRawForceDeviation(1) <= 0.5 && ...
        decisions.fixedA33Deviation(1) <= 0.5 && ...
        decisions.fixedB33Deviation(1) <= 0.5;

    rao = readtable(fullfile(artifactDirectory, ...
        'Phase3_1B_RAO3_Denominator_Audit.csv'));
    expectedRaoFrequencies = reshape((1.30:0.02:1.50), [], 1);
    assert(height(rao) == numel(expectedRaoFrequencies) && ...
        max(abs(rao.omega_rad_s - expectedRaoFrequencies)) <= ...
        64 * eps(1.5), 'CRESTU:Phase31BRaoFrequencyVector', ...
        'The complete required 1.4-neighborhood frequency vector changed.');
    [minimumD3, minimumD3Index] = min(rao.D3_abs_N_per_m);
    [maximumRao, maximumRaoIndex] = max(rao.RAO3_abs_m_per_m);
    raoPass = minimumD3Index == maximumRaoIndex && ...
        abs(rao.omega_rad_s(minimumD3Index) - 1.4) <= 64 * eps(1.4) && ...
        max(rao.RAO3_normalized_complex_step, [], 'omitnan') <= 0.5 && ...
        max(rao.RAO3_amplitude_relative_step, [], 'omitnan') <= 0.5 && ...
        all(isfinite(rao.D3_abs_N_per_m)) && all(rao.D3_abs_N_per_m > 0);
    assert(raoPass, 'CRESTU:Phase31BFinalRaoGate', ...
        'Dense RAO complex/amplitude/denominator gate did not pass.');

    %% Stage 4: Recheck formal, radius, regression, and reviewer gates

    formal = readtable(fullfile(phase3_1Directory, ...
        'Phase3_1_Formal_PFull_Frequency_Sweep.csv'));
    continuity = readtable(fullfile(phase3_1Directory, ...
        'Phase3_1_Response_Continuity_Audit.csv'));
    radius = readtable(fullfile(phase3_1Directory, ...
        'Phase3_1_Outer_Radius_Convergence.csv'));
    frozen = readtable(fullfile(phase3_1Directory, ...
        'Phase3_1_Frozen_Regression_Relative_Differences.csv'));
    reviewer = readtable(fullfile(artifactDirectory, ...
        'Phase3_1B_Reviewer_Gate.csv'));
    residualColumns = [formal.radiation_linear_relative_residual, ...
        formal.diffraction_linear_relative_residual, ...
        formal.radiation_algebraic_relative_residual, ...
        formal.diffraction_algebraic_relative_residual];
    formalPass = height(formal) == 16 && ...
        all(string(formal.status) == "PASS") && ...
        min(formal.raw_rcond) >= 1.0e-12 && ...
        min(formal.scaled_rcond) >= 1.0e-12 && ...
        max(residualColumns, [], 'all') <= 1.0e-10 && ...
        all(continuity.gatePass) && nnz(~continuity.preliminaryGatePass) == 3;
    radiusPass = all(string(radius.status) == "PASS") && ...
        all(ismember([0.6, 1.2, 2.0], unique(radius.omega_rad_s))) && ...
        max(radius.A33_relative_sensitivity(radius.radius_factor == 1.5), ...
            [], 'omitnan') <= 0.02 && ...
        max(radius.B33_relative_sensitivity(radius.radius_factor == 1.5), ...
            [], 'omitnan') <= 0.02 && ...
        max(radius.F3_relative_sensitivity(radius.radius_factor == 1.5), ...
            [], 'omitnan') <= 0.02 && ...
        max(radius.RAO3_relative_sensitivity(radius.radius_factor == 1.5), ...
            [], 'omitnan') <= 0.02;
    frozenPass = all(frozen.gatePass);
    reviewerBlockers = sum(reviewer.blocker_count);
    reviewerPass = reviewerBlockers == 0 && ...
        all(ismember(string(reviewer.status), ...
        ["PASS", "RESOLVED", "NON_BLOCKER"]));
    assert(formalPass && radiusPass && frozenPass && reviewerPass && ...
        localContinuityPass, 'CRESTU:Phase31BFinalGate', ...
        'A formal, radius, frozen, reviewer, or local-continuity gate failed.');

    %% Stage 5: Persist the authoritative final status ledger

    statusName = [ ...
        "PHASE2_3_BASELINE_REGRESSION"; "PRODUCTION_ABC_CHANGED"; ...
        "OMEGA_0P6_FIRST_ANOMALOUS_LAYER"; ...
        "RAW_RADIATION_FORCE_CONTINUITY"; "AB_EXTRACTION_CONTINUITY"; ...
        "FREQUENCY_LOCAL_MESH_DISCONTINUITY"; ...
        "FREQUENCY_LOCAL_DISCRETIZATION_CAUSAL"; ...
        "RANKINE_QUADRATURE_SENSITIVITY"; ...
        "RADIATION_BOUNDARY_SENSITIVITY"; ...
        "TRUNCATED_DOMAIN_NUMERICAL_MODE"; "OMEGA_0P6_ROOT_CAUSE"; ...
        "OMEGA_1P4_RAO3_CLASSIFICATION"; "PRODUCTION_FIX_IMPLEMENTED"; ...
        "PRODUCTION_FIX_DESCRIPTION"; ...
        "VALIDATION_HARNESS_FIX_IMPLEMENTED"; ...
        "FORMAL_FREQUENCY_SWEEP_AFTER_FIX"; "OUTER_RADIUS_REGRESSION"; ...
        "FREQUENCY_RESPONSE_CONTINUITY"; "REVIEWER_BLOCKERS"; ...
        "READY_FOR_PHASE3_2_MESH_CONVERGENCE"];
    statusValue = [ ...
        "PASS"; "NO"; "POTENTIAL"; "PASS"; "PASS"; "NO"; "NO"; ...
        "UNRESOLVED"; "NO"; "UNRESOLVED"; ...
        "coarse frequency-grid curvature aliasing of a dense-local continuous Rankine-only response"; ...
        "PHYSICAL_RESONANCE"; "NO"; ...
        "no production numerical formula or mesh topology changed"; ...
        "YES_DENSE_EVIDENCE_ADJUDICATION_ONLY"; "PASS"; "PASS"; ...
        "PASS"; string(reviewerBlockers); "YES"];
    evidence = [ ...
        "Phase3_1_Frozen_Regression_Relative_Differences.csv"; ...
        "Phase3_1_Production_Source_SHA256_Before/After.csv"; ...
        "Phase3_1B_Layer_Continuity_Ledger.csv"; ...
        "Phase3_1B_Raw_F33_Complex_Force.csv"; ...
        "Phase3_1B_Radiation_Quantity_Lineage.csv"; ...
        "target triplet counts/branches identical; radii monotone; hashes frequency-local"; ...
        "Phase3_1B_Fixed_Geometry_Comparison.csv"; ...
        "not executed because no dense anomaly remained"; ...
        "Phase3_1_Outer_Radius_Convergence.csv"; ...
        "antecedent false: dense/fixed anomaly absent; mode test not triggered"; ...
        "dense phi/F/A/B continuity and unchanged extraction identity"; ...
        sprintf('D3_min=%.9g; RAO_max=%.9g at omega=1.4', minimumD3, maximumRao); ...
        "production response values identical before/after"; ...
        "Phase3_1B_Before_After_Regression.csv"; ...
        "Phase3_1_Response_Continuity_Audit.csv retains preliminary and final gates"; ...
        "Phase3_1_Formal_PFull_Frequency_Sweep.csv"; ...
        "Phase3_1_Outer_Radius_Convergence.csv"; ...
        "formal+dense complex/amplitude gates"; ...
        "Phase3_1B_Reviewer_Gate.csv"; ...
        "all final verifier assertions passed"];
    statusTable = table(statusName, statusValue, evidence);
    writetable(statusTable, fullfile(artifactDirectory, ...
        'Phase3_1B_Final_Status.csv'));
    fprintf('[RESULT] PHASE3_1B_FINAL_EVIDENCE = PASS\n');
    fprintf('[RESULT] FREQUENCY_LOCAL_MESH_DISCONTINUITY = NO\n');
    fprintf('[RESULT] REVIEWER_BLOCKERS = %d\n', reviewerBlockers);
    fprintf('[RESULT] READY_FOR_PHASE3_2_MESH_CONVERGENCE = YES\n');
end
