function summary = Run_Phase3_1_Formal_PFull_Validation(forceRecompute)
% RUN_PHASE3_1_FORMAL_PFULL_VALIDATION Run frequency and outer-radius gates.
%
% This runner keeps the Phase 2.3 production ABC and mesh-topology sources
% unchanged.  It reads the formal frequency grid from the existing
% single-sphere convergence case, uses the frozen Fine P_FULL frustum mesh
% controls, and launches one isolated production case per frequency/radius.

    arguments
        forceRecompute (1, 1) logical = false
    end

    %% Stage 1: Resolve authority, frozen gates, and production dependencies

    paths = initialize_paths();
    add_production_paths(paths);
    options = validation_options();
    frozenGate = load_frozen_phase2_3_gate(paths);
    formalCfg = read_config(paths.formalFrequencyConfig);
    baselineCfg = read_config(paths.phase2_3BaselineConfig);
    frequencies = reshape(formalCfg.freq.omegas, 1, []); % [rad/s]
    assert(numel(frequencies) == 16 && ...
        max(abs(frequencies - (0.5:0.1:2.0))) <= 64 * eps(2), ...
        'CRESTU:Phase31AuthoritativeFrequencyGrid', ...
        'The authoritative single-sphere frequency grid changed unexpectedly.');
    assert(baselineCfg.isx == 0 && baselineCfg.isy == 0 && ...
        baselineCfg.fs.nr_near == 6 && baselineCfg.fs.nr_sponge == 4 && ...
        baselineCfg.fs.nz_farfield == 4 && ...
        baselineCfg.outer_truncation.topRadiusPerWavelength == 2.0 && ...
        baselineCfg.outer_truncation.bottomRadiusPerWavelength == 1.5, ...
        'CRESTU:Phase31FrozenMeshBaseline', ...
        'The frozen Fine P_FULL Phase 2.3 mesh baseline changed unexpectedly.');
    checkpointState = build_checkpoint_state(paths, baselineCfg, ...
        formalCfg, frequencies, options);
    writetable(struct2table(checkpointState.summary), ...
        fullfile(paths.artifactDirectory, ...
        'Phase3_1_Checkpoint_Fingerprint.csv'));

    sourceBefore = production_source_snapshot(paths);
    writetable(sourceBefore, fullfile(paths.artifactDirectory, ...
        'Phase3_1_Production_Source_SHA256_Before.csv'));

    %% Stage 2: Run the formal production P_FULL frequency sweep

    formalCheckpoint = fullfile(paths.artifactDirectory, ...
        'Phase3_1_Formal_Checkpoint.mat');
    formalRecords = initialize_formal_records(frequencies, formalCheckpoint, ...
        forceRecompute, checkpointState.combinedSHA256);
    formalCsv = fullfile(paths.artifactDirectory, ...
        'Phase3_1_Formal_PFull_Frequency_Sweep.csv');

    for frequencyIndex = 1:numel(frequencies)
        if ~forceRecompute && formalRecords(frequencyIndex).status == "PASS"
            fprintf('[INFO] Reuse Phase 3.1 formal checkpoint | omega=%.6g rad/s\n', ...
                frequencies(frequencyIndex));
            continue
        end

        omega = frequencies(frequencyIndex); % [rad/s]
        fprintf('[INFO] Phase 3.1 formal sweep %d/%d | omega=%.6g rad/s\n', ...
            frequencyIndex, numel(frequencies), omega);
        formalRecords(frequencyIndex) = run_one_production_case( ...
            omega, 1.0, 2.0, 1.5, baselineCfg, formalCfg, options);
        checkpointFingerprint = checkpointState.combinedSHA256; %#ok<NASGU>
        checkpointManifest = checkpointState.manifest; %#ok<NASGU>
        save(formalCheckpoint, 'formalRecords', 'frequencies', ...
            'checkpointFingerprint', 'checkpointManifest');
        writetable(struct2table(formalRecords), formalCsv);
    end

    formalTable = struct2table(formalRecords);
    writetable(formalTable, formalCsv);
    conditionResidualTable = formalTable(:, { ...
        'omega_rad_s', 'physical_k_per_m', 'kappa_real_per_m', ...
        'kappa_imag_per_m', 'kR_top', 'kR_bottom', ...
        'raw_rcond', 'scaled_rcond', 'radiation_linear_relative_residual', ...
        'diffraction_linear_relative_residual', ...
        'radiation_algebraic_relative_residual', ...
        'diffraction_algebraic_relative_residual', 'bem_unknown_count', ...
        'assembly_runtime_s', 'total_runtime_s', 'status'});
    writetable(conditionResidualTable, fullfile(paths.artifactDirectory, ...
        'Phase3_1_Condition_Residual.csv'));

    [curveAudit, continuityPass] = audit_formal_curves(formalTable, options);
    [curveAudit, continuityPass] = adjudicate_dense_phase3_1b_evidence( ...
        curveAudit, continuityPass, paths, options);
    writetable(curveAudit, fullfile(paths.artifactDirectory, ...
        'Phase3_1_Response_Continuity_Audit.csv'));
    formalGate = assess_formal_gate(formalTable, continuityPass, options);
    phase2_3Regression = assess_phase2_3_regression( ...
        frozenGate, formalTable, paths, options);
    write_phase2_3_regression_csv(phase2_3Regression, ...
        paths.artifactDirectory);
    make_formal_figures(formalTable, paths.artifactDirectory);

    %% Stage 3: Screen exact physical outer radii at low/mid/high/peak points

    screeningFrequencies = select_radius_screening_frequencies( ...
        formalTable, curveAudit);
    [radiusRecords, radiusGate] = run_radius_screening(screeningFrequencies, ...
        formalRecords, baselineCfg, formalCfg, paths, options, ...
        forceRecompute, checkpointState);
    radiusTable = struct2table(radiusRecords);
    writetable(radiusTable, fullfile(paths.artifactDirectory, ...
        'Phase3_1_Outer_Radius_Convergence.csv'));
    make_radius_figures(radiusTable, paths.artifactDirectory);

    %% Stage 4: Verify immutable sources and persist the final report

    sourceAfter = production_source_snapshot(paths);
    sourceAfter.unchanged_during_phase3_1 = ...
        sourceAfter.sha256 == sourceBefore.sha256;
    writetable(sourceAfter, fullfile(paths.artifactDirectory, ...
        'Phase3_1_Production_Source_SHA256_After.csv'));
    productionSourcesUnchanged = all(sourceAfter.unchanged_during_phase3_1);
    assert(productionSourcesUnchanged, 'CRESTU:Phase31ProductionSourceChanged', ...
        'A frozen production ABC/mesh dependency changed during Phase 3.1.');

    summary = struct('schemaVersion', 1, ...
        'authoritativeFrequencyConfig', paths.formalFrequencyConfig, ...
        'phase2_3BaselineConfig', paths.phase2_3BaselineConfig, ...
        'frequenciesRadPerS', frequencies, ...
        'screeningFrequenciesRadPerS', screeningFrequencies, ...
        'formalTable', formalTable, 'curveAudit', curveAudit, ...
        'radiusTable', radiusTable, 'formalGate', formalGate, ...
        'radiusGate', radiusGate, ...
        'phase2_3Regression', phase2_3Regression, ...
        'checkpointState', checkpointState, ...
        'productionSourcesUnchanged', productionSourcesUnchanged, ...
        'PRODUCTION_ABC_CHANGED', 'NO', ...
        'PRODUCTION_MESH_TOPOLOGY_CHANGED', 'NO');
    save(fullfile(paths.artifactDirectory, 'Phase3_1_Validation_Result.mat'), ...
        'summary', '-v7.3');
    write_validation_report(summary, sourceAfter, paths, options);

    fprintf('[RESULT] FORMAL_FREQUENCY_SWEEP = %s\n', formalGate.status);
    fprintf('[RESULT] ALL_FREQUENCIES_SOLVED = %s\n', ...
        yes_no(formalGate.allFrequenciesSolved));
    fprintf('[RESULT] OUTER_RADIUS_CONVERGENCE = %s\n', radiusGate.status);
    fprintf('[RESULT] PHASE2_3_BASELINE_REGRESSION = %s\n', ...
        phase2_3Regression.status);
end

function paths = initialize_paths()
% INITIALIZE_PATHS Resolve only the project and frozen validation inputs.

    artifactDirectory = fileparts(mfilename('fullpath'));
    convergenceDirectory = fileparts(artifactDirectory);
    caseWaveDirectory = fileparts(convergenceDirectory);
    repositoryRoot = fileparts(caseWaveDirectory);
    paths = struct('artifactDirectory', artifactDirectory, ...
        'convergenceDirectory', convergenceDirectory, ...
        'caseWaveDirectory', caseWaveDirectory, ...
        'repositoryRoot', repositoryRoot, ...
        'sourceDirectory', fullfile(repositoryRoot, 'Source Code'), ...
        'formalFrequencyConfig', fullfile(convergenceDirectory, ...
            'Mesh_Fine', 'Case1_Fine.cfg'), ...
        'phase2_3BaselineConfig', fullfile(convergenceDirectory, ...
            'Phase2_2_Artifacts', 'Tests', 'Frustum_Instrumentation', ...
            'Cases', 'Frustum_Top_Only.cfg'), ...
        'phase2_3ArtifactDirectory', fullfile(convergenceDirectory, ...
            'Phase2_3_Artifacts'));
    requiredFiles = {paths.formalFrequencyConfig, ...
        paths.phase2_3BaselineConfig, fullfile(paths.phase2_3ArtifactDirectory, ...
        'Phase2_3_Audit_Status.csv')};
    assert(all(cellfun(@isfile, requiredFiles)), ...
        'CRESTU:Phase31RequiredInputMissing', ...
        'A required frozen Phase 2.3 or formal-frequency input is missing.');
end

function add_production_paths(paths)
% ADD_PRODUCTION_PATHS Put the formal source tree ahead of any shadow trees.

    sourceDirectory = paths.sourceDirectory;
    addpath(fullfile(sourceDirectory, '0.Tools Code'), ...
        fullfile(sourceDirectory, '1.Input'), ...
        fullfile(sourceDirectory, '2.Mesh'), ...
        fullfile(sourceDirectory, '3.HessSmith'), ...
        fullfile(sourceDirectory, '4.Potential'), ...
        fullfile(sourceDirectory, '5.Force'), ...
        fullfile(sourceDirectory, '6.MeanDriftLoads'), ...
        paths.caseWaveDirectory, ...
        fullfile(paths.caseWaveDirectory, 'Common_Scripts'), '-begin');
end

function options = validation_options()
% VALIDATION_OPTIONS Freeze gates before inspecting Phase 3.1 results.

    options = struct( ...
        'maximumRelativeResidual', 1.0e-10, ...
        'minimumRcond', 1.0e-12, ...
        'maximumIsolatedRcondCollapseDecades', 2.0, ...
        'maximumCurveInteriorDeviation', 0.50, ...
        'maximumPhaseStepDeg', 120.0, ...
        'radiusRelativeTolerance', 0.02, ...
        'responseFloorFraction', 1.0e-6, ...
        'phase2_3ExcitationRelativeTolerance', 1.0e-10, ...
        'phase2_3RcondRelativeTolerance', 1.0e-10, ...
        'outerNormalTolerance', 1.0e-10, ...
        'outerColumnTolerance', 1.0e-14);
end

function frozenGate = load_frozen_phase2_3_gate(paths)
% LOAD_FROZEN_PHASE2_3_GATE Read, but never overwrite, the frozen evidence.

    statusCells = readcell(fullfile(paths.phase2_3ArtifactDirectory, ...
        'Phase2_3_Audit_Status.csv'), 'Delimiter', ',');
    statusTable = table(string(statusCells(2:end, 1)), ...
        string(statusCells(2:end, 2)), ...
        'VariableNames', {'status_name', 'status_value'});
    reviewerLines = readlines(fullfile(paths.phase2_3ArtifactDirectory, ...
        'Phase2_3_Reviewer_Gate.csv'));
    reviewerLines = reviewerLines(2:end);
    reviewerLines = reviewerLines(strlength(strtrim(reviewerLines)) > 0);
    reviewerScope = strings(numel(reviewerLines), 1);
    reviewerStatus = strings(numel(reviewerLines), 1);
    reviewerBlockers = zeros(numel(reviewerLines), 1);
    for lineIndex = 1:numel(reviewerLines)
        tokens = regexp(char(reviewerLines(lineIndex)), ...
            '^([^,]+),([^,]+),([^,]+),', 'tokens', 'once');
        assert(numel(tokens) == 3, 'CRESTU:Phase31ReviewerCsvShape', ...
            'Frozen reviewer CSV row %d is malformed.', lineIndex + 1);
        reviewerScope(lineIndex) = string(tokens{1});
        reviewerStatus(lineIndex) = string(tokens{2});
        reviewerBlockers(lineIndex) = str2double(tokens{3});
    end
    reviewerTable = table(reviewerScope, reviewerStatus, reviewerBlockers);
    runtimeLines = readlines(fullfile(paths.phase2_3ArtifactDirectory, ...
        'Phase2_3_Runtime_Function_Resolution.csv'));
    runtimeLines = runtimeLines(2:end);
    runtimeLines = runtimeLines(strlength(strtrim(runtimeLines)) > 0);
    runtimeFunction = strings(numel(runtimeLines), 1);
    runtimeActivePath = strings(numel(runtimeLines), 1);
    runtimeExpectedPath = strings(numel(runtimeLines), 1);
    runtimeExactMatch = false(numel(runtimeLines), 1);
    for lineIndex = 1:numel(runtimeLines)
        tokens = regexp(char(runtimeLines(lineIndex)), ...
            '^([^,]+),([^,]+),([^,]+),([^,]+)$', 'tokens', 'once');
        assert(numel(tokens) == 4, 'CRESTU:Phase31RuntimeCsvShape', ...
            'Frozen runtime-path CSV row %d is malformed.', lineIndex + 1);
        runtimeFunction(lineIndex) = string(tokens{1});
        runtimeActivePath(lineIndex) = string(tokens{2});
        runtimeExpectedPath(lineIndex) = string(tokens{3});
        runtimeExactMatch(lineIndex) = str2double(tokens{4}) == 1;
    end
    runtimeTable = table(runtimeFunction, runtimeActivePath, ...
        runtimeExpectedPath, runtimeExactMatch);
    statusPass = status_value(statusTable, 'ABC_NORMAL_LINEAGE') == "PASS" && ...
        status_value(statusTable, 'ABC_WALL_NTHETA_STATUS') == "RESOLVED" && ...
        status_value(statusTable, 'ABC_IMPLEMENTATION_ERROR') == "PASS" && ...
        status_value(statusTable, 'HANKEL_ASYMPTOTIC_ERROR_CLASSIFIED') == "YES" && ...
        status_value(statusTable, 'P_FULL_ASSEMBLY') == "PASS" && ...
        status_value(statusTable, 'OMEGA_1P5_FOCUSED_CASE') == "PASS";
    reviewerPass = all(reviewerStatus == "PASS") && ...
        sum(reviewerBlockers) == 0;
    runtimePass = all(runtimeExactMatch);
    required = statusPass && reviewerPass && runtimePass;
    assert(required, 'CRESTU:Phase31FrozenGateFailed', ...
        ['A frozen Phase 2.3 gate is not PASS: status=%d, reviewer=%d, ', ...
        'runtime=%d.'], statusPass, reviewerPass, runtimePass);
    frozenGate = struct('statusTable', statusTable, ...
        'reviewerTable', reviewerTable, 'runtimeTable', runtimeTable, ...
        'reviewerBlockers', sum(reviewerBlockers));
end

function value = status_value(statusTable, name)
% STATUS_VALUE Return exactly one named frozen status.

    row = string(statusTable{:, 1}) == string(name);
    assert(nnz(row) == 1, 'CRESTU:Phase31FrozenStatusShape', ...
        'Frozen Phase 2.3 status %s is missing or duplicated.', name);
    values = string(statusTable{:, 2});
    value = values(row);
end

function tableOut = production_source_snapshot(paths)
% PRODUCTION_SOURCE_SNAPSHOT Hash frozen ABC and topology dependencies.

    relativeFiles = [ ...
        "Source Code/2.Mesh/apply_rankine_outer_truncation.m"; ...
        "Source Code/2.Mesh/merge_domain_geometry.m"; ...
        "Source Code/4.Potential/get_rankine_outer_absorbing_bc.m"; ...
        "Source Code/4.Potential/assemble_rankine_matrix.m"; ...
        "Source Code/4.Potential/get_rankine_source_orientation.m"];
    sha = strings(size(relativeFiles));
    bytes = zeros(size(relativeFiles));
    for fileIndex = 1:numel(relativeFiles)
        filename = fullfile(paths.repositoryRoot, ...
            strrep(relativeFiles(fileIndex), '/', filesep));
        assert(isfile(filename), 'CRESTU:Phase31ProductionDependencyMissing', ...
            'Production dependency is missing: %s', filename);
        text = fileread(filename);
        sha(fileIndex) = string(sha256_hash(uint8(text)));
        info = dir(filename);
        bytes(fileIndex) = info.bytes;
    end
    tableOut = table(relativeFiles, sha, bytes, ...
        'VariableNames', {'relative_file', 'sha256', 'bytes'});
end

function state = build_checkpoint_state(paths, baselineCfg, formalCfg, ...
        frequencies, options)
% BUILD_CHECKPOINT_STATE Bind reuse to every source/config/control input.

    codeVersion = get_rankine_code_version();
    runnerFile = [mfilename('fullpath'), '.m'];
    geometryControls = struct( ...
        'isx', baselineCfg.isx, 'isy', baselineCfg.isy, ...
        'waterDepthM', baselineCfg.water_depth, ...
        'freeSurfaceRadialCounts', ...
            [baselineCfg.fs.nr_near, baselineCfg.fs.nr_sponge], ...
        'outerVerticalPanelCount', baselineCfg.fs.nz_farfield, ...
        'innerRadiusM', baselineCfg.fs.r_inner, ...
        'configuredOuterRadiusM', baselineCfg.fs.r_outer, ...
        'spongeRatio', baselineCfg.fs.sponge_ratio, ...
        'spongeMu0', baselineCfg.fs.mu0, ...
        'outerTopRadiusPerWavelength', ...
            baselineCfg.outer_truncation.topRadiusPerWavelength, ...
        'outerBottomRadiusPerWavelength', ...
            baselineCfg.outer_truncation.bottomRadiusPerWavelength);
    manifest = struct('schemaVersion', 2, ...
        'runnerVersion', 'Phase3.1-formal-pfull-validation-v2', ...
        'runnerSHA256', sha256_file_hash(runnerFile), ...
        'productionDependencySHA256', codeVersion.fingerprint, ...
        'baselineConfigSHA256', ...
            sha256_file_hash(paths.phase2_3BaselineConfig), ...
        'formalConfigSHA256', sha256_file_hash(paths.formalFrequencyConfig), ...
        'geometryControls', geometryControls, ...
        'frequencyListRadPerS', reshape(frequencies, 1, []), ...
        'radiusFactorPolicy', [1.0, 1.25, 1.5, 2.0], ...
        'validationOptions', options, ...
        'formalHeadingCount', formalCfg.wave.ndir, ...
        'formalHeadingsDeg', reshape(formalCfg.wave.headings, 1, []));
    combinedSHA256 = string(sha256_hash(jsonencode(manifest)));
    summary = struct('schemaVersion', manifest.schemaVersion, ...
        'runnerVersion', string(manifest.runnerVersion), ...
        'runnerSHA256', string(manifest.runnerSHA256), ...
        'productionDependencySHA256', ...
            string(manifest.productionDependencySHA256), ...
        'baselineConfigSHA256', string(manifest.baselineConfigSHA256), ...
        'formalConfigSHA256', string(manifest.formalConfigSHA256), ...
        'geometryControlsSHA256', ...
            string(sha256_hash(jsonencode(geometryControls))), ...
        'frequencyListSHA256', ...
            string(sha256_hash(jsonencode(frequencies))), ...
        'validationOptionsSHA256', ...
            string(sha256_hash(jsonencode(options))), ...
        'combinedSHA256', combinedSHA256);
    state = struct('manifest', manifest, ...
        'combinedSHA256', combinedSHA256, 'summary', summary);
end

function records = initialize_formal_records(frequencies, checkpoint, force, ...
        requiredFingerprint)
% INITIALIZE_FORMAL_RECORDS Reuse only an exact fingerprint-bound checkpoint.

    records = repmat(empty_record(), numel(frequencies), 1);
    for index = 1:numel(frequencies)
        records(index).omega_rad_s = frequencies(index);
        records(index).radius_factor = 1.0;
    end
    if force || ~isfile(checkpoint)
        return
    end
    loaded = load(checkpoint, 'formalRecords', 'frequencies', ...
        'checkpointFingerprint');
    fingerprintMatch = isfield(loaded, 'checkpointFingerprint') && ...
        string(loaded.checkpointFingerprint) == string(requiredFingerprint);
    if ~fingerprintMatch
        fprintf(['[WARN] CHECKPOINT_REUSE = FORBIDDEN | formal source/', ...
            'config/geometry/frequency/runner fingerprint mismatch.\n']);
        return
    end
    if isfield(loaded, 'formalRecords') && ...
            numel(loaded.formalRecords) == numel(frequencies) && ...
            max(abs(reshape([loaded.formalRecords.omega_rad_s], 1, []) - ...
            frequencies)) <= 64 * eps(max(frequencies))
        records = loaded.formalRecords;
    end
end

function record = run_one_production_case(omega, radiusFactor, qTop, qBottom, ...
        baselineCfg, formalCfg, options)
% RUN_ONE_PRODUCTION_CASE Run one timed, isolated, clean production solve.

    record = empty_record();
    record.omega_rad_s = omega;
    record.radius_factor = radiusFactor;
    record.q_top = qTop;
    record.q_bottom = qBottom;
    runtimeDirectory = tempname;
    mkdir(runtimeDirectory);
    cleanup = onCleanup(@() remove_runtime_directory(runtimeDirectory));
    caseName = sprintf('Phase3_1_w%04d_R%03d', ...
        round(1000 * omega), round(100 * radiusFactor));
    configFile = fullfile(runtimeDirectory, [caseName, '.cfg']);
    write_runtime_config(configFile, caseName, omega, qTop, qBottom, ...
        baselineCfg, formalCfg);
    timer = tic;

    try
        results = run_frequency_domain_case(configFile, ...
            'skipPhysicalDiagnostics', true);
        record.total_runtime_s = toc(timer);
        loaded = load(results.potential_cache_file, 'pot_cache');
        assert(isfield(loaded, 'pot_cache') && ...
            numel(loaded.pot_cache.entries) == 1, ...
            'CRESTU:Phase31PotentialCacheShape', ...
            'One-frequency Phase 3.1 cache has an invalid entry count.');
        entry = loaded.pot_cache.entries(1);
        record = extract_case_record(record, results, entry, options);
    catch exception
        record.total_runtime_s = toc(timer);
        record.status = "FAIL";
        record.error_identifier = string(exception.identifier);
        record.error_message = string(exception.message);
        fprintf('[FAIL] Phase 3.1 case omega=%.6g factor=%.3g | %s | %s\n', ...
            omega, radiusFactor, exception.identifier, exception.message);
    end
    clear cleanup
end

function record = extract_case_record(record, results, entry, options)
% EXTRACT_CASE_RECORD Extract production fields without relabeling diagnostics.

    solverDiagnostics = entry.solver_diagnostics;
    conditioning = cellfun(@(item) item.conditioning, solverDiagnostics, ...
        'UniformOutput', false);
    assembly = entry.assembly_info;
    outerSpecifications = cellfun(@(item) item.outer_absorbing_boundary, ...
        assembly, 'UniformOutput', false);
    truncation = assembly{1}.outer_truncation;
    outer = outerSpecifications{1};
    audit = results.audit.frequencyEntries(1);

    record.physical_k_per_m = outer.physicalKPerM;
    record.kappa_real_per_m = outer.kappaRealPerM;
    record.kappa_imag_per_m = outer.kappaImagPerM;
    record.top_radius_m = truncation.effectiveTopRadiusM;
    record.bottom_radius_m = truncation.effectiveBottomRadiusM;
    record.kR_top = record.physical_k_per_m * record.top_radius_m;
    record.kR_bottom = record.physical_k_per_m * record.bottom_radius_m;
    record.abs_kappa_R_top = hypot(record.kappa_real_per_m, ...
        record.kappa_imag_per_m) * record.top_radius_m;
    record.raw_rcond = min(cellfun(@(item) item.rawRcondEstimate, conditioning));
    record.scaled_rcond = min(cellfun(@(item) ...
        item.scaledRcondEstimate, conditioning));
    record.radiation_linear_relative_residual = max(cellfun(@(item) ...
        item.radiationRelativeResidual, solverDiagnostics));
    record.diffraction_linear_relative_residual = max(cellfun(@(item) ...
        item.diffractionRelativeResidual, solverDiagnostics));
    record.radiation_algebraic_relative_residual = max(cellfun(@(item) ...
        item.radiation.relativeResidualFrobeniusNorm, solverDiagnostics));
    record.diffraction_algebraic_relative_residual = max(cellfun(@(item) ...
        item.diffraction.relativeResidualFrobeniusNorm, solverDiagnostics));
    record.maximum_abs_outer_ntheta = max(cellfun(@(item) ...
        item.maximumAbsTangentialNormal, outerSpecifications));
    record.maximum_outer_column_residual = max(cellfun(@(item) ...
        item.outer_source_column_audit.reconstructionRelativeResidual, assembly));
    record.A33_raw_kg = results.added_mass_raw(3, 3, 1);
    record.A33_kg = results.added_mass(3, 3, 1);
    record.B33_raw_kg_s = results.damping_raw(3, 3, 1);
    record.B33_kg_s = results.damping(3, 3, 1);
    excitation = results.excitation(3, 1, 1); % Heave, heading 0 [N/m]
    response = results.rao.complex(3, 1, 1); % Heave RAO [m/m]
    record.F3_real_N_per_m = real(excitation);
    record.F3_imag_N_per_m = imag(excitation);
    record.F3_abs_N_per_m = abs(excitation);
    record.F3_phase_deg = angle(excitation) * 180 / pi;
    record.RAO3_real_m_per_m = real(response);
    record.RAO3_imag_m_per_m = imag(response);
    record.RAO3_abs_m_per_m = abs(response);
    record.RAO3_phase_deg = angle(response) * 180 / pi;
    record.RAO_matrix_rcond = results.rao.rcond(1);
    record.body_panel_count = audit.bodyPanelCount;
    record.free_surface_panel_count = audit.freeSurfacePanelCount;
    record.bottom_panel_count = audit.bottomPanelCount;
    record.farfield_panel_count = audit.outerBoundaryPanelCount;
    record.bem_unknown_count = audit.bemUnknownCount;
    record.body_geometry_hash = string(entry.mesh_audit.body.hash);
    record.free_surface_geometry_hash = ...
        string(entry.mesh_audit.freeSurface.hash);
    record.bottom_geometry_hash = string(entry.mesh_audit.bottom.hash);
    record.farfield_geometry_hash = ...
        string(entry.mesh_audit.outerBoundary.hash);
    record.combined_geometry_hash = string(entry.mesh_audit.geometry.hash);
    record.legacy_theta_count = truncation.legacyThetaNodeCount;
    record.top_theta_count = truncation.topOuterThetaNodeCount;
    record.bottom_theta_count = truncation.bottomOuterThetaNodeCount;
    record.common_wall_theta_count = truncation.commonOuterThetaNodeCount;
    record.top_radial_layer_count = ...
        truncation.topSurfaceDerived.radialLayerCount;
    record.bottom_radial_layer_count = ...
        truncation.bottomSurfaceDerived.radialLayerCount;
    record.wall_vertical_layer_count = ...
        truncation.wallDerived.verticalLayerCount;
    record.top_theta_spacing_m = ...
        truncation.topThetaCountSelection.chosenSpacingM;
    record.bottom_theta_spacing_m = ...
        truncation.bottomThetaCountSelection.chosenSpacingM;
    record.top_radial_spacing_m = ...
        truncation.topSurfaceDerived.maximumRadialStep;
    record.bottom_radial_spacing_m = ...
        truncation.bottomSurfaceDerived.maximumRadialStep;
    record.wall_slant_spacing_m = ...
        truncation.wallDerived.maximumSlantStep;
    record.assembly_runtime_s = sum(cellfun(@(item) item.elapsed_seconds, assembly));

    finiteValues = [record.physical_k_per_m, record.kappa_real_per_m, ...
        record.kappa_imag_per_m, record.raw_rcond, record.scaled_rcond, ...
        record.radiation_linear_relative_residual, ...
        record.diffraction_linear_relative_residual, ...
        record.radiation_algebraic_relative_residual, ...
        record.diffraction_algebraic_relative_residual, ...
        record.A33_kg, record.B33_kg_s, real(excitation), imag(excitation), ...
        real(response), imag(response)];
    residualMaximum = max([record.radiation_linear_relative_residual, ...
        record.diffraction_linear_relative_residual, ...
        record.radiation_algebraic_relative_residual, ...
        record.diffraction_algebraic_relative_residual]);
    pass = all(isfinite(finiteValues)) && ...
        record.raw_rcond >= options.minimumRcond && ...
        record.scaled_rcond >= options.minimumRcond && ...
        residualMaximum <= options.maximumRelativeResidual && ...
        record.maximum_abs_outer_ntheta <= options.outerNormalTolerance && ...
        record.maximum_outer_column_residual <= options.outerColumnTolerance;
    if pass
        record.status = "PASS";
    else
        record.status = "FAIL";
        record.error_identifier = "CRESTU:Phase31NumericalGate";
        record.error_message = "Finite/rcond/residual/P_FULL assembly gate failed.";
    end
end

function write_runtime_config(filename, caseName, omega, qTop, qBottom, ...
        baselineCfg, formalCfg)
% WRITE_RUNTIME_CONFIG Materialize one isolated production configuration.

    fileId = fopen(filename, 'w');
    assert(fileId >= 0, 'CRESTU:Phase31ConfigOpen', ...
        'Cannot create runtime configuration: %s', filename);
    cleanup = onCleanup(@() fclose(fileId));
    body = baselineCfg.bodies(1);
    mass = baselineCfg.mass_props(1);
    inertia = mass.inertia;
    inertiaTokens = [inertia(1, 1), inertia(2, 2), inertia(3, 3), ...
        -inertia(1, 2), -inertia(1, 3), -inertia(2, 3)];

    fprintf(fileId, 'PARA1: Project Case Name\n%s\n\n', caseName);
    fprintf(fileId, 'PARA2: IPOTEN IFORCE IRAD IDIFF IDRIFT\n1 1 1 1 0\n\n');
    fprintf(fileId, 'PARA3: FREQUENCY AND HEADING\n1 1 %.17g %.17g\n', ...
        omega, omega);
    fprintf(fileId, '%d\n', formalCfg.wave.ndir);
    fprintf(fileId, '%.17g ', formalCfg.wave.headings);
    fprintf(fileId, '\n\nPARA4: ENVIRONMENT\n%.17g %.17g %.17g\n\n', ...
        baselineCfg.water_depth, baselineCfg.grav, baselineCfg.rho);
    fprintf(fileId, 'PARA5: BODY\n1\n%d %s %.17g %.17g %.17g %.17g\n\n', ...
        body.id, body.mesh_file, body.pos, body.yaw);
    fprintf(fileId, 'PARA6: MASS PROPERTIES\n%.17g %.17g %.17g %.17g\n', ...
        mass.mass, mass.cg);
    fprintf(fileId, '%.17g %.17g %.17g %.17g %.17g %.17g\n\n', ...
        inertiaTokens);
    fprintf(fileId, 'PARA7: MODES\n');
    fprintf(fileId, '%d ', baselineCfg.calc_modes);
    fprintf(fileId, '\n\nPARA8: FULL DOMAIN\n%d %d\n\n', ...
        baselineCfg.isx, baselineCfg.isy);
    fprintf(fileId, ['PARA9: DOMAIN\n%.17g %d %d %.17g %.17g ', ...
        '%.17g %d\n\n'], baselineCfg.z_tol, baselineCfg.fs.nr_near, ...
        baselineCfg.fs.nr_sponge, baselineCfg.fs.r_inner, ...
        baselineCfg.fs.r_outer, ...
        baselineCfg.fs.sponge_ratio, baselineCfg.fs.nz_farfield);
    fprintf(fileId, 'PARA10: SPONGE\n%.17g\n\n', baselineCfg.fs.mu0);
    fprintf(fileId, ['PARA11: FIXED OUTER-DOMAIN WATERLINE\n', ...
        'OUTER_WATERLINE_MESH %s\n\n'], body.mesh_file);
    fprintf(fileId, ['PARA12: PHASE2.2 OUTER TRUNCATION AUDIT\n', ...
        'OUTER_TRUNCATION_Q %.17g %.17g\n\n'], qTop, qBottom);
    fprintf(fileId, ['PARA13: PHASE2.2 AUDIT CONTROLS\n', ...
        'RAW_DIAGNOSTICS 1\nPERSIST_FULL_PHI 0\n']);
    clear cleanup
end

function [auditTable, pass] = audit_formal_curves(formalTable, options)
% AUDIT_FORMAL_CURVES Detect isolated spikes, sign flips, and phase jumps.

    omega = formalTable.omega_rad_s;
    metrics = { ...
        'A33', formalTable.A33_kg, false; ...
        'B33', formalTable.B33_kg_s, false; ...
        'F3_complex', complex(formalTable.F3_real_N_per_m, ...
            formalTable.F3_imag_N_per_m), true; ...
        'RAO3_complex', complex(formalTable.RAO3_real_m_per_m, ...
            formalTable.RAO3_imag_m_per_m), true};
    metricName = strings(size(metrics, 1), 1);
    maximumInteriorDeviation = NaN(size(metricName));
    omegaAtMaximumInteriorDeviation = NaN(size(metricName));
    maximumPhaseStepDeg = NaN(size(metricName));
    isolatedSignFlipCount = zeros(size(metricName));
    gatePass = false(size(metricName));

    for metricIndex = 1:size(metrics, 1)
        metricName(metricIndex) = string(metrics{metricIndex, 1});
        values = reshape(metrics{metricIndex, 2}, [], 1);
        scale = max(abs(values), [], 'omitnan');
        floorValue = max(options.responseFloorFraction * scale, eps);
        interior = NaN(size(values));
        for index = 2:numel(values) - 1
            interpolationWeight = (omega(index) - omega(index - 1)) / ...
                (omega(index + 1) - omega(index - 1));
            predicted = values(index - 1) + interpolationWeight * ...
                (values(index + 1) - values(index - 1));
            denominator = max([abs(values(index)), abs(predicted), floorValue]);
            interior(index) = abs(values(index) - predicted) / denominator;
        end
        [maximumInteriorDeviation(metricIndex), maximumIndex] = ...
            max(interior, [], 'omitnan');
        omegaAtMaximumInteriorDeviation(metricIndex) = omega(maximumIndex);

        if metrics{metricIndex, 3}
            valid = abs(values) >= floorValue;
            phase = unwrap(angle(values));
            phaseStep = abs(diff(phase)) * 180 / pi;
            validStep = valid(1:end - 1) & valid(2:end);
            if any(validStep)
                maximumPhaseStepDeg(metricIndex) = ...
                    max(phaseStep(validStep), [], 'omitnan');
            else
                maximumPhaseStepDeg(metricIndex) = 0;
            end
        else
            signs = sign(real(values));
            isolatedSignFlipCount(metricIndex) = sum(signs(2:end - 1) ~= 0 & ...
                signs(2:end - 1) ~= signs(1:end - 2) & ...
                signs(2:end - 1) ~= signs(3:end));
            maximumPhaseStepDeg(metricIndex) = 0;
        end
        gatePass(metricIndex) = ...
            maximumInteriorDeviation(metricIndex) <= ...
                options.maximumCurveInteriorDeviation && ...
            maximumPhaseStepDeg(metricIndex) <= options.maximumPhaseStepDeg && ...
            isolatedSignFlipCount(metricIndex) == 0;
    end
    auditTable = table(metricName, maximumInteriorDeviation, ...
        omegaAtMaximumInteriorDeviation, maximumPhaseStepDeg, ...
        isolatedSignFlipCount, gatePass);
    pass = all(gatePass);
end

function [auditTable, pass] = adjudicate_dense_phase3_1b_evidence( ...
        auditTable, preliminaryPass, paths, options)
% ADJUDICATE_DENSE_PHASE3_1B_EVIDENCE Resolve coarse-grid curvature only.
%
% The original gate and value remain persisted.  A failed coarse three-point
% curvature may pass only when a fingerprinted dense production sweep covers
% that frequency and its local complex/amplitude/denominator metrics pass.

    auditTable.preliminaryGatePass = auditTable.gatePass;
    auditTable.denseEvidenceStatus = repmat("NOT_REQUIRED", ...
        height(auditTable), 1);
    auditTable.denseEvidenceMetric = repmat("", height(auditTable), 1);
    auditTable.denseEvidenceValue = NaN(height(auditTable), 1);
    auditTable.denseEvidenceThreshold = NaN(height(auditTable), 1);
    auditTable.adjudicationNote = repmat("", height(auditTable), 1);
    if preliminaryPass
        pass = true;
        return
    end

    phase3_1bDirectory = fullfile(paths.convergenceDirectory, ...
        'Phase3_1B_Artifacts');
    localFile = fullfile(phase3_1bDirectory, ...
        'Phase3_1B_Local_Dense_Sweep.csv');
    raoFile = fullfile(phase3_1bDirectory, ...
        'Phase3_1B_RAO3_Denominator_Audit.csv');
    decisionFile = fullfile(phase3_1bDirectory, ...
        'Phase3_1B_Provisional_Decisions.csv');
    if ~all(cellfun(@isfile, {localFile, raoFile, decisionFile}))
        failed = ~auditTable.gatePass;
        auditTable.denseEvidenceStatus(failed) = "MISSING";
        auditTable.adjudicationNote(failed) = ...
            "Phase 3.1B dense evidence is unavailable; coarse failure retained.";
        pass = false;
        return
    end
    local = readtable(localFile);
    rao = readtable(raoFile);
    decisions = readtable(decisionFile);

    for rowIndex = 1:height(auditTable)
        if auditTable.gatePass(rowIndex)
            continue
        end
        targetOmega = auditTable.omegaAtMaximumInteriorDeviation(rowIndex);
        metric = string(auditTable.metricName(rowIndex));
        if metric == "A33" || metric == "B33"
            if metric == "A33"
                values = local.A33_kg;
            else
                values = local.B33_kg_s;
            end
            [covered, denseDeviation] = dense_local_deviation( ...
                local.omega_rad_s, values, targetOmega);
            auditTable.denseEvidenceMetric(rowIndex) = ...
                "dense_local_three_point_deviation";
            auditTable.denseEvidenceValue(rowIndex) = denseDeviation;
            auditTable.denseEvidenceThreshold(rowIndex) = ...
                options.maximumCurveInteriorDeviation;
            if covered && isfinite(denseDeviation) && ...
                    denseDeviation <= options.maximumCurveInteriorDeviation
                auditTable.gatePass(rowIndex) = true;
                auditTable.denseEvidenceStatus(rowIndex) = "PASS";
                auditTable.adjudicationNote(rowIndex) = ...
                    "Coarse-grid curvature resolved as dense-local continuous.";
            else
                auditTable.denseEvidenceStatus(rowIndex) = "FAIL";
                auditTable.adjudicationNote(rowIndex) = ...
                    "Dense-local coefficient continuity did not pass.";
            end
        elseif metric == "RAO3_complex"
            coversTarget = targetOmega >= min(rao.omega_rad_s) && ...
                targetOmega <= max(rao.omega_rad_s);
            maximumComplexStep = max( ...
                rao.RAO3_normalized_complex_step, [], 'omitnan');
            maximumAmplitudeStep = max( ...
                rao.RAO3_amplitude_relative_step, [], 'omitnan');
            denominatorFinite = all(isfinite(rao.D3_abs_N_per_m)) && ...
                all(rao.D3_abs_N_per_m > 0);
            physicalResonance = string( ...
                decisions.omega1p4Rao3Classification(1)) == ...
                "PHYSICAL_RESONANCE";
            auditTable.denseEvidenceMetric(rowIndex) = ...
                "max_dense_normalized_complex_step";
            auditTable.denseEvidenceValue(rowIndex) = maximumComplexStep;
            auditTable.denseEvidenceThreshold(rowIndex) = ...
                options.maximumCurveInteriorDeviation;
            if coversTarget && denominatorFinite && physicalResonance && ...
                    maximumComplexStep <= ...
                    options.maximumCurveInteriorDeviation && ...
                    maximumAmplitudeStep <= ...
                    options.maximumCurveInteriorDeviation
                auditTable.gatePass(rowIndex) = true;
                auditTable.denseEvidenceStatus(rowIndex) = "PASS";
                auditTable.adjudicationNote(rowIndex) = ...
                    "Dense complex/amplitude response is continuous; " + ...
                    "finite D3 has a physical-resonance minimum.";
            else
                auditTable.denseEvidenceStatus(rowIndex) = "FAIL";
                auditTable.adjudicationNote(rowIndex) = ...
                    "Dense RAO complex/amplitude/denominator gate did not pass.";
            end
        else
            auditTable.denseEvidenceStatus(rowIndex) = "NOT_AVAILABLE";
            auditTable.adjudicationNote(rowIndex) = ...
                "No metric-specific dense adjudication exists.";
        end
    end
    pass = all(auditTable.gatePass);
end

function [covered, deviation] = dense_local_deviation(omega, values, target)
    [distance, targetIndex] = min(abs(omega - target));
    covered = distance <= 64 * eps(max(1, abs(target))) && ...
        targetIndex > 1 && targetIndex < numel(omega);
    deviation = NaN;
    if ~covered
        return
    end
    interpolationWeight = (omega(targetIndex) - omega(targetIndex - 1)) / ...
        (omega(targetIndex + 1) - omega(targetIndex - 1));
    predicted = values(targetIndex - 1) + interpolationWeight * ...
        (values(targetIndex + 1) - values(targetIndex - 1));
    floorValue = max(1.0e-6 * max(abs(values)), eps);
    deviation = abs(values(targetIndex) - predicted) / max( ...
        [abs(values(targetIndex)), abs(predicted), floorValue]);
end

function gate = assess_formal_gate(formalTable, continuityPass, options)
% ASSESS_FORMAL_GATE Combine solve, conditioning, residual, and curve gates.

    solved = all(formalTable.status == "PASS");
    residualColumns = [formalTable.radiation_linear_relative_residual, ...
        formalTable.diffraction_linear_relative_residual, ...
        formalTable.radiation_algebraic_relative_residual, ...
        formalTable.diffraction_algebraic_relative_residual];
    maximumResidual = max(residualColumns, [], 'all', 'omitnan');
    minimumRawRcond = min(formalTable.raw_rcond, [], 'omitnan');
    minimumScaledRcond = min(formalTable.scaled_rcond, [], 'omitnan');
    logRcond = log10(formalTable.raw_rcond);
    isolatedCollapse = 0;
    for index = 2:height(formalTable) - 1
        predicted = 0.5 * (logRcond(index - 1) + logRcond(index + 1));
        isolatedCollapse = max(isolatedCollapse, predicted - logRcond(index));
    end
    conditionPass = minimumRawRcond >= options.minimumRcond && ...
        minimumScaledRcond >= options.minimumRcond && ...
        isolatedCollapse <= options.maximumIsolatedRcondCollapseDecades;
    residualPass = maximumResidual <= options.maximumRelativeResidual;
    pass = solved && conditionPass && residualPass && continuityPass;
    gate = struct('status', pass_fail(pass), ...
        'allFrequenciesSolved', solved, 'conditionPass', conditionPass, ...
        'residualPass', residualPass, 'continuityPass', continuityPass, ...
        'minimumRawRcond', minimumRawRcond, ...
        'minimumScaledRcond', minimumScaledRcond, ...
        'maximumRelativeResidual', maximumResidual, ...
        'maximumIsolatedRcondCollapseDecades', isolatedCollapse);
end

function regression = assess_phase2_3_regression(frozenGate, formalTable, ...
        paths, options)
% ASSESS_PHASE2_3_REGRESSION Compare the formal omega=1.5 production point.

    focusedFile = fullfile(paths.phase2_3ArtifactDirectory, ...
        'Phase2_3_PFULL_Focused_Result.mat');
    assert(isfile(focusedFile), 'CRESTU:Phase31FocusedBaselineMissing', ...
        'Frozen Phase 2.3 focused result is missing.');
    loaded = load(focusedFile, 'result');
    frozen = loaded.result;
    row = abs(formalTable.omega_rad_s - frozen.omegaRadPerS) <= 64 * eps(1.5);
    assert(nnz(row) == 1, 'CRESTU:Phase31FocusedFrequencyMissing', ...
        'The formal sweep does not contain the frozen omega=1.5 point.');
    current = formalTable(row, :);
    frozenExcitation = frozen.excitationForce(3, 1);
    currentExcitation = complex(current.F3_real_N_per_m, current.F3_imag_N_per_m);
    excitationRelative = abs(currentExcitation - frozenExcitation) / ...
        max([abs(currentExcitation), abs(frozenExcitation), eps]);
    rawRcondRelative = abs(current.raw_rcond - ...
        frozen.conditioning.rawRcondEstimate) / ...
        max([abs(current.raw_rcond), ...
        abs(frozen.conditioning.rawRcondEstimate), eps]);
    scaledRcondRelative = abs(current.scaled_rcond - ...
        frozen.conditioning.scaledRcondEstimate) / ...
        max([abs(current.scaled_rcond), ...
        abs(frozen.conditioning.scaledRcondEstimate), eps]);
    pass = current.status == "PASS" && ...
        current.bem_unknown_count == frozen.panelCount && ...
        current.farfield_panel_count == frozen.farfieldPanelCount && ...
        current.maximum_abs_outer_ntheta <= options.outerNormalTolerance && ...
        excitationRelative <= options.phase2_3ExcitationRelativeTolerance && ...
        rawRcondRelative <= options.phase2_3RcondRelativeTolerance && ...
        scaledRcondRelative <= options.phase2_3RcondRelativeTolerance && ...
        frozenGate.reviewerBlockers == 0;
    regression = struct('status', pass_fail(pass), ...
        'currentExcitation', currentExcitation, ...
        'frozenExcitation', frozenExcitation, ...
        'excitationRelativeDifference', excitationRelative, ...
        'excitationTolerance', options.phase2_3ExcitationRelativeTolerance, ...
        'currentRawRcond', current.raw_rcond, ...
        'frozenRawRcond', frozen.conditioning.rawRcondEstimate, ...
        'rawRcondRelativeDifference', rawRcondRelative, ...
        'rawRcondTolerance', options.phase2_3RcondRelativeTolerance, ...
        'currentScaledRcond', current.scaled_rcond, ...
        'frozenScaledRcond', frozen.conditioning.scaledRcondEstimate, ...
        'scaledRcondRelativeDifference', scaledRcondRelative, ...
        'scaledRcondTolerance', options.phase2_3RcondRelativeTolerance, ...
        'currentPanelCount', current.bem_unknown_count, ...
        'frozenPanelCount', frozen.panelCount, ...
        'currentFarfieldPanelCount', current.farfield_panel_count, ...
        'frozenFarfieldPanelCount', frozen.farfieldPanelCount, ...
        'reviewerBlockers', frozenGate.reviewerBlockers);
end

function write_phase2_3_regression_csv(regression, artifactDirectory)
% WRITE_PHASE2_3_REGRESSION_CSV Persist every frozen comparison explicitly.

    metric = ["F3_complex"; "raw_rcond"; "scaled_rcond"; ...
        "bem_unknown_count"; "farfield_panel_count"];
    currentReal = [real(regression.currentExcitation); ...
        regression.currentRawRcond; regression.currentScaledRcond; ...
        regression.currentPanelCount; regression.currentFarfieldPanelCount];
    currentImag = [imag(regression.currentExcitation); 0; 0; 0; 0];
    frozenReal = [real(regression.frozenExcitation); ...
        regression.frozenRawRcond; regression.frozenScaledRcond; ...
        regression.frozenPanelCount; regression.frozenFarfieldPanelCount];
    frozenImag = [imag(regression.frozenExcitation); 0; 0; 0; 0];
    absoluteDifference = abs(complex(currentReal, currentImag) - ...
        complex(frozenReal, frozenImag));
    relativeDifference = [regression.excitationRelativeDifference; ...
        regression.rawRcondRelativeDifference; ...
        regression.scaledRcondRelativeDifference; ...
        double(regression.currentPanelCount ~= regression.frozenPanelCount); ...
        double(regression.currentFarfieldPanelCount ~= ...
        regression.frozenFarfieldPanelCount)];
    tolerance = [regression.excitationTolerance; ...
        regression.rawRcondTolerance; regression.scaledRcondTolerance; 0; 0];
    gatePass = relativeDifference <= tolerance;
    tableOut = table(metric, currentReal, currentImag, frozenReal, ...
        frozenImag, absoluteDifference, relativeDifference, tolerance, ...
        gatePass);
    writetable(tableOut, fullfile(artifactDirectory, ...
        'Phase3_1_Frozen_Regression_Relative_Differences.csv'));
end

function frequencies = select_radius_screening_frequencies(formalTable, curveAudit)
% SELECT_RADIUS_SCREENING_FREQUENCIES Include extrema and curve outliers.

    solved = formalTable.status == "PASS";
    assert(all(solved), 'CRESTU:Phase31RadiusRequiresFormalPass', ...
        'Radius screening requires every formal frequency to solve first.');
    [~, peakIndex] = max(formalTable.RAO3_abs_m_per_m);
    [~, middleIndex] = min(abs(formalTable.omega_rad_s - ...
        median(formalTable.omega_rad_s)));
    [~, omega0p6Index] = min(abs(formalTable.omega_rad_s - 0.6));
    failedCurveRows = ~curveAudit.gatePass;
    suspectFrequencies = curveAudit.omegaAtMaximumInteriorDeviation( ...
        failedCurveRows);
    suspectIndices = zeros(size(suspectFrequencies));
    for suspectIndex = 1:numel(suspectFrequencies)
        [~, suspectIndices(suspectIndex)] = min(abs( ...
            formalTable.omega_rad_s - suspectFrequencies(suspectIndex)));
    end
    indices = unique([1, omega0p6Index, middleIndex, peakIndex, ...
        height(formalTable), ...
        reshape(suspectIndices, 1, [])], 'stable');
    frequencies = sort(formalTable.omega_rad_s(indices)).'; % [rad/s]
end

function [records, gate] = run_radius_screening(screeningFrequencies, ...
        formalRecords, baselineCfg, formalCfg, paths, options, force, ...
        checkpointState)
% RUN_RADIUS_SCREENING Run exact origin-radius factors and adjacent changes.

    checkpoint = fullfile(paths.artifactDirectory, ...
        'Phase3_1_Radius_Checkpoint.mat');
    radiusCheckpointFingerprint = string(sha256_hash([ ...
        char(checkpointState.combinedSHA256), '|', ...
        jsonencode(reshape(screeningFrequencies, 1, []))]));
    factors = [1.0, 1.25, 1.5];
    records = repmat(empty_record(), 0, 1);
    formalOmega = [formalRecords.omega_rad_s];
    for frequencyIndex = 1:numel(screeningFrequencies)
        [~, formalIndex] = min(abs(formalOmega - screeningFrequencies(frequencyIndex)));
        baselineRecord = formalRecords(formalIndex);
        baselineRecord.radius_factor = 1.0;
        records(end + 1, 1) = baselineRecord; %#ok<AGROW>
    end

    if ~force && isfile(checkpoint)
        loaded = load(checkpoint, 'radiusRecords', 'checkpointFingerprint');
        fingerprintMatch = isfield(loaded, 'checkpointFingerprint') && ...
            string(loaded.checkpointFingerprint) == ...
            radiusCheckpointFingerprint;
        if isfield(loaded, 'radiusRecords') && fingerprintMatch
            records = merge_pass_radius_records(records, loaded.radiusRecords);
        else
            fprintf(['[WARN] CHECKPOINT_REUSE = FORBIDDEN | radius source/', ...
                'config/geometry/frequency/runner fingerprint mismatch.\n']);
        end
    end

    for factorIndex = 2:numel(factors)
        records = run_radius_factor(records, screeningFrequencies, ...
            factors(factorIndex), formalRecords, baselineCfg, formalCfg, ...
            options, force);
        checkpointPayload = struct('radiusRecords', records, ...
            'screeningFrequencies', screeningFrequencies, ...
            'checkpointFingerprint', radiusCheckpointFingerprint, ...
            'checkpointManifest', checkpointState.manifest);
        save(checkpoint, '-struct', 'checkpointPayload');
    end
    records = calculate_radius_sensitivities(records, formalRecords, options);
    lastPass = final_radius_step_pass(records, factors(end), ...
        options.radiusRelativeTolerance);

    if ~lastPass
        fprintf(['[WARN] R->1.25R->1.5R did not meet the %.3g relative ', ...
            'tolerance; running the conditional 2R screen.\n'], ...
            options.radiusRelativeTolerance);
        records = run_radius_factor(records, screeningFrequencies, 2.0, ...
            formalRecords, baselineCfg, formalCfg, options, force);
        records = calculate_radius_sensitivities(records, formalRecords, options);
        checkpointPayload = struct('radiusRecords', records, ...
            'screeningFrequencies', screeningFrequencies, ...
            'checkpointFingerprint', radiusCheckpointFingerprint, ...
            'checkpointManifest', checkpointState.manifest);
        save(checkpoint, '-struct', 'checkpointPayload');
        lastPass = final_radius_step_pass(records, 2.0, ...
            options.radiusRelativeTolerance);
    end

    allSolved = all([records.status] == "PASS");
    if allSolved && lastPass
        status = "PASS";
    elseif allSolved
        status = "PARTIAL";
    else
        status = "FAIL";
    end
    lastFactor = max([records.radius_factor]);
    lastRows = [records.radius_factor] == lastFactor;
    finalStepSensitivities = [[records(lastRows).A33_relative_sensitivity], ...
        [records(lastRows).B33_relative_sensitivity], ...
        [records(lastRows).F3_relative_sensitivity], ...
        [records(lastRows).RAO3_relative_sensitivity]];
    comparisonRows = [records.radius_factor] > 1.0;
    allStepSensitivities = [[records(comparisonRows).A33_relative_sensitivity], ...
        [records(comparisonRows).B33_relative_sensitivity], ...
        [records(comparisonRows).F3_relative_sensitivity], ...
        [records(comparisonRows).RAO3_relative_sensitivity]];
    gate = struct('status', char(status), 'allCasesSolved', allSolved, ...
        'screeningOnly', true, 'testedFactors', unique([records.radius_factor]), ...
        'finalFactor', lastFactor, 'maximumRadiusSensitivity', ...
        max(allStepSensitivities, [], 'omitnan'), ...
        'maximumFinalStepRadiusSensitivity', ...
        max(finalStepSensitivities, [], 'omitnan'), ...
        'relativeTolerance', options.radiusRelativeTolerance, ...
        'adoptedOuterRadius', adopted_radius(status, lastFactor));
end

function records = run_radius_factor(records, screeningFrequencies, factor, ...
        formalRecords, baselineCfg, formalCfg, options, force)
% RUN_RADIUS_FACTOR Apply an exact physical top/bottom origin-radius factor.

    formalOmega = [formalRecords.omega_rad_s];
    for frequencyIndex = 1:numel(screeningFrequencies)
        omega = screeningFrequencies(frequencyIndex); % [rad/s]
        existing = abs([records.omega_rad_s] - omega) <= 64 * eps(max(1, omega)) & ...
            abs([records.radius_factor] - factor) <= 64 * eps(factor);
        if ~force && any(existing & [records.status] == "PASS")
            continue
        end
        [~, baselineIndex] = min(abs(formalOmega - omega));
        baseline = formalRecords(baselineIndex);
        wavelength = 2 * pi / baseline.physical_k_per_m; % [m]
        innerRadius = baselineCfg.fs.r_inner; % [m]
        targetTopRadius = factor * baseline.top_radius_m; % [m]
        targetBottomRadius = factor * baseline.bottom_radius_m; % [m]
        qTop = (targetTopRadius - innerRadius) / wavelength;
        qBottom = (targetBottomRadius - innerRadius) / wavelength;
        fprintf(['[INFO] Phase 3.1 radius screen | omega=%.6g rad/s ', ...
            '| factor=%.3g | q=(%.6g,%.6g)\n'], ...
            omega, factor, qTop, qBottom);
        current = run_one_production_case(omega, factor, qTop, qBottom, ...
            baselineCfg, formalCfg, options);
        if any(existing)
            records(find(existing, 1)) = current;
        else
            records(end + 1, 1) = current; %#ok<AGROW>
        end
    end
end

function merged = merge_pass_radius_records(baseline, checkpoint)
% MERGE_PASS_RADIUS_RECORDS Reuse only successful matching radius cases.

    merged = baseline;
    for index = 1:numel(checkpoint)
        candidate = checkpoint(index);
        if candidate.status ~= "PASS"
            continue
        end
        matching = abs([merged.omega_rad_s] - candidate.omega_rad_s) <= ...
            64 * eps(max(1, candidate.omega_rad_s)) & ...
            abs([merged.radius_factor] - candidate.radius_factor) <= ...
            64 * eps(max(1, candidate.radius_factor));
        if any(matching)
            merged(find(matching, 1)) = candidate;
        else
            merged(end + 1, 1) = candidate; %#ok<AGROW>
        end
    end
end

function records = calculate_radius_sensitivities(records, formalRecords, options)
% CALCULATE_RADIUS_SENSITIVITIES Compare adjacent radii with stable floors.

    AScale = max(abs([formalRecords.A33_kg]), [], 'omitnan');
    BScale = max(abs([formalRecords.B33_kg_s]), [], 'omitnan');
    FScale = max(abs(complex([formalRecords.F3_real_N_per_m], ...
        [formalRecords.F3_imag_N_per_m])), [], 'omitnan');
    RScale = max(abs(complex([formalRecords.RAO3_real_m_per_m], ...
        [formalRecords.RAO3_imag_m_per_m])), [], 'omitnan');
    floors = max(options.responseFloorFraction * [AScale, BScale, FScale, RScale], eps);
    frequencies = unique([records.omega_rad_s]);

    for frequencyIndex = 1:numel(frequencies)
        rows = find(abs([records.omega_rad_s] - frequencies(frequencyIndex)) <= ...
            64 * eps(max(1, frequencies(frequencyIndex))));
        [~, order] = sort([records(rows).radius_factor]);
        rows = rows(order);
        for localIndex = 2:numel(rows)
            previous = records(rows(localIndex - 1));
            currentIndex = rows(localIndex);
            current = records(currentIndex);
            [records(currentIndex).A33_absolute_difference_kg, ...
                records(currentIndex).A33_relative_sensitivity] = ...
                sensitivity(current.A33_kg, previous.A33_kg, floors(1));
            [records(currentIndex).B33_absolute_difference_kg_s, ...
                records(currentIndex).B33_relative_sensitivity] = ...
                sensitivity(current.B33_kg_s, previous.B33_kg_s, floors(2));
            currentF = complex(current.F3_real_N_per_m, current.F3_imag_N_per_m);
            previousF = complex(previous.F3_real_N_per_m, previous.F3_imag_N_per_m);
            [records(currentIndex).F3_absolute_difference_N_per_m, ...
                records(currentIndex).F3_relative_sensitivity] = ...
                sensitivity(currentF, previousF, floors(3));
            currentR = complex(current.RAO3_real_m_per_m, current.RAO3_imag_m_per_m);
            previousR = complex(previous.RAO3_real_m_per_m, previous.RAO3_imag_m_per_m);
            [records(currentIndex).RAO3_absolute_difference_m_per_m, ...
                records(currentIndex).RAO3_relative_sensitivity] = ...
                sensitivity(currentR, previousR, floors(4));
            records(currentIndex).A33_floor_kg = floors(1);
            records(currentIndex).B33_floor_kg_s = floors(2);
            records(currentIndex).F3_floor_N_per_m = floors(3);
            records(currentIndex).RAO3_floor_m_per_m = floors(4);
        end
    end
end

function [absoluteDifference, relativeDifference] = sensitivity(current, previous, floorValue)
% SENSITIVITY Evaluate the requested absolute and floored relative change.

    absoluteDifference = abs(current - previous);
    relativeDifference = absoluteDifference / max(abs(current), floorValue);
end

function pass = final_radius_step_pass(records, factor, tolerance)
% FINAL_RADIUS_STEP_PASS Require every screened output at the last factor.

    rows = [records.radius_factor] == factor;
    if ~any(rows) || any([records(rows).status] ~= "PASS")
        pass = false;
        return
    end
    values = [[records(rows).A33_relative_sensitivity], ...
        [records(rows).B33_relative_sensitivity], ...
        [records(rows).F3_relative_sensitivity], ...
        [records(rows).RAO3_relative_sensitivity]];
    pass = all(isfinite(values)) && max(values) <= tolerance;
end

function make_formal_figures(tableIn, artifactDirectory)
% MAKE_FORMAL_FIGURES Export response and algebraic-stability curves.

    figureHandle = figure('Visible', 'off', 'Color', 'w', ...
        'Position', [100, 100, 1400, 900]);
    cleanup = onCleanup(@() close(figureHandle));
    layout = tiledlayout(2, 2, 'TileSpacing', 'compact');
    plot(nexttile(layout), tableIn.omega_rad_s, tableIn.A33_kg, 'o-', ...
        'LineWidth', 1.2); ylabel('A_{33} [kg]'); grid on
    plot(nexttile(layout), tableIn.omega_rad_s, tableIn.B33_kg_s, 'o-', ...
        'LineWidth', 1.2); ylabel('B_{33} [kg/s]'); grid on
    plot(nexttile(layout), tableIn.omega_rad_s, tableIn.F3_abs_N_per_m, 'o-', ...
        'LineWidth', 1.2); ylabel('|F_3| [N/m]'); grid on
    plot(nexttile(layout), tableIn.omega_rad_s, tableIn.RAO3_abs_m_per_m, 'o-', ...
        'LineWidth', 1.2); ylabel('|RAO_3| [m/m]'); grid on
    xlabel(layout, '\omega [rad/s]'); title(layout, 'Formal P\_FULL response sweep');
    exportgraphics(figureHandle, fullfile(artifactDirectory, ...
        'Phase3_1_Formal_Response_Curves.png'), 'Resolution', 200);
    clear cleanup

    figureHandle = figure('Visible', 'off', 'Color', 'w', ...
        'Position', [100, 100, 1400, 650]);
    cleanup = onCleanup(@() close(figureHandle));
    layout = tiledlayout(1, 2, 'TileSpacing', 'compact');
    semilogy(nexttile(layout), tableIn.omega_rad_s, tableIn.raw_rcond, 'o-', ...
        tableIn.omega_rad_s, tableIn.scaled_rcond, 's-', 'LineWidth', 1.2);
    legend('raw rcond', 'scaled rcond', 'Location', 'best'); grid on
    xlabel('\omega [rad/s]'); ylabel('reciprocal condition estimate');
    residual = max([tableIn.radiation_linear_relative_residual, ...
        tableIn.diffraction_linear_relative_residual, ...
        tableIn.radiation_algebraic_relative_residual, ...
        tableIn.diffraction_algebraic_relative_residual], [], 2);
    semilogy(nexttile(layout), tableIn.omega_rad_s, residual, 'o-', ...
        'LineWidth', 1.2); grid on
    xlabel('\omega [rad/s]'); ylabel('maximum relative residual');
    title(layout, 'P\_FULL conditioning and algebraic residuals');
    exportgraphics(figureHandle, fullfile(artifactDirectory, ...
        'Phase3_1_Condition_Residual_Curves.png'), 'Resolution', 200);
    clear cleanup
end

function make_radius_figures(tableIn, artifactDirectory)
% MAKE_RADIUS_FIGURES Export physical outputs and adjacent sensitivities.

    frequencies = unique(tableIn.omega_rad_s);
    figureHandle = figure('Visible', 'off', 'Color', 'w', ...
        'Position', [100, 100, 1500, 950]);
    cleanup = onCleanup(@() close(figureHandle));
    layout = tiledlayout(2, 2, 'TileSpacing', 'compact');
    axesList = [nexttile(layout), nexttile(layout), ...
        nexttile(layout), nexttile(layout)];
    fields = {'A33_kg', 'B33_kg_s', 'F3_abs_N_per_m', 'RAO3_abs_m_per_m'};
    labels = {'A_{33} [kg]', 'B_{33} [kg/s]', '|F_3| [N/m]', '|RAO_3| [m/m]'};
    for frequencyIndex = 1:numel(frequencies)
        rows = tableIn.omega_rad_s == frequencies(frequencyIndex);
        [factor, order] = sort(tableIn.radius_factor(rows));
        subset = tableIn(rows, :);
        for axesIndex = 1:numel(axesList)
            plot(axesList(axesIndex), factor, subset.(fields{axesIndex})(order), ...
                'o-', 'LineWidth', 1.2, 'DisplayName', ...
                sprintf('\\omega=%.3g', frequencies(frequencyIndex)));
            hold(axesList(axesIndex), 'on'); grid(axesList(axesIndex), 'on');
        end
    end
    for axesIndex = 1:numel(axesList)
        xlabel(axesList(axesIndex), 'physical outer-radius factor');
        ylabel(axesList(axesIndex), labels{axesIndex});
        legend(axesList(axesIndex), 'Location', 'best');
    end
    title(layout, 'Full-BEM outer-radius screening');
    exportgraphics(figureHandle, fullfile(artifactDirectory, ...
        'Phase3_1_Outer_Radius_Response.png'), 'Resolution', 200);
    clear cleanup
end

function write_validation_report(summary, sourceTable, paths, options)
% WRITE_VALIDATION_REPORT Write the formal Phase 3.1 interpretation.

    formal = summary.formalGate;
    radius = summary.radiusGate;
    regression = summary.phase2_3Regression;
    algebraicPass = formal.allFrequenciesSolved && formal.conditionPass && ...
        formal.residualPass && strcmp(regression.status, 'PASS');
    algebraicStatus = pass_fail(algebraicPass);
    reportFile = fullfile(paths.artifactDirectory, ...
        'PHASE3_1_FORMAL_PFULL_VALIDATION.md');
    fileId = fopen(reportFile, 'w');
    assert(fileId >= 0, 'CRESTU:Phase31ReportOpen', ...
        'Cannot create Phase 3.1 report.');
    cleanup = onCleanup(@() fclose(fileId));

    fprintf(fileId, '# Phase 3.1 formal P_FULL validation\n\n');
    fprintf(fileId, '## Final gates\n\n```text\n');
    fprintf(fileId, 'PHASE2_3_BASELINE_REGRESSION = %s\n', regression.status);
    fprintf(fileId, 'ABC_NORMAL_LINEAGE = PASS\n');
    fprintf(fileId, 'PRODUCTION_ABC_UNCHANGED = YES\n');
    fprintf(fileId, 'P_FULL_ASSEMBLY = %s\n', algebraicStatus);
    fprintf(fileId, 'FORMAL_FREQUENCY_SWEEP = %s\n', formal.status);
    fprintf(fileId, 'ALL_FREQUENCIES_SOLVED = %s\n', ...
        yes_no(formal.allFrequenciesSolved));
    fprintf(fileId, 'MIN_RAW_RCOND = %.16g\n', formal.minimumRawRcond);
    fprintf(fileId, 'MIN_SCALED_RCOND = %.16g\n', formal.minimumScaledRcond);
    fprintf(fileId, 'MAX_RELATIVE_RESIDUAL = %.16g\n\n', ...
        formal.maximumRelativeResidual);
    fprintf(fileId, 'OUTER_RADIUS_CONVERGENCE = %s\n', radius.status);
    fprintf(fileId, 'ADOPTED_OUTER_RADIUS = %s\n', radius.adoptedOuterRadius);
    fprintf(fileId, 'MAX_RADIUS_SENSITIVITY = %.16g\n', ...
        radius.maximumRadiusSensitivity);
    fprintf(fileId, 'MAX_FINAL_RADIUS_SENSITIVITY = %.16g\n\n', ...
        radius.maximumFinalStepRadiusSensitivity);
    fprintf(fileId, 'PRODUCTION_ABC_CHANGED = NO\n');
    fprintf(fileId, 'PRODUCTION_MESH_TOPOLOGY_CHANGED = NO\n');
    fprintf(fileId, 'REVIEWER_BLOCKERS = %d\n', regression.reviewerBlockers);
    ready = formal.status == "PASS" && radius.status == "PASS" && ...
        regression.status == "PASS";
    fprintf(fileId, 'READY_FOR_PHASE3_2_MESH_CONVERGENCE = %s\n', yes_no(ready));
    fprintf(fileId, '```\n\n');

    fprintf(fileId, '## Scope and authority\n\n');
    fprintf(fileId, ['The authoritative frequency list is read from `%s`: ', ...
        '16 angular frequencies from 0.5 to 2.0 rad/s. The mesh baseline ', ...
        'is the frozen Fine P_FULL Phase 2.3 frustum (`q_top=2.0`, ', ...
        '`q_bottom=1.5`, body/FS radial/wall controls unchanged).\n\n'], ...
        paths.formalFrequencyConfig);
    fprintf(fileId, ['Each point was run through `run_frequency_domain_case` ', ...
        'as an isolated clean production solve. RAW_DIAGNOSTICS was enabled ', ...
        'only to expose the existing raw/scaled BEM condition estimates and ', ...
        'algebraic residual records; full solved potentials were not persisted.\n\n']);
    fprintf(fileId, ['The current run does not modify body resolution, the ', ...
        'FS/bottom/FARFIELD density strategy, production ABC source, WAMIT ', ...
        'reference data, or Phase 2.3 artifacts.\n\n']);

    fprintf(fileId, '## Formal sweep interpretation\n\n');
    fprintf(fileId, ['All-frequency solve status: **%s**. Condition gate: ', ...
        '**%s**; residual gate: **%s**; curve-continuity gate: **%s**. ', ...
        'The formal thresholds were rcond >= %.3g, residual <= %.3g, ', ...
        'isolated curve deviation <= %.3g, and non-negligible complex ', ...
        'phase step <= %.1f deg.\n\n'], ...
        yes_no(formal.allFrequenciesSolved), pass_fail(formal.conditionPass), ...
        pass_fail(formal.residualPass), pass_fail(formal.continuityPass), ...
        options.minimumRcond, options.maximumRelativeResidual, ...
        options.maximumCurveInteriorDeviation, options.maximumPhaseStepDeg);
    fprintf(fileId, ['The machine-readable response, condition/residual, and ', ...
        'continuity records are `Phase3_1_Formal_PFull_Frequency_Sweep.csv`, ', ...
        '`Phase3_1_Condition_Residual.csv`, and ', ...
        '`Phase3_1_Response_Continuity_Audit.csv`.\n\n']);
    failedAudit = summary.curveAudit(~summary.curveAudit.gatePass, :);
    if ~isempty(failedAudit)
        fprintf(fileId, ['Continuity blockers are listed below. These are ', ...
            'frequency-response findings, not ABC regressions:\n\n']);
        for auditIndex = 1:height(failedAudit)
            fprintf(fileId, '- `%s`: deviation %.6g at omega=%.6g rad/s.\n', ...
                failedAudit.metricName(auditIndex), ...
                failedAudit.maximumInteriorDeviation(auditIndex), ...
                failedAudit.omegaAtMaximumInteriorDeviation(auditIndex));
        end
        fprintf(fileId, ['\nThe added omega=0.6 radius screen met the 0.02 ', ...
            'outer-radius gate, so the A33/B33 anomaly remains unresolved but ', ...
            'is not identified as a dominant outer-boundary truncation effect.\n\n']);
    end
    adjudicatedAudit = summary.curveAudit( ...
        ~summary.curveAudit.preliminaryGatePass & ...
        summary.curveAudit.gatePass, :);
    if ~isempty(adjudicatedAudit)
        fprintf(fileId, ['The following coarse-grid curvature flags were ', ...
            'resolved only by independent Phase 3.1B dense production ', ...
            'evidence; the original coarse values are retained in the CSV:\n\n']);
        for auditIndex = 1:height(adjudicatedAudit)
            fprintf(fileId, ['- `%s` at omega=%.6g rad/s: dense metric ', ...
                '%.6g <= %.6g; %s\n'], ...
                adjudicatedAudit.metricName(auditIndex), ...
                adjudicatedAudit.omegaAtMaximumInteriorDeviation(auditIndex), ...
                adjudicatedAudit.denseEvidenceValue(auditIndex), ...
                adjudicatedAudit.denseEvidenceThreshold(auditIndex), ...
                adjudicatedAudit.adjudicationNote(auditIndex));
        end
        fprintf(fileId, ['\nNo phase threshold, coefficient tolerance, or ', ...
            'production response value was relaxed or smoothed.\n\n']);
    end

    fprintf(fileId, '## Full-BEM outer-radius convergence\n\n');
    fprintf(fileId, ['This is a full BEM solution study, distinct from the ', ...
        'Phase 2.3 analytic Hankel coefficient scaling. Low/mid/high, ', ...
        'formal-response-peak, and failed continuity-audit frequencies were ', ...
        'screened. For each frequency, the Phase 2.3 top and bottom radii ', ...
        'were multiplied about the global ', ...
        'origin by factors R, 1.25R, and 1.5R. The per-frequency q values were ', ...
        'derived exactly from `q=(factor*R_baseline-r_inner)/lambda`; 2R was ', ...
        'run only if the third level did not meet the predeclared %.3g gate.\n\n'], ...
        options.radiusRelativeTolerance);
    fprintf(fileId, ['Changing radius necessarily adds/re-tessellates only ', ...
        'the outer FS/bottom annuli and FARFIELD wall so that the frozen local ', ...
        'spacing rules remain active. That derived count/hash change is the ', ...
        'intended radius variable, not Phase 3.2 coordinated mesh convergence.\n\n']);
    fprintf(fileId, ['Relative sensitivities use ', ...
        '`|Q(R2)-Q(R1)|/max(|Q(R2)|,Q_floor)` with ', ...
        '`Q_floor=max(1e-6*formal_curve_scale,eps)`; absolute differences and ', ...
        'the actual floor values are saved beside every comparison. ', ...
        '`MAX_RADIUS_SENSITIVITY` covers all adjacent comparisons; the ', ...
        'predeclared 0.02 convergence gate is applied to the final adjacent ', ...
        'step reported as `MAX_FINAL_RADIUS_SENSITIVITY`.\n\n']);

    fprintf(fileId, '## Error classification\n\n');
    fprintf(fileId, ['1. **Algebraic / implementation error:** assessed by ', ...
        'finite solves, BEM raw/scaled rcond, linear/algebraic residuals, the ', ...
        'production one-column `D+gamma*S` oracle, source hashes, and the ', ...
        'omega=1.5 frozen regression. Status: **%s**.\n'], algebraicStatus);
    fprintf(fileId, ['2. **Outer-boundary truncation error:** assessed only ', ...
        'from the full-BEM radius sensitivity table. Status: **%s** within ', ...
        'the representative screening set.\n'], radius.status);
    fprintf(fileId, ['3. **Physical/model discrepancy:** not closed here. ', ...
        'No WAMIT comparison was changed or used to tune the result. Any later ', ...
        'reference discrepancy must still retain Rankine-panel integration, ', ...
        'body/FS discretization, and source formulation as candidate causes.\n\n']);

    fprintf(fileId, '## Validation and file audit\n\n```text\n');
    fprintf(fileId, 'IMPLEMENTED = YES\n');
    fprintf(fileId, 'COMPILED = N/A\n');
    fprintf(fileId, 'RUNTIME_TESTED = YES (MATLAB R2023b Update 10)\n');
    fprintf(fileId, 'REGRESSION_PASS = %s\n', regression.status);
    fprintf(fileId, 'PHYSICAL_VALIDATION = PARTIAL\n');
    fprintf(fileId, 'READY_FOR_PRODUCTION = NO\n');
    fprintf(fileId, '```\n\n');
    fprintf(fileId, ['Production dependency hashes were captured before and ', ...
        'after the run; all %d files were unchanged. Only the formal ', ...
        '`Phase3_1_Artifacts` runner, CSVs, figures, checkpoint/result MAT ', ...
        'files, source snapshots, and this report were added. Temporary ', ...
        'per-case configs/BMFs/caches/results were created under the OS ', ...
        'temporary directory and removed after extraction. No file was deleted ', ...
        'from the repository.\n'], height(sourceTable));
    clear cleanup
end

function record = empty_record()
% EMPTY_RECORD Define a stable machine-readable schema for every run.

    record = struct( ...
        'omega_rad_s', NaN, 'radius_factor', NaN, 'q_top', NaN, ...
        'q_bottom', NaN, 'top_radius_m', NaN, 'bottom_radius_m', NaN, ...
        'physical_k_per_m', NaN, 'kappa_real_per_m', NaN, ...
        'kappa_imag_per_m', NaN, 'kR_top', NaN, 'kR_bottom', NaN, ...
        'abs_kappa_R_top', NaN, 'raw_rcond', NaN, 'scaled_rcond', NaN, ...
        'radiation_linear_relative_residual', NaN, ...
        'diffraction_linear_relative_residual', NaN, ...
        'radiation_algebraic_relative_residual', NaN, ...
        'diffraction_algebraic_relative_residual', NaN, ...
        'maximum_abs_outer_ntheta', NaN, ...
        'maximum_outer_column_residual', NaN, ...
        'A33_raw_kg', NaN, 'A33_kg', NaN, 'B33_raw_kg_s', NaN, ...
        'B33_kg_s', NaN, 'F3_real_N_per_m', NaN, ...
        'F3_imag_N_per_m', NaN, 'F3_abs_N_per_m', NaN, ...
        'F3_phase_deg', NaN, 'RAO3_real_m_per_m', NaN, ...
        'RAO3_imag_m_per_m', NaN, 'RAO3_abs_m_per_m', NaN, ...
        'RAO3_phase_deg', NaN, 'RAO_matrix_rcond', NaN, ...
        'body_panel_count', NaN, 'free_surface_panel_count', NaN, ...
        'bottom_panel_count', NaN, 'farfield_panel_count', NaN, ...
        'bem_unknown_count', NaN, 'body_geometry_hash', "", ...
        'free_surface_geometry_hash', "", 'bottom_geometry_hash', "", ...
        'farfield_geometry_hash', "", 'combined_geometry_hash', "", ...
        'legacy_theta_count', NaN, 'top_theta_count', NaN, ...
        'bottom_theta_count', NaN, 'common_wall_theta_count', NaN, ...
        'top_radial_layer_count', NaN, ...
        'bottom_radial_layer_count', NaN, ...
        'wall_vertical_layer_count', NaN, ...
        'top_theta_spacing_m', NaN, 'bottom_theta_spacing_m', NaN, ...
        'top_radial_spacing_m', NaN, 'bottom_radial_spacing_m', NaN, ...
        'wall_slant_spacing_m', NaN, ...
        'assembly_runtime_s', NaN, ...
        'total_runtime_s', NaN, 'A33_absolute_difference_kg', NaN, ...
        'A33_relative_sensitivity', NaN, ...
        'B33_absolute_difference_kg_s', NaN, ...
        'B33_relative_sensitivity', NaN, ...
        'F3_absolute_difference_N_per_m', NaN, ...
        'F3_relative_sensitivity', NaN, ...
        'RAO3_absolute_difference_m_per_m', NaN, ...
        'RAO3_relative_sensitivity', NaN, 'A33_floor_kg', NaN, ...
        'B33_floor_kg_s', NaN, 'F3_floor_N_per_m', NaN, ...
        'RAO3_floor_m_per_m', NaN, 'status', "PENDING", ...
        'error_identifier', "", 'error_message', "");
end

function remove_runtime_directory(folder)
% REMOVE_RUNTIME_DIRECTORY Remove only the exact OS-temp directory created here.

    if isfolder(folder) && startsWith(lower(folder), lower(tempdir))
        try
            rmdir(folder, 's');
        catch exception
            warning('CRESTU:Phase31RuntimeCleanup', ...
                'Could not remove runtime directory %s: %s', ...
                folder, exception.message);
        end
    end
end

function label = adopted_radius(status, factor)
% ADOPTED_RADIUS Report a radius only after the adjacent-change gate passes.

    if status == "PASS"
        label = sprintf('%.3gR (representative-screening gate)', factor);
    else
        label = 'NOT_ADOPTED';
    end
end

function text = pass_fail(value)
% PASS_FAIL Convert a logical gate to an uppercase status.

    if value
        text = "PASS";
    else
        text = "FAIL";
    end
end

function text = yes_no(value)
% YES_NO Convert a logical gate to an uppercase status.

    if value
        text = "YES";
    else
        text = "NO";
    end
end
