function [manifest, qualityTable] = audit_domain( ...
        definition, specification, domain, generationRuntimeS)
% AUDIT_DOMAIN Measure component h, quality, topology, and fixed geometry.

    %% Stage 1: Fingerprint actual in-memory production meshes

    audit = audit_domain_meshes(domain);
    truncation = domain.cfg.outer_truncation.effective;
    assert(abs(truncation.effectiveTopRadiusM - ...
        specification.targetTopRadiusM) <= definition.gates.geometryToleranceM && ...
        abs(truncation.effectiveBottomRadiusM - ...
        specification.targetBottomRadiusM) <= definition.gates.geometryToleranceM, ...
        'CRESTU:Phase32OuterExtent', ...
        'Actual outer extent differs from the frozen 1.5R target.');

    components = {domain.body_list{1}, domain.fs, ...
        domain.seabed, domain.farfield};
    componentNames = ["body"; "free_surface"; "bottom"; "farfield"];
    qualityRows = repmat(empty_quality_row(), numel(components), 1);
    for componentIndex = 1:numel(components)
        qualityRows(componentIndex) = component_quality( ...
            definition, specification, components{componentIndex}, ...
            componentNames(componentIndex));
    end
    qualityTable = struct2table(qualityRows);

    %% Stage 2: Audit transitions, closed edges, normals, and interfaces

    [transitionMeanH, transitionMedianH, transitionPanelCount] = ...
        transition_spacing(domain, truncation);
    topology = topology_audit(definition, domain);
    bodyQuality = qualityRows(1);
    fsQuality = qualityRows(2);
    bottomQuality = qualityRows(3);
    wallQuality = qualityRows(4);
    totalAreaM2 = sum(domain.geometry.areas);
    totalPanelCount = domain.geometry.total_panels;
    globalEquivalentH = sqrt(totalAreaM2 / totalPanelCount);
    geometryPass = all([qualityRows.component_gate_pass]) && ...
        topology.manifoldPass && topology.orientationPass && ...
        topology.interfaceContinuityPass && topology.selfIntersectionPass && ...
        topology.duplicatePanelCount == 0;

    %% Stage 3: Build the one-row mesh manifest

    level = specification.level;
    sourceVersion = get_rankine_code_version();
    manifest = struct( ...
        'stage', specification.stage, ...
        'mesh_level', level.name, ...
        'mesh_level_index', level.index, ...
        'nested_mesh', "NO", ...
        'eta_control', level.eta, ...
        'omega_rad_s', specification.omegaRadPerS, ...
        'wavelength_m', specification.wavelengthM, ...
        'body_division_count', level.bodyDivision, ...
        'fs_near_radial_count', level.fsRadialCounts(1), ...
        'fs_sponge_radial_count', level.fsRadialCounts(2), ...
        'bottom_near_radial_count', level.bottomRadialCounts(1), ...
        'bottom_sponge_radial_count', level.bottomRadialCounts(2), ...
        'configured_wall_vertical_count', level.wallVerticalCount, ...
        'configured_wall_theta_count', level.wallThetaCount, ...
        'configured_fs_theta_count', level.fsThetaCount, ...
        'configured_bottom_theta_count', level.bottomThetaCount, ...
        'actual_wall_vertical_layer_count', ...
            truncation.wallDerived.verticalLayerCount, ...
        'actual_wall_theta_count', truncation.commonOuterThetaNodeCount, ...
        'actual_fs_theta_count', truncation.topOuterThetaNodeCount, ...
        'actual_bottom_theta_count', truncation.bottomOuterThetaNodeCount, ...
        'body_panel_count', audit.body.panelCount, ...
        'free_surface_panel_count', audit.freeSurface.panelCount, ...
        'bottom_panel_count', audit.bottom.panelCount, ...
        'farfield_panel_count', audit.outerBoundary.panelCount, ...
        'total_panel_count', totalPanelCount, ...
        'body_mean_sqrt_area_m', bodyQuality.mean_sqrt_area_m, ...
        'body_median_sqrt_area_m', bodyQuality.median_sqrt_area_m, ...
        'fs_mean_sqrt_area_m', fsQuality.mean_sqrt_area_m, ...
        'fs_median_sqrt_area_m', fsQuality.median_sqrt_area_m, ...
        'bottom_mean_sqrt_area_m', bottomQuality.mean_sqrt_area_m, ...
        'bottom_median_sqrt_area_m', bottomQuality.median_sqrt_area_m, ...
        'wall_mean_sqrt_area_m', wallQuality.mean_sqrt_area_m, ...
        'wall_median_sqrt_area_m', wallQuality.median_sqrt_area_m, ...
        'transition_mean_sqrt_area_m', transitionMeanH, ...
        'transition_median_sqrt_area_m', transitionMedianH, ...
        'transition_panel_count', transitionPanelCount, ...
        'global_equivalent_h_m', globalEquivalentH, ...
        'minimum_panel_area_m2', min(domain.geometry.areas), ...
        'maximum_panel_area_m2', max(domain.geometry.areas), ...
        'median_panel_area_m2', median(domain.geometry.areas), ...
        'minimum_edge_length_m', min([qualityRows.minimum_edge_length_m]), ...
        'maximum_aspect_ratio', max([qualityRows.maximum_aspect_ratio]), ...
        'maximum_skewness_deg', max([qualityRows.maximum_skewness_deg]), ...
        'maximum_warp_deg', max([qualityRows.maximum_warp_deg]), ...
        'worst_poor_panel_fraction', ...
            max([qualityRows.poor_panel_fraction]), ...
        'unique_vertex_count', topology.uniqueVertexCount, ...
        'unique_edge_count', topology.uniqueEdgeCount, ...
        'minimum_edge_multiplicity', topology.minimumEdgeMultiplicity, ...
        'maximum_edge_multiplicity', topology.maximumEdgeMultiplicity, ...
        'nonmanifold_edge_count', topology.nonmanifoldEdgeCount, ...
        'duplicate_panel_count', topology.duplicatePanelCount, ...
        'triangle_duplicate_vertex_count', ...
            topology.triangleDuplicateVertexCount, ...
        'unexpected_within_panel_duplicate_vertex_count', ...
            topology.unexpectedWithinPanelDuplicateVertexCount, ...
        'euler_characteristic', topology.eulerCharacteristic, ...
        'manifold_status', pass_fail(topology.manifoldPass), ...
        'normal_orientation_status', pass_fail(topology.orientationPass), ...
        'waterline_continuity_status', ...
            pass_fail(topology.interfaceContinuityPass), ...
        'maximum_interface_gap_m', topology.maximumInterfaceGapM, ...
        'self_intersection_audit', topology.selfIntersectionAudit, ...
        'self_intersection_status', ...
            pass_fail(topology.selfIntersectionPass), ...
        'actual_top_outer_radius_m', truncation.effectiveTopRadiusM, ...
        'actual_bottom_outer_radius_m', truncation.effectiveBottomRadiusM, ...
        'target_top_outer_radius_m', specification.targetTopRadiusM, ...
        'target_bottom_outer_radius_m', specification.targetBottomRadiusM, ...
        'water_depth_m', domain.cfg.water_depth, ...
        'body_geometry_hash', string(audit.body.hash), ...
        'free_surface_geometry_hash', string(audit.freeSurface.hash), ...
        'bottom_geometry_hash', string(audit.bottom.hash), ...
        'farfield_geometry_hash', string(audit.outerBoundary.hash), ...
        'combined_geometry_hash', string(audit.geometry.hash), ...
        'operator_hash', "NOT_ASSEMBLED_MESH_AUDIT", ...
        'production_source_hash', string(sourceVersion.fingerprint), ...
        'physical_state_hash', specification.physicalHash, ...
        'mesh_control_hash', specification.controlHash, ...
        'config_raw_sha256', specification.configRawSHA256, ...
        'body_bmf_raw_sha256', specification.bodyFileRawSHA256, ...
        'mesh_generation_command', specification.meshGenerationCommand, ...
        'generation_runtime_s', generationRuntimeS, ...
        'geometry_gate_status', pass_fail(geometryPass));
end

function row = component_quality(definition, specification, mesh, name)
% COMPONENT_QUALITY Compute triangle-aware panel quality statistics.

    panelCount = mesh.n_panels;
    aspectRatio = zeros(panelCount, 1);
    skewnessDeg = zeros(panelCount, 1);
    minimumAngleDeg = zeros(panelCount, 1);
    maximumAngleDeg = zeros(panelCount, 1);
    warpDeg = zeros(panelCount, 1);
    minimumEdgeM = zeros(panelCount, 1);
    poor = false(panelCount, 1);
    for panelIndex = 1:panelCount
        vertices = reshape(mesh.vertices(panelIndex, :, :), 4, 3);
        if norm(vertices(4, :) - vertices(3, :)) <= ...
                definition.gates.minimumEdgeLengthM
            vertices = vertices(1:3, :);
        end
        vertexCount = size(vertices, 1);
        next = [2:vertexCount, 1];
        edges = vertices(next, :) - vertices;
        lengths = vecnorm(edges, 2, 2);
        minimumEdgeM(panelIndex) = min(lengths);
        aspectRatio(panelIndex) = max(lengths) / min(lengths);
        angles = zeros(vertexCount, 1);
        for vertexIndex = 1:vertexCount
            previousIndex = mod(vertexIndex - 2, vertexCount) + 1;
            incoming = vertices(previousIndex, :) - vertices(vertexIndex, :);
            outgoing = vertices(next(vertexIndex), :) - vertices(vertexIndex, :);
            cosine = dot(incoming, outgoing) / ...
                (norm(incoming) * norm(outgoing));
            angles(vertexIndex) = acosd(max(-1, min(1, cosine)));
        end
        minimumAngleDeg(panelIndex) = min(angles);
        maximumAngleDeg(panelIndex) = max(angles);
        skewnessDeg(panelIndex) = max(abs(angles - 90));
        if vertexCount == 4
            firstNormal = cross(edges(1, :), edges(2, :));
            secondNormal = cross(edges(3, :), edges(4, :));
            cosine = dot(firstNormal, secondNormal) / ...
                (norm(firstNormal) * norm(secondNormal));
            warpDeg(panelIndex) = acosd(max(-1, min(1, cosine)));
        end
        radiusM = hypot(mesh.centers(panelIndex, 1), ...
            mesh.centers(panelIndex, 2));
        if name == "body"
            aspectLimit = definition.gates.bodyMaximumAspectRatio;
        elseif name == "farfield" || radiusM > 20.0
            aspectLimit = definition.gates.outerMaximumAspectRatio;
        else
            aspectLimit = definition.gates.nearMaximumAspectRatio;
        end
        poor(panelIndex) = ...
            aspectRatio(panelIndex) > aspectLimit || ...
            skewnessDeg(panelIndex) > definition.gates.maximumSkewnessDeg || ...
            minimumAngleDeg(panelIndex) < ...
                definition.gates.minimumCornerAngleDeg || ...
            maximumAngleDeg(panelIndex) > ...
                definition.gates.maximumCornerAngleDeg || ...
            warpDeg(panelIndex) > definition.gates.maximumWarpDeg || ...
            minimumEdgeM(panelIndex) <= definition.gates.minimumEdgeLengthM;
    end
    poorFraction = nnz(poor) / panelCount;
    areas = reshape(mesh.areas, [], 1);
    finitePositive = all(isfinite(mesh.vertices), 'all') && ...
        all(isfinite(mesh.centers), 'all') && ...
        all(isfinite(mesh.normals), 'all') && ...
        all(isfinite(areas)) && all(areas > 0);
    pass = finitePositive && poorFraction <= ...
        definition.gates.maximumPoorPanelFraction;
    row = struct( ...
        'stage', specification.stage, ...
        'mesh_level', specification.level.name, ...
        'omega_rad_s', specification.omegaRadPerS, ...
        'component', name, 'panel_count', panelCount, ...
        'minimum_panel_area_m2', min(areas), ...
        'maximum_panel_area_m2', max(areas), ...
        'median_panel_area_m2', median(areas), ...
        'mean_sqrt_area_m', mean(sqrt(areas)), ...
        'median_sqrt_area_m', median(sqrt(areas)), ...
        'minimum_edge_length_m', min(minimumEdgeM), ...
        'maximum_aspect_ratio', max(aspectRatio), ...
        'maximum_skewness_deg', max(skewnessDeg), ...
        'minimum_corner_angle_deg', min(minimumAngleDeg), ...
        'maximum_corner_angle_deg', max(maximumAngleDeg), ...
        'maximum_warp_deg', max(warpDeg), ...
        'poor_panel_count', nnz(poor), ...
        'poor_panel_fraction', poorFraction, ...
        'finite_positive_geometry', finitePositive, ...
        'component_gate_pass', pass, ...
        'component_gate_status', pass_fail(pass));
end

function [meanH, medianH, panelCount] = transition_spacing(domain, truncation)
% TRANSITION_SPACING Measure panels that cross either transition radius.

    meshes = {domain.fs, domain.seabed};
    radiiToCheck = [domain.cfg.fs.r_inner, truncation.legacyRadiusM];
    areas = zeros(0, 1);
    for meshIndex = 1:numel(meshes)
        mesh = meshes{meshIndex};
        vertices = reshape(mesh.vertices, mesh.n_panels, 4, 3);
        vertexRadius = hypot(vertices(:, :, 1), vertices(:, :, 2));
        mask = false(mesh.n_panels, 1);
        for radiusIndex = 1:numel(radiiToCheck)
            radiusM = radiiToCheck(radiusIndex);
            mask = mask | (min(vertexRadius, [], 2) <= radiusM & ...
                max(vertexRadius, [], 2) >= radiusM);
        end
        areas = [areas; reshape(mesh.areas(mask), [], 1)]; %#ok<AGROW>
    end
    panelCount = numel(areas);
    assert(panelCount > 0, 'CRESTU:Phase32TransitionPanels', ...
        'No FS/bottom transition panel was identified.');
    meanH = mean(sqrt(areas));
    medianH = median(sqrt(areas));
end

function topology = topology_audit(definition, domain)
% TOPOLOGY_AUDIT Check closed edges and analytic component separation.

    toleranceM = definition.gates.geometryToleranceM;
    meshes = {domain.body_list{1}, domain.fs, ...
        domain.seabed, domain.farfield};
    allVertices = zeros(0, 3, 'int64');
    allEdges = zeros(0, 6, 'int64');
    panelKeys = strings(0, 1);
    triangleDuplicateCount = 0;
    unexpectedDuplicateCount = 0;
    totalFaces = 0;
    for meshIndex = 1:numel(meshes)
        mesh = meshes{meshIndex};
        totalFaces = totalFaces + mesh.n_panels;
        for panelIndex = 1:mesh.n_panels
            vertices = reshape(mesh.vertices(panelIndex, :, :), 4, 3);
            triangle = norm(vertices(4, :) - vertices(3, :)) <= toleranceM;
            if triangle
                vertices = vertices(1:3, :);
                triangleDuplicateCount = triangleDuplicateCount + 1;
            end
            quantized = int64(round(vertices / toleranceM));
            if size(unique(quantized, 'rows'), 1) ~= size(quantized, 1)
                unexpectedDuplicateCount = unexpectedDuplicateCount + 1;
            end
            allVertices = [allVertices; quantized]; %#ok<AGROW>
            vertexCount = size(quantized, 1);
            next = [2:vertexCount, 1];
            for edgeIndex = 1:vertexCount
                first = quantized(edgeIndex, :);
                second = quantized(next(edgeIndex), :);
                if lexicographically_greater(first, second)
                    temporary = first;
                    first = second;
                    second = temporary;
                end
                allEdges(end + 1, :) = [first, second]; %#ok<AGROW>
            end
            sortedVertices = sortrows(quantized);
            panelKeys(end + 1, 1) = string(sprintf('%d,', ...
                sortedVertices.')); %#ok<AGROW>
        end
    end
    uniqueVertices = unique(allVertices, 'rows');
    [uniqueEdges, ~, edgeMap] = unique(allEdges, 'rows');
    edgeMultiplicity = accumarray(edgeMap, 1);
    duplicatePanelCount = numel(panelKeys) - numel(unique(panelKeys));
    nonmanifoldEdgeCount = nnz(edgeMultiplicity ~= 2);
    eulerCharacteristic = size(uniqueVertices, 1) - ...
        size(uniqueEdges, 1) + totalFaces;
    manifoldPass = nonmanifoldEdgeCount == 0 && ...
        unexpectedDuplicateCount == 0 && eulerCharacteristic == 2;

    body = domain.body_list{1};
    bodyRadius = vecnorm(body.centers, 2, 2);
    bodyAlignment = sum(body.normals .* body.centers, 2) ./ bodyRadius;
    fsNormalPass = min(domain.fs.normals(:, 3)) >= 1 - 1.0e-10;
    bottomNormalPass = min(domain.seabed.normals(:, 3)) >= 1 - 1.0e-10;
    wallRadius = hypot(domain.farfield.centers(:, 1), ...
        domain.farfield.centers(:, 2));
    wallRadialNormal = (domain.farfield.normals(:, 1) .* ...
        domain.farfield.centers(:, 1) + domain.farfield.normals(:, 2) .* ...
        domain.farfield.centers(:, 2)) ./ wallRadius;
    orientationPass = min(bodyAlignment) > 0 && fsNormalPass && ...
        bottomNormalPass && max(wallRadialNormal) < 0;

    bodyVertices = unique(reshape(body.vertices, [], 3), 'rows');
    fsVertices = unique(reshape(domain.fs.vertices, [], 3), 'rows');
    bottomVertices = unique(reshape(domain.seabed.vertices, [], 3), 'rows');
    wallVertices = unique(reshape(domain.farfield.vertices, [], 3), 'rows');
    bodyWaterline = bodyVertices(abs(bodyVertices(:, 3)) <= toleranceM, :);
    fsRadius = hypot(fsVertices(:, 1), fsVertices(:, 2));
    fsInner = fsVertices(abs(fsRadius - min(fsRadius)) <= toleranceM, :);
    fsOuter = fsVertices(abs(fsVertices(:, 3)) <= toleranceM & ...
        abs(fsRadius - max(fsRadius)) <= toleranceM, :);
    bottomRadius = hypot(bottomVertices(:, 1), bottomVertices(:, 2));
    bottomOuter = bottomVertices(abs(bottomVertices(:, 3) + ...
        domain.cfg.water_depth) <= toleranceM & ...
        abs(bottomRadius - max(bottomRadius)) <= toleranceM, :);
    wallTop = wallVertices(abs(wallVertices(:, 3)) <= toleranceM, :);
    wallBottom = wallVertices(abs(wallVertices(:, 3) + ...
        domain.cfg.water_depth) <= toleranceM, :);
    gaps = [hausdorff_gap(bodyWaterline, fsInner), ...
        hausdorff_gap(fsOuter, wallTop), ...
        hausdorff_gap(bottomOuter, wallBottom)];
    maximumInterfaceGapM = max(gaps);
    interfacePass = all(isfinite(gaps)) && ...
        maximumInterfaceGapM <= toleranceM;

    rawBodyVertices = reshape(body.vertices, [], 3);
    bodyAnalyticPass = max(abs(vecnorm(rawBodyVertices, 2, 2) - ...
        definition.sphereRadiusM)) <= toleranceM && ...
        max(rawBodyVertices(:, 3)) <= toleranceM;
    fsAnalyticPass = max(abs(fsVertices(:, 3))) <= toleranceM;
    bottomAnalyticPass = max(abs(bottomVertices(:, 3) + ...
        domain.cfg.water_depth)) <= toleranceM;
    wallAnalyticPass = min(wallVertices(:, 3)) >= ...
        -domain.cfg.water_depth - toleranceM && ...
        max(wallVertices(:, 3)) <= toleranceM;
    selfIntersectionPass = bodyAnalyticPass && fsAnalyticPass && ...
        bottomAnalyticPass && wallAnalyticPass && duplicatePanelCount == 0;

    topology = struct( ...
        'uniqueVertexCount', size(uniqueVertices, 1), ...
        'uniqueEdgeCount', size(uniqueEdges, 1), ...
        'minimumEdgeMultiplicity', min(edgeMultiplicity), ...
        'maximumEdgeMultiplicity', max(edgeMultiplicity), ...
        'nonmanifoldEdgeCount', nonmanifoldEdgeCount, ...
        'duplicatePanelCount', duplicatePanelCount, ...
        'triangleDuplicateVertexCount', triangleDuplicateCount, ...
        'unexpectedWithinPanelDuplicateVertexCount', ...
            unexpectedDuplicateCount, ...
        'eulerCharacteristic', eulerCharacteristic, ...
        'manifoldPass', manifoldPass, ...
        'orientationPass', orientationPass, ...
        'maximumInterfaceGapM', maximumInterfaceGapM, ...
        'interfaceContinuityPass', interfacePass, ...
        'selfIntersectionAudit', ...
            "ANALYTIC_COMPONENT_SEPARATION_PLUS_DUPLICATE_PANEL_AUDIT", ...
        'selfIntersectionPass', selfIntersectionPass);
end

function value = lexicographically_greater(first, second)
    differenceIndex = find(first ~= second, 1);
    value = ~isempty(differenceIndex) && ...
        first(differenceIndex) > second(differenceIndex);
end

function gap = hausdorff_gap(first, second)
    if isempty(first) || isempty(second)
        gap = Inf;
        return
    end
    firstToSecond = zeros(size(first, 1), 1);
    for index = 1:size(first, 1)
        firstToSecond(index) = min(vecnorm(second - first(index, :), 2, 2));
    end
    secondToFirst = zeros(size(second, 1), 1);
    for index = 1:size(second, 1)
        secondToFirst(index) = min(vecnorm(first - second(index, :), 2, 2));
    end
    gap = max([firstToSecond; secondToFirst]);
end

function row = empty_quality_row()
    row = struct('stage', "", 'mesh_level', "", 'omega_rad_s', NaN, ...
        'component', "", 'panel_count', 0, ...
        'minimum_panel_area_m2', NaN, 'maximum_panel_area_m2', NaN, ...
        'median_panel_area_m2', NaN, 'mean_sqrt_area_m', NaN, ...
        'median_sqrt_area_m', NaN, 'minimum_edge_length_m', NaN, ...
        'maximum_aspect_ratio', NaN, 'maximum_skewness_deg', NaN, ...
        'minimum_corner_angle_deg', NaN, ...
        'maximum_corner_angle_deg', NaN, 'maximum_warp_deg', NaN, ...
        'poor_panel_count', 0, 'poor_panel_fraction', NaN, ...
        'finite_positive_geometry', false, 'component_gate_pass', false, ...
        'component_gate_status', "NOT_RUN");
end

function text = pass_fail(value)
    if value
        text = "PASS";
    else
        text = "FAIL";
    end
end
