function specification = create_case(definition, level, omega, stageName)
% CREATE_CASE Materialize one unique clean mesh/frequency runtime case.

    validateattributes(omega, {'numeric'}, ...
        {'scalar', 'real', 'positive', 'finite'});
    runtimeDirectory = tempname(definition.artifactDirectory);
    [created, message] = mkdir(runtimeDirectory);
    assert(created, 'CRESTU:Phase32RuntimeDirectory', ...
        'Cannot create isolated runtime directory: %s (%s)', ...
        runtimeDirectory, message);
    [~, runtimeToken] = fileparts(runtimeDirectory);
    caseName = sprintf('P32_%s_w%04d_%s', char(level.name), ...
        round(1000 * omega), runtimeToken);
    bodyFile = fullfile(runtimeDirectory, [caseName, '_body.bmf']);
    configFile = fullfile(runtimeDirectory, [caseName, '.cfg']);

    baseline = read_config(definition.baselineConfig);
    formal = read_config(definition.formalConfig);
    [waveNumber, ~] = solve_wave_dispersion( ...
        omega, baseline.grav, baseline.water_depth);
    wavelengthM = 2 * pi / waveNumber; % [m]
    innerRadiusM = baseline.fs.r_inner; % [m]
    baselineTopRadiusM = innerRadiusM + ...
        baseline.outer_truncation.topRadiusPerWavelength * wavelengthM;
    baselineBottomRadiusM = innerRadiusM + ...
        baseline.outer_truncation.bottomRadiusPerWavelength * wavelengthM;
    targetTopRadiusM = definition.outerRadiusFactor * baselineTopRadiusM;
    targetBottomRadiusM = definition.outerRadiusFactor * baselineBottomRadiusM;
    qTop = (targetTopRadiusM - innerRadiusM) / wavelengthM;
    qBottom = (targetBottomRadiusM - innerRadiusM) / wavelengthM;

    generate_body_bmf(bodyFile, 2 * definition.sphereRadiusM, ...
        baseline.isx, baseline.isy, level.bodyDivision);
    write_runtime_config(configFile, caseName, bodyFile, omega, qTop, ...
        qBottom, baseline, formal, level);

    physicalState = struct( ...
        'analyticGeometry', 'hemisphere-radius-5m', ...
        'sphereRadiusM', definition.sphereRadiusM, ...
        'waterDepthM', baseline.water_depth, ...
        'densityKgPerM3', baseline.rho, ...
        'gravityMPerS2', baseline.grav, ...
        'massProperties', baseline.mass_props, ...
        'calculationModes', baseline.calc_modes, ...
        'isx', baseline.isx, 'isy', baseline.isy, ...
        'outerRadiusFactor', definition.outerRadiusFactor, ...
        'targetTopRadiusM', targetTopRadiusM, ...
        'targetBottomRadiusM', targetBottomRadiusM, ...
        'incidentHeadingDeg', 0.0, ...
        'harmonicConvention', 'exp(+i*omega*t)');
    controlState = struct('level', level, 'omegaRadPerS', omega, ...
        'qTop', qTop, 'qBottom', qBottom, ...
        'targetTopRadiusM', targetTopRadiusM, ...
        'targetBottomRadiusM', targetBottomRadiusM);
    generationCommand = sprintf([ ...
        'generate_body_bmf(D=10,division=%d); ', ...
        'FS=[%d,%d]; bottom=[%d,%d]; wallNz=%d; ', ...
        'theta=[wall:%d,FS:%d,bottom:%d]; outerFactor=1.5'], ...
        level.bodyDivision, level.fsRadialCounts, ...
        level.bottomRadialCounts, level.wallVerticalCount, ...
        level.wallThetaCount, level.fsThetaCount, level.bottomThetaCount);
    specification = struct( ...
        'stage', string(stageName), 'level', level, 'omegaRadPerS', omega, ...
        'runtimeDirectory', runtimeDirectory, 'caseName', caseName, ...
        'bodyFile', bodyFile, 'configFile', configFile, ...
        'waveNumberPerM', waveNumber, 'wavelengthM', wavelengthM, ...
        'qTop', qTop, 'qBottom', qBottom, ...
        'targetTopRadiusM', targetTopRadiusM, ...
        'targetBottomRadiusM', targetBottomRadiusM, ...
        'physicalHash', string(sha256_hash(jsonencode(physicalState))), ...
        'controlHash', string(sha256_hash(jsonencode(controlState))), ...
        'configRawSHA256', string(sha256_file_hash(configFile)), ...
        'bodyFileRawSHA256', string(sha256_file_hash(bodyFile)), ...
        'meshGenerationCommand', string(generationCommand));
end

function write_runtime_config(filename, caseName, bodyFile, omega, ...
        qTop, qBottom, baseline, formal, level)
% WRITE_RUNTIME_CONFIG Write one clean production configuration.

    fileID = fopen(filename, 'w');
    assert(fileID >= 0, 'CRESTU:Phase32ConfigOpen', ...
        'Cannot create runtime configuration: %s', filename);
    cleanup = onCleanup(@() fclose(fileID));
    mass = baseline.mass_props(1);
    inertia = mass.inertia;
    inertiaTokens = [inertia(1, 1), inertia(2, 2), inertia(3, 3), ...
        -inertia(1, 2), -inertia(1, 3), -inertia(2, 3)];

    fprintf(fileID, 'PARA1: Project Case Name\n%s\n\n', caseName);
    fprintf(fileID, 'PARA2: IPOTEN IFORCE IRAD IDIFF IDRIFT\n1 1 1 1 0\n\n');
    fprintf(fileID, 'PARA3: FREQUENCY AND HEADING\n1 1 %.17g %.17g\n', ...
        omega, omega);
    fprintf(fileID, '1\n0\n\n');
    fprintf(fileID, 'PARA4: ENVIRONMENT\n%.17g %.17g %.17g\n\n', ...
        baseline.water_depth, baseline.grav, baseline.rho);
    fprintf(fileID, 'PARA5: BODY\n1\n%d %s %.17g %.17g %.17g %.17g\n\n', ...
        baseline.bodies(1).id, bodyFile, baseline.bodies(1).pos, ...
        baseline.bodies(1).yaw);
    fprintf(fileID, 'PARA6: MASS PROPERTIES\n%.17g %.17g %.17g %.17g\n', ...
        mass.mass, mass.cg);
    fprintf(fileID, '%.17g %.17g %.17g %.17g %.17g %.17g\n\n', ...
        inertiaTokens);
    fprintf(fileID, 'PARA7: MODES\n');
    fprintf(fileID, '%d ', baseline.calc_modes);
    fprintf(fileID, '\n\nPARA8: FULL DOMAIN\n%d %d\n\n', ...
        baseline.isx, baseline.isy);
    fprintf(fileID, ['PARA9: DOMAIN\n%.17g %d %d %.17g %.17g ', ...
        '%.17g %d\n\n'], baseline.z_tol, baseline.fs.nr_near, ...
        baseline.fs.nr_sponge, baseline.fs.r_inner, baseline.fs.r_outer, ...
        baseline.fs.sponge_ratio, baseline.fs.nz_farfield);
    fprintf(fileID, 'PARA10: SPONGE\n%.17g\n\n', baseline.fs.mu0);
    fprintf(fileID, ['PARA11: FIXED OUTER-DOMAIN WATERLINE\n', ...
        'OUTER_WATERLINE_MESH %s\n\n'], bodyFile);
    fprintf(fileID, ['PARA12: PHASE2.2 OUTER TRUNCATION AUDIT\n', ...
        'OUTER_TRUNCATION_Q %.17g %.17g\n\n'], qTop, qBottom);
    fprintf(fileID, 'PARA13: PHASE3.2 COORDINATED MESH CONTROLS\n');
    fprintf(fileID, 'FS_RADIAL_COUNTS %d %d\n', level.fsRadialCounts);
    fprintf(fileID, 'BOTTOM_RADIAL_COUNTS %d %d\n', ...
        level.bottomRadialCounts);
    fprintf(fileID, 'OUTER_VERTICAL_COUNT %d\n', level.wallVerticalCount);
    fprintf(fileID, 'OUTER_THETA_COUNT %d\n', level.wallThetaCount);
    fprintf(fileID, 'FS_OUTER_THETA_COUNT %d\n', level.fsThetaCount);
    fprintf(fileID, 'BOTTOM_OUTER_THETA_COUNT %d\n', ...
        level.bottomThetaCount);
    fprintf(fileID, 'MESH_TRANSITION_RADIUS %.17g\n', baseline.fs.r_inner);
    fprintf(fileID, 'SPONGE_START_RADIUS %.17g\n', baseline.fs.r_inner);
    fprintf(fileID, 'RAW_DIAGNOSTICS 1\nPERSIST_FULL_PHI 0\n');
    clear cleanup

    assert(formal.wave.ndir >= 1 && any(abs(formal.wave.headings) <= eps), ...
        'CRESTU:Phase32HeadingConvention', ...
        'The frozen formal config no longer contains heading 0 degrees.');
end
