function definition = definition()
% DEFINITION Return the immutable Phase 3.2 mesh family and gates.

    packageDirectory = fileparts(mfilename('fullpath'));
    artifactDirectory = fileparts(packageDirectory);
    convergenceDirectory = fileparts(artifactDirectory);
    caseWaveDirectory = fileparts(convergenceDirectory);
    repositoryRoot = fileparts(caseWaveDirectory);

    levelTemplate = struct('name', "", 'index', 0, 'eta', NaN, ...
        'bodyDivision', 0, 'fsRadialCounts', [0, 0], ...
        'bottomRadialCounts', [0, 0], 'wallVerticalCount', 0, ...
        'wallThetaCount', 0, 'fsThetaCount', 0, ...
        'bottomThetaCount', 0);
    levels = repmat(levelTemplate, 3, 1);
    levels(1) = struct('name', "MESH_L1", 'index', 1, ...
        'eta', 0.0707009403590185, 'bodyDivision', 4, ...
        'fsRadialCounts', [4, 2], 'bottomRadialCounts', [4, 2], ...
        'wallVerticalCount', 3, 'wallThetaCount', 64, ...
        'fsThetaCount', 64, 'bottomThetaCount', 64);
    levels(2) = struct('name', "MESH_L2", 'index', 2, ...
        'eta', 0.0550177552570247, 'bodyDivision', 5, ...
        'fsRadialCounts', [5, 3], 'bottomRadialCounts', [5, 3], ...
        'wallVerticalCount', 4, 'wallThetaCount', 80, ...
        'fsThetaCount', 80, 'bottomThetaCount', 80);
    levels(3) = struct('name', "MESH_L3", 'index', 3, ...
        'eta', 0.0412542094946932, 'bodyDivision', 7, ...
        'fsRadialCounts', [6, 4], 'bottomRadialCounts', [6, 4], ...
        'wallVerticalCount', 5, 'wallThetaCount', 112, ...
        'fsThetaCount', 112, 'bottomThetaCount', 112);

    gates = struct( ...
        'minimumRcond', 1.0e-12, ...
        'maximumRelativeResidual', 1.0e-10, ...
        'maximumOuterNTheta', 1.0e-10, ...
        'maximumOuterColumnResidual', 1.0e-14, ...
        'geometryToleranceM', 1.0e-8, ...
        'minimumEdgeLengthM', 1.0e-10, ...
        'bodyMaximumAspectRatio', 4.0, ...
        'nearMaximumAspectRatio', 4.5, ...
        'outerMaximumAspectRatio', 12.0, ...
        'maximumSkewnessDeg', 55.0, ...
        'minimumCornerAngleDeg', 35.0, ...
        'maximumCornerAngleDeg', 145.0, ...
        'maximumWarpDeg', 8.0, ...
        'maximumPoorPanelFraction', 0.05, ...
        'scalarPassRelative', 0.02, ...
        'scalarFailRelative', 0.10, ...
        'raoPassRelative', 0.05, ...
        'raoFailRelative', 0.15, ...
        'resonanceFrequencyPassRadPerS', 0.02, ...
        'resonanceRelativePass', 0.10, ...
        'phaseAmplitudeFloorMultiplier', 100.0);

    definition = struct( ...
        'schemaVersion', 1, ...
        'runnerVersion', 'Phase3.2-coordinated-mesh-v4', ...
        'artifactDirectory', artifactDirectory, ...
        'convergenceDirectory', convergenceDirectory, ...
        'caseWaveDirectory', caseWaveDirectory, ...
        'repositoryRoot', repositoryRoot, ...
        'sourceDirectory', fullfile(repositoryRoot, 'Source Code'), ...
        'originalRepository', ...
            'E:\CRESTU-1F_v1.0_20260824\Code\CRESTU', ...
        'baselineConfig', fullfile(convergenceDirectory, ...
            'Phase2_2_Artifacts', 'Tests', 'Frustum_Instrumentation', ...
            'Cases', 'Frustum_Top_Only.cfg'), ...
        'formalConfig', fullfile(convergenceDirectory, ...
            'Mesh_Fine', 'Case1_Fine.cfg'), ...
        'predeclaredGateFile', fullfile(artifactDirectory, ...
            'Phase3_2_Predeclared_Gates_v4.md'), ...
        'predeclaredGateCanonicalSHA256', ...
            'a7f32e4ef9cc2fb38d7bba419207fd51799bfe617cadee79d4b1302c860d476d', ...
        'predeclaredGateGitBlobID', ...
            '8eaf895daaaea7fcab8db26126ea79a8fca942bb', ...
        'checkpointCommit', ...
            '7f2d391d1b42366fdb04e1b493439dab438584eb', ...
        'checkpointTag', 'phase3-1b-checkpoint-20260901', ...
        'levels', levels, 'gates', gates, ...
        'sentinelFrequenciesRadPerS', [0.5, 0.6, 1.0, 1.4, 1.5, 2.0], ...
        'formalFrequenciesRadPerS', 0.5:0.1:2.0, ...
        'resonanceFrequenciesRadPerS', 1.30:0.02:1.50, ...
        'sphereRadiusM', 5.0, ...
        'outerRadiusFactor', 1.5, ...
        'nestedMesh', false);
end
