function definition = definition()
% DEFINITION Return the immutable Phase 3.2 mesh family and gates.

    packageDirectory = fileparts(mfilename('fullpath'));
    artifactDirectory = fileparts(packageDirectory);
    convergenceDirectory = fileparts(artifactDirectory);
    caseWaveDirectory = fileparts(convergenceDirectory);
    repositoryRoot = fileparts(caseWaveDirectory);

    levelTemplate = struct('name', "", 'index', 0, 'eta', NaN, ...
        'bodyDivision', 0, 'fsRadialCounts', [0, 0], ...
        'bottomRadialCounts', [0, 0], 'wallVerticalCount', 0, ...
        'wallThetaCount', 0, 'fsThetaCount', 0, ...
        'bottomThetaCount', 0);
    levels = repmat(levelTemplate, 3, 1);
    levels(1) = struct('name', "MESH_L1", 'index', 1, ...
        'eta', 0.0707009403590185, 'bodyDivision', 4, ...
        'fsRadialCounts', [4, 2], 'bottomRadialCounts', [4, 2], ...
        'wallVerticalCount', 3, 'wallThetaCount', 64, ...
        'fsThetaCount', 64, 'bottomThetaCount', 64);
    levels(2) = struct('name', "MESH_L2", 'index', 2, ...
        'eta', 0.0479337530744922, 'bodyDivision', 6, ...
        'fsRadialCounts', [6, 3], 'bottomRadialCounts', [6, 3], ...
        'wallVerticalCount', 4, 'wallThetaCount', 96, ...
        'fsThetaCount', 96, 'bottomThetaCount', 96);
    levels(3) = struct('name', "MESH_L3", 'index', 3, ...
        'eta', 0.0353504701795093, 'bodyDivision', 8, ...
        'fsRadialCounts', [8, 4], 'bottomRadialCounts', [8, 4], ...
        'wallVerticalCount', 6, 'wallThetaCount', 128, ...
        'fsThetaCount', 128, 'bottomThetaCount', 128);

    gates = struct( ...
        'minimumRcond', 1.0e-12, ...
        'maximumRelativeResidual', 1.0e-10, ...
        'maximumOuterNTheta', 1.0e-10, ...
        'maximumOuterColumnResidual', 1.0e-14, ...
        'geometryToleranceM', 1.0e-8, ...
        'minimumEdgeLengthM', 1.0e-10, ...
        'bodyMaximumAspectRatio', 4.0, ...
        'nearMaximumAspectRatio', 4.5, ...
        'outerMaximumAspectRatio', 12.0, ...
        'maximumSkewnessDeg', 55.0, ...
        'minimumCornerAngleDeg', 35.0, ...
        'maximumCornerAngleDeg', 145.0, ...
        'maximumWarpDeg', 8.0, ...
        'maximumPoorPanelFraction', 0.05, ...
        'scalarPassRelative', 0.02, ...
        'scalarFailRelative', 0.10, ...
        'raoPassRelative', 0.05, ...
        'raoFailRelative', 0.15, ...
        'resonanceFrequencyPassRadPerS', 0.02, ...
        'resonanceRelativePass', 0.10, ...
        'phaseAmplitudeFloorMultiplier', 100.0);

    definition = struct( ...
        'schemaVersion', 1, ...
        'runnerVersion', 'Phase3.2-coordinated-mesh-v3', ...
        'artifactDirectory', artifactDirectory, ...
        'convergenceDirectory', convergenceDirectory, ...
        'caseWaveDirectory', caseWaveDirectory, ...
        'repositoryRoot', repositoryRoot, ...
        'sourceDirectory', fullfile(repositoryRoot, 'Source Code'), ...
        'originalRepository', ...
            'E:\CRESTU-1F_v1.0_20260824\Code\CRESTU', ...
        'baselineConfig', fullfile(convergenceDirectory, ...
            'Phase2_2_Artifacts', 'Tests', 'Frustum_Instrumentation', ...
            'Cases', 'Frustum_Top_Only.cfg'), ...
        'formalConfig', fullfile(convergenceDirectory, ...
            'Mesh_Fine', 'Case1_Fine.cfg'), ...
        'predeclaredGateFile', fullfile(artifactDirectory, ...
            'Phase3_2_Predeclared_Gates_v3.md'), ...
        'predeclaredGateCanonicalSHA256', ...
            'ec39af3885460f0347f662e879a34a64411d771fec633ec6ae19e4f16087ba7c', ...
        'predeclaredGateGitBlobID', ...
            '6cb96fbf77d599e8521d36fbf8333eed33320468', ...
        'checkpointCommit', ...
            '7f2d391d1b42366fdb04e1b493439dab438584eb', ...
        'checkpointTag', 'phase3-1b-checkpoint-20260901', ...
        'levels', levels, 'gates', gates, ...
        'sentinelFrequenciesRadPerS', [0.5, 0.6, 1.0, 1.4, 1.5, 2.0], ...
        'formalFrequenciesRadPerS', 0.5:0.1:2.0, ...
        'resonanceFrequenciesRadPerS', 1.30:0.02:1.50, ...
        'sphereRadiusM', 5.0, ...
        'outerRadiusFactor', 1.5, ...
        'nestedMesh', false);
end
