function initialize(definition)
% INITIALIZE Reset MATLAB and enforce runtime/gate/checkpoint provenance.

    restoredefaultpath;
    rehash toolboxcache;
    assert(same_path(pwd, definition.repositoryRoot), ...
        'CRESTU:Phase32MatlabPwd', ...
        'MATLAB pwd must be the Phase 3.2 worktree root.');
    sourceDirectory = definition.sourceDirectory;
    addpath(fullfile(sourceDirectory, '0.Tools Code'), ...
        fullfile(sourceDirectory, '1.Input'), ...
        fullfile(sourceDirectory, '2.Mesh'), ...
        fullfile(sourceDirectory, '3.HessSmith'), ...
        fullfile(sourceDirectory, '4.Potential'), ...
        fullfile(sourceDirectory, '5.Force'), ...
        fullfile(sourceDirectory, '6.MeanDriftLoads'), ...
        definition.caseWaveDirectory, ...
        fullfile(definition.caseWaveDirectory, 'Common_Scripts'), ...
        definition.convergenceDirectory, definition.artifactDirectory, '-begin');

    %% Stage 1: Verify the immutable predeclared gate

    gateCanonical = phase32.canonical_lf_hash(definition.predeclaredGateFile);
    assert(strcmp(gateCanonical, ...
        definition.predeclaredGateCanonicalSHA256), ...
        'CRESTU:Phase32GateHash', ...
        'The predeclared Phase 3.2 gate changed after being frozen.');
    gateRelative = strrep(definition.predeclaredGateFile, ...
        [definition.repositoryRoot, filesep], '');
    gateRelative = strrep(gateRelative, '\', '/');
    [gateBlob, gateBlobStatus] = git_query(definition.repositoryRoot, ...
        sprintf('rev-parse "HEAD:%s"', gateRelative));
    assert(gateBlobStatus == 0 && strcmp(strtrim(gateBlob), ...
        definition.predeclaredGateGitBlobID), ...
        'CRESTU:Phase32GateBlob', ...
        'The committed predeclared-gate Git blob changed.');

    %% Stage 2: Verify branch, checkpoint ancestry, and runtime paths

    [branch, branchStatus] = git_query(definition.repositoryRoot, ...
        'branch --show-current');
    [tagCommit, tagStatus] = git_query(definition.repositoryRoot, ...
        sprintf('rev-parse "%s^{commit}"', definition.checkpointTag));
    [~, ancestorStatus] = git_query(definition.repositoryRoot, sprintf( ...
        'merge-base --is-ancestor %s HEAD', definition.checkpointCommit));
    assert(branchStatus == 0 && ...
        strcmp(strtrim(branch), 'phase3-2-mesh-convergence') && ...
        tagStatus == 0 && strcmp(strtrim(tagCommit), ...
        definition.checkpointCommit) && ancestorStatus == 0, ...
        'CRESTU:Phase32GitProvenance', ...
        'Branch or frozen checkpoint/tag provenance failed.');

    runtimeFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2_Runtime_Path_Resolution.csv');
    runtimeTable = readtable(runtimeFile, 'TextType', 'string');
    for index = 1:height(runtimeTable)
        activePath = string(which(runtimeTable.function_name(index)));
        expectedPath = runtimeTable.expected_path(index);
        assert(same_path(activePath, expectedPath) && ...
            path_is_within(activePath, definition.repositoryRoot) && ...
            ~path_is_within(activePath, definition.originalRepository), ...
            'CRESTU:Phase32RuntimePath', ...
            'Runtime function path is outside the Phase 3.2 worktree: %s', ...
            runtimeTable.function_name(index));
    end

    assert(isfile(definition.baselineConfig) && ...
        isfile(definition.formalConfig), ...
        'CRESTU:Phase32FrozenInputMissing', ...
        'A frozen Phase 2.3/3.1 configuration is missing.');
    fprintf('[OK] Phase 3.2 runtime/gate/checkpoint provenance verified.\n');
end

function [output, status] = git_query(repositoryRoot, arguments)
    [status, output] = system(sprintf('git -C "%s" %s', ...
        repositoryRoot, arguments));
end

function value = same_path(firstPath, secondPath)
    value = strcmpi(normalize_path(firstPath), normalize_path(secondPath));
end

function value = path_is_within(candidatePath, rootPath)
    candidate = normalize_path(candidatePath);
    root = normalize_path(rootPath);
    value = strcmpi(candidate, root) || startsWith(lower(candidate), ...
        [lower(root), filesep]);
end

function value = normalize_path(inputPath)
    value = strrep(char(string(inputPath)), '/', filesep);
    while numel(value) > 3 && endsWith(value, filesep)
        value(end) = [];
    end
end
