function [verificationTable, details] = Verify_Sphere_Meshes( ...
        meshFilenames, levelNames, sphereRadius, outputDirectory)
% VERIFY_SPHERE_MESHES Verify hemisphere geometry and panel integration identities.
%
% Syntax:
%   [verificationTable, details] = Verify_Sphere_Meshes(...)
%
% Inputs:
%   meshFilenames  - Body BMF paths for Coarse/Medium/Fine [-].
%   levelNames     - Human-readable mesh levels [-].
%   sphereRadius   - Analytical sphere radius [m].
%   outputDirectory - Directory for the verification CSV [-].
%
% Outputs:
%   verificationTable - Area, volume, normal, buoyancy, and identity checks.
%   details            - Full tensor-valued verification diagnostics.

    arguments
        meshFilenames cell
        levelNames cell
        sphereRadius (1,1) double {mustBePositive} % [m]
        outputDirectory {mustBeTextScalar}
    end

    %% 阶段 1: 验证输入并初始化解析结果

    assert(numel(meshFilenames) == numel(levelNames), ...
        'CRESTU:SphereVerificationLevels', ...
        'Mesh filename and level-name counts must agree.');
    assert(isfolder(outputDirectory), ...
        'CRESTU:SphereVerificationDirectory', ...
        'Verification output directory does not exist: %s', outputDirectory);
    meshCount = numel(meshFilenames);
    details = repmat(empty_detail(), meshCount, 1);

    %% 阶段 2: 检查解析几何量与分片积分恒等式

    for meshIndex = 1:meshCount
        assert(isfile(meshFilenames{meshIndex}), ...
            'CRESTU:SphereMeshMissing', ...
            'Sphere mesh was not found: %s', meshFilenames{meshIndex});
        mesh = read_bmf(meshFilenames{meshIndex});
        details(meshIndex) = verify_one_mesh(mesh, levelNames{meshIndex}, ...
            sphereRadius);
    end

    %% 阶段 3: 导出机器可解析核查表并打印汇总

    verificationTable = struct2table(details);
    verificationFilename = fullfile(outputDirectory, ...
        'Sphere_Mesh_Verification.csv');
    writetable(verificationTable, verificationFilename);
    fprintf('[INFO] Sphere geometry verification summary:\n');
    disp(verificationTable(:, {'level', 'panelCount', 'vertexCount', ...
        'areaRelativeError', 'volumeRelativeError', ...
        'buoyancyCenterErrorM', 'surfaceIdentityRelativeResidual', ...
        'allChecksPassed'}));
    fprintf('[OK] Sphere verification saved: %s\n', verificationFilename);
end

function detail = verify_one_mesh(mesh, levelName, sphereRadius)
% VERIFY_ONE_MESH Evaluate analytical hemisphere geometry identities.

    % <<<CORE>>> sphere_surface_integral_verification, paper_eq=divergence_theorem, benchmark=hemisphere_analytic
    areas = reshape(mesh.areas, [], 1); % [m^2]
    centers = reshape(mesh.centers, [], 3); % [m]
    normals = reshape(mesh.normals, [], 3); % [-]
    radialNormalProduct = sum(centers .* normals, 2); % [m]
    computedArea = sum(areas); % [m^2]
    computedVolume = sum(radialNormalProduct .* areas) / 3.0; % [m^3]
    firstVolumeMoment = sum(centers .* ...
        (radialNormalProduct .* areas), 1) / 4.0; % [m^4]
    computedBuoyancyCenter = firstVolumeMoment / computedVolume; % [m]
    surfaceNormalIntegral = sum(normals .* areas, 1); % [m^2]
    surfaceFirstMoment = centers.' * (normals .* areas); % [m^3]
    % <<</CORE>>>

    analyticalArea = 2.0 * pi * sphereRadius^2; % [m^2]
    analyticalVolume = (2.0 / 3.0) * pi * sphereRadius^3; % [m^3]
    analyticalBuoyancyCenter = [0.0, 0.0, -3.0 * sphereRadius / 8.0]; % [m]
    analyticalNormalIntegral = [0.0, 0.0, -pi * sphereRadius^2]; % [m^2]
    analyticalFirstMoment = analyticalVolume * eye(3); % [m^3]
    vertexRows = reshape(mesh.vertices, [], 3); % [m]
    vertexRadii = sqrt(sum(vertexRows.^2, 2)); % [m]
    centerRadii = sqrt(sum(centers.^2, 2)); % [m]
    normalAlignment = sum(centers .* normals, 2) ./ ...
        max(centerRadii, eps); % [-]
    meshAudit = mesh_fingerprint(mesh);

    areaRelativeError = abs(computedArea - analyticalArea) / analyticalArea;
    volumeRelativeError = abs(computedVolume - analyticalVolume) / ...
        analyticalVolume;
    buoyancyCenterError = norm(computedBuoyancyCenter - ...
        analyticalBuoyancyCenter); % [m]
    normalIntegralResidual = norm(surfaceNormalIntegral - ...
        analyticalNormalIntegral) / analyticalArea;
    surfaceIdentityResidual = norm(surfaceFirstMoment - ...
        analyticalFirstMoment, 'fro') / ...
        norm(analyticalFirstMoment, 'fro');
    maximumVertexRadiusError = max(abs(vertexRadii - sphereRadius)); % [m]
    outwardNormalFraction = mean(normalAlignment > 0.0);
    integrationTolerance = max(0.02, ...
        2.5 * (meshAudit.characteristicSize / sphereRadius)^2);
    allChecksPassed = maximumVertexRadiusError <= 5.0e-8 * sphereRadius && ...
        outwardNormalFraction == 1.0 && computedVolume > 0.0 && ...
        areaRelativeError <= integrationTolerance && ...
        volumeRelativeError <= integrationTolerance && ...
        surfaceIdentityResidual <= 2.0 * integrationTolerance;

    detail = struct('level', levelName, ...
        'panelCount', meshAudit.panelCount, ...
        'vertexCount', meshAudit.vertexCount, ...
        'characteristicSizeM', meshAudit.characteristicSize, ... % [m]
        'computedAreaM2', computedArea, ... % [m^2]
        'analyticalAreaM2', analyticalArea, ... % [m^2]
        'areaRelativeError', areaRelativeError, ...
        'computedVolumeM3', computedVolume, ... % [m^3]
        'analyticalVolumeM3', analyticalVolume, ... % [m^3]
        'volumeRelativeError', volumeRelativeError, ...
        'buoyancyCenterXM', computedBuoyancyCenter(1), ... % [m]
        'buoyancyCenterYM', computedBuoyancyCenter(2), ... % [m]
        'buoyancyCenterZM', computedBuoyancyCenter(3), ... % [m]
        'buoyancyCenterErrorM', buoyancyCenterError, ... % [m]
        'normalIntegralRelativeResidual', normalIntegralResidual, ...
        'surfaceIdentityRelativeResidual', surfaceIdentityResidual, ...
        'minimumNormalAlignment', min(normalAlignment), ...
        'outwardNormalFraction', outwardNormalFraction, ...
        'maximumVertexRadiusErrorM', maximumVertexRadiusError, ... % [m]
        'integrationTolerance', integrationTolerance, ...
        'allChecksPassed', allChecksPassed, ...
        'meshHash', meshAudit.hash);
end

function detail = empty_detail()
% EMPTY_DETAIL Initialize the scalar verification record.

    detail = struct('level', '', 'panelCount', 0, 'vertexCount', 0, ...
        'characteristicSizeM', NaN, 'computedAreaM2', NaN, ...
        'analyticalAreaM2', NaN, 'areaRelativeError', NaN, ...
        'computedVolumeM3', NaN, 'analyticalVolumeM3', NaN, ...
        'volumeRelativeError', NaN, 'buoyancyCenterXM', NaN, ...
        'buoyancyCenterYM', NaN, 'buoyancyCenterZM', NaN, ...
        'buoyancyCenterErrorM', NaN, ...
        'normalIntegralRelativeResidual', NaN, ...
        'surfaceIdentityRelativeResidual', NaN, ...
        'minimumNormalAlignment', NaN, 'outwardNormalFraction', NaN, ...
        'maximumVertexRadiusErrorM', NaN, 'integrationTolerance', NaN, ...
        'allChecksPassed', false, 'meshHash', '');
end
