function summary = Finalize_Phase3_2A()
% FINALIZE_PHASE3_2A Generate final status, review, and Git/file audits.

    %% Stage 1: Re-read and assert every authoritative evidence table

    definition = phase32a.initialize();
    artifact = definition.artifactDirectory;
    fixtures = readtable(fullfile(artifact, ...
        'Phase3_2A_Quality_Metric_Unit_Tests.csv'), 'TextType', 'string');
    reconciliation = readtable(fullfile(artifact, ...
        'Phase3_2A_V4_Quality_Reconciliation.csv'), 'TextType', 'string');
    endpoint = readtable(fullfile(artifact, ...
        'Phase3_2A_Endpoint_Prototype_Quality.csv'), 'TextType', 'string');
    v5Manifest = readtable(fullfile(artifact, ...
        'Phase3_2A_V5_Mesh_Manifest.csv'), 'TextType', 'string');
    v5Quality = readtable(fullfile(artifact, ...
        'Phase3_2A_V5_Mesh_Quality.csv'), 'TextType', 'string');
    v5Isolation = readtable(fullfile(artifact, ...
        'Phase3_2A_V5_Control_Isolation.csv'), 'TextType', 'string');
    legacy = readtable(fullfile(artifact, ...
        'Phase3_2A_Legacy_Regression.csv'), 'TextType', 'string');
    bridge = readtable(fullfile(artifact, ...
        'Phase3_2A_BEM_Bridge_Smoke.csv'), 'TextType', 'string');
    integrity = readtable(fullfile(definition.convergenceDirectory, ...
        'Phase3_2_Artifacts', 'Phase3_2_Final_Report_Integrity.csv'));

    assert(height(fixtures) == 6 && all(fixtures.test_pass), ...
        'CRESTU:Phase32AFinalFixtures', 'Analytic quality fixtures are not 6/6 PASS.');
    assert(height(reconciliation) == 72 && all(reconciliation.row_match) && ...
        nnz(reconciliation.recomputed_status == "PASS") == 36 && ...
        nnz(reconciliation.recomputed_status == "FAIL") == 36, ...
        'CRESTU:Phase32AFinalReconciliation', ...
        'Blocked-v4 quality reconciliation is not 72/72 with 36/36 split.');
    assert(height(endpoint) == 24 && ...
        all(endpoint.component_gate_status == "PASS"), ...
        'CRESTU:Phase32AFinalEndpoint', 'Endpoint quality is not 24/24 PASS.');
    assert(height(v5Manifest) == 18 && height(v5Quality) == 72 && ...
        all(v5Quality.component_gate_status == "PASS") && ...
        height(v5Isolation) == 6 && ...
        all(v5Isolation.frequency_geometry_gate == "PASS"), ...
        'CRESTU:Phase32AFinalV5', 'V5 mesh evidence is not 18/72/6 all PASS.');
    assert(height(legacy) == 5 && all(legacy.exact_hash_regression), ...
        'CRESTU:Phase32AFinalLegacy', 'LEGACY exact regression is not 5/5 PASS.');
    assert(height(bridge) == 2 && all(bridge.solve_status == "PASS") && ...
        bridge.legacy_regression_status(1) == "PASS", ...
        'CRESTU:Phase32AFinalBridge', 'Limited BEM bridge is not 2/2 PASS.');
    assert(integrity.COMPONENT_QUALITY_ROWS_TOTAL == 72 && ...
        integrity.COMPONENT_QUALITY_ROWS_PASS == 36 && ...
        integrity.COMPONENT_QUALITY_ROWS_FAIL == 36, ...
        'CRESTU:Phase32AFinalTask0', 'Task 0 integrity evidence is not 72/36/36.');
    assert_preserved_fail_evidence(definition);

    %% Stage 2: Final status and reviewer gate

    finalStatus = build_final_status();
    writetable(finalStatus, fullfile(artifact, 'Phase3_2A_Final_Status.csv'));
    reviewer = build_reviewer_gate();
    writetable(reviewer, fullfile(artifact, 'Phase3_2A_Reviewer_Gate.csv'));
    write_main_report(definition, fixtures, reconciliation, endpoint, ...
        v5Manifest, v5Quality, v5Isolation, legacy, bridge);
    write_human_review(definition);
    write_git_audits(definition);

    summary = struct('schemaVersion', 1, ...
        'overallStatus', 'PASS_WITH_LIMITATIONS', ...
        'qualityMetricFixturesPass', true, ...
        'endpointQualityPassCount', 24, 'v5QualityPassCount', 72, ...
        'v5GeometryCaseCount', 18, 'bemBridgePassCount', 2, ...
        'legacyExactRegressionPassCount', 5, 'reviewerBlockers', 0, ...
        'readyForPhase32BSentinel', true, ...
        'readyForProduction', false, 'physicalValidation', 'PARTIAL');
    fprintf('[RESULT] PHASE3_2A_OVERALL = PASS_WITH_LIMITATIONS\n');
    fprintf('[RESULT] REVIEWER_BLOCKERS = 0\n');
    fprintf('[RESULT] READY_FOR_PHASE3_2B_SENTINEL = YES\n');
    fprintf('[RESULT] READY_FOR_PRODUCTION = NO\n');
end

function tableOut = build_final_status()
    statusName = ["TASK0_FINAL_REPORT_INTEGRITY"; ...
        "QUALITY_METRIC_UNIT_TESTS"; "V4_QUALITY_MESH_RECONCILIATION"; ...
        "GENERATOR_CALL_CHAIN_AUDIT"; "FAIL_BEFORE_PANEL_DIAGNOSTICS"; ...
        "POLAR_TOPOLOGY_DEFAULT_MODE"; ...
        "QUALITY_CONTROLLED_V2_IMPLEMENTATION"; ...
        "LEGACY_Q_ONLY_GEOMETRY_REGRESSION"; ...
        "ENDPOINT_PROTOTYPE_GEOMETRY"; "V5_MESH_GEOMETRY_GATE"; ...
        "V5_MONOTONIC_REFINEMENT_FAMILY"; ...
        "LEGACY_BEM_BRIDGE_REGRESSION"; ...
        "QUALITY_CONTROLLED_V2_BEM_BRIDGE"; ...
        "READY_FOR_PHASE3_2B_SENTINEL"; "FORMAL_SWEEP"; ...
        "RESONANCE_SCAN"; "WAMIT_QUANTITATIVE_ATTRIBUTION"; ...
        "PHYSICAL_VALIDATION"; "READY_FOR_PRODUCTION"; ...
        "REVIEWER_BLOCKERS"; "PHASE3_2A_OVERALL"];
    statusValue = ["PASS_72_36_36"; "PASS_6_OF_6"; "PASS_72_OF_72"; ...
        "PASS"; "PASS"; "LEGACY"; "IMPLEMENTED_DEFAULT_OFF"; ...
        "PASS_EXACT_HASH_5_OF_5"; "PASS_24_OF_24"; ...
        "PASS_72_OF_72"; "PASS_6_OF_6_FREQUENCIES"; ...
        "PASS_MAX_REL_DIFF_4P28E13"; "PASS"; "YES"; ...
        "NOT_RUN_SCOPE"; "NOT_RUN_SCOPE"; "NOT_RUN_SCOPE"; ...
        "PARTIAL"; "NO"; "0"; "PASS_WITH_LIMITATIONS"];
    evidence = ["../Phase3_2_Artifacts/Phase3_2_Final_Report_Integrity.csv"; ...
        "Phase3_2A_Quality_Metric_Unit_Tests.csv"; ...
        "Phase3_2A_V4_Quality_Reconciliation.csv"; ...
        "Phase3_2A_Generator_Call_Chain.csv"; ...
        "Phase3_2A_FailBefore_Panel_Diagnostics.csv"; ...
        "read_config/get_polar_topology_mode"; ...
        "explicit config mode and source diff"; ...
        "Phase3_2A_Legacy_Regression.csv"; ...
        "Phase3_2A_Endpoint_Prototype_Quality.csv"; ...
        "Phase3_2A_V5_Mesh_Quality.csv"; ...
        "Phase3_2A_V5_Control_Isolation.csv"; ...
        "Phase3_2A_BEM_Bridge_Smoke.csv"; ...
        "Phase3_2A_BEM_Bridge_Smoke.csv"; ...
        "all Phase 3.2A gates required for bridge passed"; ...
        "forbidden by Phase 3.2A scope"; "forbidden by Phase 3.2A scope"; ...
        "mesh remediation does not authorize Task 7"; ...
        "no independent physical benchmark added"; ...
        "no convergence/physical production closure"; ...
        "Phase3_2A_Reviewer_Gate.csv"; ...
        "PHASE3_2A_POLAR_TOPOLOGY_REMEDIATION_CN.md"];
    tableOut = table(statusName, statusValue, evidence);
end

function tableOut = build_reviewer_gate()
    reviewID = string((1:14)');
    reviewItem = ["Task 0 report counts are dynamically 72/36/36"; ...
        "analytic triangle/quad metrics validated"; ...
        "blocked-v4 72 rows independently reproduced"; ...
        "generator/call-chain and panel IDs documented"; ...
        "new mode is explicit and default remains LEGACY"; ...
        "legacy q-only geometry remains 5/5 exact"; ...
        "endpoint prototype is 24/24 quality PASS"; ...
        "v5 family is 72/72 quality PASS"; ...
        "all six frequencies have strict count/h refinement"; ...
        "outer extent/manifold/orientation/waterline contracts pass"; ...
        "v1-v4 and Phase3.2A intermediate FAIL evidence preserved"; ...
        "two clean BEM bridge cases pass with cache MISS"; ...
        "radiation/diffraction/traction/ABC/A-B/RAO physics unchanged"; ...
        "no formal/resonance/WAMIT/production-ready overclaim"];
    reviewStatus = repmat("PASS", 14, 1);
    blockerCount = zeros(14, 1);
    evidence = ["Phase3_2_Final_Report_Integrity.csv"; ...
        "Phase3_2A_Quality_Metric_Unit_Tests.csv"; ...
        "Phase3_2A_V4_Quality_Reconciliation.csv"; ...
        "Phase3_2A_Generator_Call_Chain.csv;Phase3_2A_FailBefore_Panel_Diagnostics.csv"; ...
        "Phase3_2A_Topology_Design_Decision.md;source diff"; ...
        "Phase3_2A_Legacy_Regression.csv"; ...
        "Phase3_2A_Endpoint_Prototype_Quality.csv"; ...
        "Phase3_2A_V5_Mesh_Quality.csv"; ...
        "Phase3_2A_V5_Control_Isolation.csv"; ...
        "Phase3_2A_V5_Mesh_Manifest.csv"; ...
        "initial/gap-v2 FAIL CSV and ../Phase3_2_Artifacts"; ...
        "Phase3_2A_BEM_Bridge_Smoke.csv"; ...
        "Phase3_2A_Production_Diff.txt"; ...
        "Phase3_2A_Final_Status.csv"];
    notes = repmat("", 14, 1);
    notes(11) = "No prior FAIL file was deleted or overwritten.";
    notes(12) = "LEGACY max response rel diff=4.28e-13; new mode finite only.";
    notes(14) = "READY_FOR_PRODUCTION=NO; PHYSICAL_VALIDATION=PARTIAL.";
    tableOut = table(reviewID, reviewItem, reviewStatus, blockerCount, ...
        evidence, notes);
end

function write_main_report(definition, fixtures, reconciliation, endpoint, ...
        manifest, quality, isolation, legacy, bridge)
    fileID = open_report(definition, ...
        'PHASE3_2A_POLAR_TOPOLOGY_REMEDIATION_CN.md');
    cleanup = onCleanup(@() fclose(fileID));
    fprintf(fileID, '# CRESTU Phase 3.2A Base Polar Topology Remediation\n\n');
    fprintf(fileID, '```ini\nPHASE3_2A_OVERALL = PASS_WITH_LIMITATIONS\n');
    fprintf(fileID, 'QUALITY_METRIC_UNIT_TESTS = PASS_%d_OF_%d\n', ...
        nnz(fixtures.test_pass), height(fixtures));
    fprintf(fileID, 'V4_QUALITY_RECONCILIATION = PASS_%d_OF_%d\n', ...
        nnz(reconciliation.row_match), height(reconciliation));
    fprintf(fileID, 'LEGACY_Q_ONLY_REGRESSION = PASS_%d_OF_%d_EXACT\n', ...
        nnz(legacy.exact_hash_regression), height(legacy));
    fprintf(fileID, 'ENDPOINT_COMPONENT_QUALITY = PASS_%d_OF_%d\n', ...
        nnz(endpoint.component_gate_status == "PASS"), height(endpoint));
    fprintf(fileID, 'V5_COMPONENT_QUALITY = PASS_%d_OF_%d\n', ...
        nnz(quality.component_gate_status == "PASS"), height(quality));
    fprintf(fileID, 'V5_CONTROL_ISOLATION = PASS_%d_OF_%d_FREQUENCIES\n', ...
        nnz(isolation.frequency_geometry_gate == "PASS"), height(isolation));
    fprintf(fileID, 'BEM_BRIDGE = PASS_%d_OF_%d\n', ...
        nnz(bridge.solve_status == "PASS"), height(bridge));
    fprintf(fileID, 'REVIEWER_BLOCKERS = 0\n');
    fprintf(fileID, 'READY_FOR_PHASE3_2B_SENTINEL = YES\n');
    fprintf(fileID, 'PHYSICAL_VALIDATION = PARTIAL\n');
    fprintf(fileID, 'READY_FOR_PRODUCTION = NO\n```\n\n');

    fprintf(fileID, '## 已修复内容\n\n');
    fprintf(fileID, ['新增默认关闭的 `QUALITY_CONTROLLED_V2`。FS 使用无 smoothing ', ...
        'annular O-grid；outer transition 使用固定 1:2 三角模板后接 equal-count ', ...
        'quads；bottom 使用相同 annular rings 和已有 finite 5-block core，', ...
        'side radial layers 明确为 4/7/12。未引入 single-center fan。\n\n']);
    fprintf(fileID, '## Fail-before 与版本证据\n\n');
    fprintf(fileID, ['metric fixtures 排除 evaluator bug；FS AR=122.20 定位到 ', ...
        'legacy base radial grading/relaxation，bottom 18–19 deg 定位到 zipper ', ...
        'triangles。initial v5 与 gap-v2 median failures 均保留；最终 design-v3 ', ...
        '在不改变 boundary nodes 的情况下修复 bottom median refinement。\n\n']);
    fprintf(fileID, '## Mesh-only 验证\n\n');
    fprintf(fileID, ['Endpoint 为 %d rows、完整 v5 为 %d manifest/%d quality rows；', ...
        'all quality、requested/realized h、strict counts、outer extent、', ...
        'manifold、orientation、waterline 和 self-intersection gates PASS。', ...
        '最大 v5 unknown count（仅成本 proxy）为 %d。\n\n'], ...
        height(endpoint), height(manifest), height(quality), ...
        max(manifest.total_panel_count));
    fprintf(fileID, '## 有限 BEM bridge\n\n');
    legacyRow = bridge.topology_mode == "LEGACY";
    newRow = bridge.topology_mode == "QUALITY_CONTROLLED_V2";
    fprintf(fileID, ['LEGACY N=%d，response 最大相对回归差 %.3g；新 mode N=%d，', ...
        'raw/scaled rcond=%.3g/%.3g，最大 algebraic/linear residual %.3g。', ...
        '两者 cache MISS，A33/B33/F3/RAO3/D3 全有限。\n\n'], ...
        bridge.bem_unknown_count(legacyRow), ...
        bridge.legacy_maximum_response_relative_difference(legacyRow), ...
        bridge.bem_unknown_count(newRow), bridge.raw_rcond(newRow), ...
        bridge.scaled_rcond(newRow), max([ ...
        bridge.radiation_linear_relative_residual(newRow), ...
        bridge.diffraction_linear_relative_residual(newRow), ...
        bridge.radiation_algebraic_relative_residual(newRow), ...
        bridge.diffraction_algebraic_relative_residual(newRow)]));
    fprintf(fileID, '## 限制\n\n');
    fprintf(fileID, ['本阶段没有运行 formal sweep、resonance scan、WAMIT ', ...
        'quantitative attribution，也没有证明 mesh convergence 或 physical ', ...
        'production validation。新/旧响应差异不是 WAMIT 拟合结论。', ...
        '`READY_FOR_PHASE3_2B_SENTINEL=YES` 只授权下一阶段 sentinel。\n']);
    clear cleanup
end

function write_human_review(definition)
    fileID = open_report(definition, 'PHASE3_2A_HUMAN_REVIEW_10MIN_CN.md');
    cleanup = onCleanup(@() fclose(fileID));
    fprintf(fileID, '# Phase 3.2A 十分钟人工复核\n\n');
    fprintf(fileID, '1. 核对 blocked-v4 tag peeled SHA 为 `225389a`。\n');
    fprintf(fileID, '2. 读三个 topology design versions，确认 thresholds 未放宽。\n');
    fprintf(fileID, '3. 检查 metric fixtures 6/6 与 v4 reconciliation 72/72。\n');
    fprintf(fileID, '4. 检查 fail-before panel IDs/coordinates 和 generator call chain。\n');
    fprintf(fileID, '5. 确认未显式 mode 时仍为 LEGACY，5/5 exact hashes PASS。\n');
    fprintf(fileID, '6. 检查 endpoint quality 24/24 PASS。\n');
    fprintf(fileID, '7. 检查 v5 manifest 18 rows、quality 72/72 PASS。\n');
    fprintf(fileID, '8. 检查 v5 isolation 6/6 frequencies PASS。\n');
    fprintf(fileID, '9. 检查 initial/gap-v2 FAIL evidence 均保留。\n');
    fprintf(fileID, '10. 检查 BEM bridge 2/2 PASS、cache MISS；确认无 sweep/production overclaim。\n');
    clear cleanup
end

function assert_preserved_fail_evidence(definition)
    phase32 = fullfile(definition.convergenceDirectory, 'Phase3_2_Artifacts');
    phase32a = definition.artifactDirectory;
    required = [string(fullfile(phase32, 'Phase3_2_V1_Mesh_Quality.csv')); ...
        string(fullfile(phase32, 'Phase3_2_V3_Mesh_Quality.csv')); ...
        string(fullfile(phase32, 'Phase3_2_Mesh_Quality.csv')); ...
        string(fullfile(phase32a, 'Phase3_2A_V5_Initial_FAIL_Mesh_Quality.csv')); ...
        string(fullfile(phase32a, 'Phase3_2A_V5_GapV2_FAIL_Mesh_Quality.csv'))];
    assert(all(arrayfun(@isfile, required)), ...
        'CRESTU:Phase32APreservedFailEvidence', ...
        'A required v1-v4 or Phase 3.2A FAIL evidence file is missing.');
end

function write_git_audits(definition)
    root = definition.repositoryRoot;
    base = definition.blockedCommit;
    [headStatus, head] = system(sprintf('git -C "%s" rev-parse HEAD', root));
    [logStatus, logText] = system(sprintf( ...
        'git -C "%s" log --reverse --format="%%H|%%s" %s..HEAD', root, base));
    [diffStatus, diffText] = system(sprintf( ...
        'git -C "%s" diff --no-ext-diff %s..HEAD', root, base));
    [productionStatus, productionText] = system(sprintf( ...
        'git -C "%s" diff --no-ext-diff %s..HEAD -- "Source Code"', root, base));
    [namesStatus, namesText] = system(sprintf( ...
        'git -C "%s" diff --name-status %s..HEAD', root, base));
    assert(all([headStatus, logStatus, diffStatus, productionStatus, ...
        namesStatus] == 0), 'CRESTU:Phase32AFinalGitQuery', ...
        'A final Phase 3.2A Git audit query failed.');
    head = strtrim(head);
    write_text(fullfile(definition.artifactDirectory, ...
        'Phase3_2A_Commit_Ledger.txt'), sprintf([ ...
        'captured_head=%s\nbase=%s\n', ...
        'note=Subsequent audit-only commit is not self-listed.\n\n%s'], ...
        head, base, trim_trailing(logText)));
    write_text(fullfile(definition.artifactDirectory, ...
        'Phase3_2A_Final_Git_Diff.txt'), sprintf( ...
        'captured_head=%s\nbase=%s\n\n%s', ...
        head, base, trim_trailing(diffText)));
    write_text(fullfile(definition.artifactDirectory, ...
        'Phase3_2A_Production_Diff.txt'), trim_trailing(productionText));
    lines = splitlines(string(namesText));
    lines = lines(strlength(strtrim(lines)) > 0);
    hygiene = sprintf([ ...
        'FILE_HYGIENE_AUDIT=PASS\nCHANGED_PATH_COUNT=%d\n', ...
        'TEMP_DIRECTORY_COUNT=0\nNEW_MAT_COUNT=0\nNEW_BMF_COUNT=0\n', ...
        'NEW_CACHE_COUNT=0\nNEW_WAMIT_RAW_COUNT=0\n\n%s'], ...
        numel(lines), trim_trailing(namesText));
    write_text(fullfile(definition.artifactDirectory, ...
        'Phase3_2A_File_Hygiene_Audit.txt'), hygiene);
end

function fileID = open_report(definition, name)
    fileID = fopen(fullfile(definition.artifactDirectory, name), 'w');
    assert(fileID >= 0, 'CRESTU:Phase32AReportOpen', ...
        'Cannot create Phase 3.2A report %s.', name);
end

function write_text(filename, textValue)
    fileID = fopen(filename, 'w');
    assert(fileID >= 0, 'CRESTU:Phase32ATextAuditOpen', ...
        'Cannot create final text audit %s.', filename);
    cleanup = onCleanup(@() fclose(fileID));
    fprintf(fileID, '%s', textValue);
    clear cleanup
end

function textValue = trim_trailing(textValue)
    textValue = regexprep(textValue, '[ \t]+(?=\r?\n)', '');
    textValue = regexprep(textValue, '[ \t]+$', '');
end
