function summary = Run_Phase3_2A_Endpoint_Prototype()
% RUN_PHASE3_2A_ENDPOINT_PROTOTYPE Audit only omega=0.5/2.0 mesh endpoints.

    %% Stage 1: Verify frozen design and legacy exact regression evidence

    definition = phase32a.initialize();
    legacyFile = fullfile(definition.convergenceDirectory, ...
        'Phase3_2_Artifacts', 'Phase3_2_Legacy_Mesh_Regression.csv');
    legacy = readtable(legacyFile, 'TextType', 'string');
    assert(height(legacy) == 5 && all(legacy.exact_hash_regression), ...
        'CRESTU:Phase32AEndpointLegacyRegression', ...
        'Endpoint prototype requires 5/5 exact LEGACY geometry regression.');
    writetable(legacy, fullfile(definition.artifactDirectory, ...
        'Phase3_2A_Legacy_Regression.csv'));
    legacyAuditDefinition = phase32.definition();

    manifestTable = table();
    qualityTable = table();
    isolationTable = table();
    manifestFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2A_Endpoint_Prototype_Manifest.csv');
    qualityFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2A_Endpoint_Prototype_Quality.csv');
    isolationFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2A_Endpoint_Prototype_Control_Isolation.csv');

    %% Stage 2: Run three levels at low endpoint before high endpoint

    frequencies = definition.endpointFrequenciesRadPerS;
    for frequencyIndex = 1:numel(frequencies)
        omega = frequencies(frequencyIndex); % [rad/s]
        for levelIndex = 1:numel(definition.levels)
            level = definition.levels(levelIndex);
            fprintf('[INFO] Phase 3.2A endpoint | %.6g rad/s | %s\n', ...
                omega, level.name);
            specification = phase32a.create_case(definition, level, omega, ...
                'phase3_2a_endpoint_prototype');
            cleanup = onCleanup(@() phase32.remove_runtime( ...
                definition, specification.runtimeDirectory));
            timer = tic;
            try
                domain = build_bmf_domain(specification.configFile);
                generationRuntimeS = toc(timer);
                assert_runtime_scope(definition, specification, domain);
                [manifest, ~] = phase32.audit_domain( ...
                    legacyAuditDefinition, specification, domain, ...
                    generationRuntimeS);
                manifest.phase32a_design_v2_canonical_sha256 = ...
                    string(definition.designV2CanonicalSHA256);
                manifest.phase32a_design_v2_git_blob_id = ...
                    string(definition.designV2GitBlobID);
                manifest.phase32a_design_v3_canonical_sha256 = ...
                    string(definition.designV3CanonicalSHA256);
                manifest.phase32a_design_v3_git_blob_id = ...
                    string(definition.designV3GitBlobID);
                manifest.connector_gap_coefficient = 0.4;
                bottomCore = domain.seabed.quality_controlled_bottom_core;
                manifest.requested_bottom_core_radial_layer_count = ...
                    level.bottomCoreRadialLayerCount;
                manifest.realized_bottom_core_radial_layer_count = ...
                    bottomCore.realizedRadialLayerCount;
                manifest.bottom_core_structured_panel_count = ...
                    bottomCore.totalStructuredCorePanelCount;
                currentManifest = struct2table(manifest);
                currentQuality = evaluate_endpoint_components( ...
                    definition, specification, domain, manifest);
                manifestTable = append_table(manifestTable, currentManifest);
                qualityTable = append_table(qualityTable, currentQuality);
                writetable(manifestTable, manifestFile);
                writetable(qualityTable, qualityFile);
            catch exception
                failure = endpoint_failure_row(specification, exception);
                qualityTable = append_table(qualityTable, failure);
                writetable(qualityTable, qualityFile);
                clear cleanup
                rethrow(exception)
            end
            clear cleanup
        end

        currentManifest = manifestTable( ...
            abs(manifestTable.omega_rad_s - omega) <= 64 * eps(max(1, omega)), :);
        currentQuality = qualityTable( ...
            abs(qualityTable.omega_rad_s - omega) <= 64 * eps(max(1, omega)), :);
        currentIsolation = evaluate_frequency_isolation( ...
            definition, omega, currentManifest, currentQuality);
        isolationTable = append_table(isolationTable, currentIsolation);
        writetable(isolationTable, isolationFile);
        assert(currentIsolation.endpoint_frequency_gate == "PASS", ...
            'CRESTU:Phase32AEndpointFrequencyGate', ...
            'Endpoint %.6g rad/s failed; high/expanded cases are forbidden.', omega);
    end

    %% Stage 3: Enforce the complete six-case endpoint hard gate

    qualityPass = height(qualityTable) == 24 && ...
        all(qualityTable.component_gate_status == "PASS");
    topologyPass = all(manifestTable.manifold_status == "PASS") && ...
        all(manifestTable.normal_orientation_status == "PASS") && ...
        all(manifestTable.waterline_continuity_status == "PASS") && ...
        all(manifestTable.self_intersection_status == "PASS");
    isolationPass = height(isolationTable) == 2 && ...
        all(isolationTable.endpoint_frequency_gate == "PASS");
    overallPass = qualityPass && topologyPass && isolationPass;
    statusName = ["ENDPOINT_COMPONENT_QUALITY"; "ENDPOINT_TOPOLOGY"; ...
        "ENDPOINT_CONTROL_ISOLATION"; "LEGACY_Q_ONLY_REGRESSION"; ...
        "ENDPOINT_PROTOTYPE_OVERALL"];
    statusValue = [pass_fail(qualityPass); pass_fail(topologyPass); ...
        pass_fail(isolationPass); "PASS_EXACT_HASH_5_OF_5"; ...
        pass_fail(overallPass)];
    evidence = ["Phase3_2A_Endpoint_Prototype_Quality.csv"; ...
        "Phase3_2A_Endpoint_Prototype_Manifest.csv"; ...
        "Phase3_2A_Endpoint_Prototype_Control_Isolation.csv"; ...
        "Phase3_2A_Legacy_Regression.csv"; ...
        "all endpoint hard gates"];
    writetable(table(statusName, statusValue, evidence), ...
        fullfile(definition.artifactDirectory, ...
        'Phase3_2A_Endpoint_Prototype_Status.csv'));
    summary = struct('schemaVersion', 1, 'meshOnlyCaseCount', 6, ...
        'componentQualityRowCount', height(qualityTable), ...
        'componentQualityPassCount', nnz( ...
            qualityTable.component_gate_status == "PASS"), ...
        'qualityPass', qualityPass, 'topologyPass', topologyPass, ...
        'isolationPass', isolationPass, 'overallPass', overallPass);
    fprintf('[RESULT] PHASE3_2A_ENDPOINT_PROTOTYPE = %s\n', ...
        pass_fail(overallPass));
    assert(overallPass, 'CRESTU:Phase32AEndpointOverallGate', ...
        'Phase 3.2A endpoint prototype did not pass every hard gate.');
end

function tableOut = evaluate_endpoint_components( ...
        definition, specification, domain, manifest)
    components = {domain.body_list{1}, domain.fs, ...
        domain.seabed, domain.farfield};
    names = ["body"; "free_surface"; "bottom"; "farfield"];
    polar = domain.fs.quality_controlled_polar;
    truncation = domain.cfg.outer_truncation.effective;
    rows = repmat(endpoint_quality_row(), numel(components), 1);
    for index = 1:numel(components)
        [quality, ~] = phase32a.evaluate_component_quality( ...
            components{index}, names(index), definition);
        rows(index) = endpoint_quality_row();
        fields = fieldnames(quality);
        for fieldIndex = 1:numel(fields)
            rows(index).(fields{fieldIndex}) = quality.(fields{fieldIndex});
        end
        rows(index).mesh_level = specification.level.name;
        rows(index).mesh_level_index = specification.level.index;
        rows(index).omega_rad_s = specification.omegaRadPerS;
        rows(index).topology_mode = string(definition.topologyMode);
        rows(index).design_v2_canonical_sha256 = ...
            string(definition.designV2CanonicalSHA256);
        rows(index).design_v2_git_blob_id = string(definition.designV2GitBlobID);
        rows(index).design_v3_canonical_sha256 = ...
            string(definition.designV3CanonicalSHA256);
        rows(index).design_v3_git_blob_id = string(definition.designV3GitBlobID);
        rows(index).connector_gap_coefficient = 0.4;
        rows(index).requested_near_radial_step_m = ...
            polar.requestedNearRadialStepM;
        rows(index).realized_near_radial_step_m = ...
            polar.realizedNearRadialStepM;
        rows(index).requested_outer_radial_step_max_m = ...
            polar.requestedOuterRadialStepMaxM;
        rows(index).realized_outer_radial_step_m = ...
            polar.realizedOuterRadialStepM;
        rows(index).configured_outer_radial_layer_count = ...
            polar.configuredOuterRadialLayerCount;
        rows(index).realized_outer_radial_layer_count = ...
            polar.realizedOuterRadialLayerCount;
        rows(index).base_theta_count = polar.thetaNodeCount;
        rows(index).final_wall_theta_count = ...
            truncation.commonOuterThetaNodeCount;
        bottomCore = domain.seabed.quality_controlled_bottom_core;
        rows(index).requested_bottom_core_radial_layer_count = ...
            specification.level.bottomCoreRadialLayerCount;
        rows(index).realized_bottom_core_radial_layer_count = ...
            bottomCore.realizedRadialLayerCount;
        rows(index).bottom_core_structured_panel_count = ...
            bottomCore.totalStructuredCorePanelCount;
        rows(index).top_connector_minimum_angle_deg = ...
            truncation.topSurfaceDerived.oneToTwoConnectorAudit.minimumAngleDeg;
        rows(index).top_connector_maximum_aspect_ratio = ...
            truncation.topSurfaceDerived.oneToTwoConnectorAudit.maximumAspectRatio;
        rows(index).bottom_connector_minimum_angle_deg = ...
            truncation.bottomSurfaceDerived.oneToTwoConnectorAudit.minimumAngleDeg;
        rows(index).bottom_connector_maximum_aspect_ratio = ...
            truncation.bottomSurfaceDerived.oneToTwoConnectorAudit.maximumAspectRatio;
        rows(index).transition_median_sqrt_area_m = ...
            manifest.transition_median_sqrt_area_m;
        rows(index).manifold_status = manifest.manifold_status;
        rows(index).orientation_status = manifest.normal_orientation_status;
        rows(index).waterline_status = manifest.waterline_continuity_status;
        rows(index).self_intersection_status = ...
            manifest.self_intersection_status;
        rows(index).actual_top_outer_radius_m = ...
            manifest.actual_top_outer_radius_m;
        rows(index).actual_bottom_outer_radius_m = ...
            manifest.actual_bottom_outer_radius_m;
        rows(index).combined_geometry_hash = manifest.combined_geometry_hash;
        rows(index).production_source_hash = manifest.production_source_hash;
        rows(index).runtime_provenance = "PASS_CURRENT_WORKTREE";
        rows(index).error_identifier = "";
        rows(index).error_message = "";
    end
    tableOut = struct2table(rows);
end

function tableOut = evaluate_frequency_isolation( ...
        definition, omega, manifest, quality)
    manifest = sortrows(manifest, 'mesh_level_index');
    quality = sortrows(quality, {'component', 'mesh_level_index'});
    levelCount = numel(definition.levels);
    countPass = height(manifest) == levelCount && ...
        all(diff(manifest.body_panel_count) > 0) && ...
        all(diff(manifest.free_surface_panel_count) > 0) && ...
        all(diff(manifest.bottom_panel_count) > 0) && ...
        all(diff(manifest.farfield_panel_count) > 0);
    hPass = true;
    componentNames = unique(quality.component, 'stable');
    for index = 1:numel(componentNames)
        rows = quality.component == componentNames(index);
        componentRows = sortrows(quality(rows, :), 'mesh_level_index');
        hPass = hPass && height(componentRows) == levelCount && ...
            all(diff(componentRows.mean_sqrt_area_m) < 0) && ...
            all(diff(componentRows.median_sqrt_area_m) < 0);
    end
    transitionRows = sortrows(quality(quality.component == "free_surface", :), ...
        'mesh_level_index');
    transitionPass = all(diff( ...
        transitionRows.transition_median_sqrt_area_m) < 0);
    extentPass = max(manifest.actual_top_outer_radius_m) - ...
        min(manifest.actual_top_outer_radius_m) <= ...
        definition.geometryToleranceM && ...
        max(manifest.actual_bottom_outer_radius_m) - ...
        min(manifest.actual_bottom_outer_radius_m) <= ...
        definition.geometryToleranceM;
    qualityPass = height(quality) == 4 * levelCount && ...
        all(quality.component_gate_status == "PASS");
    topologyPass = all(manifest.manifold_status == "PASS") && ...
        all(manifest.normal_orientation_status == "PASS") && ...
        all(manifest.waterline_continuity_status == "PASS") && ...
        all(manifest.self_intersection_status == "PASS");
    hashPass = numel(unique(manifest.combined_geometry_hash)) == levelCount;
    gatePass = countPass && hPass && transitionPass && extentPass && ...
        qualityPass && topologyPass && hashPass;
    tableOut = table(omega, levelCount, countPass, hPass, transitionPass, ...
        extentPass, qualityPass, topologyPass, hashPass, pass_fail(gatePass), ...
        'VariableNames', {'omega_rad_s', 'level_count', ...
        'all_region_counts_strictly_increase', ...
        'all_component_mean_median_h_strictly_decrease', ...
        'transition_median_h_strictly_decreases', ...
        'same_frequency_outer_extent_exact', ...
        'all_component_quality_rows_pass', 'all_topology_contracts_pass', ...
        'combined_hashes_distinct', 'endpoint_frequency_gate'});
end

function row = endpoint_quality_row()
    row = struct('mesh_level', "", 'mesh_level_index', 0, ...
        'omega_rad_s', NaN, 'topology_mode', "", ...
        'design_v2_canonical_sha256', "", 'design_v2_git_blob_id', "", ...
        'design_v3_canonical_sha256', "", 'design_v3_git_blob_id', "", ...
        'connector_gap_coefficient', NaN, 'component', "", ...
        'panel_count', 0, 'minimum_panel_area_m2', NaN, ...
        'maximum_panel_area_m2', NaN, 'median_panel_area_m2', NaN, ...
        'mean_sqrt_area_m', NaN, 'median_sqrt_area_m', NaN, ...
        'minimum_edge_length_m', NaN, 'maximum_aspect_ratio', NaN, ...
        'maximum_skewness_deg', NaN, 'minimum_corner_angle_deg', NaN, ...
        'maximum_corner_angle_deg', NaN, 'maximum_warp_deg', NaN, ...
        'poor_panel_count', 0, 'poor_panel_fraction', NaN, ...
        'finite_positive_geometry', false, 'duplicate_panel_count', 0, ...
        'component_gate_pass', false, 'component_gate_status', "NOT_RUN", ...
        'requested_near_radial_step_m', NaN, ...
        'realized_near_radial_step_m', NaN, ...
        'requested_outer_radial_step_max_m', NaN, ...
        'realized_outer_radial_step_m', NaN, ...
        'configured_outer_radial_layer_count', 0, ...
        'realized_outer_radial_layer_count', 0, ...
        'base_theta_count', 0, 'final_wall_theta_count', 0, ...
        'requested_bottom_core_radial_layer_count', 0, ...
        'realized_bottom_core_radial_layer_count', 0, ...
        'bottom_core_structured_panel_count', 0, ...
        'top_connector_minimum_angle_deg', NaN, ...
        'top_connector_maximum_aspect_ratio', NaN, ...
        'bottom_connector_minimum_angle_deg', NaN, ...
        'bottom_connector_maximum_aspect_ratio', NaN, ...
        'transition_median_sqrt_area_m', NaN, ...
        'manifold_status', "NOT_RUN", 'orientation_status', "NOT_RUN", ...
        'waterline_status', "NOT_RUN", ...
        'self_intersection_status', "NOT_RUN", ...
        'actual_top_outer_radius_m', NaN, ...
        'actual_bottom_outer_radius_m', NaN, ...
        'combined_geometry_hash', "", 'production_source_hash', "", ...
        'runtime_provenance', "", 'error_identifier', "", ...
        'error_message', "");
end

function tableOut = endpoint_failure_row(specification, exception)
    row = endpoint_quality_row();
    row.mesh_level = specification.level.name;
    row.mesh_level_index = specification.level.index;
    row.omega_rad_s = specification.omegaRadPerS;
    row.topology_mode = "QUALITY_CONTROLLED_V2";
    row.component = "case_build";
    row.component_gate_status = "FAIL";
    row.error_identifier = string(exception.identifier);
    row.error_message = string(exception.message);
    tableOut = struct2table(row);
end

function combined = append_table(combined, current)
    if isempty(combined)
        combined = current;
    else
        combined = [combined; current];
    end
end

function assert_runtime_scope(definition, specification, domain)
    paths = [string(specification.configFile); string(specification.bodyFile); ...
        string(domain.cfg.files.fs); string(domain.cfg.files.seabed); ...
        string(domain.cfg.files.farfield)];
    runtimePrefix = lower(string(specification.runtimeDirectory) + filesep);
    for index = 1:numel(paths)
        normalized = lower(strrep(paths(index), '/', filesep));
        assert(startsWith(normalized, runtimePrefix) && ...
            ~contains(normalized, lower(definition.originalRepository)), ...
            'CRESTU:Phase32AEndpointRuntimeScope', ...
            'Endpoint prototype path escaped the isolated current-worktree case.');
    end
end

function text = pass_fail(value)
    if value
        text = "PASS";
    else
        text = "FAIL";
    end
end
