function summary = Run_Phase3_2A_Quality_Metric_Unit_Tests(reconcileV4)
% RUN_PHASE3_2A_QUALITY_METRIC_UNIT_TESTS Validate metrics before topology work.

    arguments
        reconcileV4 (1, 1) logical = true
    end

    %% Stage 1: Analytic triangle/quad fixtures

    definition = phase32a.initialize();
    fixtureTable = run_analytic_fixtures();
    fixtureFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2A_Quality_Metric_Unit_Tests.csv');
    writetable(fixtureTable, fixtureFile);
    assert(all(fixtureTable.test_pass), ...
        'CRESTU:Phase32AQualityFixtureFailure', ...
        'At least one analytic panel-quality fixture failed.');

    %% Stage 2: Recompute all 72 blocked-v4 component rows from meshes

    reconciliationTable = table();
    if reconcileV4
        reconciliationTable = reconcile_v4_mesh_quality(definition);
        assert(height(reconciliationTable) == 72 && ...
            all(reconciliationTable.row_match), ...
            'CRESTU:Phase32AV4QualityReconciliation', ...
            'The independent evaluator did not reproduce all 72 v4 rows.');
    end

    rawQualityFile = fullfile(definition.convergenceDirectory, ...
        'Phase3_2_Artifacts', 'Phase3_2_Mesh_Quality.csv');
    rawQuality = readtable(rawQualityFile, 'TextType', 'string');
    rawPass = nnz(rawQuality.component_gate_status == "PASS");
    rawFail = nnz(rawQuality.component_gate_status == "FAIL");
    if reconcileV4
        recomputedPass = nnz(reconciliationTable.recomputed_status == "PASS");
        recomputedFail = nnz(reconciliationTable.recomputed_status == "FAIL");
    else
        recomputedPass = NaN;
        recomputedFail = NaN;
    end
    summary = struct('schemaVersion', 1, ...
        'analyticFixtureCount', height(fixtureTable), ...
        'analyticFixturesPass', all(fixtureTable.test_pass), ...
        'rawQualityRowCount', height(rawQuality), ...
        'rawQualityPassCount', rawPass, 'rawQualityFailCount', rawFail, ...
        'meshReconciliationExecuted', reconcileV4, ...
        'meshRecomputedPassCount', recomputedPass, ...
        'meshRecomputedFailCount', recomputedFail, ...
        'basePolarTopologyClassification', 'PRIMARY_DESIGN_LIMITATION');
    assert(height(rawQuality) == 72 && rawPass == 36 && rawFail == 36, ...
        'CRESTU:Phase32ARawQualityCounts', ...
        'Blocked-v4 raw quality row counts are not 72/36/36.');
    if reconcileV4
        assert(recomputedPass == 36 && recomputedFail == 36, ...
            'CRESTU:Phase32ARecomputedQualityCounts', ...
            'Mesh-recomputed quality row counts are not 36/36.');
    end
    fprintf('[RESULT] QUALITY_METRIC_FIXTURES = PASS (%d/%d)\n', ...
        nnz(fixtureTable.test_pass), height(fixtureTable));
    fprintf('[RESULT] V4_COMPONENT_QUALITY_ROWS = %d/%d/%d total/pass/fail\n', ...
        height(rawQuality), rawPass, rawFail);
    fprintf('[RESULT] BASE_POLAR_TOPOLOGY = PRIMARY_DESIGN_LIMITATION\n');
end

function tableOut = run_analytic_fixtures()
% RUN_ANALYTIC_FIXTURES Exercise exact metric and defect behavior.

    rootThree = sqrt(3.0);
    triangle = reshape([0, 0, 0; 1, 0, 0; ...
        0.5, rootThree / 2, 0; 0.5, rootThree / 2, 0], 1, 4, 3);
    square = reshape([0, 0, 0; 1, 0, 0; 1, 1, 0; 0, 1, 0], ...
        1, 4, 3);
    rectangle = reshape([0, 0, 0; 10, 0, 0; 10, 1, 0; 0, 1, 0], ...
        1, 4, 3);
    sliver = reshape([0, 0, 0; 1, 0, 0; 1.0e-3, 1.0e-4, 0; ...
        1.0e-3, 1.0e-4, 0], 1, 4, 3);
    reversed = reshape([0, 0, 0; 0, 1, 0; 1, 1, 0; 1, 0, 0], ...
        1, 4, 3);
    duplicate = cat(1, square, square);
    names = ["regular_triangle"; "square_quad"; "rectangle_10_to_1"; ...
        "sliver_triangle"; "reversed_panel"; "duplicate_panel"];
    behaviors = ["ACCEPTED_REFERENCE"; "ACCEPTED_REFERENCE"; ...
        "ASPECT_RATIO_FAIL"; "MINIMUM_ANGLE_FAIL"; ...
        "REVERSED_ORIENTATION_DETECTED"; "DUPLICATE_DETECTED"];
    vertices = {triangle; square; rectangle; sliver; reversed; duplicate};
    triangleArea = rootThree / 4;
    sliverArea = 5.0e-5;
    sliverAspect = 1.0 / hypot(1.0e-3, 1.0e-4);
    sliverMinimumAngle = atand(1.0e-4 / (1.0 - 1.0e-3));
    expectedAspect = [1; 1; 10; sliverAspect; 1; 1];
    expectedMinimumAngle = [60; 90; 90; sliverMinimumAngle; 90; 90];
    expectedTotalArea = [triangleArea; 1; 10; sliverArea; 1; 2];
    expectedOrientation = [1; 1; 1; 1; -1; 1];
    expectedDuplicateCount = [0; 0; 0; 0; 0; 1];
    expectedMedianH = [sqrt(triangleArea); 1; sqrt(10); ...
        sqrt(sliverArea); 1; 1];
    rowTemplate = struct('fixture', "", 'expected_behavior', "", ...
        'panel_count', 0, 'expected_aspect_ratio', NaN, ...
        'actual_maximum_aspect_ratio', NaN, ...
        'expected_minimum_angle_deg', NaN, ...
        'actual_minimum_angle_deg', NaN, ...
        'expected_total_area_m2', NaN, 'actual_total_area_m2', NaN, ...
        'expected_minimum_orientation_alignment', NaN, ...
        'actual_minimum_orientation_alignment', NaN, ...
        'expected_duplicate_panel_count', 0, ...
        'actual_duplicate_panel_count', 0, ...
        'expected_median_characteristic_h_m', NaN, ...
        'actual_median_characteristic_h_m', NaN, 'test_pass', false);
    rows = repmat(rowTemplate, numel(names), 1);
    tolerance = 1.0e-8;
    for index = 1:numel(names)
        expectedNormals = repmat([0, 0, 1], size(vertices{index}, 1), 1);
        result = phase32a.evaluate_panels(vertices{index}, ...
            expectedNormals, 1.0e-12);
        actualOrientation = min(result.orientationAlignment);
        pass = relative_match(max(result.aspectRatio), ...
            expectedAspect(index), tolerance) && ...
            relative_match(min(result.minimumAngleDeg), ...
            expectedMinimumAngle(index), tolerance) && ...
            relative_match(result.totalAreaM2, expectedTotalArea(index), ...
            tolerance) && ...
            abs(actualOrientation - expectedOrientation(index)) <= tolerance && ...
            result.duplicatePanelCount == expectedDuplicateCount(index) && ...
            relative_match(result.medianCharacteristicHM, ...
            expectedMedianH(index), tolerance);
        rows(index) = struct('fixture', names(index), ...
            'expected_behavior', behaviors(index), ...
            'panel_count', result.panelCount, ...
            'expected_aspect_ratio', expectedAspect(index), ...
            'actual_maximum_aspect_ratio', max(result.aspectRatio), ...
            'expected_minimum_angle_deg', expectedMinimumAngle(index), ...
            'actual_minimum_angle_deg', min(result.minimumAngleDeg), ...
            'expected_total_area_m2', expectedTotalArea(index), ...
            'actual_total_area_m2', result.totalAreaM2, ...
            'expected_minimum_orientation_alignment', ...
                expectedOrientation(index), ...
            'actual_minimum_orientation_alignment', actualOrientation, ...
            'expected_duplicate_panel_count', expectedDuplicateCount(index), ...
            'actual_duplicate_panel_count', result.duplicatePanelCount, ...
            'expected_median_characteristic_h_m', expectedMedianH(index), ...
            'actual_median_characteristic_h_m', ...
                result.medianCharacteristicHM, 'test_pass', pass);
    end
    tableOut = struct2table(rows);
end

function tableOut = reconcile_v4_mesh_quality(definition)
% RECONCILE_V4_MESH_QUALITY Regenerate meshes, never old result CSVs.

    blockedArtifact = fullfile(definition.convergenceDirectory, ...
        'Phase3_2_Artifacts');
    raw = readtable(fullfile(blockedArtifact, ...
        'Phase3_2_Mesh_Quality.csv'), 'TextType', 'string');
    v4 = phase32.definition();
    levels = v4.levels;
    frequencies = v4.sentinelFrequenciesRadPerS;
    rowTemplate = reconciliation_row();
    rows = repmat(rowTemplate, 0, 1);
    outputFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2A_V4_Quality_Reconciliation.csv');
    caseCount = numel(levels) * numel(frequencies);
    completed = 0;
    for frequencyIndex = 1:numel(frequencies)
        omega = frequencies(frequencyIndex); % [rad/s]
        for levelIndex = 1:numel(levels)
            level = levels(levelIndex);
            completed = completed + 1;
            fprintf('[INFO] V4 quality reconciliation %d/%d | %s | %.6g rad/s\n', ...
                completed, caseCount, level.name, omega);
            specification = phase32.create_case(v4, level, omega, ...
                'phase3_2a_v4_quality_reconciliation');
            cleanup = onCleanup(@() phase32.remove_runtime( ...
                v4, specification.runtimeDirectory));
            domain = build_bmf_domain(specification.configFile);
            components = {domain.body_list{1}, domain.fs, ...
                domain.seabed, domain.farfield};
            names = ["body"; "free_surface"; "bottom"; "farfield"];
            for componentIndex = 1:numel(components)
                [recomputed, ~] = phase32a.evaluate_component_quality( ...
                    components{componentIndex}, names(componentIndex), definition);
                rawRows = raw.mesh_level == level.name & ...
                    abs(raw.omega_rad_s - omega) <= 64 * eps(max(1, omega)) & ...
                    raw.component == names(componentIndex);
                assert(nnz(rawRows) == 1, ...
                    'CRESTU:Phase32AV4RawQualityRow', ...
                    'Expected one blocked-v4 raw component row.');
                expected = raw(rawRows, :);
                rows(end + 1, 1) = compare_quality_row( ...
                    level.name, omega, names(componentIndex), ...
                    expected, recomputed); %#ok<AGROW>
            end
            writetable(struct2table(rows), outputFile);
            clear cleanup
        end
    end
    tableOut = struct2table(rows);
    rawPass = nnz(raw.component_gate_status == "PASS");
    rawFail = nnz(raw.component_gate_status == "FAIL");
    recomputedPass = nnz(tableOut.recomputed_status == "PASS");
    recomputedFail = nnz(tableOut.recomputed_status == "FAIL");
    assert(height(raw) == 72 && height(tableOut) == 72 && ...
        rawPass == 36 && rawFail == 36 && ...
        recomputedPass == 36 && recomputedFail == 36, ...
        'CRESTU:Phase32AV4QualityCountReconciliation', ...
        'Raw/mesh-recomputed v4 quality counts differ from 72/36/36.');
end

function row = compare_quality_row(levelName, omega, componentName, ...
        expected, actual)
    numericNames = ["panel_count"; "minimum_panel_area_m2"; ...
        "maximum_panel_area_m2"; "median_panel_area_m2"; ...
        "mean_sqrt_area_m"; "median_sqrt_area_m"; ...
        "minimum_edge_length_m"; "maximum_aspect_ratio"; ...
        "maximum_skewness_deg"; "minimum_corner_angle_deg"; ...
        "maximum_corner_angle_deg"; "maximum_warp_deg"; ...
        "poor_panel_count"; "poor_panel_fraction"];
    maximumRelativeDifference = 0.0;
    numericMatch = true;
    for index = 1:numel(numericNames)
        name = numericNames(index);
        expectedValue = expected.(name)(1);
        actualValue = actual.(name);
        relativeDifference = abs(actualValue - expectedValue) / ...
            max([abs(actualValue), abs(expectedValue), 1.0e-14]);
        maximumRelativeDifference = max(maximumRelativeDifference, ...
            relativeDifference);
        numericMatch = numericMatch && relativeDifference <= 1.0e-10;
    end
    statusMatch = expected.component_gate_status(1) == ...
        actual.component_gate_status;
    rowMatch = numericMatch && statusMatch;
    row = struct('mesh_level', string(levelName), 'omega_rad_s', omega, ...
        'component', string(componentName), ...
        'raw_panel_count', expected.panel_count(1), ...
        'recomputed_panel_count', actual.panel_count, ...
        'raw_maximum_aspect_ratio', expected.maximum_aspect_ratio(1), ...
        'recomputed_maximum_aspect_ratio', actual.maximum_aspect_ratio, ...
        'raw_minimum_corner_angle_deg', ...
            expected.minimum_corner_angle_deg(1), ...
        'recomputed_minimum_corner_angle_deg', ...
            actual.minimum_corner_angle_deg, ...
        'raw_poor_panel_fraction', expected.poor_panel_fraction(1), ...
        'recomputed_poor_panel_fraction', actual.poor_panel_fraction, ...
        'raw_status', expected.component_gate_status(1), ...
        'recomputed_status', actual.component_gate_status, ...
        'maximum_numeric_relative_difference', maximumRelativeDifference, ...
        'numeric_match', numericMatch, 'status_match', statusMatch, ...
        'row_match', rowMatch);
end

function row = reconciliation_row()
    row = struct('mesh_level', "", 'omega_rad_s', NaN, ...
        'component', "", 'raw_panel_count', 0, ...
        'recomputed_panel_count', 0, 'raw_maximum_aspect_ratio', NaN, ...
        'recomputed_maximum_aspect_ratio', NaN, ...
        'raw_minimum_corner_angle_deg', NaN, ...
        'recomputed_minimum_corner_angle_deg', NaN, ...
        'raw_poor_panel_fraction', NaN, ...
        'recomputed_poor_panel_fraction', NaN, ...
        'raw_status', "", 'recomputed_status', "", ...
        'maximum_numeric_relative_difference', NaN, ...
        'numeric_match', false, 'status_match', false, 'row_match', false);
end

function value = relative_match(actual, expected, tolerance)
    value = abs(actual - expected) <= tolerance * ...
        max([abs(actual), abs(expected), 1.0]);
end
