function tableOut = Run_Phase3_2A_V5_Bottom_Median_Diagnostic()
% RUN_PHASE3_2A_V5_BOTTOM_MEDIAN_DIAGNOSTIC Partition omega=1 bottom h.

    definition = phase32a.initialize();
    rows = repmat(struct('mesh_level', "", 'region', "", ...
        'panel_count', 0, 'minimum_h_m', NaN, 'q25_h_m', NaN, ...
        'median_h_m', NaN, 'q75_h_m', NaN, 'maximum_h_m', NaN, ...
        'mean_h_m', NaN, 'base_annulus_panel_count', 0, ...
        'structured_core_panel_count', 0, ...
        'outer_truncation_panel_count', 0), 0, 1);
    omega = 1.0; % [rad/s]
    for levelIndex = 1:numel(definition.levels)
        level = definition.levels(levelIndex);
        specification = phase32a.create_case(definition, level, omega, ...
            'phase3_2a_v5_bottom_median_diagnostic');
        cleanup = onCleanup(@() phase32.remove_runtime( ...
            definition, specification.runtimeDirectory));
        domain = build_bmf_domain(specification.configFile);
        truncation = domain.cfg.outer_truncation.effective;
        polar = domain.fs.quality_controlled_polar;
        baseAnnulusPanelCount = polar.thetaNodeCount * ...
            (polar.nearRadialLayerCount + polar.realizedOuterRadialLayerCount);
        beforeBottomCount = truncation.componentPanelCountsBefore(2);
        structuredCorePanelCount = beforeBottomCount - baseAnnulusPanelCount;
        outerTruncationPanelCount = domain.seabed.n_panels - beforeBottomCount;
        assert(all([baseAnnulusPanelCount, structuredCorePanelCount, ...
            outerTruncationPanelCount] > 0), ...
            'CRESTU:Phase32ABottomPartition', ...
            'Bottom diagnostic partition has an empty region.');
        regions = {1:baseAnnulusPanelCount; ...
            baseAnnulusPanelCount + (1:structuredCorePanelCount); ...
            beforeBottomCount + (1:outerTruncationPanelCount); ...
            1:domain.seabed.n_panels};
        names = ["BASE_ANNULAR_O_GRID"; "STRUCTURED_5_BLOCK_CORE"; ...
            "OUTER_FIXED_1_TO_2_AND_EQUAL_RINGS"; "ALL_BOTTOM"];
        for regionIndex = 1:numel(regions)
            h = sort(sqrt(domain.seabed.areas(regions{regionIndex})));
            rows(end + 1, 1) = struct('mesh_level', level.name, ...
                'region', names(regionIndex), 'panel_count', numel(h), ...
                'minimum_h_m', h(1), 'q25_h_m', percentile(h, 0.25), ...
                'median_h_m', median(h), 'q75_h_m', percentile(h, 0.75), ...
                'maximum_h_m', h(end), 'mean_h_m', mean(h), ...
                'base_annulus_panel_count', baseAnnulusPanelCount, ...
                'structured_core_panel_count', structuredCorePanelCount, ...
                'outer_truncation_panel_count', outerTruncationPanelCount); %#ok<AGROW>
        end
        clear cleanup
    end
    tableOut = struct2table(rows);
    writetable(tableOut, fullfile(definition.artifactDirectory, ...
        'Phase3_2A_V5_Bottom_Median_Diagnostics.csv'));
end

function value = percentile(sortedValues, fraction)
    position = 1 + fraction * (numel(sortedValues) - 1);
    lowerIndex = floor(position);
    upperIndex = ceil(position);
    weight = position - lowerIndex;
    value = (1 - weight) * sortedValues(lowerIndex) + ...
        weight * sortedValues(upperIndex);
end
