function summary = Run_Phase3_2A_V5_Mesh_Family()
% RUN_PHASE3_2A_V5_MESH_FAMILY Run 6 frequencies x 3 levels, mesh only.

    %% Stage 1: Verify endpoint and legacy prerequisites

    definition = phase32a.initialize();
    endpointCells = readcell(fullfile(definition.artifactDirectory, ...
        'Phase3_2A_Endpoint_Prototype_Status.csv'));
    endpointNames = string(endpointCells(2:end, 1));
    endpointValues = string(endpointCells(2:end, 2));
    endpointRow = endpointNames == "ENDPOINT_PROTOTYPE_OVERALL";
    assert(nnz(endpointRow) == 1 && endpointValues(endpointRow) == "PASS", ...
        'CRESTU:Phase32AV5EndpointPrerequisite', ...
        'V5 full mesh family requires endpoint prototype PASS.');
    legacy = readtable(fullfile(definition.artifactDirectory, ...
        'Phase3_2A_Legacy_Regression.csv'), 'TextType', 'string');
    assert(height(legacy) == 5 && all(legacy.exact_hash_regression), ...
        'CRESTU:Phase32AV5LegacyPrerequisite', ...
        'V5 full mesh family requires 5/5 exact legacy regression.');
    preservedFiles = ["Phase3_2_V1_Mesh_Manifest.csv"; ...
        "Phase3_2_V1_Mesh_Quality.csv"; "Phase3_2_V3_Mesh_Manifest.csv"; ...
        "Phase3_2_V3_Mesh_Quality.csv"; "Phase3_2_Mesh_Manifest.csv"; ...
        "Phase3_2_Mesh_Quality.csv"];
    blockedArtifact = fullfile(definition.convergenceDirectory, ...
        'Phase3_2_Artifacts');
    assert(all(arrayfun(@(name) isfile(fullfile(blockedArtifact, name)), ...
        preservedFiles)), 'CRESTU:Phase32AV5FailEvidenceMissing', ...
        'A preserved v1-v4 FAIL evidence file is missing.');

    manifestTable = table();
    qualityTable = table();
    isolationTable = table();
    manifestFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2A_V5_Mesh_Manifest.csv');
    qualityFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2A_V5_Mesh_Quality.csv');
    isolationFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2A_V5_Control_Isolation.csv');

    %% Stage 2: Regenerate every case in a unique directory

    frequencies = definition.sentinelFrequenciesRadPerS;
    caseCount = numel(frequencies) * numel(definition.levels);
    completed = 0;
    for frequencyIndex = 1:numel(frequencies)
        omega = frequencies(frequencyIndex); % [rad/s]
        for levelIndex = 1:numel(definition.levels)
            level = definition.levels(levelIndex);
            completed = completed + 1;
            fprintf('[INFO] Phase 3.2A v5 mesh %d/%d | %.6g rad/s | %s\n', ...
                completed, caseCount, omega, level.name);
            specification = phase32a.create_case(definition, level, omega, ...
                'phase3_2a_v5_mesh_family');
            cleanup = onCleanup(@() phase32.remove_runtime( ...
                definition, specification.runtimeDirectory));
            timer = tic;
            domain = build_bmf_domain(specification.configFile);
            generationRuntimeS = toc(timer);
            assert_runtime_scope(definition, specification, domain);
            [currentManifest, currentQuality] = phase32a.audit_case( ...
                definition, specification, domain, generationRuntimeS);
            manifestTable = append_table(manifestTable, currentManifest);
            qualityTable = append_table(qualityTable, currentQuality);
            writetable(manifestTable, manifestFile);
            writetable(qualityTable, qualityFile);
            clear cleanup
        end
        currentManifest = manifestTable( ...
            abs(manifestTable.omega_rad_s - omega) <= 64 * eps(max(1, omega)), :);
        currentQuality = qualityTable( ...
            abs(qualityTable.omega_rad_s - omega) <= 64 * eps(max(1, omega)), :);
        currentIsolation = phase32a.evaluate_isolation( ...
            definition, omega, currentManifest, currentQuality);
        isolationTable = append_table(isolationTable, currentIsolation);
        writetable(isolationTable, isolationFile);
        assert(currentIsolation.frequency_geometry_gate == "PASS", ...
            'CRESTU:Phase32AV5FrequencyGate', ...
            'V5 mesh family failed at omega=%.6g rad/s.', omega);
    end

    %% Stage 3: Enforce the complete v5 geometry gate

    qualityPass = height(qualityTable) == 72 && ...
        all(qualityTable.component_gate_status == "PASS");
    isolationPass = height(isolationTable) == 6 && ...
        all(isolationTable.frequency_geometry_gate == "PASS");
    legacyPass = all(legacy.exact_hash_regression);
    overallPass = qualityPass && isolationPass && legacyPass;
    statusName = ["V5_COMPONENT_QUALITY"; "V5_CONTROL_ISOLATION"; ...
        "LEGACY_Q_ONLY_REGRESSION"; "V1_V4_FAIL_EVIDENCE_PRESERVED"; ...
        "V5_MESH_GEOMETRY_GATE"];
    statusValue = [pass_fail(qualityPass); pass_fail(isolationPass); ...
        "PASS_EXACT_HASH_5_OF_5"; "YES"; pass_fail(overallPass)];
    evidence = ["Phase3_2A_V5_Mesh_Quality.csv"; ...
        "Phase3_2A_V5_Control_Isolation.csv"; ...
        "Phase3_2A_Legacy_Regression.csv"; ...
        "../Phase3_2_Artifacts/Phase3_2_V1/V3/current CSV"; ...
        "18 fresh mesh-only cases"];
    writetable(table(statusName, statusValue, evidence), ...
        fullfile(definition.artifactDirectory, ...
        'Phase3_2A_V5_Mesh_Status.csv'));
    summary = struct('schemaVersion', 1, 'meshOnlyCaseCount', caseCount, ...
        'manifestRowCount', height(manifestTable), ...
        'qualityRowCount', height(qualityTable), ...
        'qualityPassCount', nnz(qualityTable.component_gate_status == "PASS"), ...
        'isolationFrequencyCount', height(isolationTable), ...
        'legacyExactRegressionPass', legacyPass, 'overallPass', overallPass);
    fprintf('[RESULT] PHASE3_2A_V5_MESH_GEOMETRY_GATE = %s\n', ...
        pass_fail(overallPass));
    assert(overallPass, 'CRESTU:Phase32AV5OverallGate', ...
        'The complete v5 mesh family did not pass all geometry gates.');
end

function combined = append_table(combined, current)
    if isempty(combined)
        combined = current;
    else
        combined = [combined; current];
    end
end

function assert_runtime_scope(definition, specification, domain)
    paths = [string(specification.configFile); string(specification.bodyFile); ...
        string(domain.cfg.files.fs); string(domain.cfg.files.seabed); ...
        string(domain.cfg.files.farfield)];
    runtimePrefix = lower(string(specification.runtimeDirectory) + filesep);
    for index = 1:numel(paths)
        normalized = lower(strrep(paths(index), '/', filesep));
        assert(startsWith(normalized, runtimePrefix) && ...
            ~contains(normalized, lower(definition.originalRepository)), ...
            'CRESTU:Phase32AV5RuntimeScope', ...
            'A v5 mesh path escaped the isolated current-worktree case.');
    end
end

function text = pass_fail(value)
    if value
        text = "PASS";
    else
        text = "FAIL";
    end
end
