function summary = Run_Phase3_2A_BEM_Bridge_Smoke()
% RUN_PHASE3_2A_BEM_BRIDGE_SMOKE Run exactly two omega=1.5 clean solves.

    %% Stage 1: Verify geometry prerequisites and frozen legacy reference

    definition = phase32a.initialize();
    v5Cells = readcell(fullfile(definition.artifactDirectory, ...
        'Phase3_2A_V5_Mesh_Status.csv'));
    names = string(v5Cells(2:end, 1));
    values = string(v5Cells(2:end, 2));
    v5Row = names == "V5_MESH_GEOMETRY_GATE";
    assert(nnz(v5Row) == 1 && values(v5Row) == "PASS", ...
        'CRESTU:Phase32ABridgeGeometryPrerequisite', ...
        'BEM bridge requires the complete v5 mesh geometry gate PASS.');
    legacyReference = readtable(fullfile(definition.convergenceDirectory, ...
        'Phase3_1_Artifacts', 'Phase3_1_Formal_PFull_Frequency_Sweep.csv'), ...
        'TextType', 'string');
    referenceRow = abs(legacyReference.omega_rad_s - 1.5) <= 64 * eps(1.5);
    assert(nnz(referenceRow) == 1, 'CRESTU:Phase32ABridgeLegacyReference', ...
        'Frozen Phase 3.1 omega=1.5 formal reference row is missing.');
    reference = legacyReference(referenceRow, :);
    outputFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2A_BEM_Bridge_Smoke.csv');
    records = repmat(empty_record(), 0, 1);

    %% Stage 2: Run and enforce the LEGACY frozen regression first

    legacyCase = create_legacy_case(definition, 1.5);
    legacyCleanup = onCleanup(@() phase32.remove_runtime( ...
        definition, legacyCase.runtimeDirectory));
    legacyRecord = run_one_case(definition, legacyCase, "LEGACY");
    legacyRecord = bind_legacy_regression(legacyRecord, reference);
    records(end + 1, 1) = legacyRecord;
    writetable(struct2table(records), outputFile);
    clear legacyCleanup
    assert(legacyRecord.solve_status == "PASS" && ...
        legacyRecord.legacy_regression_status == "PASS", ...
        'CRESTU:Phase32ABridgeLegacyFailure', ...
        'LEGACY omega=1.5 clean regression failed; new-mode solve is forbidden.');

    %% Stage 3: Run one QUALITY_CONTROLLED_V2 L3 clean solve

    newCase = phase32a.create_case(definition, definition.levels(3), ...
        1.5, 'phase3_2a_bem_bridge_smoke');
    newCleanup = onCleanup(@() phase32.remove_runtime( ...
        definition, newCase.runtimeDirectory));
    newRecord = run_one_case(definition, newCase, "QUALITY_CONTROLLED_V2");
    newRecord.legacy_regression_status = "NOT_APPLICABLE_NEW_MODE";
    records(end + 1, 1) = newRecord;
    writetable(struct2table(records), outputFile);
    clear newCleanup

    ready = all([records.solve_status] == "PASS") && ...
        legacyRecord.legacy_regression_status == "PASS";
    summary = struct('schemaVersion', 1, 'caseCount', numel(records), ...
        'legacyStatus', char(legacyRecord.solve_status), ...
        'legacyRegressionStatus', char(legacyRecord.legacy_regression_status), ...
        'qualityControlledStatus', char(newRecord.solve_status), ...
        'readyForPhase32BSentinel', ready);
    fprintf('[RESULT] BEM_BRIDGE_LEGACY = %s\n', legacyRecord.solve_status);
    fprintf('[RESULT] BEM_BRIDGE_QUALITY_CONTROLLED_V2 = %s\n', ...
        newRecord.solve_status);
    fprintf('[RESULT] READY_FOR_PHASE3_2B_SENTINEL = %s\n', yes_no(ready));
    assert(ready, 'CRESTU:Phase32ABridgeOverallFailure', ...
        'The limited Phase 3.2A BEM bridge smoke did not pass.');
end

function specification = create_legacy_case(definition, omega)
% CREATE_LEGACY_CASE Reproduce the frozen Phase 3.1 formal q-only case.

    runtimeDirectory = tempname(definition.artifactDirectory);
    mkdir(runtimeDirectory);
    [~, token] = fileparts(runtimeDirectory);
    caseName = sprintf('P32A_LegacyBridge_w%04d_%s', ...
        round(1000 * omega), token);
    bodyFile = fullfile(runtimeDirectory, [caseName, '_body.bmf']);
    configFile = fullfile(runtimeDirectory, [caseName, '.cfg']);
    baseline = read_config(definition.baselineConfig);
    generate_body_bmf(bodyFile, 2 * definition.sphereRadiusM, ...
        baseline.isx, baseline.isy, 7);
    write_legacy_config(configFile, caseName, bodyFile, omega, baseline);
    specification = struct('runtimeDirectory', runtimeDirectory, ...
        'configFile', configFile, 'bodyFile', bodyFile, ...
        'caseName', caseName, 'omegaRadPerS', omega, ...
        'configRawSHA256', string(sha256_file_hash(configFile)));
end

function write_legacy_config(filename, caseName, bodyFile, omega, baseline)
    fileID = fopen(filename, 'w');
    assert(fileID >= 0, 'CRESTU:Phase32ABridgeLegacyConfigOpen', ...
        'Cannot create legacy bridge configuration.');
    cleanup = onCleanup(@() fclose(fileID));
    mass = baseline.mass_props(1);
    inertia = mass.inertia;
    inertiaTokens = [inertia(1, 1), inertia(2, 2), inertia(3, 3), ...
        -inertia(1, 2), -inertia(1, 3), -inertia(2, 3)];
    fprintf(fileID, 'PARA1: Project Case Name\n%s\n\n', caseName);
    fprintf(fileID, 'PARA2: IPOTEN IFORCE IRAD IDIFF IDRIFT\n1 1 1 1 0\n\n');
    fprintf(fileID, 'PARA3: FREQUENCY AND HEADING\n1 1 %.17g %.17g\n1\n0\n\n', ...
        omega, omega);
    fprintf(fileID, 'PARA4: ENVIRONMENT\n%.17g %.17g %.17g\n\n', ...
        baseline.water_depth, baseline.grav, baseline.rho);
    fprintf(fileID, 'PARA5: BODY\n1\n%d %s %.17g %.17g %.17g %.17g\n\n', ...
        baseline.bodies(1).id, bodyFile, baseline.bodies(1).pos, ...
        baseline.bodies(1).yaw);
    fprintf(fileID, 'PARA6: MASS PROPERTIES\n%.17g %.17g %.17g %.17g\n', ...
        mass.mass, mass.cg);
    fprintf(fileID, '%.17g %.17g %.17g %.17g %.17g %.17g\n\n', ...
        inertiaTokens);
    fprintf(fileID, 'PARA7: MODES\n');
    fprintf(fileID, '%d ', baseline.calc_modes);
    fprintf(fileID, '\n\nPARA8: FULL DOMAIN\n%d %d\n\n', ...
        baseline.isx, baseline.isy);
    fprintf(fileID, ['PARA9: DOMAIN\n%.17g %d %d %.17g %.17g ', ...
        '%.17g %d\n\n'], baseline.z_tol, baseline.fs.nr_near, ...
        baseline.fs.nr_sponge, baseline.fs.r_inner, baseline.fs.r_outer, ...
        baseline.fs.sponge_ratio, baseline.fs.nz_farfield);
    fprintf(fileID, 'PARA10: SPONGE\n%.17g\n\n', baseline.fs.mu0);
    fprintf(fileID, ['PARA11: FIXED OUTER-DOMAIN WATERLINE\n', ...
        'OUTER_WATERLINE_MESH %s\n\n'], bodyFile);
    fprintf(fileID, ['PARA12: PHASE2.2 OUTER TRUNCATION AUDIT\n', ...
        'OUTER_TRUNCATION_Q 2 1.5\n\n']);
    fprintf(fileID, ['PARA13: LEGACY BRIDGE DIAGNOSTICS\n', ...
        'RAW_DIAGNOSTICS 1\nPERSIST_FULL_PHI 0\n']);
    clear cleanup
end

function record = run_one_case(definition, specification, mode)
% RUN_ONE_CASE Execute one clean production solve and extract direct gates.

    record = empty_record();
    record.topology_mode = string(mode);
    record.omega_rad_s = specification.omegaRadPerS;
    record.config_raw_sha256 = specification.configRawSHA256;
    timer = tic;
    try
        results = run_frequency_domain_case(specification.configFile, ...
            'skipPhysicalDiagnostics', true);
        record.total_runtime_s = toc(timer);
        assert_runtime_scope(definition, specification, results);
        loaded = load(results.potential_cache_file, 'pot_cache');
        entry = loaded.pot_cache.entries(1);
        diagnostics = entry.solver_diagnostics;
        conditioning = cellfun(@(item) item.conditioning, diagnostics, ...
            'UniformOutput', false);
        assembly = entry.assembly_info;
        record.matrix_assembly_status = "PASS";
        record.bem_unknown_count = entry.mesh_audit.bemUnknownCount;
        record.raw_rcond = min(cellfun(@(item) ...
            item.rawRcondEstimate, conditioning));
        record.scaled_rcond = min(cellfun(@(item) ...
            item.scaledRcondEstimate, conditioning));
        record.radiation_linear_relative_residual = max(cellfun(@(item) ...
            item.radiationRelativeResidual, diagnostics));
        record.diffraction_linear_relative_residual = max(cellfun(@(item) ...
            item.diffractionRelativeResidual, diagnostics));
        record.radiation_algebraic_relative_residual = max(cellfun(@(item) ...
            item.radiation.relativeResidualFrobeniusNorm, diagnostics));
        record.diffraction_algebraic_relative_residual = max(cellfun(@(item) ...
            item.diffraction.relativeResidualFrobeniusNorm, diagnostics));
        record.maximum_abs_outer_ntheta = max(cellfun(@(item) ...
            item.outer_absorbing_boundary.maximumAbsTangentialNormal, assembly));
        record.maximum_outer_column_residual = max(cellfun(@(item) ...
            item.outer_source_column_audit.reconstructionRelativeResidual, assembly));
        record.assembly_runtime_s = sum(cellfun(@(item) ...
            item.elapsed_seconds, assembly));
        record.A33_kg = results.added_mass(3, 3, 1);
        record.B33_kg_s = results.damping(3, 3, 1);
        excitation = results.excitation(3, 1, 1);
        response = results.rao.complex(3, 1, 1);
        denominator = results.rao.dynamic_matrix(3, 3, 1);
        record.F3_real_N_per_m = real(excitation);
        record.F3_imag_N_per_m = imag(excitation);
        record.RAO3_real_m_per_m = real(response);
        record.RAO3_imag_m_per_m = imag(response);
        record.D3_real_N_per_m = real(denominator);
        record.D3_imag_N_per_m = imag(denominator);
        record.D3_abs_N_per_m = abs(denominator);
        audit = results.audit.frequencyEntries(1);
        record.cache_status = string(audit.cacheStatus);
        record.body_geometry_hash = string(entry.mesh_audit.body.hash);
        record.free_surface_geometry_hash = ...
            string(entry.mesh_audit.freeSurface.hash);
        record.bottom_geometry_hash = string(entry.mesh_audit.bottom.hash);
        record.farfield_geometry_hash = ...
            string(entry.mesh_audit.outerBoundary.hash);
        record.combined_geometry_hash = string(entry.mesh_audit.geometry.hash);
        record.operator_hash = string(entry.phase2_2_control_manifest. ...
            effective.boundaryOperatorStateSHA256);
        record.production_source_hash = string(results.audit.codeVersion.fingerprint);
        finiteValues = [record.raw_rcond, record.scaled_rcond, ...
            record.radiation_linear_relative_residual, ...
            record.diffraction_linear_relative_residual, ...
            record.radiation_algebraic_relative_residual, ...
            record.diffraction_algebraic_relative_residual, ...
            record.A33_kg, record.B33_kg_s, real(excitation), ...
            imag(excitation), real(response), imag(response), ...
            real(denominator), imag(denominator)];
        maximumResidual = max([ ...
            record.radiation_linear_relative_residual, ...
            record.diffraction_linear_relative_residual, ...
            record.radiation_algebraic_relative_residual, ...
            record.diffraction_algebraic_relative_residual]);
        pass = all(isfinite(finiteValues)) && ...
            record.raw_rcond >= 1.0e-12 && ...
            record.scaled_rcond >= 1.0e-12 && ...
            maximumResidual <= 1.0e-10 && ...
            record.maximum_abs_outer_ntheta <= 1.0e-10 && ...
            record.maximum_outer_column_residual <= 1.0e-14 && ...
            lower(record.cache_status) == "miss";
        record.solve_status = pass_fail(pass);
    catch exception
        record.total_runtime_s = toc(timer);
        record.solve_status = "FAIL";
        record.error_identifier = string(exception.identifier);
        record.error_message = string(exception.message);
    end
end

function record = bind_legacy_regression(record, reference)
    referenceExcitation = complex(reference.F3_real_N_per_m, ...
        reference.F3_imag_N_per_m);
    referenceResponse = complex(reference.RAO3_real_m_per_m, ...
        reference.RAO3_imag_m_per_m);
    actualExcitation = complex(record.F3_real_N_per_m, record.F3_imag_N_per_m);
    actualResponse = complex(record.RAO3_real_m_per_m, ...
        record.RAO3_imag_m_per_m);
    differences = [relative_difference(record.A33_kg, reference.A33_kg); ...
        relative_difference(record.B33_kg_s, reference.B33_kg_s); ...
        relative_difference(actualExcitation, referenceExcitation); ...
        relative_difference(actualResponse, referenceResponse)];
    record.legacy_maximum_response_relative_difference = max(differences);
    geometryMatch = record.body_geometry_hash == ...
        reference.body_geometry_hash && ...
        record.free_surface_geometry_hash == ...
        reference.free_surface_geometry_hash && ...
        record.bottom_geometry_hash == reference.bottom_geometry_hash && ...
        record.farfield_geometry_hash == reference.farfield_geometry_hash && ...
        record.combined_geometry_hash == reference.combined_geometry_hash;
    record.legacy_geometry_exact_hash_match = geometryMatch;
    pass = geometryMatch && max(differences) <= 1.0e-10;
    record.legacy_regression_status = pass_fail(pass);
end

function value = relative_difference(actual, expected)
    value = abs(actual - expected) / max([abs(actual), abs(expected), eps]);
end

function assert_runtime_scope(definition, specification, results)
    paths = [string(specification.configFile); string(specification.bodyFile); ...
        string(results.config.files.potential_cache); ...
        string(results.config.files.results); ...
        string(results.audit.meshAuditFile)];
    prefix = lower(string(specification.runtimeDirectory) + filesep);
    for index = 1:numel(paths)
        normalized = lower(strrep(paths(index), '/', filesep));
        assert(startsWith(normalized, prefix) && ...
            ~contains(normalized, lower(definition.originalRepository)), ...
            'CRESTU:Phase32ABridgeRuntimeScope', ...
            'A BEM bridge path escaped the isolated current-worktree case.');
    end
end

function record = empty_record()
    record = struct('topology_mode', "", 'omega_rad_s', NaN, ...
        'matrix_assembly_status', "NOT_RUN", 'bem_unknown_count', 0, ...
        'raw_rcond', NaN, 'scaled_rcond', NaN, ...
        'radiation_linear_relative_residual', NaN, ...
        'diffraction_linear_relative_residual', NaN, ...
        'radiation_algebraic_relative_residual', NaN, ...
        'diffraction_algebraic_relative_residual', NaN, ...
        'maximum_abs_outer_ntheta', NaN, ...
        'maximum_outer_column_residual', NaN, ...
        'A33_kg', NaN, 'B33_kg_s', NaN, ...
        'F3_real_N_per_m', NaN, 'F3_imag_N_per_m', NaN, ...
        'RAO3_real_m_per_m', NaN, 'RAO3_imag_m_per_m', NaN, ...
        'D3_real_N_per_m', NaN, 'D3_imag_N_per_m', NaN, ...
        'D3_abs_N_per_m', NaN, 'cache_status', "NOT_RUN", ...
        'body_geometry_hash', "", 'free_surface_geometry_hash', "", ...
        'bottom_geometry_hash', "", 'farfield_geometry_hash', "", ...
        'combined_geometry_hash', "", 'operator_hash', "", ...
        'production_source_hash', "", 'config_raw_sha256', "", ...
        'assembly_runtime_s', NaN, 'total_runtime_s', NaN, ...
        'legacy_geometry_exact_hash_match', false, ...
        'legacy_maximum_response_relative_difference', NaN, ...
        'legacy_regression_status', "NOT_RUN", 'solve_status', "NOT_RUN", ...
        'error_identifier', "", 'error_message', "");
end

function text = pass_fail(value)
    if value
        text = "PASS";
    else
        text = "FAIL";
    end
end

function text = yes_no(value)
    if value
        text = 'YES';
    else
        text = 'NO';
    end
end
