function summary = Run_Phase3_2A_Generator_Audit()
% RUN_PHASE3_2A_GENERATOR_AUDIT Locate fail-before panels and producer chain.

    %% Stage 1: Freeze the read-only call-chain interpretation

    definition = phase32a.initialize();
    callChain = build_call_chain();
    writetable(callChain, fullfile(definition.artifactDirectory, ...
        'Phase3_2A_Generator_Call_Chain.csv'));

    %% Stage 2: Rebuild only low/high endpoint v4 meshes

    v4 = phase32.definition();
    frequencies = [0.5, 2.0]; % [rad/s]
    levels = v4.levels;
    diagnosticRows = repmat(empty_panel_record(), 0, 1);
    transitionRows = repmat(empty_transition_record(), 0, 1);
    diagnosticFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2A_FailBefore_Panel_Diagnostics.csv');
    transitionFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2A_Transition_H_Diagnostics.csv');

    caseCount = numel(frequencies) * numel(levels);
    completed = 0;
    for frequencyIndex = 1:numel(frequencies)
        omega = frequencies(frequencyIndex); % [rad/s]
        for levelIndex = 1:numel(levels)
            level = levels(levelIndex);
            completed = completed + 1;
            fprintf('[INFO] Generator audit %d/%d | %s | %.6g rad/s\n', ...
                completed, caseCount, level.name, omega);
            specification = phase32.create_case(v4, level, omega, ...
                'phase3_2a_generator_audit');
            cleanup = onCleanup(@() phase32.remove_runtime( ...
                v4, specification.runtimeDirectory));
            domain = build_bmf_domain(specification.configFile);
            assert_runtime_scope(definition, specification, domain);
            truncation = domain.cfg.outer_truncation.effective;
            waterlineCount = domain.outer_waterlines{1}.n_pts;
            components = {domain.body_list{1}, domain.fs, ...
                domain.seabed, domain.farfield};
            names = ["body"; "free_surface"; "bottom"; "farfield"];
            for componentIndex = 1:numel(components)
                mesh = components{componentIndex};
                [~, details] = phase32a.evaluate_component_quality( ...
                    mesh, names(componentIndex), definition);
                [~, aspectOrder] = sort(details.aspect_ratio, 'descend');
                [~, angleOrder] = sort(details.minimum_angle_deg, 'ascend');
                selectionCount = min(5, mesh.n_panels);
                for rankIndex = 1:selectionCount
                    panelIndex = aspectOrder(rankIndex);
                    diagnosticRows(end + 1, 1) = panel_record( ...
                        definition, specification, truncation, ...
                        names(componentIndex), mesh, details, panelIndex, ...
                        "WORST_ASPECT_RATIO", rankIndex, waterlineCount); %#ok<AGROW>
                    panelIndex = angleOrder(rankIndex);
                    diagnosticRows(end + 1, 1) = panel_record( ...
                        definition, specification, truncation, ...
                        names(componentIndex), mesh, details, panelIndex, ...
                        "WORST_MINIMUM_ANGLE", rankIndex, waterlineCount); %#ok<AGROW>
                end
            end
            transitionRows = append_transition_records(transitionRows, ...
                specification, domain, truncation);
            writetable(struct2table(diagnosticRows), diagnosticFile);
            writetable(struct2table(transitionRows), transitionFile);
            clear cleanup
        end
    end

    %% Stage 3: Classify evidence without overclaiming a unique root cause

    diagnostics = struct2table(diagnosticRows);
    transitions = struct2table(transitionRows);
    fsLow = diagnostics.component == "free_surface" & ...
        diagnostics.omega_rad_s == 0.5;
    bottomHigh = diagnostics.component == "bottom" & ...
        diagnostics.omega_rad_s == 2.0;
    fsWorstAspect = max(diagnostics.aspect_ratio(fsLow));
    bottomMinimumAngle = min(diagnostics.minimum_angle_deg(bottomHigh));
    bottomWorst = diagnostics(bottomHigh & ...
        diagnostics.minimum_angle_deg == bottomMinimumAngle, :);
    bottomSingleCenterFan = any(bottomWorst.generator_region == ...
        "BOTTOM_SINGLE_CENTER_FAN");
    summary = struct('schemaVersion', 1, ...
        'selectedCaseCount', caseCount, ...
        'diagnosticPanelRowCount', height(diagnostics), ...
        'transitionSummaryRowCount', height(transitions), ...
        'fsOmega0p5MaximumAspectRatio', fsWorstAspect, ...
        'bottomOmega2MinimumAngleDeg', bottomMinimumAngle, ...
        'bottomMinimumAngleFromSingleCenterFan', bottomSingleCenterFan, ...
        'metricBug', false, ...
        'classification', 'PRIMARY_DESIGN_LIMITATION', ...
        'uniqueRootCauseConfirmed', false);
    fprintf('[RESULT] FS_OMEGA_0P5_MAX_ASPECT_RATIO = %.9g\n', ...
        fsWorstAspect);
    fprintf('[RESULT] BOTTOM_OMEGA_2_MIN_ANGLE_DEG = %.9g\n', ...
        bottomMinimumAngle);
    fprintf('[RESULT] BOTTOM_SINGLE_CENTER_FAN = %s\n', ...
        yes_no(bottomSingleCenterFan));
    fprintf('[RESULT] METRIC_BUG = NO\n');
    fprintf('[RESULT] ROOT_CAUSE = NOT_YET_UNIQUE\n');
end

function tableOut = build_call_chain()
    functionName = ["read_config/parse_phase2_2_controls"; ...
        "build_bmf_domain"; "extract_waterline"; ...
        "generate_free_surface_bmf"; ...
        "get_phase2_2_bottom_mesh_inputs"; "generate_seabed_mesh"; ...
        "apply_rankine_outer_truncation/choose_endpoint_theta_count"; ...
        "apply_rankine_outer_truncation/prepare_horizontal_surface"; ...
        "apply_rankine_outer_truncation/gradual_ring_count"; ...
        "apply_rankine_outer_truncation/zipper_annulus"; ...
        "apply_rankine_outer_truncation/build_frustum_wall"; ...
        "generate_farfield_mesh"];
    relativeFile = ["Source Code/1.Input/read_config.m"; ...
        "Source Code/2.Mesh/build_bmf_domain.m"; ...
        "Source Code/2.Mesh/extract_waterline.m"; ...
        "Source Code/2.Mesh/generate_free_surface_bmf.m"; ...
        "Source Code/2.Mesh/get_phase2_2_bottom_mesh_inputs.m"; ...
        "Source Code/2.Mesh/generate_seabed_mesh.m"; ...
        repmat("Source Code/2.Mesh/apply_rankine_outer_truncation.m", 5, 1); ...
        "Source Code/2.Mesh/generate_farfield_mesh.m"];
    role = ["configuration producer"; "domain orchestrator"; ...
        "body-waterline producer"; "FS base polar producer"; ...
        "bottom control adapter"; "bottom ring/core producer"; ...
        "endpoint count scheduler"; "radial/count scheduler"; ...
        "integer count scheduler"; "transition connector"; ...
        "wall top/bottom ring consumer"; "legacy wall producer"];
    primaryInput = ["PARA13 named controls"; "validated cfg/body mesh"; ...
        "body vertices/normals/z_tol"; ...
        "waterline nodes,nr_near,nr_sponge,Rinner,Rout,sponge_ratio"; ...
        "bottomRadialCounts,FS reference"; ...
        "waterline,bottom cfg,mirrored FS ring"; ...
        "radius,chord target,explicit/common count"; ...
        "legacy/final radius,radial target,theta counts"; ...
        "legacy/final count,layer index"; ...
        "two ordered circular rings"; ...
        "top/bottom rings,depth,slant target"; ...
        "waterline nodes,Rout,Nz"];
    outputContract = ["explicit controls or legacy defaults"; ...
        "body/FS/bottom/wall merged domain"; ...
        "ordered CCW closed ring with body node count"; ...
        "equal-count radial quad rings; inner ring exactly body waterline"; ...
        "independent bottom radial cfg/reference FS"; ...
        "mirrored outer ring plus adaptive 5-block structured infill"; ...
        "multiple-of-4 endpoint count; held-or-finer spacing"; ...
        "horizontal annulus ending at common wall count"; ...
        "multiple-of-4 monotone intermediate counts"; ...
        "conforming quad/triangle panels; no T-junction"; ...
        "equal-count structured FARFIELD frustum"; ...
        "equal waterline sector count at top/bottom"];
    integerRounding = ["positive integer validation"; "none"; "none"; ...
        "nr counts exact; no theta change in base producer"; ...
        "counts copied exactly"; ...
        "corner indices/Nx/Ny/Nr use round"; ...
        "round-to-multiple-4 or ceil-to-finer"; ...
        "ceil(extension/radialTarget)"; ...
        "4*round(interpolated/4)"; ...
        "fraction-order merge"; "round/ceil vertical layers"; ...
        "Nz exact; theta inherited from waterline"];
    symmetryConstraint = ["theta controls multiple of four"; ...
        "active truncation limited to full-domain single body"; ...
        "open/closed waterline follows ISX/ISY"; ...
        "n_theta equals waterline nodes"; ...
        "inherits cfg symmetry"; "full-domain producer"; ...
        "count multiple of four"; "full-domain active truncation"; ...
        "count multiple of four"; "ordered closed rings"; ...
        "common equal count"; "waterline sector count"];
    tableOut = table(functionName, relativeFile, role, primaryInput, ...
        outputContract, integerRounding, symmetryConstraint);
end

function row = panel_record(definition, specification, truncation, ...
        componentName, mesh, details, panelIndex, eventType, rankIndex, ...
        waterlineCount)
    [region, ringIndex, sectorIndex, scheduler] = classify_panel( ...
        specification, truncation, componentName, panelIndex, ...
        waterlineCount);
    vertices = reshape(mesh.vertices(panelIndex, :, :), 4, 3);
    row = empty_panel_record();
    row.mesh_level = specification.level.name;
    row.omega_rad_s = specification.omegaRadPerS;
    row.component = componentName;
    row.event_type = eventType;
    row.event_rank = rankIndex;
    row.panel_id = panelIndex;
    row.generator_region = region;
    row.ring_index = ringIndex;
    row.sector_index = sectorIndex;
    row.scheduler = scheduler;
    row.is_triangle = details.is_triangle(panelIndex);
    row.is_poor = details.is_poor(panelIndex);
    row.area_m2 = details.area_m2(panelIndex);
    row.sqrt_area_m = sqrt(details.area_m2(panelIndex));
    row.aspect_ratio = details.aspect_ratio(panelIndex);
    row.aspect_limit = details.aspect_limit(panelIndex);
    row.minimum_angle_deg = details.minimum_angle_deg(panelIndex);
    row.maximum_angle_deg = details.maximum_angle_deg(panelIndex);
    row.skewness_deg = details.skewness_deg(panelIndex);
    row.warp_deg = details.warp_deg(panelIndex);
    row.center_x_m = details.center_x_m(panelIndex);
    row.center_y_m = details.center_y_m(panelIndex);
    row.center_z_m = details.center_z_m(panelIndex);
    for vertexIndex = 1:4
        row.(sprintf('v%d_x_m', vertexIndex)) = vertices(vertexIndex, 1);
        row.(sprintf('v%d_y_m', vertexIndex)) = vertices(vertexIndex, 2);
        row.(sprintf('v%d_z_m', vertexIndex)) = vertices(vertexIndex, 3);
    end
    row.body_division_count = specification.level.bodyDivision;
    row.fs_radial_counts = join(string( ...
        specification.level.fsRadialCounts), '|');
    row.bottom_radial_counts = join(string( ...
        specification.level.bottomRadialCounts), '|');
    row.configured_wall_theta_count = ...
        specification.level.wallThetaCount;
    row.legacy_theta_count = truncation.legacyThetaNodeCount;
    row.final_wall_theta_count = truncation.commonOuterThetaNodeCount;
    row.radial_scheduler_candidate = classify_candidate(region);
    row.metric_bug = "NO";
    row.root_cause_status = "NOT_YET_UNIQUE";
    row.runtime_provenance = "PASS_CURRENT_WORKTREE";
    assert(~contains(lower(specification.configFile), ...
        lower(definition.originalRepository)), ...
        'CRESTU:Phase32APanelDiagnosticPath', ...
        'A diagnostic case path points to the original repository.');
end

function [region, ringIndex, sectorIndex, scheduler] = classify_panel( ...
        specification, truncation, componentName, panelIndex, ...
        waterlineCount)
    before = truncation.componentPanelCountsBefore;
    ringIndex = NaN;
    sectorIndex = NaN;
    scheduler = "not-applicable";
    if componentName == "body"
        region = "BODY_SURFACE";
        return
    elseif componentName == "farfield"
        region = "FARFIELD_STRUCTURED_WALL";
        scheduler = "build_frustum_wall equal-count rings";
        return
    end
    if componentName == "free_surface"
        baseRingPanels = before(1);
        if panelIndex <= baseRingPanels
            region = "FS_BASE_EQUAL_COUNT_POLAR_RING";
            ringIndex = ceil(panelIndex / waterlineCount);
            sectorIndex = mod(panelIndex - 1, waterlineCount) + 1;
            scheduler = "generate_free_surface_bmf radial weights + elliptic smoothing";
        else
            region = "FS_OUTER_TRUNCATION_TRANSITION";
            scheduler = "prepare_horizontal_surface + zipper_annulus";
        end
        return
    end

    bottomRingPanels = sum(specification.level.bottomRadialCounts) * ...
        waterlineCount;
    if panelIndex <= bottomRingPanels
        region = "BOTTOM_MIRRORED_FS_POLAR_RING";
        ringIndex = ceil(panelIndex / waterlineCount);
        sectorIndex = mod(panelIndex - 1, waterlineCount) + 1;
        scheduler = "bottomReferenceSurface mirrored from FS producer";
    elseif panelIndex <= before(2)
        localIndex = panelIndex - bottomRingPanels;
        [blockName, blockRing] = bottom_block(localIndex, waterlineCount);
        region = blockName;
        ringIndex = blockRing;
        scheduler = "generate_seabed_mesh adaptive 5-block structured infill";
    else
        region = "BOTTOM_OUTER_TRUNCATION_TRANSITION";
        scheduler = "prepare_horizontal_surface + zipper_annulus";
    end
end

function [blockName, blockRing] = bottom_block(localIndex, waterlineCount)
    quarterCount = waterlineCount / 4;
    Nx = max(2, round(quarterCount));
    Ny = Nx;
    Nr = max(3, round((Nx + Ny) * 0.25));
    sideBlockCount = Nx * Nr;
    if localIndex <= 4 * sideBlockCount
        blockIndex = ceil(localIndex / sideBlockCount);
        blockName = "BOTTOM_STRUCTURED_SIDE_BLOCK_" + string(blockIndex);
        withinBlock = mod(localIndex - 1, sideBlockCount) + 1;
        blockRing = ceil(withinBlock / Nr);
    else
        blockName = "BOTTOM_STRUCTURED_CENTRAL_PATCH";
        withinBlock = localIndex - 4 * sideBlockCount;
        blockRing = ceil(withinBlock / Ny);
    end
end

function candidate = classify_candidate(region)
    if contains(region, "BASE_EQUAL_COUNT_POLAR_RING") || ...
            contains(region, "MIRRORED_FS_POLAR_RING")
        candidate = "RADIAL_GRADING_OR_FIXED_RING_COUNT";
    elseif contains(region, "STRUCTURED")
        candidate = "FIVE_BLOCK_CORE_MAPPING_OR_ROUNDING";
    elseif contains(region, "TRUNCATION_TRANSITION")
        candidate = "COUNT_TRANSITION_OR_ZIPPER";
    else
        candidate = "NOT_CLASSIFIED";
    end
end

function rows = append_transition_records(rows, specification, domain, truncation)
    boundaries = [20.0, truncation.legacyRadiusM]; % [m]
    boundaryNames = ["MESH_TRANSITION_RADIUS"; "LEGACY_TRUNCATION_RADIUS"];
    meshes = {domain.fs, domain.seabed};
    componentNames = ["free_surface"; "bottom"];
    allH = zeros(0, 1);
    for componentIndex = 1:numel(meshes)
        mesh = meshes{componentIndex};
        vertices = reshape(mesh.vertices, mesh.n_panels, 4, 3);
        vertexRadius = hypot(vertices(:, :, 1), vertices(:, :, 2));
        for boundaryIndex = 1:numel(boundaries)
            radiusM = boundaries(boundaryIndex);
            mask = min(vertexRadius, [], 2) <= radiusM + 1.0e-8 & ...
                max(vertexRadius, [], 2) >= radiusM - 1.0e-8;
            h = sqrt(mesh.areas(mask));
            allH = [allH; h]; %#ok<AGROW>
            rows(end + 1, 1) = transition_record(specification, ...
                componentNames(componentIndex), boundaryNames(boundaryIndex), ...
                radiusM, h); %#ok<AGROW>
        end
    end
    rows(end + 1, 1) = transition_record(specification, "combined", ...
        "V4_COMBINED_TRANSITION_DEFINITION", NaN, allH);
end

function row = transition_record(specification, component, boundaryName, ...
        boundaryRadiusM, h)
    row = empty_transition_record();
    row.mesh_level = specification.level.name;
    row.omega_rad_s = specification.omegaRadPerS;
    row.component = component;
    row.boundary = boundaryName;
    row.boundary_radius_m = boundaryRadiusM;
    row.panel_count = numel(h);
    row.minimum_sqrt_area_m = min(h);
    row.maximum_sqrt_area_m = max(h);
    row.mean_sqrt_area_m = mean(h);
    row.median_sqrt_area_m = median(h);
    row.body_division_count = specification.level.bodyDivision;
    row.fs_radial_counts = join(string( ...
        specification.level.fsRadialCounts), '|');
    row.bottom_radial_counts = join(string( ...
        specification.level.bottomRadialCounts), '|');
end

function assert_runtime_scope(definition, specification, domain)
    paths = [string(specification.configFile); ...
        string(specification.bodyFile); string(domain.cfg.files.fs); ...
        string(domain.cfg.files.seabed); string(domain.cfg.files.farfield)];
    runtimePrefix = lower(string(specification.runtimeDirectory) + filesep);
    for index = 1:numel(paths)
        normalized = lower(strrep(paths(index), '/', filesep));
        assert(startsWith(normalized, runtimePrefix) && ...
            ~contains(normalized, lower(definition.originalRepository)), ...
            'CRESTU:Phase32AGeneratorRuntimeScope', ...
            'A generator audit path escaped the isolated current-worktree case.');
    end
end

function row = empty_panel_record()
    row = struct('mesh_level', "", 'omega_rad_s', NaN, ...
        'component', "", 'event_type', "", 'event_rank', 0, ...
        'panel_id', 0, 'generator_region', "", 'ring_index', NaN, ...
        'sector_index', NaN, 'scheduler', "", 'is_triangle', false, ...
        'is_poor', false, 'area_m2', NaN, 'sqrt_area_m', NaN, ...
        'aspect_ratio', NaN, 'aspect_limit', NaN, ...
        'minimum_angle_deg', NaN, 'maximum_angle_deg', NaN, ...
        'skewness_deg', NaN, 'warp_deg', NaN, ...
        'center_x_m', NaN, 'center_y_m', NaN, 'center_z_m', NaN, ...
        'v1_x_m', NaN, 'v1_y_m', NaN, 'v1_z_m', NaN, ...
        'v2_x_m', NaN, 'v2_y_m', NaN, 'v2_z_m', NaN, ...
        'v3_x_m', NaN, 'v3_y_m', NaN, 'v3_z_m', NaN, ...
        'v4_x_m', NaN, 'v4_y_m', NaN, 'v4_z_m', NaN, ...
        'body_division_count', 0, 'fs_radial_counts', "", ...
        'bottom_radial_counts', "", 'configured_wall_theta_count', 0, ...
        'legacy_theta_count', 0, 'final_wall_theta_count', 0, ...
        'radial_scheduler_candidate', "", 'metric_bug', "NO", ...
        'root_cause_status', "NOT_YET_UNIQUE", ...
        'runtime_provenance', "");
end

function row = empty_transition_record()
    row = struct('mesh_level', "", 'omega_rad_s', NaN, ...
        'component', "", 'boundary', "", 'boundary_radius_m', NaN, ...
        'panel_count', 0, 'minimum_sqrt_area_m', NaN, ...
        'maximum_sqrt_area_m', NaN, 'mean_sqrt_area_m', NaN, ...
        'median_sqrt_area_m', NaN, 'body_division_count', 0, ...
        'fs_radial_counts', "", 'bottom_radial_counts', "");
end

function text = yes_no(value)
    if value
        text = 'YES';
    else
        text = 'NO';
    end
end
