function [freeSurface, bottom, outerBoundary, audit] = ...
    apply_rankine_outer_truncation(freeSurface, bottom, outerBoundary, ...
    cfg, wavelength)
% APPLY_RANKINE_OUTER_TRUNCATION Build an audit-only closed frustum domain.
% The absent/default q=1.5 path returns the legacy meshes without mutation.

    validateattributes(wavelength, {'numeric'}, ...
        {'scalar', 'real', 'positive', 'finite'});
    specification = default_specification();
    if isfield(cfg, 'outer_truncation')
        specification = cfg.outer_truncation;
    end
    legacyRadius = cfg.fs.r_outer;
    baselineQ = (legacyRadius - cfg.fs.r_inner) / wavelength;
    desiredTopRadius = max(legacyRadius, cfg.fs.r_inner + ...
        specification.topRadiusPerWavelength * wavelength);
    desiredBottomRadius = max(legacyRadius, cfg.fs.r_inner + ...
        specification.bottomRadiusPerWavelength * wavelength);
    beforeCounts = [freeSurface.n_panels, bottom.n_panels, ...
        outerBoundary.n_panels];
    tolerance = 64 * eps(max([legacyRadius, desiredTopRadius, ...
        desiredBottomRadius, 1]));
    extensionRequested = desiredTopRadius > legacyRadius + tolerance || ...
        desiredBottomRadius > legacyRadius + tolerance;
    thetaControls = resolve_theta_controls(cfg);
    thetaResolutionRequested = any([thetaControls.common, ...
        thetaControls.top, thetaControls.bottom] > 0);
    qualityControlledTransition = ...
        get_polar_topology_mode(cfg) == "QUALITY_CONTROLLED_V2";
    policy = policy_specification();

    if (~specification.enabled || ~extensionRequested) && ...
            ~thetaResolutionRequested
        audit = unchanged_audit(specification, policy, wavelength, ...
            legacyRadius, baselineQ, beforeCounts, freeSurface, bottom, ...
            outerBoundary);
        return
    end
    assert(cfg.n_bodies == 1 && cfg.isx == 0 && cfg.isy == 0, ...
        'CRESTU:OuterTruncationScope', ...
        'Active frustum instrumentation is limited to one full-domain body.');
    assert(cfg.water_depth > 0 && ~isempty(bottom) && ~isempty(outerBoundary), ...
        'CRESTU:OuterTruncationDepth', ...
        'Active frustum instrumentation requires a finite-depth closed domain.');

    topLegacyRing = extract_outer_ring(freeSurface, 0.0, legacyRadius);
    bottomLegacyRing = extract_outer_ring(bottom, -cfg.water_depth, legacyRadius);
    assert(size(topLegacyRing, 1) == size(bottomLegacyRing, 1), ...
        'CRESTU:OuterTruncationLegacyRing', ...
        'Legacy free-surface and bottom outer rings have different node counts.');
    legacyThetaCount = size(topLegacyRing, 1);
    topThetaTarget = max_ring_edge(topLegacyRing);
    bottomThetaTarget = max_ring_edge(bottomLegacyRing);
    topRadialTarget = outer_band_radial_target(freeSurface, legacyRadius);
    bottomRadialTarget = outer_band_radial_target(bottom, legacyRadius);
    wallTarget = cfg.water_depth / cfg.fs.nz_farfield;
    assert(isfinite(wallTarget) && wallTarget > 0, ...
        'CRESTU:OuterTruncationWallTarget', ...
        'The Fine-baseline wall target depth/Nz is invalid.');
    [topThetaSelection, bottomThetaSelection, thetaSelection] = ...
        choose_endpoint_theta_counts(desiredTopRadius, topThetaTarget, ...
        desiredBottomRadius, bottomThetaTarget, legacyRadius, ...
        legacyThetaCount, thetaControls);
    topThetaCount = topThetaSelection.chosenCount;
    bottomThetaCount = bottomThetaSelection.chosenCount;
    [commonThetaCount, commonThetaProvenance] = ...
        choose_common_wall_count(topThetaCount, bottomThetaCount, ...
        thetaControls);
    startAngle = atan2(topLegacyRing(1, 2), topLegacyRing(1, 1));

    [freeSurface, topRing, topInfo] = prepare_horizontal_surface( ...
        freeSurface, desiredTopRadius, legacyRadius, commonThetaCount, ...
        startAngle, 0.0, topRadialTarget, topThetaTarget, cfg, 2, ...
        thetaResolutionRequested, qualityControlledTransition);
    [bottom, bottomRing, bottomInfo] = prepare_horizontal_surface( ...
        bottom, desiredBottomRadius, legacyRadius, commonThetaCount, ...
        startAngle, -cfg.water_depth, bottomRadialTarget, ...
        bottomThetaTarget, cfg, 4, thetaResolutionRequested, ...
        qualityControlledTransition);
    topInfo.endpointThetaNodeCount = topThetaCount;
    topInfo.wallRingNodeCount = size(topRing, 1);
    topInfo.endpointToWallCountTransition = topThetaCount ~= commonThetaCount;
    topInfo.transitionBoundaryType = 2;
    bottomInfo.endpointThetaNodeCount = bottomThetaCount;
    bottomInfo.wallRingNodeCount = size(bottomRing, 1);
    bottomInfo.endpointToWallCountTransition = ...
        bottomThetaCount ~= commonThetaCount;
    bottomInfo.transitionBoundaryType = 4;
    [outerBoundary, wallInfo] = build_frustum_wall(topRing, bottomRing, ...
        desiredTopRadius, desiredBottomRadius, cfg.water_depth, wallTarget, ...
        topThetaTarget, bottomThetaTarget, cfg.isx, cfg.isy);

    topFingerprint = mesh_fingerprint(freeSurface);
    bottomFingerprint = mesh_fingerprint(bottom);
    outerFingerprint = mesh_fingerprint(outerBoundary);
    geometryDiagnostics = audit_axisymmetric_wall_geometry( ...
        outerBoundary, topRing, bottomRing, commonThetaCount, ...
        topThetaCount, bottomThetaCount, topInfo, bottomInfo, ...
        commonThetaProvenance);
    afterCounts = [freeSurface.n_panels, bottom.n_panels, ...
        outerBoundary.n_panels];
    actualTopTheta = max_ring_edge(topRing);
    actualBottomTheta = max_ring_edge(bottomRing);
    resolutionStatuses = {topInfo.radialResolution, ...
        topInfo.thetaResolution, bottomInfo.radialResolution, ...
        bottomInfo.thetaResolution, wallInfo.slantResolution, ...
        wallInfo.topTangentialResolution, ...
        wallInfo.bottomTangentialResolution};
    resolutionPass = all(cellfun(@(item) item.accepted, resolutionStatuses));
    resolutionHeld = all(cellfun(@(item) ...
        item.heldWithinTolerance, resolutionStatuses));
    roundingFinerException = any(cellfun(@(item) ...
        item.roundingFinerException, resolutionStatuses)) || ...
        topThetaSelection.roundingFinerException || ...
        bottomThetaSelection.roundingFinerException || ...
        wallInfo.countSelection.roundingFinerException;
    assert(resolutionPass, 'CRESTU:OuterTruncationResolution', ...
        'A derived frustum spacing is more than 5%% coarser than its target.');

    audit = struct('schemaVersion', 2, 'policy', policy, ...
        'polarTopologyMode', char(get_polar_topology_mode(cfg)), ...
        'enabled', true, 'inputMode', specification.inputMode, ...
        'geometryModified', true, ...
        'independentTopQ', specification.topRadiusPerWavelength, ...
        'independentBottomQ', specification.bottomRadiusPerWavelength, ...
        'wavelengthM', wavelength, 'legacyRadiusM', legacyRadius, ...
        'legacyRadiusPerWavelength', baselineQ, ...
        'effectiveTopRadiusM', desiredTopRadius, ...
        'effectiveBottomRadiusM', desiredBottomRadius, ...
        'effectiveTopRadiusPerWavelength', ...
            (desiredTopRadius - cfg.fs.r_inner) / wavelength, ...
        'effectiveBottomRadiusPerWavelength', ...
            (desiredBottomRadius - cfg.fs.r_inner) / wavelength, ...
        'legacyThetaNodeCount', legacyThetaCount, ...
        'commonOuterThetaNodeCount', commonThetaCount, ...
        'legacyThetaTargetM', max(topThetaTarget, bottomThetaTarget), ...
        'legacyTopThetaTargetM', topThetaTarget, ...
        'legacyBottomThetaTargetM', bottomThetaTarget, ...
        'legacyRadialTargetM', max(topRadialTarget, bottomRadialTarget), ...
        'legacyTopRadialTargetM', topRadialTarget, ...
        'legacyBottomRadialTargetM', bottomRadialTarget, ...
        'topTargetProvenance', ...
            'final-legacy-free-surface-outer-ring/band-vertices', ...
        'bottomTargetProvenance', ...
            'final-legacy-bottom-outer-ring/band-vertices-independent-of-FS', ...
        'legacyWallSlantTargetM', wallTarget, ...
        'thetaTargetPerWavelength', ...
            max(topThetaTarget, bottomThetaTarget) / wavelength, ...
        'topThetaTargetPerWavelength', topThetaTarget / wavelength, ...
        'bottomThetaTargetPerWavelength', bottomThetaTarget / wavelength, ...
        'radialTargetPerWavelength', ...
            max(topRadialTarget, bottomRadialTarget) / wavelength, ...
        'topRadialTargetPerWavelength', topRadialTarget / wavelength, ...
        'bottomRadialTargetPerWavelength', bottomRadialTarget / wavelength, ...
        'wallSlantTargetPerWavelength', wallTarget / wavelength, ...
        'actualMaximumThetaPerWavelength', ...
            max(actualTopTheta, actualBottomTheta) / wavelength, ...
        'actualTopThetaPerWavelength', actualTopTheta / wavelength, ...
        'actualBottomThetaPerWavelength', actualBottomTheta / wavelength, ...
        'actualTopMaximumRadialPerWavelength', ...
            topInfo.maximumRadialStep / wavelength, ...
        'actualBottomMaximumRadialPerWavelength', ...
            bottomInfo.maximumRadialStep / wavelength, ...
        'actualWallMaximumSlantPerWavelength', ...
            wallInfo.maximumSlantStep / wavelength, ...
        'roundingPolicy', ['Ntheta=nearest-multiple-4-if-within-5pct-', ...
            'else-4*ceil;Nz=round-if-within-5pct-else-ceil;', ...
            'finer-exceptions-are-not-held'], ...
        'configuredThetaControls', thetaControls, ...
        'topOuterThetaNodeCount', topThetaCount, ...
        'bottomOuterThetaNodeCount', bottomThetaCount, ...
        'commonWallCountProvenance', commonThetaProvenance, ...
        'topWallRingNodeCount', size(topRing, 1), ...
        'bottomWallRingNodeCount', size(bottomRing, 1), ...
        'thetaCountSelection', thetaSelection, ...
        'topThetaCountSelection', topThetaSelection, ...
        'bottomThetaCountSelection', bottomThetaSelection, ...
        'resolutionPass', resolutionPass, ...
        'resolutionHeld', resolutionHeld, ...
        'roundingFinerException', roundingFinerException, ...
        'componentPanelCountsBefore', beforeCounts, ...
        'componentPanelCountsAfter', afterCounts, ...
        'topSurfaceDerived', topInfo, 'bottomSurfaceDerived', bottomInfo, ...
        'wallDerived', wallInfo, ...
        'geometryDiagnostics', geometryDiagnostics, ...
        'freeSurfaceHash', topFingerprint.hash, ...
        'bottomHash', bottomFingerprint.hash, ...
        'outerBoundaryHash', outerFingerprint.hash, ...
        'connectorComponent', 'outer_boundary/FARFIELD', ...
        'sensitivityLabel', 'top/bottom-truncation-shape-sensitivity', ...
        'derivedClosureWhitelist', {{'surface-annulus-panel-count', ...
            'surface-outer-ring-node-count', 'endpoint-theta-count', ...
            'wall-ring-count-transition', 'wall-z-level-count', ...
            'wall-panel-count', 'vertices', 'centers', 'normals', ...
            'areas', 'component-hashes', 'merged-hash', 'matrix-size'}});
end

function specification = default_specification()
    specification = struct('enabled', false, ...
        'topRadiusPerWavelength', 1.5, ...
        'bottomRadiusPerWavelength', 1.5, ...
        'inputMode', 'legacy-absent', ...
        'minimumRadiusPerWavelength', 1.5);
end

function controls = resolve_theta_controls(cfg)
% RESOLVE_THETA_CONTROLS Read optional P-full endpoint controls.
% A zero value is an unset sentinel.  In particular, a q-only scientific
% truncation case does not acquire a second configured input: the changed
% endpoint count is derived internally from its frozen legacy spacing.
    controls = struct('common', 0, 'top', 0, 'bottom', 0, ...
        'commonField', 'outerThetaPanelCount', ...
        'topField', 'freeSurfaceOuterThetaPanelCount', ...
        'bottomField', 'bottomOuterThetaPanelCount');
    if ~isfield(cfg, 'phase2_2_controls')
        return
    end
    source = cfg.phase2_2_controls;
    controls.common = optional_theta_value(source, ...
        controls.commonField);
    controls.top = optional_theta_value(source, controls.topField);
    controls.bottom = optional_theta_value(source, controls.bottomField);
end

function value = optional_theta_value(source, name)
    value = 0;
    if isfield(source, name)
        value = source.(name);
    end
    assert(isnumeric(value) && isscalar(value) && isfinite(value) && ...
        value >= 0 && fix(value) == value && ...
        (value == 0 || mod(value, 4) == 0), ...
        'CRESTU:OuterTruncationThetaControl', ...
        '%s must be zero (unset) or a positive multiple of four.', name);
end

function policy = policy_specification()
    policy = struct('modelName', 'phase2.2-axisymmetric-wall-zipper-v4', ...
        'isEmpiricalCorrection', false, 'connectorComponent', 'FARFIELD', ...
        'radiusDefinition', 'R_top/bottom=r_inner+q_top/bottom*lambda', ...
        'legacyBaselineDefinition', 'R0=r_inner+1.5*lambda', ...
        'inactiveIdentityContract', ...
            'absent-PARA12-or-explicit-qtop=qbottom=1.5-does-not-mutate-mesh', ...
        'horizontalTransition', ...
            'conforming-monotone-zipper-with-degenerate-quad-triangles', ...
        'wallConstruction', ...
            ['common-count-structured-wall:legacy-structured-quads;', ...
            'endpoint-count-transition:horizontal-FS-or-bottom-annulus'], ...
        'wallStoredNormal', ...
            'n_s=(-e_r+(dR/dz)*e_z)/sqrt(1+(dR/dz)^2)', ...
        'resolutionRounding', ...
            'nearest-multiple4/round within 5pct; otherwise ceil-finer exception', ...
        'resolutionAcceptance', ...
            'held iff abs(h/target-1)<=0.05; finer exception accepted-not-held; coarser rejected', ...
        'legacyInnerRingRetained', true, 'allowsTJunctions', false, ...
        'endpointCountControl', ...
            ['q-only:internally-derived-from-frozen-endpoint-target;', ...
            'explicit-common-or-endpoint-counts:resolution-factor-only'], ...
        'changesSpongeParameters', false, 'changesBoundaryConditions', false);
end

function audit = unchanged_audit(specification, policy, wavelength, ...
        legacyRadius, baselineQ, counts, freeSurface, bottom, outerBoundary)
    freeSurfaceFingerprint = mesh_fingerprint(freeSurface);
    bottomFingerprint = mesh_fingerprint(bottom);
    outerFingerprint = mesh_fingerprint(outerBoundary);
    audit = struct('schemaVersion', 2, 'policy', policy, ...
        'enabled', specification.enabled, 'inputMode', specification.inputMode, ...
        'geometryModified', false, ...
        'independentTopQ', specification.topRadiusPerWavelength, ...
        'independentBottomQ', specification.bottomRadiusPerWavelength, ...
        'wavelengthM', wavelength, 'legacyRadiusM', legacyRadius, ...
        'legacyRadiusPerWavelength', baselineQ, ...
        'effectiveTopRadiusM', legacyRadius, ...
        'effectiveBottomRadiusM', legacyRadius, ...
        'effectiveTopRadiusPerWavelength', baselineQ, ...
        'effectiveBottomRadiusPerWavelength', baselineQ, ...
        'legacyThetaNodeCount', NaN, 'commonOuterThetaNodeCount', NaN, ...
        'configuredThetaControls', resolve_theta_controls(struct()), ...
        'topOuterThetaNodeCount', NaN, ...
        'bottomOuterThetaNodeCount', NaN, ...
        'topWallRingNodeCount', NaN, ...
        'bottomWallRingNodeCount', NaN, ...
        'commonWallCountProvenance', 'inactive', ...
        'legacyThetaTargetM', NaN, ...
        'legacyTopThetaTargetM', NaN, ...
        'legacyBottomThetaTargetM', NaN, ...
        'legacyRadialTargetM', NaN, ...
        'legacyTopRadialTargetM', NaN, ...
        'legacyBottomRadialTargetM', NaN, ...
        'topTargetProvenance', 'not-active', ...
        'bottomTargetProvenance', 'not-active', ...
        'legacyWallSlantTargetM', NaN, ...
        'thetaTargetPerWavelength', NaN, ...
        'topThetaTargetPerWavelength', NaN, ...
        'bottomThetaTargetPerWavelength', NaN, ...
        'radialTargetPerWavelength', NaN, ...
        'topRadialTargetPerWavelength', NaN, ...
        'bottomRadialTargetPerWavelength', NaN, ...
        'wallSlantTargetPerWavelength', NaN, ...
        'actualMaximumThetaPerWavelength', NaN, ...
        'actualTopThetaPerWavelength', NaN, ...
        'actualBottomThetaPerWavelength', NaN, ...
        'actualTopMaximumRadialPerWavelength', NaN, ...
        'actualBottomMaximumRadialPerWavelength', NaN, ...
        'actualWallMaximumSlantPerWavelength', NaN, ...
        'roundingPolicy', 'not-active', ...
        'thetaCountSelection', struct(), ...
        'topThetaCountSelection', struct(), ...
        'bottomThetaCountSelection', struct(), ...
        'resolutionPass', true, ...
        'resolutionHeld', true, 'roundingFinerException', false, ...
        'componentPanelCountsBefore', counts, ...
        'componentPanelCountsAfter', counts, ...
        'topSurfaceDerived', struct(), 'bottomSurfaceDerived', struct(), ...
        'wallDerived', struct(), ...
        'geometryDiagnostics', struct(), ...
        'freeSurfaceHash', freeSurfaceFingerprint.hash, ...
        'bottomHash', bottomFingerprint.hash, ...
        'outerBoundaryHash', outerFingerprint.hash, ...
        'connectorComponent', 'outer_boundary/FARFIELD', ...
        'sensitivityLabel', 'top/bottom-truncation-shape-sensitivity', ...
        'derivedClosureWhitelist', {{}});
end

function ring = extract_outer_ring(mesh, zValue, expectedRadius)
    vertices = reshape(mesh.vertices, [], 3);
    tolerance = 2e-8 * max([expectedRadius, abs(zValue), 1]);
    radius = hypot(vertices(:, 1), vertices(:, 2));
    mask = abs(vertices(:, 3) - zValue) <= tolerance & ...
        abs(radius - expectedRadius) <= tolerance;
    ring = unique(vertices(mask, :), 'rows');
    assert(size(ring, 1) >= 4, 'CRESTU:OuterTruncationRing', ...
        'Cannot identify a closed outer ring at r=%g,z=%g.', ...
        expectedRadius, zValue);
    theta = atan2(ring(:, 2), ring(:, 1));
    [~, order] = sort(theta);
    ring = ring(order, :);
end

function value = max_ring_edge(ring)
    next = ring([2:end, 1], :);
    value = max(sqrt(sum((next - ring) .^ 2, 2)));
end

function [top, bottom, combined] = choose_endpoint_theta_counts( ...
        topRadius, topTarget, bottomRadius, bottomTarget, legacyRadius, ...
        legacyCount, controls)
% CHOOSE_ENDPOINT_THETA_COUNTS Resolve each closure ring independently.
% This is the P-full isolation contract.  q_top alone derives only the top
% count; the fixed bottom ring remains the original legacy object.
    tolerance = 64 * eps(max([topRadius, bottomRadius, legacyRadius, 1]));
    top = choose_endpoint_theta_count('top', topRadius, topTarget, ...
        legacyRadius, legacyCount, controls.top, controls.common, ...
        topRadius > legacyRadius + tolerance);
    bottom = choose_endpoint_theta_count('bottom', bottomRadius, ...
        bottomTarget, legacyRadius, legacyCount, controls.bottom, ...
        controls.common, bottomRadius > legacyRadius + tolerance);
    sameCount = top.chosenCount == bottom.chosenCount;
    if sameCount
        chosenCount = top.chosenCount;
    else
        chosenCount = NaN;
    end
    combined = struct('mode', 'independent-endpoint-counts', ...
        'sameEndpointCount', sameCount, 'chosenCount', chosenCount, ...
        'topChosenCount', top.chosenCount, ...
        'bottomChosenCount', bottom.chosenCount, ...
        'topProvenance', top.provenance, ...
        'bottomProvenance', bottom.provenance, ...
        'roundingFinerException', top.roundingFinerException || ...
            bottom.roundingFinerException);
end

function selection = choose_endpoint_theta_count(endpoint, radius, target, ...
        legacyRadius, legacyCount, endpointControl, commonControl, extended)
    idealCount = exact_circle_panel_count(radius, target);
    configuredCount = endpointControl;
    provenance = [endpoint '-explicit-endpoint-count'];
    if configuredCount == 0 && commonControl > 0
        configuredCount = commonControl;
        provenance = 'explicit-common-count-fallback';
    end
    if configuredCount > 0
        candidateCount = configuredCount;
        chosenCount = configuredCount;
        roundingFinerException = false;
    elseif extended
        provenance = [endpoint '-q-derived-from-frozen-legacy-chord-target'];
        candidateCount = max(legacyCount, ...
            4 * max(1, round(idealCount / 4)));
        candidateStatus = assess_rankine_resolution( ...
            circle_chord(radius, candidateCount), target, 0.05);
        if candidateStatus.heldWithinTolerance
            chosenCount = candidateCount;
            roundingFinerException = false;
        else
            chosenCount = max(legacyCount, ...
                4 * max(1, ceil(idealCount / 4)));
            roundingFinerException = true;
        end
    else
        provenance = [endpoint '-unchanged-legacy-ring'];
        candidateCount = legacyCount;
        chosenCount = legacyCount;
        roundingFinerException = false;
    end
    assert(mod(chosenCount, 4) == 0, ...
        'CRESTU:OuterTruncationThetaMultiple', ...
        'The %s endpoint count must be a multiple of four.', endpoint);
    candidateSpacing = circle_chord(radius, candidateCount);
    candidateStatus = assess_rankine_resolution(candidateSpacing, ...
        target, 0.05);
    chosenSpacing = circle_chord(radius, chosenCount);
    chosenStatus = assess_rankine_resolution(chosenSpacing, target, 0.05);
    assert(chosenStatus.accepted, 'CRESTU:OuterTruncationThetaRounding', ...
        'The %s endpoint count is more than 5%% coarser than its target.', ...
        endpoint);
    if configuredCount > 0 && ~chosenStatus.heldWithinTolerance
        assert(chosenStatus.roundingFinerException, ...
            'CRESTU:OuterTruncationExplicitThetaCoarse', ...
            'An explicit %s endpoint theta count may be held or finer, not coarser.', ...
            endpoint);
        roundingFinerException = true;
    end
    selection = struct('endpoint', endpoint, 'multiple', 4, ...
        'provenance', provenance, 'configuredEndpointCount', ...
        endpointControl, 'configuredCommonFallbackCount', commonControl, ...
        'legacyRadiusM', legacyRadius, 'legacyCount', legacyCount, ...
        'radiusM', radius, 'targetM', target, 'idealCount', idealCount, ...
        'candidateCount', candidateCount, ...
        'candidateSpacingM', candidateSpacing, ...
        'candidateSignedRelativeDeviation', ...
            candidateStatus.signedRelativeDeviation, ...
        'candidateWithinTolerance', candidateStatus.heldWithinTolerance, ...
        'chosenCount', chosenCount, 'chosenSpacingM', chosenSpacing, ...
        'chosenSignedRelativeDeviation', ...
            chosenStatus.signedRelativeDeviation, ...
        'roundingFinerException', roundingFinerException, ...
        'chosenResolution', chosenStatus);
end

function count = exact_circle_panel_count(radius, chordTarget)
    ratio = min(1, chordTarget / (2 * radius));
    count = pi / asin(ratio);
end

function [count, provenance] = choose_common_wall_count(topCount, ...
        bottomCount, controls)
% CHOOSE_COMMON_WALL_COUNT Keep count transitions out of ABC-active panels.
% The common wall layout is at least as fine as either endpoint layout.  Any
% finer endpoint is connected to this layout by a horizontal annular zipper,
% whose panels retain the free-surface or bottom boundary classification.
    assert(isnumeric([topCount, bottomCount]) && ...
        all(isfinite([topCount, bottomCount])) && ...
        all([topCount, bottomCount] >= 4) && ...
        all(mod([topCount, bottomCount], 4) == 0), ...
        'CRESTU:OuterTruncationCommonCount', ...
        'Endpoint theta counts must be positive multiples of four.');
    if controls.common > 0
        count = controls.common;
        provenance = 'explicit-common-count';
        assert(count >= max(topCount, bottomCount), ...
            'CRESTU:OuterTruncationCommonCountCoarse', ...
            ['The explicit common wall count cannot be coarser than ', ...
            'either endpoint count.']);
    else
        count = max(topCount, bottomCount);
        provenance = 'worst-endpoint-resolution-count';
    end
    assert(mod(count, 4) == 0, 'CRESTU:OuterTruncationCommonMultiple', ...
        'The common ABC-wall count must be a multiple of four.');
end

function chord = circle_chord(radius, count)
    chord = 2 * radius * sin(pi / count);
end

function value = outer_band_radial_target(mesh, outerRadius)
    panelRadius = hypot(mesh.vertices(:, :, 1), mesh.vertices(:, :, 2));
    maximumRadius = max(panelRadius, [], 2);
    tolerance = 2e-8 * max(outerRadius, 1);
    rows = abs(maximumRadius - outerRadius) <= tolerance;
    assert(any(rows), 'CRESTU:OuterTruncationRadialTarget', ...
        'No legacy outer horizontal band was found.');
    selected = panelRadius(rows, :);
    value = max(max(selected, [], 2) - min(selected, [], 2));
    assert(isfinite(value) && value > 0, ...
        'CRESTU:OuterTruncationRadialTarget', ...
        'Legacy outer horizontal radial target is invalid.');
end

function [mesh, outerRing, info] = prepare_horizontal_surface(mesh, ...
        targetRadius, legacyRadius, commonThetaCount, startAngle, zValue, ...
        radialTarget, thetaTarget, cfg, panelType, gradualThetaTransition, ...
        qualityControlledTransition)
    legacyRing = extract_outer_ring(mesh, zValue, legacyRadius);
    legacyCount = size(legacyRing, 1);
    tolerance = 64 * eps(max([targetRadius, legacyRadius, 1]));
    extension = targetRadius - legacyRadius;
    if qualityControlledTransition
        [mesh, outerRing, info] = ...
            prepare_quality_controlled_one_to_two_surface(mesh, ...
            targetRadius, legacyRadius, commonThetaCount, startAngle, ...
            zValue, radialTarget, thetaTarget, cfg, panelType);
        return
    end
    if extension <= tolerance && commonThetaCount == legacyCount
        outerRing = legacyRing;
        info = surface_info(0, 0, 0, legacyCount, legacyCount, ...
            radialTarget, max_ring_edge(outerRing), radialTarget, ...
            thetaTarget, false, false);
        info.ringThetaNodeCounts = legacyCount;
        info.gradualThetaTransition = false;
        return
    end
    retessellationOnly = extension <= tolerance;
    if extension <= tolerance
        [mesh, innerRing, replacedPanelCount, maximumRadialStep] = ...
            remove_outer_band(mesh, legacyRadius);
        outerRing = circle_ring(legacyRadius, zValue, ...
            commonThetaCount, startAngle);
        panels = zipper_annulus(innerRing, outerRing);
        mesh = append_horizontal_panels(mesh, panels, panelType, cfg);
        appendedPanelCount = size(panels, 1);
        radialLayerCount = 1;
        ringThetaNodeCounts = [size(innerRing, 1); commonThetaCount];
    else
        replacedPanelCount = 0;
        radialLayerCount = max(1, ceil(extension / radialTarget));
        if gradualThetaTransition && commonThetaCount > legacyCount
            minimumTransitionLayers = ceil( ...
                (commonThetaCount - legacyCount) / 4);
            radialLayerCount = max(radialLayerCount, ...
                minimumTransitionLayers);
        end
        currentRing = legacyRing;
        currentCount = legacyCount;
        ringThetaNodeCounts = zeros(radialLayerCount + 1, 1);
        ringThetaNodeCounts(1) = legacyCount;
        panelBlocks = cell(radialLayerCount, 1);
        for layerIndex = 1:radialLayerCount
            radius = legacyRadius + extension * layerIndex / radialLayerCount;
            nextCount = commonThetaCount;
            if gradualThetaTransition
                nextCount = gradual_ring_count(legacyCount, ...
                    commonThetaCount, currentCount, layerIndex, ...
                    radialLayerCount);
            end
            nextRing = circle_ring(radius, zValue, nextCount, startAngle);
            panelBlocks{layerIndex} = zipper_annulus(currentRing, nextRing);
            currentRing = nextRing;
            currentCount = nextCount;
            ringThetaNodeCounts(layerIndex + 1) = nextCount;
        end
        panels = cat(1, panelBlocks{:});
        mesh = append_horizontal_panels(mesh, panels, panelType, cfg);
        outerRing = currentRing;
        appendedPanelCount = size(panels, 1);
        maximumRadialStep = extension / radialLayerCount;
    end
    mesh.header = sprintf('%s | Phase2.2 truncation r=%.9g Ntheta=%d', ...
        mesh.header, targetRadius, commonThetaCount);
    info = surface_info(replacedPanelCount, appendedPanelCount, ...
        radialLayerCount, legacyCount, commonThetaCount, maximumRadialStep, ...
        max_ring_edge(outerRing), radialTarget, thetaTarget, true, ...
        retessellationOnly);
    info.ringThetaNodeCounts = ringThetaNodeCounts;
    info.gradualThetaTransition = gradualThetaTransition && ...
        commonThetaCount > legacyCount;
    if numel(ringThetaNodeCounts) > 1
        info.maximumAdjacentThetaCountRatio = max( ...
            ringThetaNodeCounts(2:end) ./ ringThetaNodeCounts(1:end - 1));
    else
        info.maximumAdjacentThetaCountRatio = 1.0;
    end
    assert(~info.gradualThetaTransition || all( ...
        diff(ringThetaNodeCounts) <= 4), ...
        'CRESTU:OuterTruncationGradualThetaRatio', ...
        'An explicit horizontal-annulus transition adds more than 4 nodes.');
end

function [mesh, outerRing, info] = ...
        prepare_quality_controlled_one_to_two_surface(mesh, targetRadius, ...
        legacyRadius, commonThetaCount, startAngle, zValue, radialTarget, ...
        thetaTarget, cfg, panelType)
% PREPARE_QUALITY_CONTROLLED_ONE_TO_TWO_SURFACE Use a fixed 1:2 template.

    legacyRing = extract_outer_ring(mesh, zValue, legacyRadius);
    legacyCount = size(legacyRing, 1);
    assert(commonThetaCount == 2 * legacyCount, ...
        'CRESTU:QualityPolarOneToTwoCount', ...
        'QUALITY_CONTROLLED_V2 requires final theta count = 2*legacy count.');
    extension = targetRadius - legacyRadius;
    transitionStep = min(0.4 * max_ring_edge(legacyRing), radialTarget);
    tolerance = 64 * eps(max([targetRadius, legacyRadius, 1]));
    assert(extension > transitionStep + tolerance, ...
        'CRESTU:QualityPolarOneToTwoExtent', ...
        'Outer extension is too short for the predeclared 1:2 connector.');
    transitionRadius = legacyRadius + transitionStep;
    doubledRing = circle_ring(transitionRadius, zValue, ...
        commonThetaCount, startAngle);
    connectorPanels = one_to_two_annulus(legacyRing, doubledRing);
    connectorAudit = audit_one_to_two_connector(connectorPanels);

    remainingExtension = targetRadius - transitionRadius;
    equalLayerCount = max(1, ceil(remainingExtension / radialTarget));
    equalBlocks = cell(equalLayerCount, 1);
    currentRing = doubledRing;
    for layerIndex = 1:equalLayerCount
        radius = transitionRadius + remainingExtension * ...
            layerIndex / equalLayerCount;
        nextRing = circle_ring(radius, zValue, commonThetaCount, startAngle);
        equalBlocks{layerIndex} = zipper_annulus(currentRing, nextRing);
        currentRing = nextRing;
    end
    panels = cat(1, connectorPanels, equalBlocks{:});
    mesh = append_horizontal_panels(mesh, panels, panelType, cfg);
    outerRing = currentRing;
    radialLayerCount = 1 + equalLayerCount;
    maximumRadialStep = max(transitionStep, ...
        remainingExtension / equalLayerCount);
    mesh.header = sprintf('%s | QUALITY_CONTROLLED_V2 r=%.9g Ntheta=%d', ...
        mesh.header, targetRadius, commonThetaCount);
    info = surface_info(0, size(panels, 1), radialLayerCount, ...
        legacyCount, commonThetaCount, maximumRadialStep, ...
        max_ring_edge(outerRing), radialTarget, thetaTarget, true, false);
    info.ringThetaNodeCounts = [legacyCount; ...
        repmat(commonThetaCount, equalLayerCount + 1, 1)];
    info.gradualThetaTransition = false;
    info.qualityControlledOneToTwo = true;
    info.maximumAdjacentThetaCountRatio = 2.0;
    info.oneToTwoTransitionRadiusM = transitionRadius;
    info.oneToTwoTransitionStepM = transitionStep;
    info.oneToTwoConnectorAudit = connectorAudit;
    info.topology = 'quality-controlled-fixed-1to2-then-equal-count-quads';
end

function panels = one_to_two_annulus(innerRing, outerRing)
% ONE_TO_TWO_ANNULUS Apply the predeclared three-triangle sector template.

    innerCount = size(innerRing, 1);
    outerCount = size(outerRing, 1);
    assert(outerCount == 2 * innerCount, ...
        'CRESTU:QualityPolarOneToTwoShape', ...
        'The fixed connector requires exactly twice as many outer nodes.');
    panels = zeros(3 * innerCount, 4, 3);
    cursor = 0;
    for innerIndex = 1:innerCount
        nextInner = mod(innerIndex, innerCount) + 1;
        outerFirst = 2 * innerIndex - 1;
        outerMiddle = 2 * innerIndex;
        outerLast = mod(2 * innerIndex, outerCount) + 1;
        triangles = { ...
            [innerRing(innerIndex, :); outerRing(outerFirst, :); ...
                outerRing(outerMiddle, :)]; ...
            [innerRing(innerIndex, :); outerRing(outerMiddle, :); ...
                innerRing(nextInner, :)]; ...
            [innerRing(nextInner, :); outerRing(outerMiddle, :); ...
                outerRing(outerLast, :)]};
        for triangleIndex = 1:3
            triangle = triangles{triangleIndex};
            cursor = cursor + 1;
            panels(cursor, :, :) = reshape([triangle; triangle(3, :)], ...
                1, 4, 3);
        end
    end
end

function audit = audit_one_to_two_connector(panels)
% AUDIT_ONE_TO_TWO_CONNECTOR Enforce frozen angle/aspect/orientation gates.

    panelCount = size(panels, 1);
    minimumAngle = Inf;
    maximumAspectRatio = 0.0;
    minimumWindingAlignment = Inf;
    for panelIndex = 1:panelCount
        triangle = reshape(panels(panelIndex, 1:3, :), 3, 3);
        next = [2, 3, 1];
        edges = triangle(next, :) - triangle;
        lengths = vecnorm(edges, 2, 2);
        maximumAspectRatio = max(maximumAspectRatio, ...
            max(lengths) / min(lengths));
        for vertexIndex = 1:3
            previousIndex = mod(vertexIndex - 2, 3) + 1;
            incoming = triangle(previousIndex, :) - triangle(vertexIndex, :);
            outgoing = triangle(next(vertexIndex), :) - triangle(vertexIndex, :);
            cosine = dot(incoming, outgoing) / ...
                (norm(incoming) * norm(outgoing));
            minimumAngle = min(minimumAngle, ...
                acosd(max(-1, min(1, cosine))));
        end
        winding = cross(triangle(2, :) - triangle(1, :), ...
            triangle(3, :) - triangle(1, :));
        winding = winding / norm(winding);
        minimumWindingAlignment = min(minimumWindingAlignment, winding(3));
    end
    assert(minimumAngle >= 35.0 && maximumAspectRatio <= 12.0 && ...
        minimumWindingAlignment >= 1 - 1.0e-12, ...
        'CRESTU:QualityPolarOneToTwoQuality', ...
        ['The fixed 1:2 connector violates a frozen quality gate: ', ...
        'angle=%.9g deg, AR=%.9g, orientation=%.9g.'], ...
        minimumAngle, maximumAspectRatio, minimumWindingAlignment);
    audit = struct('panelCount', panelCount, ...
        'minimumAngleDeg', minimumAngle, ...
        'maximumAspectRatio', maximumAspectRatio, ...
        'minimumWindingAlignment', minimumWindingAlignment, ...
        'qualityGatePass', true, 'template', 'three-triangles-per-inner-sector');
end

function count = gradual_ring_count(legacyCount, finalCount, ...
        previousCount, layerIndex, layerCount)
% GRADUAL_RING_COUNT Distribute explicit count changes across radial layers.

    if layerIndex == layerCount
        count = finalCount;
        return
    end
    interpolated = legacyCount + (finalCount - legacyCount) * ...
        layerIndex / layerCount;
    count = 4 * round(interpolated / 4);
    count = min(finalCount, max(previousCount, count));
    assert(mod(count, 4) == 0 && count >= legacyCount && ...
        count <= finalCount, 'CRESTU:OuterTruncationGradualThetaCount', ...
        'A gradual explicit theta count is invalid.');
end

function info = surface_info(replacedCount, appendedCount, radialLayers, ...
        innerCount, outerCount, maximumRadialStep, maximumThetaStep, ...
        radialTarget, thetaTarget, modified, retessellationOnly)
    radialResolution = assess_rankine_resolution(maximumRadialStep, ...
        radialTarget, 0.05);
    thetaResolution = assess_rankine_resolution(maximumThetaStep, ...
        thetaTarget, 0.05);
    assert(radialResolution.accepted && thetaResolution.accepted, ...
        'CRESTU:OuterTruncationSurfaceResolution', ...
        'A generated horizontal-surface spacing is too coarse.');
    info = struct('geometryModified', modified, ...
        'retessellationOnly', retessellationOnly, ...
        'replacedLegacyOuterBandPanelCount', replacedCount, ...
        'appendedPanelCount', appendedCount, ...
        'radialLayerCount', radialLayers, ...
        'legacyInnerRingNodeCount', innerCount, ...
        'outerRingNodeCount', outerCount, ...
        'maximumRadialStep', maximumRadialStep, ...
        'maximumThetaStep', maximumThetaStep, ...
        'radialTargetM', radialTarget, 'thetaTargetM', thetaTarget, ...
        'radialResolution', radialResolution, ...
        'thetaResolution', thetaResolution, ...
        'topology', 'conforming-monotone-zipper-no-T-junction');
end

function [mesh, innerRing, removedCount, maximumRadialStep] = ...
        remove_outer_band(mesh, outerRadius)
    panelRadius = hypot(mesh.vertices(:, :, 1), mesh.vertices(:, :, 2));
    maximumRadius = max(panelRadius, [], 2);
    tolerance = 2e-8 * max(outerRadius, 1);
    removeRows = abs(maximumRadius - outerRadius) <= tolerance;
    assert(any(removeRows), 'CRESTU:OuterTruncationRemoveBand', ...
        'No outer band is available for a closure-only ring refinement.');
    removedVertices = reshape(mesh.vertices(removeRows, :, :), [], 3);
    removedRadius = hypot(removedVertices(:, 1), removedVertices(:, 2));
    innerRadius = min(removedRadius);
    innerRows = abs(removedRadius - innerRadius) <= tolerance;
    innerRing = unique(removedVertices(innerRows, :), 'rows');
    theta = atan2(innerRing(:, 2), innerRing(:, 1));
    [~, order] = sort(theta);
    innerRing = innerRing(order, :);
    maximumRadialStep = outerRadius - innerRadius;
    removedCount = nnz(removeRows);
    mesh = select_mesh_rows(mesh, ~removeRows);
end

function mesh = select_mesh_rows(mesh, keepRows)
    rowFields = {'vertices', 'centers', 'normals', 'areas', 'e1', 'e2', ...
        'panel_type', 'mu_damping'};
    oldCount = mesh.n_panels;
    for fieldIndex = 1:numel(rowFields)
        name = rowFields{fieldIndex};
        if isfield(mesh, name) && ~isempty(mesh.(name)) && ...
                size(mesh.(name), 1) == oldCount
            mesh.(name) = mesh.(name)(keepRows, :, :);
        end
    end
    mesh.n_panels = nnz(keepRows);
end

function ring = circle_ring(radius, zValue, count, startAngle)
    theta = startAngle + (0:count - 1)' * (2 * pi / count);
    ring = [radius * cos(theta), radius * sin(theta), ...
        repmat(zValue, count, 1)];
end

function panels = zipper_annulus(innerRing, outerRing)
    innerCount = size(innerRing, 1);
    outerCount = size(outerRing, 1);
    blocks = cell(innerCount + outerCount, 1);
    blockCount = 0;
    innerIndex = 0;
    outerIndex = 0;
    while innerIndex < innerCount || outerIndex < outerCount
        nextInner = inf;
        nextOuter = inf;
        if innerIndex < innerCount
            nextInner = (innerIndex + 1) / innerCount;
        end
        if outerIndex < outerCount
            nextOuter = (outerIndex + 1) / outerCount;
        end
        innerPoint = innerRing(mod(innerIndex, innerCount) + 1, :);
        outerPoint = outerRing(mod(outerIndex, outerCount) + 1, :);
        blockCount = blockCount + 1;
        if abs(nextInner - nextOuter) <= 32 * eps(max([nextInner, nextOuter, 1]))
            nextInnerPoint = innerRing(mod(innerIndex + 1, innerCount) + 1, :);
            nextOuterPoint = outerRing(mod(outerIndex + 1, outerCount) + 1, :);
            blocks{blockCount} = reshape([innerPoint; outerPoint; ...
                nextOuterPoint; nextInnerPoint], 1, 4, 3);
            innerIndex = innerIndex + 1;
            outerIndex = outerIndex + 1;
        elseif nextInner < nextOuter
            nextInnerPoint = innerRing(mod(innerIndex + 1, innerCount) + 1, :);
            blocks{blockCount} = triangle_quad(innerPoint, outerPoint, ...
                nextInnerPoint);
            innerIndex = innerIndex + 1;
        else
            nextOuterPoint = outerRing(mod(outerIndex + 1, outerCount) + 1, :);
            blocks{blockCount} = triangle_quad(innerPoint, outerPoint, ...
                nextOuterPoint);
            outerIndex = outerIndex + 1;
        end
    end
    panels = cat(1, blocks{1:blockCount});
end

function panel = triangle_quad(first, second, third)
    panel = reshape([first; second; third; third], 1, 4, 3);
end

function mesh = append_horizontal_panels(mesh, panels, panelType, cfg)
    [centers, normals, areas, e1, e2] = panel_geometry(panels, [0, 0, 1]);
    count = size(panels, 1);
    mesh.vertices = cat(1, mesh.vertices, panels);
    mesh.centers = cat(1, mesh.centers, centers);
    mesh.normals = cat(1, mesh.normals, normals);
    mesh.areas = cat(1, mesh.areas, areas);
    mesh.e1 = cat(1, mesh.e1, e1);
    mesh.e2 = cat(1, mesh.e2, e2);
    mesh.panel_type = cat(1, mesh.panel_type, repmat(panelType, count, 1));
    if isfield(mesh, 'mu_damping')
        radii = hypot(centers(:, 1), centers(:, 2));
        width = cfg.fs.r_outer - cfg.fs.r_inner;
        mu = cfg.fs.mu0 * max(0, min(1, ...
            (radii - cfg.fs.r_inner) / width)) .^ 2;
        mesh.mu_damping = cat(1, mesh.mu_damping, mu);
    end
    mesh.n_panels = size(mesh.centers, 1);
end

function [mesh, info] = build_frustum_wall(topRing, bottomRing, ...
        topRadius, bottomRadius, depth, slantTarget, topThetaTarget, ...
        bottomThetaTarget, isx, isy)
    assert(size(topRing, 1) == size(bottomRing, 1), ...
        'CRESTU:OuterTruncationWallRingCount', ...
        ['The ABC-active wall requires one common ring count; ', ...
        'count transitions belong on horizontal annuli.']);
    thetaCount = size(topRing, 1);
    slantLength = hypot(depth, topRadius - bottomRadius);
    countSelection = choose_linear_layer_count(slantLength, slantTarget);
    verticalLayerCount = countSelection.chosenCount;
    zLevels = linspace(0, -depth, verticalLayerCount + 1);
    radiusLevels = linspace(topRadius, bottomRadius, verticalLayerCount + 1);
    startAngle = atan2(topRing(1, 2), topRing(1, 1));
    rings = cell(verticalLayerCount + 1, 1);
    rings{1} = topRing;
    rings{end} = bottomRing;
    for levelIndex = 2:verticalLayerCount
        rings{levelIndex} = circle_ring(radiusLevels(levelIndex), ...
            zLevels(levelIndex), thetaCount, startAngle);
    end
    panels = zeros(verticalLayerCount * thetaCount, 4, 3);
    cursor = 0;
    for levelIndex = 1:verticalLayerCount
        upper = rings{levelIndex};
        lower = rings{levelIndex + 1};
        for thetaIndex = 1:thetaCount
            nextTheta = mod(thetaIndex, thetaCount) + 1;
            cursor = cursor + 1;
            panels(cursor, :, :) = reshape([upper(thetaIndex, :); ...
                upper(nextTheta, :); lower(nextTheta, :); ...
                lower(thetaIndex, :)], 1, 4, 3);
        end
    end
    slope = (topRadius - bottomRadius) / depth;
    [centers, windingNormals, areas, e1, e2] = panel_geometry(panels, []);
    centerRadius = hypot(centers(:, 1), centers(:, 2));
    analyticNormals = [-centers(:, 1) ./ centerRadius, ...
        -centers(:, 2) ./ centerRadius, repmat(slope, cursor, 1)];
    analyticNormals = analyticNormals ./ sqrt(1 + slope ^ 2);
    normalAlignment = sum(windingNormals .* analyticNormals, 2);
    facetSlope = slope * cos(pi / thetaCount);
    facetNormals = [-centers(:, 1) ./ centerRadius, ...
        -centers(:, 2) ./ centerRadius, repmat(facetSlope, cursor, 1)];
    facetNormals = facetNormals ./ sqrt(1 + facetSlope ^ 2);
    facetAlignment = sum(windingNormals .* facetNormals, 2);
    assert(min(facetAlignment) >= 1 - 1e-10 && ...
            min(normalAlignment) >= 1 - 1e-6, ...
        'CRESTU:OuterTruncationWallNormal', ...
        ['Frustum winding and analytic inward normals are inconsistent ', ...
        '(facet %.16g, continuous %.16g).'], ...
        min(facetAlignment), min(normalAlignment));
    slantResolution = assess_rankine_resolution( ...
        slantLength / verticalLayerCount, slantTarget, 0.05);
    topTangentialResolution = assess_rankine_resolution( ...
        max_ring_edge(topRing), topThetaTarget, 0.05);
    bottomTangentialResolution = assess_rankine_resolution( ...
        max_ring_edge(bottomRing), bottomThetaTarget, 0.05);
    assert(slantResolution.accepted && topTangentialResolution.accepted && ...
            bottomTangentialResolution.accepted, ...
        'CRESTU:OuterTruncationWallResolution', ...
        'A generated frustum-wall spacing is too coarse.');
    mesh = struct('header', sprintf( ...
        'Phase2.2 FARFIELD frustum Rt=%.9g Rb=%.9g Nz=%d Ntheta=%d', ...
        topRadius, bottomRadius, verticalLayerCount, thetaCount), ...
        'ulen', 1.0, 'panel_type', repmat(5, cursor, 1), ...
        'isx', isx, 'isy', isy, 'n_panels', cursor, ...
        'vertices', panels, 'centers', centers, 'normals', windingNormals, ...
        'areas', areas, 'e1', e1, 'e2', e2, ...
        'hydrostatics', struct('Vx', 0, 'Vy', 0, 'Vz', 0, ...
            'V_mean', 0, 'center_of_buoyancy', [0, 0, 0]));
    info = struct('verticalLayerCount', verticalLayerCount, ...
        'thetaNodeCount', thetaCount, 'panelCount', cursor, ...
        'topThetaNodeCount', thetaCount, ...
        'bottomThetaNodeCount', thetaCount, ...
        'ringThetaNodeCounts', repmat(thetaCount, ...
            verticalLayerCount + 1, 1), ...
        'equalEndpointCounts', true, ...
        'topology', 'legacy-structured-equal-count-quads', ...
        'topRadiusM', topRadius, 'bottomRadiusM', bottomRadius, ...
        'slopeDRDZ', slope, 'slantLengthM', slantLength, ...
        'maximumSlantStep', slantLength / verticalLayerCount, ...
        'slantTargetM', slantTarget, 'countSelection', countSelection, ...
        'slantResolution', slantResolution, ...
        'topTangentialResolution', topTangentialResolution, ...
        'bottomTangentialResolution', bottomTangentialResolution, ...
        'minimumWindingFacetNormalAlignment', min(facetAlignment), ...
        'minimumWindingAnalyticNormalAlignment', min(normalAlignment), ...
        'analyticAreaM2', pi * (topRadius + bottomRadius) * slantLength, ...
        'panelAreaM2', sum(areas), ...
        'component', 'outer_boundary/FARFIELD');
end

function selection = choose_linear_layer_count(lengthValue, targetSpacing)
    idealCount = lengthValue / targetSpacing;
    candidateCount = max(1, round(idealCount));
    candidateSpacing = lengthValue / candidateCount;
    candidateStatus = assess_rankine_resolution(candidateSpacing, ...
        targetSpacing, 0.05);
    if candidateStatus.heldWithinTolerance
        chosenCount = candidateCount;
        roundingFinerException = false;
    else
        chosenCount = max(1, ceil(idealCount));
        roundingFinerException = true;
    end
    chosenSpacing = lengthValue / chosenCount;
    chosenStatus = assess_rankine_resolution(chosenSpacing, ...
        targetSpacing, 0.05);
    assert(chosenStatus.accepted, 'CRESTU:OuterTruncationWallRounding', ...
        'The rounded frustum wall spacing is too coarse.');
    selection = struct('idealCount', idealCount, ...
        'candidateCount', candidateCount, ...
        'candidateSpacingM', candidateSpacing, ...
        'candidateSignedRelativeDeviation', ...
            candidateStatus.signedRelativeDeviation, ...
        'candidateWithinTolerance', ...
            candidateStatus.heldWithinTolerance, ...
        'chosenCount', chosenCount, 'chosenSpacingM', chosenSpacing, ...
        'chosenSignedRelativeDeviation', ...
            chosenStatus.signedRelativeDeviation, ...
        'roundingFinerException', roundingFinerException, ...
        'chosenResolution', chosenStatus);
end

function [centers, normals, areas, e1, e2] = panel_geometry(vertices, forcedNormal)
    panelCount = size(vertices, 1);
    centers = zeros(panelCount, 3);
    normals = zeros(panelCount, 3);
    areas = zeros(panelCount, 1);
    e1 = zeros(panelCount, 3);
    e2 = zeros(panelCount, 3);
    for panelIndex = 1:panelCount
        panel = reshape(vertices(panelIndex, :, :), 4, 3);
        isTriangle = norm(panel(4, :) - panel(3, :)) <= 1e-13;
        if isTriangle
            centers(panelIndex, :) = mean(panel(1:3, :), 1);
        else
            centers(panelIndex, :) = mean(panel, 1);
        end
        areaVector = cross(panel(3, :) - panel(1, :), ...
            panel(4, :) - panel(2, :));
        magnitude = norm(areaVector);
        assert(magnitude > 1e-12, 'CRESTU:OuterTruncationPanelArea', ...
            'A generated truncation panel has zero area.');
        areas(panelIndex) = 0.5 * magnitude;
        windingNormal = areaVector / magnitude;
        if isempty(forcedNormal)
            normals(panelIndex, :) = windingNormal;
        else
            normals(panelIndex, :) = forcedNormal;
            assert(dot(windingNormal, forcedNormal) >= 1 - 1e-10, ...
                'CRESTU:OuterTruncationPanelWinding', ...
                'Horizontal truncation panel winding is inconsistent.');
        end
        tangent = panel(2, :) - panel(1, :);
        if norm(tangent) <= 1e-12
            tangent = panel(3, :) - panel(1, :);
        end
        tangent = tangent - dot(tangent, normals(panelIndex, :)) * ...
            normals(panelIndex, :);
        e1(panelIndex, :) = tangent / norm(tangent);
        e2(panelIndex, :) = cross(normals(panelIndex, :), e1(panelIndex, :));
    end
end

function diagnostics = audit_axisymmetric_wall_geometry(mesh, topRing, ...
        bottomRing, commonCount, topEndpointCount, bottomEndpointCount, ...
        topInfo, bottomInfo, commonCountProvenance)
% AUDIT_AXISYMMETRIC_WALL_GEOMETRY Enforce the mesh-side ABC contract.
% This audit derives normals from the stored panel vertices and never changes
% them.  The only panels allowed to change circumferential count are the
% horizontal FS/bottom annuli; every FARFIELD panel is from one structured
% equal-count ring layout.
    vertices = reshape(mesh.vertices, [], 4, 3);
    panelCount = size(vertices, 1);
    assert(panelCount == mesh.n_panels && panelCount > 0, ...
        'CRESTU:OuterTruncationGeometryPanelCount', ...
        'The active ABC wall has an invalid panel count.');
    assert(all(isfinite(vertices), 'all') && all(isfinite(mesh.centers), 'all') && ...
        all(isfinite(mesh.normals), 'all') && all(isfinite(mesh.areas)) && ...
        all(mesh.areas > 0), 'CRESTU:OuterTruncationGeometryFinite', ...
        'The active ABC wall contains non-finite or non-positive geometry.');

    windingNormals = zeros(panelCount, 3);
    windingAlignment = zeros(panelCount, 1);
    for panelIndex = 1:panelCount
        panel = reshape(vertices(panelIndex, :, :), 4, 3);
        areaVector = cross(panel(3, :) - panel(1, :), ...
            panel(4, :) - panel(2, :));
        magnitude = norm(areaVector);
        assert(isfinite(magnitude) && magnitude > 0, ...
            'CRESTU:OuterTruncationGeometryDegenerate', ...
            'The active ABC wall contains a degenerate panel.');
        windingNormals(panelIndex, :) = areaVector / magnitude;
        windingAlignment(panelIndex) = dot(windingNormals(panelIndex, :), ...
            mesh.normals(panelIndex, :));
    end
    geometryTolerance = 4096 * eps;
    assert(min(windingAlignment) >= 1 - geometryTolerance, ...
        'CRESTU:OuterTruncationGeometryWinding', ...
        'Stored ABC-wall normals do not match the actual panel winding.');

    centerRadius = hypot(mesh.centers(:, 1), mesh.centers(:, 2));
    radialUnit = [mesh.centers(:, 1) ./ centerRadius, ...
        mesh.centers(:, 2) ./ centerRadius, zeros(panelCount, 1)];
    tangentialUnit = [-mesh.centers(:, 2) ./ centerRadius, ...
        mesh.centers(:, 1) ./ centerRadius, zeros(panelCount, 1)];
    radialNormal = sum(mesh.normals .* radialUnit, 2);
    tangentialNormal = sum(mesh.normals .* tangentialUnit, 2);
    assert(all(centerRadius > 0) && all(radialNormal < 0), ...
        'CRESTU:OuterTruncationGeometryRadial', ...
        'The active ABC wall has an invalid radial location or orientation.');
    maximumAbsTangentialNormal = max(abs(tangentialNormal));
    assert(maximumAbsTangentialNormal <= geometryTolerance, ...
        'CRESTU:OuterTruncationGeometryTangential', ...
        'The active ABC wall has a geometric azimuthal normal component.');

    radiusTolerance = 512 * eps(max([max(centerRadius), 1]));
    vertexRadius = hypot(vertices(:, :, 1), vertices(:, :, 2));
    assert(all(abs(vertexRadius(:, 1) - vertexRadius(:, 2)) <= radiusTolerance) && ...
        all(abs(vertexRadius(:, 3) - vertexRadius(:, 4)) <= radiusTolerance), ...
        'CRESTU:OuterTruncationGeometryRadius', ...
        'ABC-wall panel vertices do not remain on their local circular rings.');
    assert(size(topRing, 1) == commonCount && ...
        size(bottomRing, 1) == commonCount && ...
        mesh.n_panels >= commonCount, ...
        'CRESTU:OuterTruncationGeometryMapping', ...
        'The ABC-wall ring mapping is not a common equal-count layout.');
    assert(all(mesh.panel_type == 5), ...
        'CRESTU:OuterTruncationGeometryBC', ...
        'The active ABC wall contains a non-FARFIELD panel type.');
    wallTopVertices = unique(reshape(vertices(1:commonCount, 1:2, :), ...
        [], 3), 'rows');
    wallBottomVertices = unique(reshape(vertices(end - commonCount + 1:end, ...
        3:4, :), [], 3), 'rows');
    sortedTopRing = sortrows(topRing);
    sortedBottomRing = sortrows(bottomRing);
    assert(size(wallTopVertices, 1) == commonCount && ...
        size(wallBottomVertices, 1) == commonCount && ...
        max(abs(sortrows(wallTopVertices) - sortedTopRing), [], 'all') <= radiusTolerance && ...
        max(abs(sortrows(wallBottomVertices) - sortedBottomRing), [], 'all') <= radiusTolerance, ...
        'CRESTU:OuterTruncationGeometryClosure', ...
        'The horizontal-to-ABC ring mapping has a gap or duplicate node.');

    panelKeys = reshape(vertices, panelCount, 12);
    duplicatePanelCount = panelCount - size(unique(panelKeys, 'rows'), 1);
    assert(duplicatePanelCount == 0, 'CRESTU:OuterTruncationDuplicatePanel', ...
        'The active ABC wall contains duplicate panels.');

    transitionPanelCount = 0;
    transitionPanelCount = transitionPanelCount + ...
        topInfo.appendedPanelCount * (topEndpointCount ~= commonCount);
    transitionPanelCount = transitionPanelCount + ...
        bottomInfo.appendedPanelCount * (bottomEndpointCount ~= commonCount);
    transitionPass = (topEndpointCount == bottomEndpointCount) || ...
        transitionPanelCount > 0;
    assert(transitionPass, 'CRESTU:OuterTruncationTransitionMissing', ...
        ['Unequal endpoint counts require a non-ABC horizontal annular ', ...
        'transition.']);

    transitionBoundaryTypes = [];
    if topEndpointCount ~= commonCount
        transitionBoundaryTypes(end + 1) = topInfo.transitionBoundaryType;
    end
    if bottomEndpointCount ~= commonCount
        transitionBoundaryTypes(end + 1) = bottomInfo.transitionBoundaryType;
    end
    transitionBoundaryTypes = unique(transitionBoundaryTypes);
    transitionIsNonABC = all(ismember(transitionBoundaryTypes, [2, 4]));
    assert(transitionIsNonABC, 'CRESTU:OuterTruncationTransitionType', ...
        'A count-transition adapter was not classified as FS/bottom.');

    diagnostics = struct('geometryTolerance', geometryTolerance, ...
        'radiusTolerance', radiusTolerance, ...
        'maximumAbsTangentialNormal', maximumAbsTangentialNormal, ...
        'radialNormalRange', [min(radialNormal), max(radialNormal)], ...
        'minimumWindingAlignment', min(windingAlignment), ...
        'duplicatePanelCount', duplicatePanelCount, ...
        'topEndpointCount', topEndpointCount, ...
        'bottomEndpointCount', bottomEndpointCount, ...
        'commonWallCount', commonCount, ...
        'topWallRingCount', size(topRing, 1), ...
        'bottomWallRingCount', size(bottomRing, 1), ...
        'transitionPanelCount', transitionPanelCount, ...
        'transitionBoundaryTypes', transitionBoundaryTypes, ...
        'transitionIsNonABC', transitionIsNonABC, ...
        'radiusConsistencyPass', true, ...
        'windingPass', true, ...
        'positiveAreaPass', true, ...
        'duplicatePanelPass', true, ...
        'mappingPass', true, ...
        'commonCountProvenance', commonCountProvenance);
end
