function status = assess_rankine_resolution(actualSpacing, targetSpacing, ...
        toleranceFraction)
% ASSESS_RANKINE_RESOLUTION Classify one physical mesh-spacing ratio.
% A spacing is held only inside the symmetric tolerance.  A spacing that is
% more than the tolerance finer is admissible only as an explicit rounding
% exception; a spacing that is more than the tolerance coarser is rejected.

    if nargin < 3
        toleranceFraction = 0.05;
    end
    validateattributes(actualSpacing, {'numeric'}, ...
        {'scalar', 'real', 'nonnegative', 'finite'});
    validateattributes(targetSpacing, {'numeric'}, ...
        {'scalar', 'real', 'positive', 'finite'});
    validateattributes(toleranceFraction, {'numeric'}, ...
        {'scalar', 'real', 'nonnegative', 'finite', '<', 1});

    signedDeviation = actualSpacing / targetSpacing - 1;
    comparisonTolerance = 64 * eps(max([abs(signedDeviation), ...
        toleranceFraction, 1]));
    heldWithinTolerance = abs(signedDeviation) <= ...
        toleranceFraction + comparisonTolerance;
    roundingFinerException = signedDeviation < ...
        -toleranceFraction - comparisonTolerance;
    coarserViolation = signedDeviation > ...
        toleranceFraction + comparisonTolerance;
    accepted = heldWithinTolerance || roundingFinerException;
    if heldWithinTolerance
        classification = 'held-within-plus-minus-5-percent';
    elseif roundingFinerException
        classification = 'accepted-finer-rounding-exception-not-held';
    else
        classification = 'rejected-coarser-than-plus-5-percent';
    end
    status = struct('actualSpacingM', actualSpacing, ...
        'targetSpacingM', targetSpacing, ...
        'actualOverTarget', actualSpacing / targetSpacing, ...
        'signedRelativeDeviation', signedDeviation, ...
        'toleranceFraction', toleranceFraction, ...
        'heldWithinTolerance', heldWithinTolerance, ...
        'roundingFinerException', roundingFinerException, ...
        'coarserViolation', coarserViolation, 'accepted', accepted, ...
        'classification', classification);
end
