function [cfg, manifest] = bind_phase2_2_operator_state(cfg, operatorState)
% BIND_PHASE2_2_OPERATOR_STATE Bind actual BC/operator hashes per frequency.

    assert(isfield(cfg, 'phase2_2_controls') && ...
        isfield(cfg.phase2_2_controls, 'manifest') && ...
        isfield(operatorState, 'boundaryOperatorStateSHA256'), ...
        'CRESTU:Phase22OperatorManifest', ...
        'A finalized control manifest and operator state are required.');
    manifest = cfg.phase2_2_controls.manifest;
    manifest.boundaryOperatorState = operatorState;
    manifest.effective.freeSurfaceRobinCoefficientSHA256 = ...
        operatorState.freeSurfaceRobinCoefficientSHA256;
    manifest.effective.freeSurfaceDampingSHA256 = ...
        operatorState.freeSurfaceDampingSHA256;
    manifest.effective.outerGammaSHA256 = operatorState.outerGammaSHA256;
    manifest.effective.boundaryOperatorStateSHA256 = ...
        operatorState.boundaryOperatorStateSHA256;
    manifest.effectiveSHA256 = sha256_hash(jsonencode(manifest.effective));
    cfg.phase2_2_controls.effective = manifest.effective;
    cfg.phase2_2_controls.manifest = manifest;
end
