function [mesh, info] = build_rankine_unequal_frustum_wall(topRing, ...
        bottomRing, topRadius, bottomRadius, depth, slantTarget, ...
        topThetaTarget, bottomThetaTarget, topSelection, ...
        bottomSelection, isx, isy)
% BUILD_RANKINE_UNEQUAL_FRUSTUM_WALL Close independently meshed endpoints.
% This helper is geometry/control instrumentation only.  It does not alter
% any boundary-condition, kernel, right-hand-side, or force formula.
%
% The stored FARFIELD normal points into the bounded fluid domain.  Each
% adjacent z-ring pair is joined by a monotone cyclic zipper.  Degenerate
% quads encode triangles as [v1 v2 v3 v3], which is supported by the active
% analytic Rankine panel-integral path.

    validate_ring(topRing, topRadius, 0, 'top');
    validate_ring(bottomRing, bottomRadius, -depth, 'bottom');
    topCount = size(topRing, 1);
    bottomCount = size(bottomRing, 1);
    assert(topCount ~= bottomCount, 'CRESTU:UnequalWallEqualCounts', ...
        'The unequal-count helper must not replace the legacy equal-count path.');
    assert(topSelection.chosenCount == topCount && ...
            bottomSelection.chosenCount == bottomCount, ...
        'CRESTU:UnequalWallSelection', ...
        'Endpoint rings do not match their resolved count selections.');
    assert(depth > 0 && slantTarget > 0 && ...
            all(isfinite([depth, slantTarget, topRadius, bottomRadius])), ...
        'CRESTU:UnequalWallInput', ...
        'Frustum dimensions and target spacing must be finite and positive.');

    slantLength = hypot(depth, topRadius - bottomRadius);
    countSelection = select_linear_count(slantLength, slantTarget);
    initialVerticalCount = countSelection.chosenCount;
    verticalCount = initialVerticalCount;
    startAngle = atan2(topRing(1, 2), topRing(1, 1));
    accepted = false;
    maximumCandidates = 256;
    for candidateIndex = 1:maximumCandidates
        [panels, ringCounts] = build_candidate(topRing, bottomRing, ...
            topRadius, bottomRadius, depth, verticalCount, startAngle);
        maximumSlantStep = maximum_cross_level_edge(panels);
        slantResolution = assess_rankine_resolution(maximumSlantStep, ...
            slantTarget, 0.05);
        if slantResolution.accepted
            accepted = true;
            break
        end
        verticalCount = verticalCount + 1;
    end
    assert(accepted, 'CRESTU:UnequalWallLayerSearch', ...
        ['Unable to hold the unequal-count wall cross-level spacing ', ...
        'after %d layer-count candidates.'], maximumCandidates);

    [centers, normals, areas, e1, e2, triangleMask] = ...
        panel_geometry(panels);
    panelCount = size(panels, 1);
    slope = (topRadius - bottomRadius) / depth;
    centerRadius = hypot(centers(:, 1), centers(:, 2));
    analyticNormals = [-centers(:, 1) ./ centerRadius, ...
        -centers(:, 2) ./ centerRadius, repmat(slope, panelCount, 1)];
    analyticNormals = analyticNormals ./ sqrt(1 + slope ^ 2);
    alignment = sum(normals .* analyticNormals, 2);
    assert(all(isfinite(panels), 'all') && ...
            all(isfinite(centers), 'all') && ...
            all(isfinite(normals), 'all') && all(isfinite(areas)) && ...
            all(areas > 0) && min(alignment) > 0, ...
        'CRESTU:UnequalWallGeometry', ...
        ['Every zipper panel must be finite, positive-area, and inward ', ...
        '(minimum analytic-normal dot %.16g).'], min(alignment));

    topTangentialResolution = assess_rankine_resolution( ...
        max_ring_edge(topRing), topThetaTarget, 0.05);
    bottomTangentialResolution = assess_rankine_resolution( ...
        max_ring_edge(bottomRing), bottomThetaTarget, 0.05);
    assert(topTangentialResolution.accepted && ...
            bottomTangentialResolution.accepted, ...
        'CRESTU:UnequalWallTangentialResolution', ...
        'An endpoint tangential spacing is more than 5%% coarser than target.');

    nominalSpacing = slantLength / verticalCount;
    nominalResolution = assess_rankine_resolution(nominalSpacing, ...
        slantTarget, 0.05);
    countSelection.initialChosenCount = initialVerticalCount;
    countSelection.chosenCount = verticalCount;
    countSelection.chosenSpacingM = nominalSpacing;
    countSelection.chosenSignedRelativeDeviation = ...
        nominalResolution.signedRelativeDeviation;
    countSelection.roundingFinerException = ...
        countSelection.roundingFinerException || ...
        verticalCount > initialVerticalCount || ...
        nominalResolution.roundingFinerException;
    countSelection.chosenResolution = nominalResolution;
    countSelection.actualMaximumCrossLevelEdgeM = maximumSlantStep;
    countSelection.actualCrossLevelResolution = slantResolution;
    mesh = struct('header', sprintf( ...
        ['Phase2.2 FARFIELD frustum Rt=%.9g Rb=%.9g Nz=%d ', ...
        'Ntheta=%d->%d unequal-zipper'], topRadius, bottomRadius, ...
        verticalCount, topCount, bottomCount), ...
        'ulen', 1.0, 'panel_type', repmat(5, panelCount, 1), ...
        'isx', isx, 'isy', isy, 'n_panels', panelCount, ...
        'vertices', panels, 'centers', centers, 'normals', normals, ...
        'areas', areas, 'e1', e1, 'e2', e2, ...
        'hydrostatics', struct('Vx', 0, 'Vy', 0, 'Vz', 0, ...
            'V_mean', 0, 'center_of_buoyancy', [0, 0, 0]));
    info = struct('verticalLayerCount', verticalCount, ...
        'thetaNodeCount', NaN, 'topThetaNodeCount', topCount, ...
        'bottomThetaNodeCount', bottomCount, ...
        'ringThetaNodeCounts', ringCounts, ...
        'equalEndpointCounts', false, ...
        'topology', 'shared-ring-monotone-unequal-count-zipper', ...
        'panelCount', panelCount, 'trianglePanelCount', nnz(triangleMask), ...
        'quadPanelCount', nnz(~triangleMask), ...
        'topRadiusM', topRadius, 'bottomRadiusM', bottomRadius, ...
        'slopeDRDZ', slope, 'slantLengthM', slantLength, ...
        'maximumSlantStep', maximumSlantStep, ...
        'slantTargetM', slantTarget, 'countSelection', countSelection, ...
        'slantResolution', slantResolution, ...
        'topTangentialResolution', topTangentialResolution, ...
        'bottomTangentialResolution', bottomTangentialResolution, ...
        'minimumWindingFacetNormalAlignment', NaN, ...
        'minimumWindingAnalyticNormalAlignment', min(alignment), ...
        'analyticAreaM2', pi * (topRadius + bottomRadius) * slantLength, ...
        'panelAreaM2', sum(areas), ...
        'component', 'outer_boundary/FARFIELD');
end

function validate_ring(ring, radius, zValue, label)
    assert(isnumeric(ring) && size(ring, 2) == 3 && ...
            size(ring, 1) >= 4 && mod(size(ring, 1), 4) == 0 && ...
            all(isfinite(ring), 'all'), ...
        'CRESTU:UnequalWallRing', ...
        'The %s endpoint ring must be finite with a multiple-of-four count.', ...
        label);
    tolerance = 2e-8 * max([radius, abs(zValue), 1]);
    assert(max(abs(hypot(ring(:, 1), ring(:, 2)) - radius)) <= tolerance && ...
            max(abs(ring(:, 3) - zValue)) <= tolerance, ...
        'CRESTU:UnequalWallRingLocation', ...
        'The %s endpoint ring is not on its declared circle.', label);
end

function selection = select_linear_count(lengthValue, target)
    ideal = lengthValue / target;
    candidate = max(1, round(ideal));
    candidateStatus = assess_rankine_resolution(lengthValue / candidate, ...
        target, 0.05);
    if candidateStatus.heldWithinTolerance
        count = candidate;
        finerException = false;
    else
        count = max(1, ceil(ideal));
        finerException = true;
    end
    chosenSpacing = lengthValue / count;
    chosenStatus = assess_rankine_resolution(chosenSpacing, target, 0.05);
    assert(chosenStatus.accepted, 'CRESTU:UnequalWallLinearRounding', ...
        'The selected nominal wall layer spacing is too coarse.');
    selection = struct('idealCount', ideal, 'candidateCount', candidate, ...
        'candidateSpacingM', lengthValue / candidate, ...
        'candidateSignedRelativeDeviation', ...
            candidateStatus.signedRelativeDeviation, ...
        'candidateWithinTolerance', candidateStatus.heldWithinTolerance, ...
        'chosenCount', count, 'chosenSpacingM', chosenSpacing, ...
        'chosenSignedRelativeDeviation', ...
            chosenStatus.signedRelativeDeviation, ...
        'roundingFinerException', finerException, ...
        'chosenResolution', chosenStatus);
end

function [panels, counts] = build_candidate(topRing, bottomRing, ...
        topRadius, bottomRadius, depth, verticalCount, startAngle)
    fractions = (0:verticalCount)' / verticalCount;
    counts = 4 * max(1, round((size(topRing, 1) + fractions * ...
        (size(bottomRing, 1) - size(topRing, 1))) / 4));
    counts(1) = size(topRing, 1);
    counts(end) = size(bottomRing, 1);
    zLevels = -depth * fractions;
    radiusLevels = topRadius + fractions * (bottomRadius - topRadius);
    rings = cell(verticalCount + 1, 1);
    rings{1} = topRing;
    rings{end} = bottomRing;
    for levelIndex = 2:verticalCount
        rings{levelIndex} = circle_ring(radiusLevels(levelIndex), ...
            zLevels(levelIndex), counts(levelIndex), startAngle);
    end
    blocks = cell(verticalCount, 1);
    for levelIndex = 1:verticalCount
        blocks{levelIndex} = zipper_cyclic(rings{levelIndex + 1}, ...
            rings{levelIndex});
    end
    panels = cat(1, blocks{:});
end

function ring = circle_ring(radius, zValue, count, startAngle)
    theta = startAngle + (0:count - 1)' * (2 * pi / count);
    ring = [radius * cos(theta), radius * sin(theta), ...
        repmat(zValue, count, 1)];
end

function panels = zipper_cyclic(lowerRing, upperRing)
% ZIPPER_CYCLIC Passing lower first preserves the legacy inward winding.
    lowerCount = size(lowerRing, 1);
    upperCount = size(upperRing, 1);
    blocks = cell(lowerCount + upperCount, 1);
    blockCount = 0;
    lowerIndex = 0;
    upperIndex = 0;
    while lowerIndex < lowerCount || upperIndex < upperCount
        nextLower = inf;
        nextUpper = inf;
        if lowerIndex < lowerCount
            nextLower = (lowerIndex + 1) / lowerCount;
        end
        if upperIndex < upperCount
            nextUpper = (upperIndex + 1) / upperCount;
        end
        lower = lowerRing(mod(lowerIndex, lowerCount) + 1, :);
        upper = upperRing(mod(upperIndex, upperCount) + 1, :);
        blockCount = blockCount + 1;
        if abs(nextLower - nextUpper) <= ...
                32 * eps(max([nextLower, nextUpper, 1]))
            nextLowerPoint = lowerRing( ...
                mod(lowerIndex + 1, lowerCount) + 1, :);
            nextUpperPoint = upperRing( ...
                mod(upperIndex + 1, upperCount) + 1, :);
            blocks{blockCount} = reshape([lower; upper; ...
                nextUpperPoint; nextLowerPoint], 1, 4, 3);
            lowerIndex = lowerIndex + 1;
            upperIndex = upperIndex + 1;
        elseif nextLower < nextUpper
            nextLowerPoint = lowerRing( ...
                mod(lowerIndex + 1, lowerCount) + 1, :);
            blocks{blockCount} = triangle_quad(lower, upper, nextLowerPoint);
            lowerIndex = lowerIndex + 1;
        else
            nextUpperPoint = upperRing( ...
                mod(upperIndex + 1, upperCount) + 1, :);
            blocks{blockCount} = triangle_quad(lower, upper, nextUpperPoint);
            upperIndex = upperIndex + 1;
        end
    end
    panels = cat(1, blocks{1:blockCount});
end

function panel = triangle_quad(first, second, third)
    panel = reshape([first; second; third; third], 1, 4, 3);
end

function value = max_ring_edge(ring)
    next = ring([2:end, 1], :);
    value = max(sqrt(sum((next - ring) .^ 2, 2)));
end

function value = maximum_cross_level_edge(panels)
    value = 0;
    for panelIndex = 1:size(panels, 1)
        polygon = unique_polygon(reshape(panels(panelIndex, :, :), 4, 3));
        for vertexIndex = 1:size(polygon, 1)
            nextIndex = mod(vertexIndex, size(polygon, 1)) + 1;
            first = polygon(vertexIndex, :);
            second = polygon(nextIndex, :);
            if abs(second(3) - first(3)) > 1e-12
                value = max(value, norm(second - first));
            end
        end
    end
    assert(isfinite(value) && value > 0, ...
        'CRESTU:UnequalWallCrossLevelEdge', ...
        'The zipper has no finite positive cross-level edge.');
end

function polygon = unique_polygon(panel)
    if norm(panel(4, :) - panel(3, :)) <= 1e-13
        polygon = panel(1:3, :);
    else
        polygon = panel;
    end
end

function [centers, normals, areas, e1, e2, triangleMask] = ...
        panel_geometry(vertices)
    panelCount = size(vertices, 1);
    centers = zeros(panelCount, 3);
    normals = zeros(panelCount, 3);
    areas = zeros(panelCount, 1);
    e1 = zeros(panelCount, 3);
    e2 = zeros(panelCount, 3);
    triangleMask = false(panelCount, 1);
    for panelIndex = 1:panelCount
        panel = reshape(vertices(panelIndex, :, :), 4, 3);
        triangleMask(panelIndex) = ...
            norm(panel(4, :) - panel(3, :)) <= 1e-13;
        if triangleMask(panelIndex)
            centers(panelIndex, :) = mean(panel(1:3, :), 1);
        else
            centers(panelIndex, :) = mean(panel, 1);
        end
        areaVector = cross(panel(3, :) - panel(1, :), ...
            panel(4, :) - panel(2, :));
        magnitude = norm(areaVector);
        assert(isfinite(magnitude) && magnitude > 1e-12, ...
            'CRESTU:UnequalWallPanelArea', ...
            'A zipper panel has zero or non-finite area.');
        areas(panelIndex) = 0.5 * magnitude;
        normals(panelIndex, :) = areaVector / magnitude;
        tangent = panel(2, :) - panel(1, :);
        if norm(tangent) <= 1e-12
            tangent = panel(3, :) - panel(1, :);
        end
        tangent = tangent - dot(tangent, normals(panelIndex, :)) * ...
            normals(panelIndex, :);
        assert(norm(tangent) > 1e-12, ...
            'CRESTU:UnequalWallPanelTangent', ...
            'A zipper panel has no finite tangent.');
        e1(panelIndex, :) = tangent / norm(tangent);
        e2(panelIndex, :) = cross(normals(panelIndex, :), e1(panelIndex, :));
    end
end
