function mesh = generate_quality_controlled_polar_surface( ...
        waterline, cfg, zValue, panelType)
% GENERATE_QUALITY_CONTROLLED_POLAR_SURFACE Build an explicit annular O-grid.
% This helper is reachable only through POLAR_TOPOLOGY_MODE=QUALITY_CONTROLLED_V2.

    %% Stage 1: Validate the explicit single-body/full-domain contract

    assert(get_polar_topology_mode(cfg) == "QUALITY_CONTROLLED_V2", ...
        'CRESTU:QualityPolarModeInactive', ...
        'Quality-controlled polar generation requires its explicit mode.');
    assert(cfg.n_bodies == 1 && cfg.isx == 0 && cfg.isy == 0 && ...
        waterline.is_closed, 'CRESTU:QualityPolarScope', ...
        'QUALITY_CONTROLLED_V2 currently requires one full-domain closed body.');
    nodes = double(waterline.nodes); % [m]
    thetaCount = size(nodes, 1);
    assert(thetaCount >= 8 && mod(thetaCount, 8) == 0, ...
        'CRESTU:QualityPolarThetaCount', ...
        'Quality-controlled waterline count must be a multiple of eight.');
    nodeRadius = hypot(nodes(:, 1), nodes(:, 2));
    innerRadiusM = mean(nodeRadius); % [m]
    assert(max(abs(nodeRadius - innerRadiusM)) <= 1.0e-6, ...
        'CRESTU:QualityPolarAxisymmetry', ...
        'QUALITY_CONTROLLED_V2 currently requires an axisymmetric waterline.');
    transitionRadiusM = cfg.fs.r_inner; % [m]
    if isfield(cfg, 'phase2_2_controls') && ...
            isfield(cfg.phase2_2_controls, 'meshTransitionRadiusM')
        transitionRadiusM = cfg.phase2_2_controls.meshTransitionRadiusM;
    end
    outerRadiusM = cfg.fs.r_outer; % [m]
    assert(innerRadiusM < transitionRadiusM && ...
        transitionRadiusM < outerRadiusM, ...
        'CRESTU:QualityPolarRadii', ...
        'Quality-controlled inner/transition/outer radii are invalid.');

    %% Stage 2: Resolve predeclared radial targets without smoothing

    nearLayerCount = cfg.fs.nr_near;
    configuredOuterLayerCount = cfg.fs.nr_sponge;
    transitionChordM = maximum_ring_edge( ...
        circular_ring(nodes, transitionRadiusM, zValue)); % [m]
    requestedOuterStepMaxM = 8.0 * transitionChordM; % [m]
    requestedOuterLayerCount = ceil( ...
        (outerRadiusM - transitionRadiusM) / requestedOuterStepMaxM);
    outerLayerCount = max(configuredOuterLayerCount, ...
        requestedOuterLayerCount);
    nearRadii = linspace(innerRadiusM, transitionRadiusM, ...
        nearLayerCount + 1);
    outerRadii = linspace(transitionRadiusM, outerRadiusM, ...
        outerLayerCount + 1);
    ringRadii = [nearRadii, outerRadii(2:end)]; % [m]
    radialLayerCount = numel(ringRadii) - 1;
    realizedNearStepM = (transitionRadiusM - innerRadiusM) / ...
        nearLayerCount;
    realizedOuterStepM = (outerRadiusM - transitionRadiusM) / ...
        outerLayerCount;

    %% Stage 3: Build equal-count orthogonal annular rings

    rings = cell(numel(ringRadii), 1);
    rings{1} = [nodes, repmat(zValue, thetaCount, 1)];
    for ringIndex = 2:numel(ringRadii)
        rings{ringIndex} = circular_ring(nodes, ringRadii(ringIndex), zValue);
    end
    panelCount = radialLayerCount * thetaCount;
    vertices = zeros(panelCount, 4, 3);
    centers = zeros(panelCount, 3);
    normals = repmat([0, 0, 1], panelCount, 1);
    areas = zeros(panelCount, 1);
    e1 = zeros(panelCount, 3);
    e2 = zeros(panelCount, 3);
    muDamping = zeros(panelCount, 1);
    cursor = 0;
    for ringIndex = 1:radialLayerCount
        innerRing = rings{ringIndex};
        outerRing = rings{ringIndex + 1};
        for thetaIndex = 1:thetaCount
            nextTheta = mod(thetaIndex, thetaCount) + 1;
            cursor = cursor + 1;
            panel = [innerRing(thetaIndex, :); outerRing(thetaIndex, :); ...
                outerRing(nextTheta, :); innerRing(nextTheta, :)];
            vertices(cursor, :, :) = reshape(panel, 1, 4, 3);
            centers(cursor, :) = mean(panel, 1);
            areaVector = cross(panel(3, :) - panel(1, :), ...
                panel(4, :) - panel(2, :));
            assert(areaVector(3) > 0, 'CRESTU:QualityPolarOrientation', ...
                'A quality-controlled horizontal panel is reversed.');
            areas(cursor) = 0.5 * norm(areaVector);
            radialVector = mean(panel(2:3, :), 1) - mean(panel([1, 4], :), 1);
            e1(cursor, :) = radialVector / norm(radialVector);
            e2(cursor, :) = cross(normals(cursor, :), e1(cursor, :));
            centerRadiusM = hypot(centers(cursor, 1), centers(cursor, 2));
            if centerRadiusM > transitionRadiusM
                normalizedRadius = (centerRadiusM - transitionRadiusM) / ...
                    (outerRadiusM - transitionRadiusM);
                muDamping(cursor) = cfg.fs.mu0 * normalizedRadius ^ 2;
            end
        end
    end

    %% Stage 4: Persist requested/realized topology metadata

    innerChordM = maximum_ring_edge(rings{1});
    outerChordM = maximum_ring_edge(rings{end});
    mesh = struct('header', sprintf( ...
        'QUALITY_CONTROLLED_V2 polar surface Ntheta=%d Nnear=%d Nouter=%d', ...
        thetaCount, nearLayerCount, outerLayerCount), ...
        'ulen', 1.0, 'panel_type', repmat(panelType, panelCount, 1), ...
        'isx', cfg.isx, 'isy', cfg.isy, 'n_panels', panelCount, ...
        'vertices', vertices, 'centers', centers, 'normals', normals, ...
        'areas', areas, 'e1', e1, 'e2', e2, ...
        'mu_damping', muDamping, ...
        'hydrostatics', struct('Vx', 0, 'Vy', 0, 'Vz', 0, ...
            'V_mean', 0, 'center_of_buoyancy', [0, 0, 0]), ...
        'quality_controlled_polar', struct('schemaVersion', 1, ...
            'mode', 'QUALITY_CONTROLLED_V2', ...
            'thetaNodeCount', thetaCount, ...
            'nearRadialLayerCount', nearLayerCount, ...
            'configuredOuterRadialLayerCount', configuredOuterLayerCount, ...
            'requestedOuterRadialLayerCount', requestedOuterLayerCount, ...
            'realizedOuterRadialLayerCount', outerLayerCount, ...
            'innerRadiusM', innerRadiusM, ...
            'transitionRadiusM', transitionRadiusM, ...
            'outerRadiusM', outerRadiusM, ...
            'requestedNearRadialStepM', ...
                (transitionRadiusM - innerRadiusM) / nearLayerCount, ...
            'realizedNearRadialStepM', realizedNearStepM, ...
            'requestedOuterRadialStepMaxM', requestedOuterStepMaxM, ...
            'realizedOuterRadialStepM', realizedOuterStepM, ...
            'innerChordM', innerChordM, ...
            'transitionChordM', transitionChordM, ...
            'outerChordM', outerChordM, ...
            'ringRadiiM', ringRadii, ...
            'smoothingApplied', false));
end

function ring = circular_ring(waterlineNodes, radiusM, zValue)
    theta = atan2(waterlineNodes(:, 2), waterlineNodes(:, 1));
    ring = [radiusM * cos(theta), radiusM * sin(theta), ...
        repmat(zValue, numel(theta), 1)];
end

function value = maximum_ring_edge(ring)
    next = ring([2:end, 1], :);
    value = max(vecnorm(next - ring, 2, 2));
end
