function mode = get_polar_topology_mode(cfg)
% GET_POLAR_TOPOLOGY_MODE Resolve the explicit polar-mesh topology mode.
% Missing fields always preserve the historical LEGACY production path.

    mode = "LEGACY";
    if isfield(cfg, 'phase2_2_controls') && ...
            isfield(cfg.phase2_2_controls, 'polarTopologyMode') && ...
            ~isempty(cfg.phase2_2_controls.polarTopologyMode)
        mode = upper(string(cfg.phase2_2_controls.polarTopologyMode));
    end
    assert(isscalar(mode) && any(mode == ...
        ["LEGACY", "QUALITY_CONTROLLED_V2"]), ...
        'CRESTU:PolarTopologyModeValue', ...
        'Polar topology mode must be LEGACY or QUALITY_CONTROLLED_V2.');
end
