function [cfg, manifest] = resolve_phase2_2_controls(cfg, omega)
% RESOLVE_PHASE2_2_CONTROLS Resolve configured audit inputs at one frequency.
% Geometry tuning is intentionally separate from the sponge-BC controls.

    validateattributes(omega, {'numeric'}, ...
        {'scalar', 'real', 'positive', 'finite'});
    assert(isfield(cfg, 'phase2_2_controls'), ...
        'CRESTU:Phase22ControlMissing', ...
        'Validated configuration lacks Phase-2.2 control defaults.');
    controls = cfg.phase2_2_controls;
    controls = add_theta_control_defaults(controls);
    cfg.phase2_2_controls = controls;
    [waveNumber, ~] = solve_wave_dispersion(omega, cfg.grav, cfg.water_depth);
    wavelength = 2 * pi / waveNumber;
    startRadius = controls.spongeStartRadiusM;
    if strcmp(controls.spongeWidthMode, 'explicit')
        width = controls.spongeWidthM;
    else
        width = cfg.fs.r_outer - startRadius;
    end
    assert(isfinite(startRadius) && startRadius > 0 && ...
        startRadius < cfg.fs.r_outer, 'CRESTU:Phase22SpongeStart', ...
        'Effective sponge start must lie strictly inside the active outer radius.');
    assert(isfinite(width) && width > 0, 'CRESTU:Phase22SpongeWidth', ...
        'Effective sponge width must be finite and positive.');

    if strcmp(controls.spongeMuPolicy, 'explicit')
        assert(~controls.spongeAutoTuneEnabled, ...
            'CRESTU:Phase22ControlMuConflict', ...
            'Explicit sponge mu cannot be combined with automatic tuning.');
        actualMu0 = controls.spongeMu0;
        muResolution = 'explicit-mu0';
    elseif controls.spongeAutoTuneEnabled
        actualMu0 = min(2.5, max(controls.spongeMu0, ...
            12 / (waveNumber * width)));
        muResolution = 'legacy-floor-with-dynamic-attenuation-target';
    else
        actualMu0 = controls.spongeMu0;
        muResolution = 'configured-floor-auto-disabled';
    end

    independentInputs = struct( ...
        'fsRadialCounts', controls.fsRadialCounts, ...
        'bottomRadialCounts', controls.bottomRadialCounts, ...
        'outerVerticalPanelCount', controls.outerVerticalPanelCount, ...
        'outerThetaPanelCount', controls.outerThetaPanelCount, ...
        'freeSurfaceOuterThetaPanelCount', ...
            controls.freeSurfaceOuterThetaPanelCount, ...
        'bottomOuterThetaPanelCount', ...
            controls.bottomOuterThetaPanelCount, ...
        'meshTransitionRadiusM', controls.meshTransitionRadiusM, ...
        'spongeStartRadiusM', controls.spongeStartRadiusM, ...
        'spongeWidth', struct('mode', controls.spongeWidthMode, ...
            'valueM', controls.spongeWidthM), ...
        'spongeMuPolicy', controls.spongeMuPolicy, ...
        'spongeMu0', controls.spongeMu0, ...
        'spongeAutoTuneEnabled', controls.spongeAutoTuneEnabled, ...
        'rawDiagnosticsEnabled', controls.rawDiagnosticsEnabled, ...
        'persistFullSolutions', controls.persistFullSolutions);
    effective = struct( ...
        'frequencyRadPerS', omega, ...
        'physicalWaveNumberPerM', waveNumber, ...
        'wavelengthM', wavelength, ...
        'legacyInnerRadiusM', cfg.fs.r_inner, ...
        'activeGeometryOuterRadiusM', cfg.fs.r_outer, ...
        'meshTransitionRadiusM', controls.meshTransitionRadiusM, ...
        'fsRadialCounts', controls.fsRadialCounts, ...
        'bottomRadialCounts', controls.bottomRadialCounts, ...
        'outerVerticalPanelCount', controls.outerVerticalPanelCount, ...
        'outerThetaPanelCount', controls.outerThetaPanelCount, ...
        'freeSurfaceOuterThetaPanelCount', ...
            controls.freeSurfaceOuterThetaPanelCount, ...
        'bottomOuterThetaPanelCount', ...
            controls.bottomOuterThetaPanelCount, ...
        'spongeStartRadiusM', startRadius, ...
        'spongeWidthM', width, ...
        'spongeEndRadiusM', startRadius + width, ...
        'spongePlateauStartRadiusM', startRadius + width, ...
        'spongeMuPolicy', controls.spongeMuPolicy, ...
        'spongeAutoTuneEnabled', controls.spongeAutoTuneEnabled, ...
        'configuredMu0', controls.spongeMu0, ...
        'actualMu0', actualMu0, ...
        'muResolution', muResolution, ...
        'profile', 'quadratic-clamped:mu=mu0*clamp((r-start)/width,0,1)^2', ...
        'rawDiagnosticsEnabled', controls.rawDiagnosticsEnabled, ...
        'persistFullSolutions', controls.persistFullSolutions);
    configuredSHA = sha256_hash(jsonencode(independentInputs));
    effectiveSHA = sha256_hash(jsonencode(effective));
    manifest = struct('schemaVersion', 1, ...
        'inputMode', controls.inputMode, ...
        'sectionPresent', controls.sectionPresent, ...
        'independentInputs', independentInputs, ...
        'configuredSHA256', configuredSHA, ...
        'effective', effective, ...
        'effectiveSHA256', effectiveSHA);
    cfg.phase2_2_controls.manifest = manifest;
    cfg.phase2_2_controls.effective = effective;
end

function controls = add_theta_control_defaults(controls)
% ADD_THETA_CONTROL_DEFAULTS Preserve old in-memory audit fixtures.
% Zero means that the endpoint count is not an independent configured input;
% an active truncation may still derive that endpoint count from its frozen
% legacy chord-spacing target.
    defaults = {'outerThetaPanelCount', ...
        'freeSurfaceOuterThetaPanelCount', ...
        'bottomOuterThetaPanelCount'};
    for index = 1:numel(defaults)
        name = defaults{index};
        if ~isfield(controls, name)
            controls.(name) = 0;
        end
        value = controls.(name);
        assert(isnumeric(value) && isscalar(value) && isfinite(value) && ...
            value >= 0 && fix(value) == value, ...
            'CRESTU:Phase22ThetaControl', ...
            '%s must be zero (unset) or a positive integer.', name);
        assert(value == 0 || mod(value, 4) == 0, ...
            'CRESTU:Phase22ThetaMultiple', ...
            '%s must be a multiple of four.', name);
    end
end
