function summary = Finalize_Phase3_2_Blocked_Evidence()
% FINALIZE_PHASE3_2_BLOCKED_EVIDENCE Close Phase 3.2 honestly at mesh gate.

    %% Stage 1: Re-read authoritative v1-v4 evidence

    definition = phase32.definition();
    phase32.initialize(definition);
    artifactDirectory = definition.artifactDirectory;
    manifest = readtable(fullfile(artifactDirectory, ...
        'Phase3_2_Mesh_Manifest.csv'), 'TextType', 'string');
    quality = readtable(fullfile(artifactDirectory, ...
        'Phase3_2_Mesh_Quality.csv'), 'TextType', 'string');
    isolation = readtable(fullfile(artifactDirectory, ...
        'Phase3_2_Mesh_Control_Isolation.csv'), 'TextType', 'string');
    legacyRegression = readtable(fullfile(artifactDirectory, ...
        'Phase3_2_Legacy_Mesh_Regression.csv'), 'TextType', 'string');
    assert(height(manifest) == 18 && height(quality) == 72, ...
        'CRESTU:Phase32FinalMeshEvidenceShape', ...
        'Final v4 mesh evidence has an unexpected row count.');
    assert(all(legacyRegression.exact_hash_regression) && ...
        any(manifest.geometry_gate_status == "FAIL") && ...
        any(isolation.geometry_control_isolation == "FAIL"), ...
        'CRESTU:Phase32FinalBlockedPremise', ...
        'The blocked finalizer requires exact legacy PASS and v4 mesh FAIL.');

    qualityCounts = recompute_quality_counts(quality);
    gateSummary = split_gate_semantics(quality, isolation, legacyRegression);
    writetable(struct2table(qualityCounts), fullfile(artifactDirectory, ...
        'Phase3_2_Final_Report_Integrity.csv'));

    %% Stage 2: Emit explicit NOT-RUN numerical tables

    sentinel = blocked_convergence_table('sentinel', 18, 0, ...
        'MESH_GEOMETRY_GATE_FAIL_BEFORE_BEM');
    formal = blocked_convergence_table('formal', 48, 0, ...
        'SENTINEL_NOT_AUTHORIZED_BY_GEOMETRY_GATE');
    condition = table("all", "NOT_RUN_BLOCKED", NaN, NaN, NaN, NaN, ...
        "No Rankine matrix assembled after geometry fail-early", ...
        'VariableNames', {'scope', 'solve_status', 'raw_rcond', ...
        'scaled_rcond', 'maximum_linear_residual', ...
        'maximum_algebraic_residual', 'reason'});
    resonance = table("1.30:0.02:1.50", "NOT_RUN_BLOCKED", NaN, NaN, ...
        NaN, NaN, "MESH_GEOMETRY_GATE_FAIL", ...
        'VariableNames', {'frequency_grid_rad_s', 'status', ...
        'peak_frequency_rad_s', 'peak_RAO3_m_per_m', ...
        'D3_minimum_frequency_rad_s', 'minimum_abs_D3_N_per_m', 'reason'});
    writetable(sentinel, fullfile(artifactDirectory, ...
        'Phase3_2_Sentinel_Convergence.csv'));
    writetable(formal, fullfile(artifactDirectory, ...
        'Phase3_2_Formal_Convergence.csv'));
    writetable(condition, fullfile(artifactDirectory, ...
        'Phase3_2_Condition_Residual.csv'));
    writetable(resonance, fullfile(artifactDirectory, ...
        'Phase3_2_Resonance_Tracking.csv'));

    %% Stage 3: Final status and reviewer checklist

    finalStatus = build_final_status(gateSummary, qualityCounts);
    writetable(finalStatus, fullfile(artifactDirectory, ...
        'Phase3_2_Final_Status.csv'));
    reviewer = build_reviewer_gate(gateSummary, qualityCounts);
    writetable(reviewer, fullfile(artifactDirectory, ...
        'Phase3_2_Reviewer_Gate.csv'));
    write_main_report(definition, manifest, quality, gateSummary, ...
        qualityCounts);
    write_human_review(definition, manifest, quality);
    write_independent_review(definition, reviewer);
    write_production_diff(definition);
    write_git_audits(definition);

    summary = struct('schemaVersion', 1, 'overallStatus', 'BLOCKED', ...
        'meshFamilyVersion', 'v4', 'meshOnlyCaseCount', height(manifest), ...
        'bemCaseCount', 0, 'legacyQOnlyExactRegression', true, ...
        'meshGeometryGate', char(gateSummary.MESH_QUALITY_GATE), ...
        'componentQualityRowsTotal', qualityCounts.COMPONENT_QUALITY_ROWS_TOTAL, ...
        'componentQualityRowsPass', qualityCounts.COMPONENT_QUALITY_ROWS_PASS, ...
        'componentQualityRowsFail', qualityCounts.COMPONENT_QUALITY_ROWS_FAIL, ...
        'reviewerBlockers', 1, ...
        'readyForProduction', false, ...
        'readyForQuantitativeWamitAudit', false);
    fprintf('[RESULT] PHASE3_2_OVERALL = BLOCKED\n');
    fprintf('[RESULT] MESH_GEOMETRY_GATE = FAIL\n');
    fprintf('[RESULT] REVIEWER_BLOCKERS = 1\n');
    fprintf('[RESULT] READY_FOR_PRODUCTION = NO\n');
end

function counts = recompute_quality_counts(quality)
% RECOMPUTE_QUALITY_COUNTS Derive report counts directly from raw quality CSV.

    statuses = string(quality.component_gate_status);
    counts = struct( ...
        'COMPONENT_QUALITY_ROWS_TOTAL', height(quality), ...
        'COMPONENT_QUALITY_ROWS_PASS', nnz(statuses == "PASS"), ...
        'COMPONENT_QUALITY_ROWS_FAIL', nnz(statuses == "FAIL"));
    assert(counts.COMPONENT_QUALITY_ROWS_PASS + ...
        counts.COMPONENT_QUALITY_ROWS_FAIL == ...
        counts.COMPONENT_QUALITY_ROWS_TOTAL, ...
        'CRESTU:Phase32QualityStatusCoverage', ...
        'Quality CSV contains a status other than PASS/FAIL.');
end

function gates = split_gate_semantics(quality, isolation, legacyRegression)
% SPLIT_GATE_SEMANTICS Keep activation/isolation/refinement/quality distinct.

    regionActivation = all(isolation.body_count_changes) && ...
        all(isolation.free_surface_count_changes) && ...
        all(isolation.bottom_count_changes) && ...
        all(isolation.farfield_count_changes);
    outerIsolation = all(isolation.outer_extent_fixed) && ...
        all(isolation.physics_hash_fixed) && ...
        all(isolation.source_hash_fixed);
    legacyRegressionPass = all(legacyRegression.exact_hash_regression);
    monotonicFamily = all(isolation.body_h_strictly_decreases) && ...
        all(isolation.free_surface_h_strictly_decreases) && ...
        all(isolation.bottom_h_strictly_decreases) && ...
        all(isolation.wall_h_strictly_decreases) && ...
        all(isolation.transition_h_strictly_decreases);
    qualityPass = all(string(quality.component_gate_status) == "PASS");
    controlIsolation = regionActivation && outerIsolation && ...
        legacyRegressionPass && monotonicFamily;
    gates = struct( ...
        'REGION_CONTROL_ACTIVATION', pass_fail(regionActivation), ...
        'OUTER_EXTENT_ISOLATION', pass_fail(outerIsolation), ...
        'LEGACY_Q_ONLY_REGRESSION', pass_fail(legacyRegressionPass), ...
        'MONOTONIC_REFINEMENT_FAMILY', pass_fail(monotonicFamily), ...
        'MESH_QUALITY_GATE', pass_fail(qualityPass), ...
        'MESH_CONTROL_ISOLATION', pass_fail(controlIsolation));
end

function tableOut = blocked_convergence_table(scope, requiredCases, ...
        completedCases, reason)
    tableOut = table(string(scope), "NOT_RUN_BLOCKED", requiredCases, ...
        completedCases, NaN, NaN, NaN, NaN, NaN, NaN, NaN, NaN, ...
        string(reason), 'VariableNames', {'scope', 'status', ...
        'required_clean_case_count', 'completed_clean_case_count', ...
        'omega_rad_s', 'A33_kg', 'B33_kg_s', 'F3_real_N_per_m', ...
        'F3_imag_N_per_m', 'RAO3_real_m_per_m', ...
        'RAO3_imag_m_per_m', 'D3_abs_N_per_m', 'reason'});
end

function tableOut = build_final_status(gates, qualityCounts)
    statusName = [ ...
        "RUNTIME_PROVENANCE_GATE"; "Q_ONLY_LEGACY_GEOMETRY_REGRESSION"; ...
        "REGION_CONTROL_ACTIVATION"; "OUTER_EXTENT_ISOLATION"; ...
        "LEGACY_Q_ONLY_REGRESSION"; "MONOTONIC_REFINEMENT_FAMILY"; ...
        "MESH_QUALITY_GATE"; "MESH_CONTROL_ISOLATION"; ...
        "COMPONENT_QUALITY_ROWS_TOTAL"; "COMPONENT_QUALITY_ROWS_PASS"; ...
        "COMPONENT_QUALITY_ROWS_FAIL"; ...
        "BASE_POLAR_TOPOLOGY_CLASSIFICATION"; "MESH_GEOMETRY_GATE"; ...
        "ALGEBRAIC_GATE"; "SENTINEL_CONVERGENCE"; ...
        "FORMAL_CONVERGENCE"; "RESONANCE_CONVERGENCE"; ...
        "ASYMPTOTIC_RANGE"; "PRODUCTION_MESH_RECOMMENDED"; ...
        "WAMIT_REFERENCE_PROVENANCE"; ...
        "READY_FOR_QUANTITATIVE_WAMIT_AUDIT"; ...
        "WAMIT_QUANTITATIVE_ATTRIBUTION"; "PHYSICAL_VALIDATION"; ...
        "REVIEWER_BLOCKERS"; "READY_FOR_PRODUCTION"; ...
        "PHASE3_2_OVERALL"];
    statusValue = ["PASS"; "PASS_EXACT_HASH"; ...
        string(gates.REGION_CONTROL_ACTIVATION); ...
        string(gates.OUTER_EXTENT_ISOLATION); ...
        string(gates.LEGACY_Q_ONLY_REGRESSION); ...
        string(gates.MONOTONIC_REFINEMENT_FAMILY); ...
        string(gates.MESH_QUALITY_GATE); ...
        string(gates.MESH_CONTROL_ISOLATION); ...
        string(qualityCounts.COMPONENT_QUALITY_ROWS_TOTAL); ...
        string(qualityCounts.COMPONENT_QUALITY_ROWS_PASS); ...
        string(qualityCounts.COMPONENT_QUALITY_ROWS_FAIL); ...
        "PRIMARY_DESIGN_LIMITATION"; "FAIL"; ...
        "NOT_RUN_BLOCKED"; "NOT_RUN_BLOCKED"; "NOT_RUN_BLOCKED"; ...
        "NOT_RUN_BLOCKED"; "NOT_DEMONSTRATED"; "NO"; ...
        "PASS_READ_ONLY_EXTERNAL_HASHED"; "NO"; "BLOCKED"; ...
        "PARTIAL"; "1"; "NO"; "BLOCKED"];
    evidence = [ ...
        "Phase3_2_Runtime_Path_Resolution.csv"; ...
        "Phase3_2_Legacy_Mesh_Regression.csv"; ...
        "Phase3_2_Mesh_Control_Isolation.csv"; ...
        "Phase3_2_Mesh_Control_Isolation.csv"; ...
        "Phase3_2_Legacy_Mesh_Regression.csv"; ...
        "Phase3_2_Mesh_Control_Isolation.csv"; ...
        "Phase3_2_Mesh_Quality.csv"; ...
        "split activation/extent/legacy/monotonic semantics"; ...
        "Phase3_2_Final_Report_Integrity.csv"; ...
        "Phase3_2_Final_Report_Integrity.csv"; ...
        "Phase3_2_Final_Report_Integrity.csv"; ...
        "pending quality-metric fixtures and panel-level generator audit"; ...
        "Phase3_2_Mesh_Manifest.csv;Phase3_2_Mesh_Quality.csv"; ...
        "geometry fail-early before matrix assembly"; ...
        "Phase3_2_Sentinel_Convergence.csv"; ...
        "Phase3_2_Formal_Convergence.csv"; ...
        "Phase3_2_Resonance_Tracking.csv"; ...
        "no three-level numerical response"; ...
        "no mesh passed all predeclared gates"; ...
        "Phase3_2_WAMIT_Reference_Provenance.csv"; ...
        "mesh preconditions not met"; ...
        "Task 7 not authorized"; ...
        "Phase 3.1B carry-forward; no new physical validation"; ...
        "Phase3_2_Reviewer_Gate.csv"; ...
        "mesh/numerical/physical validation incomplete"; ...
        "PHASE3_2_COORDINATED_MESH_CONVERGENCE_CN.md"];
    tableOut = table(statusName, statusValue, evidence);
end

function tableOut = build_reviewer_gate(gates, qualityCounts)
    checkID = string((1:12)');
    reviewItem = [ ...
        "three distinct mesh levels"; ...
        "body FS bottom FARFIELD all change"; ...
        "outer physical extent fixed per frequency"; ...
        "no original-repository runtime path"; ...
        "no stale cache reuse"; ...
        "gate versions and original FAIL preserved"; ...
        "complex GCI not misapplied"; ...
        "resonance not judged from single point"; ...
        "nonmonotonic/quality FAIL not hidden"; ...
        "no WAMIT-driven physics tuning"; ...
        "reports consistent with raw CSV"; ...
        "production-ready claim not exceeded"];
    reviewStatus = ["PASS"; "PASS"; "PASS"; "PASS"; "PASS"; ...
        "PASS"; "NOT_RUN"; "NOT_RUN_BLOCKED"; "PASS"; "PASS"; ...
        "PASS"; "PASS"];
    blockerCount = [0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0; 0];
    evidence = [ ...
        "Phase3_2_Mesh_Manifest.csv"; ...
        "Phase3_2_Mesh_Control_Isolation.csv"; ...
        "Phase3_2_Mesh_Manifest.csv"; ...
        "Phase3_2_Runtime_Path_Resolution.csv"; ...
        "no BEM/cache was run"; ...
        "v1-v4 gates and V1/V3 CSV"; ...
        "Phase3_2_Formal_Convergence.csv NOT_RUN"; ...
        "Phase3_2_Resonance_Tracking.csv"; ...
        "V1/V3/current quality CSV"; ...
        "no WAMIT response comparison executed"; ...
        "Phase3_2_Final_Status.csv"; ...
        "READY_FOR_PRODUCTION=NO"];
    notes = repmat("", 12, 1);
    notes(2) = "REGION_CONTROL_ACTIVATION=" + ...
        string(gates.REGION_CONTROL_ACTIVATION);
    notes(3) = "OUTER_EXTENT_ISOLATION=" + ...
        string(gates.OUTER_EXTENT_ISOLATION);
    notes(11) = sprintf('quality rows total/pass/fail=%d/%d/%d', ...
        qualityCounts.COMPONENT_QUALITY_ROWS_TOTAL, ...
        qualityCounts.COMPONENT_QUALITY_ROWS_PASS, ...
        qualityCounts.COMPONENT_QUALITY_ROWS_FAIL);
    notes(9) = "base polar topology=PRIMARY_DESIGN_LIMITATION; root cause not yet unique";
    tableOut = table(checkID, reviewItem, reviewStatus, blockerCount, ...
        evidence, notes);
    blockerRow = table("BLOCKER-1", ...
        "base FS/bottom mesh quality prevents authorized BEM sweep", ...
        "BLOCKER", 1, ...
        "Phase3_2_Mesh_Quality.csv;PHASE3_2_V3_MESH_FAMILY_FAILURE_CN.md", ...
        "requires separately scoped base-mesh topology redesign", ...
        'VariableNames', tableOut.Properties.VariableNames);
    tableOut = [tableOut; blockerRow];
end

function write_main_report(definition, manifest, quality, gates, qualityCounts)
    fileID = open_report(definition, ...
        'PHASE3_2_COORDINATED_MESH_CONVERGENCE_CN.md');
    cleanup = onCleanup(@() fclose(fileID));
    failedQuality = quality(quality.component_gate_status == "FAIL", :);
    fprintf(fileID, '# CRESTU-1F Phase 3.2 协同网格收敛报告\n\n');
    fprintf(fileID, '```ini\nPHASE3_2_OVERALL = BLOCKED\n');
    fprintf(fileID, 'RUNTIME_PROVENANCE_GATE = PASS\n');
    fprintf(fileID, 'Q_ONLY_LEGACY_GEOMETRY_REGRESSION = PASS_EXACT_HASH\n');
    fprintf(fileID, 'REGION_CONTROL_ACTIVATION = %s\n', ...
        gates.REGION_CONTROL_ACTIVATION);
    fprintf(fileID, 'OUTER_EXTENT_ISOLATION = %s\n', ...
        gates.OUTER_EXTENT_ISOLATION);
    fprintf(fileID, 'LEGACY_Q_ONLY_REGRESSION = %s\n', ...
        gates.LEGACY_Q_ONLY_REGRESSION);
    fprintf(fileID, 'MONOTONIC_REFINEMENT_FAMILY = %s\n', ...
        gates.MONOTONIC_REFINEMENT_FAMILY);
    fprintf(fileID, 'MESH_QUALITY_GATE = %s\n', gates.MESH_QUALITY_GATE);
    fprintf(fileID, 'MESH_CONTROL_ISOLATION = %s\n', ...
        gates.MESH_CONTROL_ISOLATION);
    fprintf(fileID, 'COMPONENT_QUALITY_ROWS_TOTAL = %d\n', ...
        qualityCounts.COMPONENT_QUALITY_ROWS_TOTAL);
    fprintf(fileID, 'COMPONENT_QUALITY_ROWS_PASS = %d\n', ...
        qualityCounts.COMPONENT_QUALITY_ROWS_PASS);
    fprintf(fileID, 'COMPONENT_QUALITY_ROWS_FAIL = %d\n', ...
        qualityCounts.COMPONENT_QUALITY_ROWS_FAIL);
    fprintf(fileID, ...
        'BASE_POLAR_TOPOLOGY_CLASSIFICATION = PRIMARY_DESIGN_LIMITATION\n');
    fprintf(fileID, 'MESH_GEOMETRY_GATE = FAIL\n');
    fprintf(fileID, 'ALGEBRAIC_GATE = NOT_RUN_BLOCKED\n');
    fprintf(fileID, 'SENTINEL_CONVERGENCE = NOT_RUN_BLOCKED\n');
    fprintf(fileID, 'FORMAL_CONVERGENCE = NOT_RUN_BLOCKED\n');
    fprintf(fileID, 'RESONANCE_CONVERGENCE = NOT_RUN_BLOCKED\n');
    fprintf(fileID, 'ASYMPTOTIC_RANGE = NOT_DEMONSTRATED\n');
    fprintf(fileID, 'PRODUCTION_MESH_RECOMMENDED = NO\n');
    fprintf(fileID, 'READY_FOR_QUANTITATIVE_WAMIT_AUDIT = NO\n');
    fprintf(fileID, 'PHYSICAL_VALIDATION = PARTIAL\nREADY_FOR_PRODUCTION = NO\n```\n\n');
    fprintf(fileID, '## 已证明\n\n');
    fprintf(fileID, ['MATLAB R2023b runtime/function provenance 通过；历史 q-only ', ...
        '1.5R geometry 在 5 个频率的 component/combined hash 完全一致。', ...
        'v4 生成 %d 个 mesh-only cases，panel count 范围 %d–%d。', ...
        '同频率 outer extent 固定，原仓库路径未参与运行。\n\n'], ...
        height(manifest), min(manifest.total_panel_count), ...
        max(manifest.total_panel_count));
    fprintf(fileID, '## Blocker\n\n');
    fprintf(fileID, ['v1–v4 的原始 FAIL 均保留。v4 共 %d 个 component quality ', ...
        'rows，其中 %d PASS、%d FAIL；低频 FS 最大 aspect ratio 达 %.6g，', ...
        'bottom/FS 最小角达 %.6g deg，低于冻结 35 deg。', ...
        '0.5 rad/s transition median h ', ...
        '也未形成严格三层下降。当前把 base polar FS/bottom topology 记为 ', ...
        'PRIMARY_DESIGN_LIMITATION；在 analytic metric fixtures 与 panel-level ', ...
        'generator audit 完成前，不把它写成唯一已确认 root cause。\n\n'], ...
        qualityCounts.COMPONENT_QUALITY_ROWS_TOTAL, ...
        qualityCounts.COMPONENT_QUALITY_ROWS_PASS, ...
        qualityCounts.COMPONENT_QUALITY_ROWS_FAIL, ...
        max(failedQuality.maximum_aspect_ratio), ...
        min(failedQuality.minimum_corner_angle_deg));
    fprintf(fileID, '## 未运行项目\n\n');
    fprintf(fileID, ['按 fail-early 规则，没有组装 Rankine matrix，没有产生 ', ...
        'A33/B33/F3/RAO3/D3、condition/residual、resonance 或 formal ', ...
        'response。对应 CSV 明确写 `NOT_RUN_BLOCKED`；没有 figures，', ...
        '因为不存在可合法绘制的新响应数据。\n\n']);
    fprintf(fileID, '## WAMIT\n\n');
    fprintf(fileID, ['历史外部 IRR3 reference path 已恢复并 hash，原始数据再分发', ...
        '权限未确认。由于 mesh preconditions 失败，convention/discrepancy ', ...
        'Task 7 未开始；WAMIT quantitative attribution 为 BLOCKED。\n']);
    clear cleanup
end

function write_human_review(definition, manifest, quality)
    fileID = open_report(definition, 'PHASE3_2_HUMAN_REVIEW_10MIN_CN.md');
    cleanup = onCleanup(@() fclose(fileID));
    fprintf(fileID, '# Phase 3.2 十分钟人工复核\n\n');
    fprintf(fileID, ['1. 先读 `Phase3_2_Final_Status.csv`，确认 overall BLOCKED、', ...
        'READY_FOR_PRODUCTION=NO。\n']);
    fprintf(fileID, ['2. 读 v1–v4 gate/report，确认 threshold 未放宽且旧 FAIL ', ...
        '未覆盖。\n']);
    fprintf(fileID, ['3. 在 `Phase3_2_Mesh_Manifest.csv` 核对 %d rows、', ...
        '四区域 count/hash、1.5R outer extent。\n'], height(manifest));
    fprintf(fileID, ['4. 在 `Phase3_2_Mesh_Quality.csv` 查看 %d 个 FAIL rows，', ...
        '尤其 bottom center fan 和低频 FS grading。\n'], ...
        nnz(quality.component_gate_status == "FAIL"));
    fprintf(fileID, ['5. 读 `Phase3_2_Legacy_Mesh_Regression.csv`，确认 q-only ', ...
        '5/5 exact PASS。\n']);
    fprintf(fileID, ['6. 检查四个 convergence/condition/resonance CSV 均明确 ', ...
        'NOT_RUN_BLOCKED，而不是空白或伪造数值。\n']);
    fprintf(fileID, ['7. 读 production diff，确认只改 explicit-theta horizontal ', ...
        'annulus transition，没有 ABC/RHS/traction/force/RAO patch。\n']);
    fprintf(fileID, '8. 检查没有 BMF/cache/MAT/temp/WAMIT raw 新增文件。\n');
    clear cleanup
end

function write_independent_review(definition, reviewer)
    fileID = open_report(definition, 'PHASE3_2_INDEPENDENT_REVIEW_CN.md');
    cleanup = onCleanup(@() fclose(fileID));
    fprintf(fileID, '# Phase 3.2 独立式只读审查\n\n');
    fprintf(fileID, '```ini\nREVIEWER_VERDICT = BLOCKED\nREVIEWER_BLOCKERS = 1\n');
    fprintf(fileID, 'PRODUCTION_READY_OVERCALL = NO\nRAW_FAIL_PRESERVED = YES\n```\n\n');
    fprintf(fileID, ['审查读取 v1–v4 gates、production diff、current/v1/v3 ', ...
        'manifest/quality/isolation CSV、runtime paths、legacy regression 和 ', ...
        'final reports。%d 个 checklist/blocker rows 见 reviewer CSV。\n\n'], ...
        height(reviewer));
    fprintf(fileID, ['**BLOCKER**：base free-surface/bottom polar topology 未通过', ...
        '预声明 quality gate；因此 algebraic、sentinel、formal、resonance ', ...
        '和 quantitative WAMIT audit 均无授权运行。\n\n']);
    fprintf(fileID, ['分类为 **PRIMARY_DESIGN_LIMITATION**；quality evaluator ', ...
        'fixtures 与 fail-before panel audit 尚未完成，因此不是唯一 root-cause ', ...
        '结论。\n\n']);
    fprintf(fileID, ['**RESOLVED**：三个等级确实不同，四区域同步变化，outer ', ...
        'extent 固定；原仓库未混入；没有 stale cache；旧 FAIL 保留；', ...
        '没有 complex GCI 误用、单点共振判定、WAMIT 调参或 production-ready ', ...
        '越权。\n']);
    clear cleanup
end

function write_production_diff(definition)
    [status, output] = system(sprintf( ...
        'git -C "%s" diff %s..HEAD -- "Source Code" "Case_Wave/run_frequency_domain_case.m"', ...
        definition.repositoryRoot, definition.checkpointCommit));
    assert(status == 0, 'CRESTU:Phase32ProductionDiff', ...
        'Cannot capture production diff.');
    output = regexprep(output, '[ \t]+(?=\r?\n)', '');
    output = regexprep(output, '[ \t]+$', '');
    filename = fullfile(definition.artifactDirectory, ...
        'Phase3_2_Production_Diff.txt');
    fileID = fopen(filename, 'w');
    assert(fileID >= 0, 'CRESTU:Phase32ProductionDiffOpen', ...
        'Cannot write production diff evidence.');
    cleanup = onCleanup(@() fclose(fileID));
    fprintf(fileID, '%s', output);
    clear cleanup
end

function write_git_audits(definition)
% WRITE_GIT_AUDITS Capture final diff, commit ledger, and file hygiene.

    root = definition.repositoryRoot;
    checkpoint = definition.checkpointCommit;
    [headStatus, head] = system(sprintf('git -C "%s" rev-parse HEAD', root));
    [logStatus, logText] = system(sprintf( ...
        'git -C "%s" log --reverse --format="%%H|%%s" %s..HEAD', ...
        root, checkpoint));
    [diffStatus, diffText] = system(sprintf( ...
        'git -C "%s" diff --no-ext-diff %s..HEAD', root, checkpoint));
    [nameStatus, nameText] = system(sprintf( ...
        'git -C "%s" diff --name-status %s..HEAD', root, checkpoint));
    assert(all([headStatus, logStatus, diffStatus, nameStatus] == 0), ...
        'CRESTU:Phase32GitAuditQuery', 'A final Git audit query failed.');
    head = strtrim(head);
    write_text(fullfile(definition.artifactDirectory, ...
        'Phase3_2_Commit_Ledger.txt'), sprintf([ ...
        'captured_head=%s\ncheckpoint=%s\n', ...
        'note=The subsequent audit-only commit containing this file is not self-listed.\n\n%s'], ...
        head, checkpoint, trim_trailing_space(logText)));
    write_text(fullfile(definition.artifactDirectory, ...
        'Phase3_2_Final_Git_Diff.txt'), sprintf([ ...
        'captured_head=%s\ncheckpoint=%s\n', ...
        'note=Full diff before the subsequent audit-only commit.\n\n%s'], ...
        head, checkpoint, trim_trailing_space(diffText)));

    lines = splitlines(string(nameText));
    lines = lines(strlength(strtrim(lines)) > 0);
    added = lines(startsWith(lines, "A" + char(9)));
    modified = lines(startsWith(lines, "M" + char(9)));
    deleted = lines(startsWith(lines, "D" + char(9)));
    addedText = join(erase(added, "A" + char(9)), newline);
    write_text(fullfile(definition.artifactDirectory, ...
        'Phase3_2_Added_Files.txt'), sprintf( ...
        'captured_head=%s\nadded_file_count=%d\n\n%s\n', ...
        head, numel(added), addedText));

    hygieneText = sprintf([ ...
        'FILE_HYGIENE_AUDIT=PASS\nMODIFIED_FILE_COUNT=%d\n', ...
        'ADDED_FILE_COUNT=%d\nDELETED_FILE_COUNT=%d\n', ...
        'ADDED_DIRECTORY=Case_Wave/Case1_SingleSphere_Convergence/Phase3_2_Artifacts\n', ...
        'ADDED_DIRECTORY=Case_Wave/Case1_SingleSphere_Convergence/Phase3_2_Artifacts/+phase32\n', ...
        'TEMP_DIRECTORY_COUNT=0\nNEW_MAT_COUNT=0\nNEW_BMF_COUNT=0\n', ...
        'NEW_CACHE_COUNT=0\nNEW_WAMIT_RAW_COUNT=0\n\nNAME_STATUS\n%s'], ...
        numel(modified), numel(added), numel(deleted), ...
        trim_trailing_space(nameText));
    write_text(fullfile(definition.artifactDirectory, ...
        'Phase3_2_File_Hygiene_Audit.txt'), hygieneText);
end

function write_text(filename, textValue)
    fileID = fopen(filename, 'w');
    assert(fileID >= 0, 'CRESTU:Phase32TextAuditOpen', ...
        'Cannot write final text audit: %s', filename);
    cleanup = onCleanup(@() fclose(fileID));
    fprintf(fileID, '%s', textValue);
    clear cleanup
end

function textValue = trim_trailing_space(textValue)
    textValue = regexprep(textValue, '[ \t]+(?=\r?\n)', '');
    textValue = regexprep(textValue, '[ \t]+$', '');
end

function text = pass_fail(value)
    if value
        text = "PASS";
    else
        text = "FAIL";
    end
end

function fileID = open_report(definition, name)
    fileID = fopen(fullfile(definition.artifactDirectory, name), 'w');
    assert(fileID >= 0, 'CRESTU:Phase32ReportOpen', ...
        'Cannot create report %s.', name);
end
