function summary = Initialize_Phase3_2_Baseline()
% INITIALIZE_PHASE3_2_BASELINE Freeze Phase 3.2 source/runtime provenance.
% This entry point does not generate a new mesh or run a BEM solve.

    %% Stage 1: Reset MATLAB and verify the authorized worktree

    paths = initialize_paths();
    restoredefaultpath;
    rehash toolboxcache;
    assert(same_path(pwd, paths.repositoryRoot), ...
        'CRESTU:Phase32MatlabPwd', ...
        'MATLAB pwd must be the Phase 3.2 worktree root: %s', ...
        paths.repositoryRoot);
    add_production_paths(paths);

    [gitRoot, rootStatus] = run_git(paths.repositoryRoot, ...
        'rev-parse --show-toplevel');
    [gitBranch, branchStatus] = run_git(paths.repositoryRoot, ...
        'branch --show-current');
    [gitHead, headStatus] = run_git(paths.repositoryRoot, 'rev-parse HEAD');
    assert(all([rootStatus, branchStatus, headStatus] == 0), ...
        'CRESTU:Phase32GitQuery', 'A required Git provenance query failed.');
    assert(same_path(strtrim(gitRoot), paths.repositoryRoot), ...
        'CRESTU:Phase32GitRoot', 'Git root is outside the authorized worktree.');
    assert(strcmp(strtrim(gitBranch), 'phase3-2-mesh-convergence'), ...
        'CRESTU:Phase32GitBranch', 'Unexpected branch: %s', gitBranch);
    expectedHead = '7f2d391d1b42366fdb04e1b493439dab438584eb';
    [tagHead, tagStatus] = run_git(paths.repositoryRoot, ...
        'rev-parse "phase3-1b-checkpoint-20260901^{commit}"');
    [~, ancestorStatus] = run_git(paths.repositoryRoot, sprintf( ...
        'merge-base --is-ancestor %s HEAD', expectedHead));
    assert(tagStatus == 0 && strcmp(strtrim(tagHead), expectedHead) && ...
        ancestorStatus == 0, 'CRESTU:Phase32GitHead', ...
        'The frozen Phase 3.1B checkpoint/tag is not an ancestor of HEAD.');

    %% Stage 2: Resolve every required function to the current worktree

    runtimeTable = resolve_runtime_functions(paths);
    writetable(runtimeTable, fullfile(paths.artifactDirectory, ...
        'Phase3_2_Runtime_Path_Resolution.csv'));
    runtimePass = all(runtimeTable.exact_match & ...
        runtimeTable.within_phase3_2_worktree & ...
        ~runtimeTable.resolves_to_original_repository);
    assert(runtimePass, 'CRESTU:Phase32RuntimeProvenance', ...
        'A production function did not resolve to the Phase 3.2 worktree.');

    %% Stage 3: Record raw, canonical-LF, and Git-object identities

    sourceTable = build_source_manifest(paths);
    writetable(sourceTable, fullfile(paths.artifactDirectory, ...
        'Phase3_2_Baseline_Source_Manifest.csv'));
    assert(all(sourceTable.file_exists & sourceTable.git_tracked), ...
        'CRESTU:Phase32BaselineSource', ...
        'A frozen baseline input is missing or not tracked.');

    %% Stage 4: Recover historical external WAMIT provenance read-only

    wamitTable = audit_wamit_reference_provenance(paths);
    writetable(wamitTable, fullfile(paths.artifactDirectory, ...
        'Phase3_2_WAMIT_Reference_Provenance.csv'));
    historicalRows = wamitTable.source_role == ...
        "historical_phase3_1_reference_file";
    wamitRecovered = any(historicalRows) && ...
        all(wamitTable.exists(historicalRows)) && ...
        all(strlength(wamitTable.raw_sha256(historicalRows)) == 64);

    %% Stage 5: Persist the freeze report

    summary = struct('schemaVersion', 1, ...
        'repositoryRoot', paths.repositoryRoot, 'matlabPwd', pwd, ...
        'branch', strtrim(gitBranch), 'head', expectedHead, ...
        'auditRuntimeHead', strtrim(gitHead), ...
        'initialWorktreeStatus', 'clean-before-phase3.2-files', ...
        'runtimeProvenancePass', runtimePass, ...
        'baselineTrackedSourceCount', height(sourceTable), ...
        'historicalWamitReferenceRecovered', wamitRecovered, ...
        'productionPhysicsChanged', false);
    write_baseline_report(summary, paths, runtimeTable, wamitTable);
    fprintf('[RESULT] PHASE3_2_RUNTIME_PROVENANCE = PASS\n');
    fprintf('[RESULT] WAMIT_REFERENCE_PATH_RECOVERED = %s\n', ...
        yes_no(wamitRecovered));
    fprintf('[RESULT] WAMIT_RAW_REDISTRIBUTION = UNCONFIRMED_DO_NOT_COMMIT\n');
end

function paths = initialize_paths()
    artifactDirectory = fileparts(mfilename('fullpath'));
    convergenceDirectory = fileparts(artifactDirectory);
    caseWaveDirectory = fileparts(convergenceDirectory);
    repositoryRoot = fileparts(caseWaveDirectory);
    paths = struct('artifactDirectory', artifactDirectory, ...
        'convergenceDirectory', convergenceDirectory, ...
        'caseWaveDirectory', caseWaveDirectory, ...
        'repositoryRoot', repositoryRoot, ...
        'sourceDirectory', fullfile(repositoryRoot, 'Source Code'), ...
        'originalRepository', ...
            'E:\CRESTU-1F_v1.0_20260824\Code\CRESTU', ...
        'historicalWamitRoot', ...
            'E:\CRESTU-1F_v1.0_20260824\WAMIT');
    assert(isfolder(repositoryRoot) && isfolder(artifactDirectory), ...
        'CRESTU:Phase32PathMissing', 'Phase 3.2 paths are missing.');
end

function add_production_paths(paths)
    sourceDirectory = paths.sourceDirectory;
    addpath(fullfile(sourceDirectory, '0.Tools Code'), ...
        fullfile(sourceDirectory, '1.Input'), ...
        fullfile(sourceDirectory, '2.Mesh'), ...
        fullfile(sourceDirectory, '3.HessSmith'), ...
        fullfile(sourceDirectory, '4.Potential'), ...
        fullfile(sourceDirectory, '5.Force'), ...
        fullfile(sourceDirectory, '6.MeanDriftLoads'), ...
        paths.caseWaveDirectory, ...
        fullfile(paths.caseWaveDirectory, 'Common_Scripts'), ...
        paths.convergenceDirectory, paths.artifactDirectory, '-begin');
end

function tableOut = resolve_runtime_functions(paths)
    functionNames = ["run_frequency_domain_case"; "read_config"; ...
        "build_bmf_domain"; "apply_rankine_outer_truncation"; ...
        "assemble_rankine_matrix"; "get_rankine_outer_absorbing_bc"; ...
        "build_rankine_radiation_rhs"; "compute_hydrodynamic_coeffs"; ...
        "compute_wave_excitation"];
    relativePaths = ["Case_Wave/run_frequency_domain_case.m"; ...
        "Source Code/1.Input/read_config.m"; ...
        "Source Code/2.Mesh/build_bmf_domain.m"; ...
        "Source Code/2.Mesh/apply_rankine_outer_truncation.m"; ...
        "Source Code/4.Potential/assemble_rankine_matrix.m"; ...
        "Source Code/4.Potential/get_rankine_outer_absorbing_bc.m"; ...
        "Source Code/4.Potential/build_rankine_radiation_rhs.m"; ...
        "Source Code/5.Force/compute_hydrodynamic_coeffs.m"; ...
        "Source Code/5.Force/compute_wave_excitation.m"];
    resolvedPaths = strings(size(functionNames));
    expectedPaths = strings(size(functionNames));
    exactMatch = false(size(functionNames));
    withinWorktree = false(size(functionNames));
    resolvesToOriginal = false(size(functionNames));
    for index = 1:numel(functionNames)
        resolvedPaths(index) = string(which(functionNames(index)));
        expectedPaths(index) = string(fullfile(paths.repositoryRoot, ...
            strrep(relativePaths(index), '/', filesep)));
        exactMatch(index) = same_path(resolvedPaths(index), expectedPaths(index));
        withinWorktree(index) = path_is_within(resolvedPaths(index), ...
            paths.repositoryRoot);
        resolvesToOriginal(index) = path_is_within(resolvedPaths(index), ...
            paths.originalRepository);
    end
    tableOut = table(functionNames, relativePaths, resolvedPaths, ...
        expectedPaths, exactMatch, withinWorktree, resolvesToOriginal, ...
        'VariableNames', {'function_name', 'repo_relative_path', ...
        'resolved_path', 'expected_path', 'exact_match', ...
        'within_phase3_2_worktree', 'resolves_to_original_repository'});
end

function tableOut = build_source_manifest(paths)
    codeVersion = get_rankine_code_version();
    relativeFiles = string(codeVersion.relativeFiles(:));
    extras = [".gitattributes"; ".gitignore"; ...
        "Case_Wave/Case1_SingleSphere_Convergence/Mesh_Fine/Case1_Fine.cfg"; ...
        "Case_Wave/Case1_SingleSphere_Convergence/Mesh_Fine/hemi_D10_fine_body.bmf"; ...
        "Case_Wave/Case1_SingleSphere_Convergence/Phase2_2_Artifacts/Tests/Frustum_Instrumentation/Cases/Frustum_Top_Only.cfg"; ...
        "Case_Wave/Case1_SingleSphere_Convergence/Phase3_1_Artifacts/Run_Phase3_1_Formal_PFull_Validation.m"; ...
        "Case_Wave/Case1_SingleSphere_Convergence/Phase3_1B_Artifacts/Run_Phase3_1B_Frequency_Anomaly_Audit.m"; ...
        "Case_Wave/Case1_SingleSphere_Convergence/Run_SingleSphere_Convergence.m"; ...
        "Case_Wave/Case1_SingleSphere_Convergence/Fine_FirstOrder_WAMIT_Comparison.csv"; ...
        "Case_Wave/Common_Scripts/read_wamit_dataset.m"; ...
        "Source Code/5.Force/read_wamit_first_order.m"; ...
        "Source Code/5.Force/read_wamit_excitation.m"; ...
        "Source Code/5.Force/read_wamit_rao.m"];
    relativeFiles = unique([relativeFiles; extras], 'stable');
    rowCount = numel(relativeFiles);
    absolutePath = strings(rowCount, 1);
    fileExists = false(rowCount, 1);
    byteCount = zeros(rowCount, 1);
    rawSHA256 = strings(rowCount, 1);
    canonicalSHA256 = strings(rowCount, 1);
    gitBlobID = strings(rowCount, 1);
    gitTracked = false(rowCount, 1);
    for index = 1:rowCount
        absolutePath(index) = string(fullfile(paths.repositoryRoot, ...
            strrep(relativeFiles(index), '/', filesep)));
        fileExists(index) = isfile(absolutePath(index));
        assert(fileExists(index), 'CRESTU:Phase32ManifestFileMissing', ...
            'Frozen input is missing: %s', absolutePath(index));
        information = dir(absolutePath(index));
        byteCount(index) = information.bytes;
        rawSHA256(index) = string(sha256_file_hash(absolutePath(index)));
        canonicalSHA256(index) = string(canonical_lf_file_hash( ...
            absolutePath(index)));
        [gitBlobID(index), gitTracked(index)] = git_blob_id( ...
            paths.repositoryRoot, relativeFiles(index));
    end
    fileClass = repmat("text", rowCount, 1);
    tableOut = table(relativeFiles, absolutePath, fileClass, fileExists, ...
        byteCount, rawSHA256, canonicalSHA256, gitBlobID, gitTracked, ...
        'VariableNames', {'repo_relative_path', 'absolute_path', ...
        'file_class', 'file_exists', 'byte_count', 'raw_byte_sha256', ...
        'canonical_lf_sha256', 'git_blob_id', 'git_tracked'});
end

function tableOut = audit_wamit_reference_provenance(paths)
    currentDerivedRoot = fullfile(fileparts(fileparts(paths.repositoryRoot)), ...
        'WAMIT');
    externalRelative = ["FullSphereIRR3/hemisphere.1"; ...
        "FullSphereIRR3/hemisphere.2"; "FullSphereIRR3/hemisphere.3"; ...
        "FullSphereIRR3/hemisphere.4"; "FullSphereIRR3/hemiSphere.frc"; ...
        "FullSphereIRR3/hemiSphere.gdf"];
    sourceRole = ["current_worktree_derived_root"; ...
        repmat("historical_phase3_1_reference_file", ...
        numel(externalRelative), 1)];
    logicalPath = [string(currentDerivedRoot); externalRelative];
    absolutePath = strings(size(logicalPath));
    absolutePath(1) = string(currentDerivedRoot);
    for index = 1:numel(externalRelative)
        absolutePath(index + 1) = string(fullfile(paths.historicalWamitRoot, ...
            strrep(externalRelative(index), '/', filesep)));
    end
    existsValue = false(size(logicalPath));
    byteCount = zeros(size(logicalPath));
    rawSHA256 = strings(size(logicalPath));
    canonicalSHA256 = strings(size(logicalPath));
    for index = 1:numel(logicalPath)
        existsValue(index) = isfile(absolutePath(index)) || ...
            isfolder(absolutePath(index));
        if isfile(absolutePath(index))
            information = dir(absolutePath(index));
            byteCount(index) = information.bytes;
            rawSHA256(index) = string(sha256_file_hash(absolutePath(index)));
            canonicalSHA256(index) = string(canonical_lf_file_hash( ...
                absolutePath(index)));
        end
    end
    gitTracked = false(size(logicalPath));
    redistribution = repmat("UNCONFIRMED_DO_NOT_COMMIT_RAW", ...
        size(logicalPath));
    callChain = repmat( ...
        "Run_SingleSphere_Convergence.initialize_paths -> read_wamit_dataset", ...
        size(logicalPath));
    tableOut = table(sourceRole, logicalPath, absolutePath, existsValue, ...
        byteCount, rawSHA256, canonicalSHA256, gitTracked, redistribution, ...
        callChain, 'VariableNames', {'source_role', 'logical_path', ...
        'absolute_path', 'exists', 'byte_count', 'raw_sha256', ...
        'canonical_lf_sha256', 'git_tracked', 'redistribution_status', ...
        'producer_call_chain'});
end

function write_baseline_report(summary, paths, runtimeTable, wamitTable)
    filename = fullfile(paths.artifactDirectory, ...
        'PHASE3_2_BASELINE_FREEZE_CN.md');
    fileID = fopen(filename, 'w');
    assert(fileID >= 0, 'CRESTU:Phase32BaselineReportOpen', ...
        'Cannot create baseline report: %s', filename);
    cleanup = onCleanup(@() fclose(fileID));
    fprintf(fileID, '# CRESTU-1F Phase 3.2 基线冻结与来源审计\n\n');
    fprintf(fileID, '生成日期：2026-09-01（Asia/Shanghai）\n\n```ini\n');
    fprintf(fileID, 'GIT_REPO_ROOT = %s\nBRANCH = %s\n', ...
        summary.repositoryRoot, summary.branch);
    fprintf(fileID, 'INITIAL_HEAD = %s\nINITIAL_WORKTREE_STATUS = CLEAN\n', ...
        summary.head);
    fprintf(fileID, 'AUDIT_RUNTIME_HEAD_RELATION = CHECKPOINT_OR_DESCENDANT\n');
    fprintf(fileID, 'MATLAB_PWD = %s\nPHASE3_2_RUNTIME_PROVENANCE = PASS\n', ...
        summary.matlabPwd);
    fprintf(fileID, 'PRODUCTION_PHYSICS_CHANGED = NO\n');
    fprintf(fileID, 'WAMIT_REFERENCE_PATH_RECOVERED = %s\n', ...
        yes_no(summary.historicalWamitReferenceRecovered));
    fprintf(fileID, 'WAMIT_RAW_REDISTRIBUTION = UNCONFIRMED_DO_NOT_COMMIT\n```\n\n');
    fprintf(fileID, '## 冻结边界\n\n');
    fprintf(fileID, ['冻结 checkpoint 为 `7f2d391d1b42366fdb04e1b493439dab438584eb`。', ...
        '本审计没有修改 production physics、mesh topology 或 WAMIT 数值。\n\n']);
    fprintf(fileID, ['文本输入同时记录 raw-byte SHA-256、canonical-LF SHA-256 ', ...
        '和 Git blob ID；没有统一换行、renormalize 或修改 `.gitattributes`。', ...
        '清单共 %d 个已跟踪文件。\n\n'], summary.baselineTrackedSourceCount);
    fprintf(fileID, '## MATLAB runtime path\n\n');
    fprintf(fileID, ['要求的 %d 个 production function 均精确解析到当前 ', ...
        'worktree；没有路径解析到原仓库。\n\n'], height(runtimeTable));
    fprintf(fileID, '## WAMIT provenance\n\n');
    fprintf(fileID, ['目标 worktree 推导路径 `%s` 不存在。只读调用链恢复出 ', ...
        'Phase 3.1 历史外部目录 `%s`；%d 个关键文件已记录 hash。', ...
        '它们不属于 Git，公开再分发权限未确认，禁止复制或提交。\n\n'], ...
        wamitTable.absolute_path(1), paths.historicalWamitRoot, ...
        nnz(wamitTable.source_role == "historical_phase3_1_reference_file"));
    fprintf(fileID, '## 可信度边界\n\n');
    fprintf(fileID, ['本文件只证明 checkpoint/source/runtime provenance。', ...
        '它不证明 Phase 3.2 mesh convergence，不把 WAMIT 作为调参目标，', ...
        '也不提升 `PHYSICAL_VALIDATION=PARTIAL` 或 ', ...
        '`READY_FOR_PRODUCTION=NO`。\n']);
    clear cleanup
end

function hashText = canonical_lf_file_hash(filename)
    fileID = fopen(filename, 'rb');
    assert(fileID >= 0, 'CRESTU:Phase32CanonicalHashOpen', ...
        'Cannot open file for hashing: %s', filename);
    cleanup = onCleanup(@() fclose(fileID));
    bytes = fread(fileID, Inf, '*uint8')';
    clear cleanup
    textValue = native2unicode(bytes, 'UTF-8');
    textValue = strrep(textValue, [char(13), newline], newline);
    textValue = strrep(textValue, char(13), newline);
    hashText = sha256_hash(uint8(unicode2native(textValue, 'UTF-8')));
end

function [blobID, tracked] = git_blob_id(repositoryRoot, relativePath)
    relativeForward = strrep(char(relativePath), '\', '/');
    [output, status] = run_git(repositoryRoot, ...
        sprintf('rev-parse "HEAD:%s"', relativeForward));
    tracked = status == 0 && strlength(strtrim(string(output))) == 40;
    if tracked
        blobID = strtrim(string(output));
    else
        blobID = "";
    end
end

function [output, status] = run_git(repositoryRoot, arguments)
    [status, output] = system(sprintf('git -C "%s" %s', ...
        repositoryRoot, arguments));
end

function value = same_path(firstPath, secondPath)
    value = strcmpi(normalize_path(firstPath), normalize_path(secondPath));
end

function value = path_is_within(candidatePath, rootPath)
    candidate = normalize_path(candidatePath);
    root = normalize_path(rootPath);
    value = strcmpi(candidate, root) || startsWith(lower(candidate), ...
        [lower(root), filesep]);
end

function value = normalize_path(inputPath)
    value = strrep(char(string(inputPath)), '/', filesep);
    while numel(value) > 3 && endsWith(value, filesep)
        value(end) = [];
    end
end

function text = yes_no(value)
    if value
        text = 'YES';
    else
        text = 'NO';
    end
end
