function summary = Run_Phase3_2_Mesh_Audit()
% RUN_PHASE3_2_MESH_AUDIT Generate and audit L1/L2/L3 sentinel meshes only.
% No Rankine matrix is assembled and no BEM solution is computed here.

    %% Stage 1: Verify frozen gate/runtime provenance

    definition = phase32.definition();
    phase32.initialize(definition);
    frequencies = definition.sentinelFrequenciesRadPerS;
    levels = definition.levels;
    manifestRecords = repmat(empty_manifest_record(), 0, 1);
    qualityTable = table();
    costRecords = repmat(empty_cost_record(), 0, 1);

    manifestFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2_Mesh_Manifest.csv');
    qualityFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2_Mesh_Quality.csv');
    costFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2_Mesh_Cost.csv');

    %% Stage 2: Build every sentinel mesh in a unique clean directory

    caseCount = numel(frequencies) * numel(levels);
    completedCount = 0;
    for frequencyIndex = 1:numel(frequencies)
        omega = frequencies(frequencyIndex); % [rad/s]
        for levelIndex = 1:numel(levels)
            level = levels(levelIndex);
            completedCount = completedCount + 1;
            fprintf(['[INFO] Phase 3.2 mesh audit %d/%d | %s | ', ...
                'omega=%.6g rad/s\n'], completedCount, caseCount, ...
                level.name, omega);
            specification = phase32.create_case( ...
                definition, level, omega, 'mesh_audit');
            cleanup = onCleanup(@() phase32.remove_runtime( ...
                definition, specification.runtimeDirectory));
            timer = tic;
            domain = build_bmf_domain(specification.configFile);
            generationRuntimeS = toc(timer);
            assert_runtime_paths(definition, specification, domain);
            [manifest, currentQuality] = phase32.audit_domain( ...
                definition, specification, domain, generationRuntimeS);
            manifestRecords(end + 1, 1) = manifest; %#ok<AGROW>
            if isempty(qualityTable)
                qualityTable = currentQuality;
            else
                qualityTable = [qualityTable; currentQuality]; %#ok<AGROW>
            end
            costRecords(end + 1, 1) = struct( ...
                'stage', "mesh_audit", 'mesh_level', level.name, ...
                'omega_rad_s', omega, ...
                'bem_unknown_count', manifest.total_panel_count, ...
                'mesh_generation_runtime_s', generationRuntimeS, ...
                'assembly_runtime_s', NaN, 'solve_runtime_s', NaN, ...
                'total_runtime_s', generationRuntimeS, ...
                'peak_memory_bytes', NaN, ...
                'memory_measurement_status', ...
                    "NOT_RELIABLY_AVAILABLE_MESH_ONLY", ...
                'estimated_dense_complex_matrix_bytes', ...
                    16 * manifest.total_panel_count ^ 2, ...
                'solve_status', "NOT_RUN_MESH_AUDIT"); %#ok<AGROW>
            writetable(struct2table(manifestRecords), manifestFile);
            writetable(qualityTable, qualityFile);
            writetable(struct2table(costRecords), costFile);
            clear cleanup
        end
    end

    %% Stage 3: Prove coordinated controls and geometry gate

    manifestTable = struct2table(manifestRecords);
    isolationTable = build_control_isolation(definition, manifestTable);
    isolationFile = fullfile(definition.artifactDirectory, ...
        'Phase3_2_Mesh_Control_Isolation.csv');
    writetable(isolationTable, isolationFile);
    geometryPass = all(manifestTable.geometry_gate_status == "PASS") && ...
        all(qualityTable.component_gate_status == "PASS");
    isolationPass = all(isolationTable.geometry_control_isolation == "PASS");
    statusName = ["MESH_GEOMETRY_GATE"; ...
        "MESH_CONTROL_ISOLATION_GEOMETRY"; ...
        "OPERATOR_HASH_ISOLATION"];
    statusValue = [pass_fail(geometryPass); pass_fail(isolationPass); ...
        "PENDING_SENTINEL_ASSEMBLY"];
    evidence = ["Phase3_2_Mesh_Manifest.csv;Phase3_2_Mesh_Quality.csv"; ...
        "Phase3_2_Mesh_Control_Isolation.csv"; ...
        "requires clean sentinel BEM assembly"];
    writetable(table(statusName, statusValue, evidence), ...
        fullfile(definition.artifactDirectory, ...
        'Phase3_2_Mesh_Audit_Status.csv'));

    summary = struct('schemaVersion', 1, ...
        'meshFamily', 'coordinated_non_nested_L1_L2_L3_v4', ...
        'caseCount', height(manifestTable), ...
        'geometryGatePass', geometryPass, ...
        'geometryControlIsolationPass', isolationPass, ...
        'operatorHashIsolation', 'PENDING_SENTINEL_ASSEMBLY');
    fprintf('[RESULT] MESH_GEOMETRY_GATE = %s\n', pass_fail(geometryPass));
    fprintf('[RESULT] MESH_CONTROL_ISOLATION_GEOMETRY = %s\n', ...
        pass_fail(isolationPass));
    assert(geometryPass && isolationPass, ...
        'CRESTU:Phase32MeshAuditGate', ...
        'Phase 3.2 mesh geometry/control-isolation gate failed.');
end

function assert_runtime_paths(definition, specification, domain)
% ASSERT_RUNTIME_PATHS Reject output/config paths outside the unique case.

    paths = [string(specification.configFile); ...
        string(specification.bodyFile); string(domain.cfg.files.fs); ...
        string(domain.cfg.files.seabed); string(domain.cfg.files.farfield); ...
        string(domain.cfg.files.potential_cache); ...
        string(domain.cfg.files.results)];
    runtimePrefix = lower(string(specification.runtimeDirectory) + filesep);
    for index = 1:numel(paths)
        normalized = lower(strrep(paths(index), '/', filesep));
        assert(startsWith(normalized, runtimePrefix) && ...
            ~startsWith(normalized, ...
            lower(string(definition.originalRepository) + filesep)), ...
            'CRESTU:Phase32CasePathProvenance', ...
            'A runtime input/output path escaped the unique Phase 3.2 case.');
    end
end

function tableOut = build_control_isolation(definition, manifest)
% BUILD_CONTROL_ISOLATION Verify all four components and actual h changed.

    frequencies = unique(manifest.omega_rad_s, 'stable');
    rows = repmat(struct('omega_rad_s', NaN, ...
        'level_count', 0, 'body_panel_counts', "", ...
        'free_surface_panel_counts', "", 'bottom_panel_counts', "", ...
        'farfield_panel_counts', "", 'body_count_changes', false, ...
        'free_surface_count_changes', false, ...
        'bottom_count_changes', false, 'farfield_count_changes', false, ...
        'body_h_strictly_decreases', false, ...
        'free_surface_h_strictly_decreases', false, ...
        'bottom_h_strictly_decreases', false, ...
        'wall_h_strictly_decreases', false, ...
        'transition_h_strictly_decreases', false, ...
        'component_geometry_hashes_distinct', false, ...
        'outer_extent_fixed', false, 'physics_hash_fixed', false, ...
        'source_hash_fixed', false, ...
        'operator_hash_isolation', "PENDING_SENTINEL_ASSEMBLY", ...
        'geometry_control_isolation', "FAIL"), numel(frequencies), 1);
    for frequencyIndex = 1:numel(frequencies)
        omega = frequencies(frequencyIndex);
        current = sortrows(manifest(manifest.omega_rad_s == omega, :), ...
            'mesh_level_index');
        bodyCounts = current.body_panel_count;
        fsCounts = current.free_surface_panel_count;
        bottomCounts = current.bottom_panel_count;
        wallCounts = current.farfield_panel_count;
        countPass = all(diff(bodyCounts) > 0) && all(diff(fsCounts) > 0) && ...
            all(diff(bottomCounts) > 0) && all(diff(wallCounts) > 0);
        hPass = all(diff(current.body_median_sqrt_area_m) < 0) && ...
            all(diff(current.fs_median_sqrt_area_m) < 0) && ...
            all(diff(current.bottom_median_sqrt_area_m) < 0) && ...
            all(diff(current.wall_median_sqrt_area_m) < 0) && ...
            all(diff(current.transition_median_sqrt_area_m) < 0);
        hashColumns = {'body_geometry_hash', 'free_surface_geometry_hash', ...
            'bottom_geometry_hash', 'farfield_geometry_hash', ...
            'combined_geometry_hash'};
        hashesDistinct = true;
        for hashIndex = 1:numel(hashColumns)
            hashesDistinct = hashesDistinct && ...
                numel(unique(current.(hashColumns{hashIndex}))) == ...
                numel(definition.levels);
        end
        outerFixed = max(current.actual_top_outer_radius_m) - ...
            min(current.actual_top_outer_radius_m) <= ...
            definition.gates.geometryToleranceM && ...
            max(current.actual_bottom_outer_radius_m) - ...
            min(current.actual_bottom_outer_radius_m) <= ...
            definition.gates.geometryToleranceM;
        physicsFixed = numel(unique(current.physical_state_hash)) == 1;
        sourceFixed = numel(unique(current.production_source_hash)) == 1;
        pass = height(current) == numel(definition.levels) && countPass && ...
            hPass && hashesDistinct && outerFixed && physicsFixed && sourceFixed;
        rows(frequencyIndex) = struct( ...
            'omega_rad_s', omega, 'level_count', height(current), ...
            'body_panel_counts', join_numbers(bodyCounts), ...
            'free_surface_panel_counts', join_numbers(fsCounts), ...
            'bottom_panel_counts', join_numbers(bottomCounts), ...
            'farfield_panel_counts', join_numbers(wallCounts), ...
            'body_count_changes', all(diff(bodyCounts) > 0), ...
            'free_surface_count_changes', all(diff(fsCounts) > 0), ...
            'bottom_count_changes', all(diff(bottomCounts) > 0), ...
            'farfield_count_changes', all(diff(wallCounts) > 0), ...
            'body_h_strictly_decreases', ...
                all(diff(current.body_median_sqrt_area_m) < 0), ...
            'free_surface_h_strictly_decreases', ...
                all(diff(current.fs_median_sqrt_area_m) < 0), ...
            'bottom_h_strictly_decreases', ...
                all(diff(current.bottom_median_sqrt_area_m) < 0), ...
            'wall_h_strictly_decreases', ...
                all(diff(current.wall_median_sqrt_area_m) < 0), ...
            'transition_h_strictly_decreases', ...
                all(diff(current.transition_median_sqrt_area_m) < 0), ...
            'component_geometry_hashes_distinct', hashesDistinct, ...
            'outer_extent_fixed', outerFixed, ...
            'physics_hash_fixed', physicsFixed, ...
            'source_hash_fixed', sourceFixed, ...
            'operator_hash_isolation', "PENDING_SENTINEL_ASSEMBLY", ...
            'geometry_control_isolation', pass_fail(pass));
    end
    tableOut = struct2table(rows);
end

function value = join_numbers(values)
    value = join(string(reshape(values, 1, [])), '|');
end

function record = empty_manifest_record()
% EMPTY_MANIFEST_RECORD Match the audit-domain manifest schema.

    record = struct('stage', "", 'mesh_level', "", ...
        'mesh_level_index', 0, 'nested_mesh', "NO", ...
        'eta_control', NaN, 'omega_rad_s', NaN, 'wavelength_m', NaN, ...
        'body_division_count', 0, 'fs_near_radial_count', 0, ...
        'fs_sponge_radial_count', 0, 'bottom_near_radial_count', 0, ...
        'bottom_sponge_radial_count', 0, ...
        'configured_wall_vertical_count', 0, ...
        'configured_wall_theta_count', 0, ...
        'configured_fs_theta_count', 0, ...
        'configured_bottom_theta_count', 0, ...
        'actual_wall_vertical_layer_count', 0, ...
        'actual_wall_theta_count', 0, 'actual_fs_theta_count', 0, ...
        'actual_bottom_theta_count', 0, 'body_panel_count', 0, ...
        'free_surface_panel_count', 0, 'bottom_panel_count', 0, ...
        'farfield_panel_count', 0, 'total_panel_count', 0, ...
        'body_mean_sqrt_area_m', NaN, 'body_median_sqrt_area_m', NaN, ...
        'fs_mean_sqrt_area_m', NaN, 'fs_median_sqrt_area_m', NaN, ...
        'bottom_mean_sqrt_area_m', NaN, ...
        'bottom_median_sqrt_area_m', NaN, ...
        'wall_mean_sqrt_area_m', NaN, 'wall_median_sqrt_area_m', NaN, ...
        'transition_mean_sqrt_area_m', NaN, ...
        'transition_median_sqrt_area_m', NaN, ...
        'transition_panel_count', 0, 'global_equivalent_h_m', NaN, ...
        'minimum_panel_area_m2', NaN, 'maximum_panel_area_m2', NaN, ...
        'median_panel_area_m2', NaN, 'minimum_edge_length_m', NaN, ...
        'maximum_aspect_ratio', NaN, 'maximum_skewness_deg', NaN, ...
        'maximum_warp_deg', NaN, 'worst_poor_panel_fraction', NaN, ...
        'unique_vertex_count', 0, 'unique_edge_count', 0, ...
        'minimum_edge_multiplicity', 0, 'maximum_edge_multiplicity', 0, ...
        'nonmanifold_edge_count', 0, 'duplicate_panel_count', 0, ...
        'triangle_duplicate_vertex_count', 0, ...
        'unexpected_within_panel_duplicate_vertex_count', 0, ...
        'euler_characteristic', NaN, 'manifold_status', "NOT_RUN", ...
        'normal_orientation_status', "NOT_RUN", ...
        'waterline_continuity_status', "NOT_RUN", ...
        'maximum_interface_gap_m', NaN, ...
        'self_intersection_audit', "NOT_RUN", ...
        'self_intersection_status', "NOT_RUN", ...
        'actual_top_outer_radius_m', NaN, ...
        'actual_bottom_outer_radius_m', NaN, ...
        'target_top_outer_radius_m', NaN, ...
        'target_bottom_outer_radius_m', NaN, 'water_depth_m', NaN, ...
        'body_geometry_hash', "", 'free_surface_geometry_hash', "", ...
        'bottom_geometry_hash', "", 'farfield_geometry_hash', "", ...
        'combined_geometry_hash', "", 'operator_hash', "", ...
        'production_source_hash', "", 'physical_state_hash', "", ...
        'mesh_control_hash', "", 'config_raw_sha256', "", ...
        'body_bmf_raw_sha256', "", 'mesh_generation_command', "", ...
        'generation_runtime_s', NaN, 'geometry_gate_status', "NOT_RUN");
end

function record = empty_cost_record()
    record = struct('stage', "", 'mesh_level', "", 'omega_rad_s', NaN, ...
        'bem_unknown_count', 0, 'mesh_generation_runtime_s', NaN, ...
        'assembly_runtime_s', NaN, 'solve_runtime_s', NaN, ...
        'total_runtime_s', NaN, 'peak_memory_bytes', NaN, ...
        'memory_measurement_status', "NOT_AVAILABLE", ...
        'estimated_dense_complex_matrix_bytes', NaN, ...
        'solve_status', "NOT_RUN");
end

function text = pass_fail(value)
    if value
        text = "PASS";
    else
        text = "FAIL";
    end
end
