function tableOut = Verify_Phase3_2_Legacy_Mesh_Regression()
% VERIFY_PHASE3_2_LEGACY_MESH_REGRESSION Prove q-only geometry is unchanged.

    %% Stage 1: Load frozen Phase 3.1 1.5R geometry identities

    definition = phase32.definition();
    referenceFile = fullfile(definition.convergenceDirectory, ...
        'Phase3_1_Artifacts', 'Phase3_1_Outer_Radius_Convergence.csv');
    reference = readtable(referenceFile, 'TextType', 'string');
    reference = reference(reference.radius_factor == 1.5, :);
    assert(~isempty(reference), 'CRESTU:Phase32LegacyReference', ...
        'Frozen Phase 3.1 1.5R geometry rows are missing.');
    baseline = read_config(definition.baselineConfig);
    formal = read_config(definition.formalConfig);
    rows = repmat(struct('omega_rad_s', NaN, ...
        'q_top', NaN, 'q_bottom', NaN, ...
        'body_expected_hash', "", 'body_actual_hash', "", ...
        'free_surface_expected_hash', "", ...
        'free_surface_actual_hash', "", ...
        'bottom_expected_hash', "", 'bottom_actual_hash', "", ...
        'farfield_expected_hash', "", 'farfield_actual_hash', "", ...
        'combined_expected_hash', "", 'combined_actual_hash', "", ...
        'exact_hash_regression', false, 'status', "FAIL"), ...
        height(reference), 1);

    %% Stage 2: Rebuild q-only meshes with no explicit theta controls

    for index = 1:height(reference)
        runtimeDirectory = tempname(definition.artifactDirectory);
        mkdir(runtimeDirectory);
        cleanup = onCleanup(@() phase32.remove_runtime( ...
            definition, runtimeDirectory));
        omega = reference.omega_rad_s(index); % [rad/s]
        caseName = sprintf('P32_LegacyRegression_w%04d', round(1000 * omega));
        configFile = fullfile(runtimeDirectory, [caseName, '.cfg']);
        write_q_only_config(configFile, caseName, omega, ...
            reference.q_top(index), reference.q_bottom(index), ...
            baseline, formal);
        domain = build_bmf_domain(configFile);
        audit = audit_domain_meshes(domain);
        exact = string(audit.body.hash) == ...
            reference.body_geometry_hash(index) && ...
            string(audit.freeSurface.hash) == ...
            reference.free_surface_geometry_hash(index) && ...
            string(audit.bottom.hash) == ...
            reference.bottom_geometry_hash(index) && ...
            string(audit.outerBoundary.hash) == ...
            reference.farfield_geometry_hash(index) && ...
            string(audit.geometry.hash) == ...
            reference.combined_geometry_hash(index);
        rows(index) = struct('omega_rad_s', omega, ...
            'q_top', reference.q_top(index), ...
            'q_bottom', reference.q_bottom(index), ...
            'body_expected_hash', reference.body_geometry_hash(index), ...
            'body_actual_hash', string(audit.body.hash), ...
            'free_surface_expected_hash', ...
                reference.free_surface_geometry_hash(index), ...
            'free_surface_actual_hash', string(audit.freeSurface.hash), ...
            'bottom_expected_hash', reference.bottom_geometry_hash(index), ...
            'bottom_actual_hash', string(audit.bottom.hash), ...
            'farfield_expected_hash', ...
                reference.farfield_geometry_hash(index), ...
            'farfield_actual_hash', string(audit.outerBoundary.hash), ...
            'combined_expected_hash', ...
                reference.combined_geometry_hash(index), ...
            'combined_actual_hash', string(audit.geometry.hash), ...
            'exact_hash_regression', exact, 'status', pass_fail(exact));
        clear cleanup
    end

    %% Stage 3: Persist and enforce exact legacy regression

    tableOut = struct2table(rows);
    writetable(tableOut, fullfile(definition.artifactDirectory, ...
        'Phase3_2_Legacy_Mesh_Regression.csv'));
    pass = all(tableOut.exact_hash_regression);
    fprintf('[RESULT] Q_ONLY_LEGACY_GEOMETRY_REGRESSION = %s\n', ...
        pass_fail(pass));
    assert(pass, 'CRESTU:Phase32LegacyMeshRegression', ...
        'The explicit-theta patch changed a frozen q-only Phase 3.1 mesh.');
end

function write_q_only_config(filename, caseName, omega, qTop, qBottom, ...
        baseline, formal)
    fileID = fopen(filename, 'w');
    assert(fileID >= 0, 'CRESTU:Phase32LegacyConfigOpen', ...
        'Cannot create legacy regression config.');
    cleanup = onCleanup(@() fclose(fileID));
    body = baseline.bodies(1);
    mass = baseline.mass_props(1);
    inertia = mass.inertia;
    inertiaTokens = [inertia(1, 1), inertia(2, 2), inertia(3, 3), ...
        -inertia(1, 2), -inertia(1, 3), -inertia(2, 3)];
    fprintf(fileID, 'PARA1: Project Case Name\n%s\n\n', caseName);
    fprintf(fileID, 'PARA2: IPOTEN IFORCE IRAD IDIFF IDRIFT\n1 0 0 1 0\n\n');
    fprintf(fileID, 'PARA3: FREQUENCY AND HEADING\n1 1 %.17g %.17g\n', ...
        omega, omega);
    fprintf(fileID, '%d\n', formal.wave.ndir);
    fprintf(fileID, '%.17g ', formal.wave.headings);
    fprintf(fileID, '\n\nPARA4: ENVIRONMENT\n%.17g %.17g %.17g\n\n', ...
        baseline.water_depth, baseline.grav, baseline.rho);
    fprintf(fileID, 'PARA5: BODY\n1\n%d %s %.17g %.17g %.17g %.17g\n\n', ...
        body.id, body.mesh_file, body.pos, body.yaw);
    fprintf(fileID, 'PARA6: MASS PROPERTIES\n%.17g %.17g %.17g %.17g\n', ...
        mass.mass, mass.cg);
    fprintf(fileID, '%.17g %.17g %.17g %.17g %.17g %.17g\n\n', ...
        inertiaTokens);
    fprintf(fileID, 'PARA7: MODES\n');
    fprintf(fileID, '%d ', baseline.calc_modes);
    fprintf(fileID, '\n\nPARA8: FULL DOMAIN\n%d %d\n\n', ...
        baseline.isx, baseline.isy);
    fprintf(fileID, ['PARA9: DOMAIN\n%.17g %d %d %.17g %.17g ', ...
        '%.17g %d\n\n'], baseline.z_tol, baseline.fs.nr_near, ...
        baseline.fs.nr_sponge, baseline.fs.r_inner, baseline.fs.r_outer, ...
        baseline.fs.sponge_ratio, baseline.fs.nz_farfield);
    fprintf(fileID, 'PARA10: SPONGE\n%.17g\n\n', baseline.fs.mu0);
    fprintf(fileID, ['PARA11: FIXED OUTER-DOMAIN WATERLINE\n', ...
        'OUTER_WATERLINE_MESH %s\n\n'], body.mesh_file);
    fprintf(fileID, ['PARA12: PHASE2.2 OUTER TRUNCATION AUDIT\n', ...
        'OUTER_TRUNCATION_Q %.17g %.17g\n\n'], qTop, qBottom);
    fprintf(fileID, ['PARA13: DIAGNOSTICS ONLY, NO THETA CONTROL\n', ...
        'RAW_DIAGNOSTICS 1\nPERSIST_FULL_PHI 0\n']);
    clear cleanup
end

function text = pass_fail(value)
    if value
        text = "PASS";
    else
        text = "FAIL";
    end
end
