function assert_v5_match(expected, actual, specification, ...
        operatorState, controlManifest, meshAudit)
% ASSERT_V5_MATCH Stop before assembly if v5 provenance changed.

    exactTextFields = ["mesh_level"; "topology_mode"; ...
        "body_geometry_hash"; "free_surface_geometry_hash"; ...
        "bottom_geometry_hash"; "farfield_geometry_hash"; ...
        "combined_geometry_hash"; "production_source_hash"; ...
        "physical_state_hash"; "mesh_control_hash"];
    exactNumericFields = ["mesh_level_index"; "omega_rad_s"; ...
        "body_panel_count"; "free_surface_panel_count"; ...
        "bottom_panel_count"; "farfield_panel_count"; ...
        "total_panel_count"; "water_depth_m"];
    toleranceFields = ["actual_top_outer_radius_m"; ...
        "actual_bottom_outer_radius_m"; "target_top_outer_radius_m"; ...
        "target_bottom_outer_radius_m"; ...
        "realized_near_radial_step_m"; ...
        "realized_outer_radial_step_m"];
    for fieldIndex = 1:numel(exactTextFields)
        name = exactTextFields(fieldIndex);
        assert(string(actual.(name)) == string(expected.(name)), ...
            'CRESTU:Phase32BV5TextMismatch', ...
            'Frozen v5 field %s did not reproduce before assembly.', name);
    end
    for fieldIndex = 1:numel(exactNumericFields)
        name = exactNumericFields(fieldIndex);
        assert(isequaln(actual.(name), expected.(name)), ...
            'CRESTU:Phase32BV5NumericMismatch', ...
            'Frozen v5 field %s did not reproduce before assembly.', name);
    end
    for fieldIndex = 1:numel(toleranceFields)
        name = toleranceFields(fieldIndex);
        scale = max([1.0, abs(actual.(name)), abs(expected.(name))]);
        assert(abs(actual.(name) - expected.(name)) <= 1.0e-12 * scale, ...
            'CRESTU:Phase32BV5ToleranceMismatch', ...
            'Frozen v5 field %s exceeded tolerance before assembly.', name);
    end
    assert(string(specification.physicalHash) == ...
        string(expected.physical_state_hash) && ...
        string(specification.controlHash) == ...
        string(expected.mesh_control_hash), ...
        'CRESTU:Phase32BConfigSemanticHash', ...
        'Physical/control semantic config hashes changed.');
    assert(string(operatorState.boundaryOperatorStateSHA256) == ...
        string(expected.preassembly_operator_hash) && ...
        string(controlManifest.configuredSHA256) == ...
        string(expected.preassembly_configured_controls_hash) && ...
        string(controlManifest.effectiveSHA256) == ...
        string(expected.preassembly_effective_controls_hash), ...
        'CRESTU:Phase32BOperatorHash', ...
        'Preassembly operator or configured/effective control hash changed.');
    assert(string(meshAudit.sourcePointHash) == ...
        string(expected.preassembly_source_point_hash) && ...
        string(meshAudit.collocationPointHash) == ...
        string(expected.preassembly_collocation_point_hash), ...
        'CRESTU:Phase32BPointHash', ...
        'Source/collocation point hash changed before assembly.');
end
