function record = empty_response_record()
% EMPTY_RESPONSE_RECORD Stable schema for one isolated Phase 3.2B solve.

    record = struct('execution_stage', "", 'case_id', "", ...
        'mesh_level', "", 'mesh_level_index', 0, 'eta_control', NaN, ...
        'omega_rad_s', NaN, 'topology_mode', "", ...
        'preassembly_status', "NOT_RUN", ...
        'v5_mesh_reproducibility', "NOT_RUN", ...
        'matrix_assembly_status', "NOT_RUN", 'solve_status', "NOT_RUN", ...
        'cache_status', "NOT_RUN", 'all_finite', false, ...
        'algebraic_gate_status', "NOT_RUN", ...
        'body_panel_count', 0, 'free_surface_panel_count', 0, ...
        'bottom_panel_count', 0, 'farfield_panel_count', 0, ...
        'bem_unknown_count', 0, 'matrix_rows', 0, 'matrix_columns', 0, ...
        'raw_rcond', NaN, 'scaled_rcond', NaN, ...
        'radiation_linear_relative_residual', NaN, ...
        'diffraction_linear_relative_residual', NaN, ...
        'radiation_algebraic_relative_residual', NaN, ...
        'diffraction_algebraic_relative_residual', NaN, ...
        'maximum_abs_outer_ntheta', NaN, ...
        'maximum_outer_column_residual', NaN, ...
        'A33_kg', NaN, 'B33_kg_s', NaN, ...
        'F3_real_N_per_m', NaN, 'F3_imag_N_per_m', NaN, ...
        'F3_abs_N_per_m', NaN, 'F3_phase_deg', NaN, ...
        'RAO3_real_m_per_m', NaN, 'RAO3_imag_m_per_m', NaN, ...
        'RAO3_abs_m_per_m', NaN, 'RAO3_phase_deg', NaN, ...
        'D3_real_N_per_m', NaN, 'D3_imag_N_per_m', NaN, ...
        'D3_abs_N_per_m', NaN, 'D3_phase_deg', NaN, ...
        'omega_B33_N_per_m', NaN, ...
        'raw_added_mass_symmetry_error', NaN, ...
        'raw_damping_symmetry_error', NaN, ...
        'minimum_eigenvalue_symmetric_damping_raw', NaN, ...
        'negative_damping_diagnostic', "NOT_RUN", ...
        'symmetry_leakage_diagnostic', ...
            "NOT_AVAILABLE_SINGLE_SYMMETRY_REDUCED_CASE", ...
        'solver_warning_count', 0, 'solver_warning_id', "", ...
        'body_geometry_hash', "", 'free_surface_geometry_hash', "", ...
        'bottom_geometry_hash', "", 'farfield_geometry_hash', "", ...
        'combined_geometry_hash', "", 'source_point_hash', "", ...
        'collocation_point_hash', "", 'operator_hash', "", ...
        'configured_controls_hash', "", 'effective_controls_hash', "", ...
        'production_source_hash', "", 'physical_state_hash', "", ...
        'mesh_control_hash', "", 'config_raw_sha256', "", ...
        'body_bmf_raw_sha256', "", 'actual_top_outer_radius_m', NaN, ...
        'actual_bottom_outer_radius_m', NaN, 'water_depth_m', NaN, ...
        'assembly_runtime_s', NaN, 'total_runtime_s', NaN, ...
        'peak_working_set_bytes', NaN, ...
        'runtime_directory_policy', "UNIQUE_TEMP_REMOVED_AFTER_EXTRACTION", ...
        'original_repository_path_detected', false, ...
        'error_identifier', "", 'error_message', "");
end
