function definition = initialize()
% INITIALIZE Enforce Phase 3.2B branch, ancestry, paths, and frozen inputs.

    %% Stage 1: Resolve the authorized worktree and production runtime

    packageDirectory = fileparts(mfilename('fullpath'));
    artifactDirectory = fileparts(packageDirectory);
    convergenceDirectory = fileparts(artifactDirectory);
    caseWaveDirectory = fileparts(convergenceDirectory);
    repositoryRoot = fileparts(caseWaveDirectory);
    sourceDirectory = fullfile(repositoryRoot, 'Source Code');

    restoredefaultpath;
    rehash toolboxcache;
    assert(same_path(pwd, repositoryRoot), 'CRESTU:Phase32BMatlabPwd', ...
        'MATLAB pwd must be the authorized Phase 3.2B worktree root.');
    addpath(fullfile(sourceDirectory, '0.Tools Code'), ...
        fullfile(sourceDirectory, '1.Input'), ...
        fullfile(sourceDirectory, '2.Mesh'), ...
        fullfile(sourceDirectory, '3.HessSmith'), ...
        fullfile(sourceDirectory, '4.Potential'), ...
        fullfile(sourceDirectory, '5.Force'), ...
        fullfile(sourceDirectory, '6.MeanDriftLoads'), ...
        caseWaveDirectory, fullfile(caseWaveDirectory, 'Common_Scripts'), ...
        convergenceDirectory, ...
        fullfile(convergenceDirectory, 'Phase3_2_Artifacts'), ...
        fullfile(convergenceDirectory, 'Phase3_2A_Artifacts'), ...
        artifactDirectory, '-begin');

    %% Stage 2: Enforce Git provenance without requiring an old HEAD

    baselineCommit = '4a1bb81f6db6e577a1b45263d9e224a9260a5153';
    baselineTag = 'phase3-2a-v5-ready-for-sentinel';
    [branch, branchStatus] = git_query(repositoryRoot, 'branch --show-current');
    [tagCommit, tagStatus] = git_query(repositoryRoot, sprintf( ...
        'rev-parse "%s^{commit}"', baselineTag));
    [~, ancestorStatus] = git_query(repositoryRoot, sprintf( ...
        'merge-base --is-ancestor %s HEAD', baselineCommit));
    assert(branchStatus == 0 && ...
        strcmp(strtrim(branch), 'phase3-2b-response-convergence') && ...
        tagStatus == 0 && strcmp(strtrim(tagCommit), baselineCommit) && ...
        ancestorStatus == 0, 'CRESTU:Phase32BGitProvenance', ...
        'Phase 3.2B branch, frozen tag, or baseline ancestry is invalid.');

    requiredFunctions = ["run_frequency_domain_case"; "read_config"; ...
        "build_bmf_domain"; "assemble_rankine_matrix"; ...
        "estimate_rankine_conditioning"; "get_polar_topology_mode"];
    originalRepository = 'E:\CRESTU-1F_v1.0_20260824\Code\CRESTU';
    for functionIndex = 1:numel(requiredFunctions)
        activePath = string(which(requiredFunctions(functionIndex)));
        assert(path_is_within(activePath, repositoryRoot) && ...
            ~path_is_within(activePath, originalRepository), ...
            'CRESTU:Phase32BRuntimePath', ...
            'A production function resolved outside the authorized worktree.');
    end

    %% Stage 3: Read and validate the immutable Phase 3.2A evidence

    phase32aDirectory = fullfile(convergenceDirectory, 'Phase3_2A_Artifacts');
    manifestFile = fullfile(phase32aDirectory, ...
        'Phase3_2A_V5_Mesh_Manifest.csv');
    qualityFile = fullfile(phase32aDirectory, ...
        'Phase3_2A_V5_Mesh_Quality.csv');
    isolationFile = fullfile(phase32aDirectory, ...
        'Phase3_2A_V5_Control_Isolation.csv');
    manifest = readtable(manifestFile, 'TextType', 'string');
    quality = readtable(qualityFile, 'TextType', 'string');
    isolation = readtable(isolationFile, 'TextType', 'string');
    assert(height(manifest) == 18 && height(quality) == 72 && ...
        height(isolation) == 6 && ...
        all(quality.component_gate_status == "PASS") && ...
        all(isolation.frequency_geometry_gate == "PASS") && ...
        all(manifest.topology_mode == "QUALITY_CONTROLLED_V2") && ...
        all(manifest.geometry_gate_status == "PASS"), ...
        'CRESTU:Phase32BFrozenEvidence', ...
        'The authoritative Phase 3.2A v5 evidence is incomplete or failed.');
    levels = build_levels(manifest);

    %% Stage 4: Publish the frozen Phase 3.2B definition

    definition = struct('schemaVersion', 1, ...
        'artifactDirectory', artifactDirectory, ...
        'phase32aDirectory', phase32aDirectory, ...
        'convergenceDirectory', convergenceDirectory, ...
        'caseWaveDirectory', caseWaveDirectory, ...
        'repositoryRoot', repositoryRoot, ...
        'sourceDirectory', sourceDirectory, ...
        'originalRepository', originalRepository, ...
        'baselineCommit', baselineCommit, 'baselineTag', baselineTag, ...
        'baselineManifestFile', manifestFile, ...
        'baselineQualityFile', qualityFile, ...
        'baselineIsolationFile', isolationFile, ...
        'baselineManifest', manifest, 'levels', levels, ...
        'baselineConfig', fullfile(convergenceDirectory, ...
            'Phase2_2_Artifacts', 'Tests', 'Frustum_Instrumentation', ...
            'Cases', 'Frustum_Top_Only.cfg'), ...
        'formalConfig', fullfile(convergenceDirectory, ...
            'Mesh_Fine', 'Case1_Fine.cfg'), ...
        'topologyMode', 'QUALITY_CONTROLLED_V2', ...
        'outerRadiusFactor', 1.5, 'sphereRadiusM', 5.0, ...
        'sentinelFrequenciesRadPerS', [0.5, 0.6, 1.0, 1.4, 1.5, 2.0], ...
        'resonanceFrequenciesRadPerS', 1.30:0.02:1.50, ...
        'formalFrequenciesRadPerS', 0.5:0.1:2.0, ...
        'rawRcondMinimum', 1.0e-12, ...
        'scaledRcondMinimum', 1.0e-12, ...
        'relativeResidualMaximum', 1.0e-10, ...
        'maximumAbsOuterNtheta', 1.0e-10, ...
        'maximumOuterColumnResidual', 1.0e-14, ...
        'responseFloors', struct('A33Kg', 1.0, 'B33KgPerS', 1.0, ...
            'F3NPerM', 1.0, 'RAO3MPerM', 1.0e-6, ...
            'D3NPerM', 1.0), ...
        'responseRelativeGates', struct('A33', 0.05, 'B33', 0.05, ...
            'F3', 0.05, 'RAO3', 0.10), ...
        'resonanceGates', struct('peakFrequencyRadPerS', 0.02, ...
            'peakMagnitudeRelative', 0.10, ...
            'd3MinimumFrequencyRadPerS', 0.02, ...
            'd3MinimumMagnitudeRelative', 0.15), ...
        'maximumConcurrentL3Solves', 1, ...
        'geometryToleranceM', 1.0e-8, ...
        'minimumEdgeLengthM', 1.0e-10, ...
        'bodyMaximumAspectRatio', 4.0, ...
        'nearMaximumAspectRatio', 4.5, ...
        'outerMaximumAspectRatio', 12.0, ...
        'maximumSkewnessDeg', 55.0, ...
        'minimumCornerAngleDeg', 35.0, ...
        'maximumCornerAngleDeg', 145.0, ...
        'maximumWarpDeg', 8.0, ...
        'maximumPoorPanelFraction', 0.05, ...
        'meshTransitionRadiusM', 20.0, ...
        'designCanonicalSHA256', unique_scalar(manifest.design_canonical_sha256), ...
        'designGitBlobID', unique_scalar(manifest.design_git_blob_id), ...
        'designV2CanonicalSHA256', unique_scalar(manifest.design_v2_canonical_sha256), ...
        'designV2GitBlobID', unique_scalar(manifest.design_v2_git_blob_id), ...
        'designV3CanonicalSHA256', unique_scalar(manifest.design_v3_canonical_sha256), ...
        'designV3GitBlobID', unique_scalar(manifest.design_v3_git_blob_id));
    fprintf('[OK] Phase 3.2B branch, ancestry, runtime, and frozen inputs verified.\n');
end

function levels = build_levels(manifest)
    template = struct('name', "", 'index', 0, 'eta', NaN, ...
        'bodyDivision', 0, 'fsRadialCounts', [0, 0], ...
        'bottomRadialCounts', [0, 0], 'wallVerticalCount', 0, ...
        'wallThetaCount', 0, 'fsThetaCount', 0, ...
        'bottomThetaCount', 0, 'bottomCoreRadialLayerCount', 0);
    levels = repmat(template, 3, 1);
    for levelIndex = 1:3
        rows = manifest.mesh_level_index == levelIndex;
        assert(nnz(rows) == 6, 'CRESTU:Phase32BLevelRows', ...
            'Each frozen mesh level must contain six sentinel rows.');
        row = manifest(find(rows, 1), :);
        assert_constant(manifest(rows, :), ...
            ["mesh_level"; "eta_control"; "body_division_count"; ...
            "fs_near_radial_count"; "fs_sponge_radial_count"; ...
            "bottom_near_radial_count"; "bottom_sponge_radial_count"; ...
            "configured_wall_vertical_count"; ...
            "configured_wall_theta_count"; "configured_fs_theta_count"; ...
            "configured_bottom_theta_count"; ...
            "requested_bottom_core_radial_layer_count"]);
        levels(levelIndex) = struct('name', row.mesh_level, ...
            'index', levelIndex, 'eta', row.eta_control, ...
            'bodyDivision', row.body_division_count, ...
            'fsRadialCounts', [row.fs_near_radial_count, ...
                row.fs_sponge_radial_count], ...
            'bottomRadialCounts', [row.bottom_near_radial_count, ...
                row.bottom_sponge_radial_count], ...
            'wallVerticalCount', row.configured_wall_vertical_count, ...
            'wallThetaCount', row.configured_wall_theta_count, ...
            'fsThetaCount', row.configured_fs_theta_count, ...
            'bottomThetaCount', row.configured_bottom_theta_count, ...
            'bottomCoreRadialLayerCount', ...
                row.requested_bottom_core_radial_layer_count);
    end
end

function assert_constant(tableIn, names)
    for nameIndex = 1:numel(names)
        values = tableIn.(names(nameIndex));
        assert(numel(unique(values)) == 1, 'CRESTU:Phase32BLevelControlDrift', ...
            'Frozen level control %s changes with frequency.', names(nameIndex));
    end
end

function value = unique_scalar(values)
    uniqueValues = unique(string(values));
    assert(numel(uniqueValues) == 1, 'CRESTU:Phase32BFrozenHashDrift', ...
        'A frozen source/design hash is not constant.');
    value = char(uniqueValues);
end

function [output, status] = git_query(repositoryRoot, arguments)
    [status, output] = system(sprintf('git -C "%s" %s', ...
        repositoryRoot, arguments));
end

function value = same_path(firstPath, secondPath)
    value = strcmpi(normalize_path(firstPath), normalize_path(secondPath));
end

function value = path_is_within(candidatePath, rootPath)
    candidate = normalize_path(candidatePath);
    root = normalize_path(rootPath);
    value = strcmpi(candidate, root) || startsWith(lower(candidate), ...
        [lower(root), filesep]);
end

function value = normalize_path(inputPath)
    value = strrep(char(string(inputPath)), '/', filesep);
    while numel(value) > 3 && endsWith(value, filesep)
        value(end) = [];
    end
end
