function [operatorState, controlManifest, meshAudit] = ...
        preview_operator_state(domain, omega)
% PREVIEW_OPERATOR_STATE Hash the matrix-defining state without assembly.

    validateattributes(omega, {'numeric'}, ...
        {'scalar', 'real', 'positive', 'finite'});
    meshAudit = audit_domain_meshes(domain);
    cfg = domain.cfg;
    cfg.fs.r_outer = cfg.fs.tuning_report.original_outer_radius;
    [cfg, cfg.fs.tuning_report] = tune_sponge_layer(cfg, omega);
    cfg = apply_phase2_2_mesh_controls(cfg);
    [cfg, ~] = resolve_phase2_2_controls(cfg, omega);
    [cfg, ~] = finalize_phase2_2_manifest(cfg, meshAudit, domain.stats);
    [physicalWaveNumber, ~] = solve_wave_dispersion( ...
        omega, cfg.grav, cfg.water_depth);
    freeSurface = get_rankine_free_surface_robin_bc( ...
        domain.geometry.centers, domain.stats, omega, cfg.grav, cfg);
    nominalMu = cfg.phase2_2_controls.effective.actualMu0;
    outer = get_rankine_outer_absorbing_bc( ...
        domain.geometry.centers, domain.geometry.normals, domain.stats, ...
        omega, cfg.grav, cfg.water_depth, cfg, physicalWaveNumber, nominalMu);
    operatorState = get_rankine_boundary_operator_state( ...
        freeSurface.cacheSpecification, outer.cacheSpecification, ...
        meshAudit.geometry.hash);
    [~, controlManifest] = bind_phase2_2_operator_state(cfg, operatorState);
end
