function record = run_v5_case(definition, level, omega, executionStage)
% RUN_V5_CASE Execute one isolated, preassembly-gated v5 clean solve.

    validateattributes(omega, {'numeric'}, ...
        {'scalar', 'real', 'positive', 'finite'});
    record = phase32b.empty_response_record();
    record.execution_stage = string(executionStage);
    record.mesh_level = level.name;
    record.mesh_level_index = level.index;
    record.eta_control = level.eta;
    record.omega_rad_s = omega;
    record.topology_mode = "QUALITY_CONTROLLED_V2";
    expected = phase32b.find_frozen_row(definition, level, omega);
    record.case_id = string(sprintf('%s_%s_w%04d', ...
        char(executionStage), char(level.name), round(1000 * omega)));
    timer = tic;
    assemblyAuthorized = false;

    try
        %% Stage 1: Generate a unique case and enforce preassembly provenance

        specification = phase32a.create_case(definition, level, omega, ...
            char(executionStage));
        cleanup = onCleanup(@() phase32.remove_runtime( ...
            definition, specification.runtimeDirectory));
        record.config_raw_sha256 = specification.configRawSHA256;
        record.body_bmf_raw_sha256 = specification.bodyFileRawSHA256;
        record.physical_state_hash = specification.physicalHash;
        record.mesh_control_hash = specification.controlHash;
        record.original_repository_path_detected = ...
            contains(lower(string(specification.runtimeDirectory)), ...
            lower(string(definition.originalRepository)));
        assert(~record.original_repository_path_detected, ...
            'CRESTU:Phase32BOriginalRepositoryPath', ...
            'A runtime path points to the original repository.');

        preflightDomain = build_bmf_domain(specification.configFile);
        preflightConfig = read_config(specification.configFile);
        assert(get_polar_topology_mode(preflightConfig) == ...
            "QUALITY_CONTROLLED_V2", 'CRESTU:Phase32BExplicitTopology', ...
            'Every Phase 3.2B v5 solve must explicitly select V2.');
        [actualManifest, ~] = phase32a.audit_case( ...
            definition, specification, preflightDomain, NaN);
        [operatorState, controlManifest, meshAudit] = ...
            phase32b.preview_operator_state(preflightDomain, omega);
        phase32b.assert_v5_match(expected, actualManifest, specification, ...
            operatorState, controlManifest, meshAudit);
        record.preassembly_status = "PASS";
        record.v5_mesh_reproducibility = "PASS";
        bind_preflight_record();
        assemblyAuthorized = true;

        %% Stage 2: Execute one production clean solve with cache MISS

        lastwarn('');
        results = run_frequency_domain_case(specification.configFile, ...
            'skipPhysicalDiagnostics', true);
        record.total_runtime_s = toc(timer);
        [warningMessage, warningID] = lastwarn;
        record.solver_warning_count = double(~isempty(warningMessage));
        record.solver_warning_id = string(warningID);
        assert_runtime_scope(specification, results);
        loaded = load(results.potential_cache_file, 'pot_cache');
        assert(numel(loaded.pot_cache.entries) == 1, ...
            'CRESTU:Phase32BCacheEntryCount', ...
            'An isolated case must contain exactly one cache entry.');
        entry = loaded.pot_cache.entries(1);
        bind_solve_record();
        assert_postsolve_match();

        %% Stage 3: Apply the frozen algebraic gates

        maximumResidual = max([ ...
            record.radiation_linear_relative_residual, ...
            record.diffraction_linear_relative_residual, ...
            record.radiation_algebraic_relative_residual, ...
            record.diffraction_algebraic_relative_residual]);
        finiteValues = [record.raw_rcond, record.scaled_rcond, ...
            maximumResidual, record.maximum_abs_outer_ntheta, ...
            record.maximum_outer_column_residual, record.A33_kg, ...
            record.B33_kg_s, record.F3_real_N_per_m, ...
            record.F3_imag_N_per_m, record.RAO3_real_m_per_m, ...
            record.RAO3_imag_m_per_m, record.D3_real_N_per_m, ...
            record.D3_imag_N_per_m];
        record.all_finite = all(isfinite(finiteValues));
        algebraicPass = record.all_finite && ...
            record.raw_rcond >= definition.rawRcondMinimum && ...
            record.scaled_rcond >= definition.scaledRcondMinimum && ...
            maximumResidual <= definition.relativeResidualMaximum && ...
            record.maximum_abs_outer_ntheta <= ...
                definition.maximumAbsOuterNtheta && ...
            record.maximum_outer_column_residual <= ...
                definition.maximumOuterColumnResidual && ...
            lower(record.cache_status) == "miss" && ...
            record.solver_warning_count == 0;
        record.algebraic_gate_status = pass_fail(algebraicPass);
        record.solve_status = pass_fail(algebraicPass);
    catch exception
        record.total_runtime_s = toc(timer);
        record.error_identifier = string(exception.identifier);
        record.error_message = string(exception.message);
        if ~assemblyAuthorized
            record.preassembly_status = "FAIL";
            record.v5_mesh_reproducibility = "FAIL";
            record.solve_status = "NOT_RUN_PREASSEMBLY_FAIL";
        elseif is_resource_exception(exception)
            record.solve_status = "BLOCKED_RESOURCE";
            record.algebraic_gate_status = "BLOCKED_RESOURCE";
        else
            record.solve_status = "FAIL";
            record.algebraic_gate_status = "FAIL";
        end
    end
    clear cleanup

    function bind_preflight_record()
        record.body_panel_count = actualManifest.body_panel_count;
        record.free_surface_panel_count = ...
            actualManifest.free_surface_panel_count;
        record.bottom_panel_count = actualManifest.bottom_panel_count;
        record.farfield_panel_count = actualManifest.farfield_panel_count;
        record.bem_unknown_count = actualManifest.total_panel_count;
        record.body_geometry_hash = actualManifest.body_geometry_hash;
        record.free_surface_geometry_hash = ...
            actualManifest.free_surface_geometry_hash;
        record.bottom_geometry_hash = actualManifest.bottom_geometry_hash;
        record.farfield_geometry_hash = ...
            actualManifest.farfield_geometry_hash;
        record.combined_geometry_hash = ...
            actualManifest.combined_geometry_hash;
        record.source_point_hash = string(meshAudit.sourcePointHash);
        record.collocation_point_hash = ...
            string(meshAudit.collocationPointHash);
        record.operator_hash = string( ...
            operatorState.boundaryOperatorStateSHA256);
        record.configured_controls_hash = string( ...
            controlManifest.configuredSHA256);
        record.effective_controls_hash = string( ...
            controlManifest.effectiveSHA256);
        record.production_source_hash = ...
            actualManifest.production_source_hash;
        record.actual_top_outer_radius_m = ...
            actualManifest.actual_top_outer_radius_m;
        record.actual_bottom_outer_radius_m = ...
            actualManifest.actual_bottom_outer_radius_m;
        record.water_depth_m = actualManifest.water_depth_m;
    end

    function bind_solve_record()
        diagnostics = entry.solver_diagnostics;
        conditioning = cellfun(@(item) item.conditioning, diagnostics, ...
            'UniformOutput', false);
        assembly = entry.assembly_info;
        record.matrix_assembly_status = "PASS";
        record.matrix_rows = entry.mesh_audit.bemUnknownCount;
        record.matrix_columns = entry.mesh_audit.bemUnknownCount;
        record.bem_unknown_count = entry.mesh_audit.bemUnknownCount;
        record.raw_rcond = min(cellfun(@(item) ...
            item.rawRcondEstimate, conditioning));
        record.scaled_rcond = min(cellfun(@(item) ...
            item.scaledRcondEstimate, conditioning));
        record.radiation_linear_relative_residual = max(cellfun(@(item) ...
            item.radiationRelativeResidual, diagnostics));
        record.diffraction_linear_relative_residual = max(cellfun(@(item) ...
            item.diffractionRelativeResidual, diagnostics));
        record.radiation_algebraic_relative_residual = max(cellfun(@(item) ...
            item.radiation.relativeResidualFrobeniusNorm, diagnostics));
        record.diffraction_algebraic_relative_residual = max(cellfun(@(item) ...
            item.diffraction.relativeResidualFrobeniusNorm, diagnostics));
        record.maximum_abs_outer_ntheta = max(cellfun(@(item) ...
            item.outer_absorbing_boundary.maximumAbsTangentialNormal, ...
            assembly));
        record.maximum_outer_column_residual = max(cellfun(@(item) ...
            item.outer_source_column_audit.reconstructionRelativeResidual, ...
            assembly));
        record.assembly_runtime_s = sum(cellfun(@(item) ...
            item.elapsed_seconds, assembly));
        record.A33_kg = results.added_mass(3, 3, 1);
        record.B33_kg_s = results.damping(3, 3, 1);
        excitation = results.excitation(3, 1, 1);
        response = results.rao.complex(3, 1, 1);
        denominator = results.rao.dynamic_matrix(3, 3, 1);
        record.F3_real_N_per_m = real(excitation);
        record.F3_imag_N_per_m = imag(excitation);
        record.F3_abs_N_per_m = abs(excitation);
        record.F3_phase_deg = rad2deg(angle(excitation));
        record.RAO3_real_m_per_m = real(response);
        record.RAO3_imag_m_per_m = imag(response);
        record.RAO3_abs_m_per_m = abs(response);
        record.RAO3_phase_deg = rad2deg(angle(response));
        record.D3_real_N_per_m = real(denominator);
        record.D3_imag_N_per_m = imag(denominator);
        record.D3_abs_N_per_m = abs(denominator);
        record.D3_phase_deg = rad2deg(angle(denominator));
        record.omega_B33_N_per_m = omega * record.B33_kg_s;
        coefficientDiagnostics = results.diagnostics(1);
        record.raw_added_mass_symmetry_error = ...
            coefficientDiagnostics.raw_added_mass_symmetry_error;
        record.raw_damping_symmetry_error = ...
            coefficientDiagnostics.raw_damping_symmetry_error;
        record.minimum_eigenvalue_symmetric_damping_raw = ...
            coefficientDiagnostics.minimum_eigenvalue_symmetric_damping_raw;
        record.negative_damping_diagnostic = negative_damping_status( ...
            record.minimum_eigenvalue_symmetric_damping_raw);
        record.cache_status = string(results.audit.frequencyEntries(1).cacheStatus);
        record.body_geometry_hash = string(entry.mesh_audit.body.hash);
        record.free_surface_geometry_hash = ...
            string(entry.mesh_audit.freeSurface.hash);
        record.bottom_geometry_hash = string(entry.mesh_audit.bottom.hash);
        record.farfield_geometry_hash = ...
            string(entry.mesh_audit.outerBoundary.hash);
        record.combined_geometry_hash = string(entry.mesh_audit.geometry.hash);
        record.source_point_hash = string(entry.mesh_audit.sourcePointHash);
        record.collocation_point_hash = ...
            string(entry.mesh_audit.collocationPointHash);
        record.operator_hash = string(entry.phase2_2_control_manifest. ...
            effective.boundaryOperatorStateSHA256);
        record.configured_controls_hash = string( ...
            entry.phase2_2_control_manifest.configuredSHA256);
        record.effective_controls_hash = string( ...
            entry.phase2_2_control_manifest.effectiveSHA256);
        record.production_source_hash = string(results.audit.codeVersion.fingerprint);
    end

    function assert_postsolve_match()
        assert(record.bem_unknown_count == expected.total_panel_count && ...
            record.matrix_rows == expected.total_panel_count && ...
            record.matrix_columns == expected.total_panel_count && ...
            record.body_geometry_hash == expected.body_geometry_hash && ...
            record.free_surface_geometry_hash == ...
                expected.free_surface_geometry_hash && ...
            record.bottom_geometry_hash == expected.bottom_geometry_hash && ...
            record.farfield_geometry_hash == expected.farfield_geometry_hash && ...
            record.combined_geometry_hash == expected.combined_geometry_hash && ...
            record.source_point_hash == ...
                expected.preassembly_source_point_hash && ...
            record.collocation_point_hash == ...
                expected.preassembly_collocation_point_hash && ...
            record.operator_hash == expected.preassembly_operator_hash && ...
            record.configured_controls_hash == ...
                expected.preassembly_configured_controls_hash && ...
            record.effective_controls_hash == ...
                expected.preassembly_effective_controls_hash && ...
            record.production_source_hash == expected.production_source_hash, ...
            'CRESTU:Phase32BPostsolveProvenance', ...
            'Post-solve matrix, mesh, source, control, or operator provenance changed.');
    end

    function assert_runtime_scope(specificationIn, resultsIn)
        paths = [string(specificationIn.configFile); ...
            string(specificationIn.bodyFile); ...
            string(resultsIn.config.files.potential_cache); ...
            string(resultsIn.config.files.results); ...
            string(resultsIn.audit.meshAuditFile)];
        prefix = lower(string(specificationIn.runtimeDirectory) + filesep);
        for pathIndex = 1:numel(paths)
            normalized = lower(strrep(paths(pathIndex), '/', filesep));
            assert(startsWith(normalized, prefix) && ...
                ~contains(normalized, lower(definition.originalRepository)), ...
                'CRESTU:Phase32BRuntimeScope', ...
                'A solve path escaped the unique current-worktree directory.');
        end
    end
end

function status = negative_damping_status(minimumEigenvalue)
    if ~isfinite(minimumEigenvalue)
        status = "NOT_AVAILABLE";
    elseif minimumEigenvalue < 0
        status = "NEGATIVE_EIGENVALUE_OBSERVED_DIAGNOSTIC_ONLY";
    else
        status = "NONNEGATIVE";
    end
end

function value = is_resource_exception(exception)
    text = lower(string(exception.identifier) + " " + ...
        string(exception.message));
    value = contains(text, "out of memory") || ...
        contains(text, "nomem") || contains(text, "memory allocation");
end

function text = pass_fail(value)
    if value
        text = "PASS";
    else
        text = "FAIL";
    end
end
